### PR TITLE
Add Nightshade V2

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
**Details of Changes**
Add details of changes here.
- Added theme 'Nightshade.xaml'

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 this theme isn't going to work if it's not included in the cproj file. Can you include the file and verify that it works?

**Comment by DeveloperWOW64** [comment]
sure

**Comment by DeveloperWOW64** [comment]
do you mean csproj?

**Comment by yaichenbaum** [comment]
> do you mean csproj?

Yes

**Comment by DeveloperWOW64** [comment]
> > do you mean csproj?
> 
> Yes

err how?

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 the easiest way is to create the file in the Files project in Visual Studio.

**Pull request closed without merging**
