### PR TITLE
Fix: Added support for ejecting virtual drives

### LINKED ISSUE #10154: Virtual (vhdx) mounted drives don't have Eject option
### Description

File explorer has the option to eject a mounted drive in the context menu when Files doesn't.
image
image

### Steps To Reproduce

1. Create a Hyper-V VM
2. Right click virtual drive
3. Select mount option
4. Right click mounted drive
5. See no eject option

### Steps to fix

Add eject to context menu

### Files Version

2.3.47.0

### Windows Version

10.0.22621.608

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9737867/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9737865/debug_fulltrust.log)

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #10154

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaira2** [comment]
@hecksmosis can you confirm it works as expected?

**Comment by hecksmosis** [comment]
I noticed that although this is checking for VirtualDrive, VirtualDrive is never set, so I am trying to look for a way to implement this

**Comment by hecksmosis** [comment]
@yair100 Fixed

**Comment by yaira2** [comment]
@hecksmosis it's working now?

**Comment by hecksmosis** [comment]
> @hecksmosis still doesn't show for me.

Now it should, pushed it last night and left the computer, but the push rejected because I hadn't pulled the changes

**Comment by yaira2** [comment]
I'm getting a message that the drive is in use and PowerToys File Locker says it's in use by Files.
image

**Comment by hecksmosis** [comment]
I am drafting this until I find a way to fix the problems

**Comment by yaira2** [comment]
Can we use the shell command?

**Comment by hecksmosis** [comment]
Probably, I don't know how this would be done, I'll look into it

**Comment by yaira2** [comment]
I think we should close this for now

**Pull request closed without merging**
