### PR TITLE
Code Quality: Conversion of strings with Toggle value to Show/Hide/Toggle using ICU syntax

### PR DESCRIPTION
**Pull request by XTorLukas**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files
2. Try click to Info Pane Button
3. Tooltip now show Show/Hide text

**Showcase**

https://github.com/files-community/Files/assets/84145589/d66b2808-fe0e-4d14-88df-34dd5244754c

### CODE REVIEW

**Comment by XTorLukas** [comment]
@yaira2 fyi

**Comment by yaira2** [comment]
I like the idea but we need to consider if there are any downsides

**Comment by 0x5bfa** [comment]
I don't know it is a good idea though there's problems in some languages(according to Files Translators).

**Comment by yaira2** [comment]
What type of issue?

**Comment by 0x5bfa** [comment]
Not sure one of translator said so for some languages.
https://discord.com/channels/725513575971684472/1070771912797597917/1248618725763186688
And 4 people voted so

image

**Comment by XTorLukas** [comment]
I'll end this PR for now. Once the implementation of the resource manager is complete with the optimized ICU message parser implemented, we can possibly try to finish this PR.

**Pull request closed without merging**
