### PR TITLE
Compact spacing for the details layout

### LINKED ISSUE #1940: Add option for compact layout
**Is your feature request related to a problem? Please describe.**
Its annoying that so much space is wasted in comparison to the default explorer

**Describe the solution you'd like**
An option to reduce the font size

**Describe alternatives you've considered**
Changing the windows scale seems not to work on a per-app basis on UWP apps

**Additional context**
comparison screenshot:
left the old explorer showing 27 items, right the files-uwp showing 16 on the same window size. 
image

| Capability | Priority |
| :---------- | :------- |
| This proposal will add a setting to turn on the compact layout | Must |
| This option will use the compact styles for the sidebar and details layout | Must |

### PR DESCRIPTION
**Pull request by yair100**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #1940

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
image

### CODE REVIEW

**Review by lukeblevins — APPROVED** [review]
LGTM

**Review by lukeblevins — CHANGES_REQUESTED** [review]
Will this eventually be consolidated into the work done here: https://github.com/files-community/Files/pull/7941

**Comment by yaichenbaum** [comment]
> Will this eventually be consolidated into the work done here: #7941

This replaces the work done in #7941 but I'm keeping it open for now since there are still some additional styles to port over.

**Comment by lukeblevins** [comment]
@yair100 Why are we replacing that work? How will it differ? Where did this discussion take place? Why is #7941 still open?

**Review by lukeblevins — APPROVED** [review]

**Pull request merged**
