### PR TITLE
Feature: Added a tooltip when hovering over OneDrive status icons

### LINKED ISSUE #15182: Feature: Add a tooltip on what the cloud drive status icon means
### What feature or improvement do you think would benefit Files?

Right now, I think it can be hard to tell what exactly these icons mean, especially when you have two green ones which look pretty similar.

image

### Requirements

A UI change

### Files Version

3.3.0.0

### Windows Version

11

### Comments

_No response_

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Resolved / Related Issues

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15182

### Steps used to test these changes

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Open Files app
2. Go to cloud drive folder
3. Hover on

### Screenshots

image

### CODE REVIEW

**Comment by yaira2** [comment]
Is the text localized?

**Comment by 0x5bfa** [comment]
Absolutely.

**Comment by yaira2** [comment]
What is the text for each status?

**Comment by 0x5bfa** [comment]
IMG_0133

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
