### PR TITLE
Feature: Improve navigations in Column View

### LINKED ISSUE #11128: Feature: Improve backwards navigation in Column View
### What feature or improvement do you think would benefit Files?

I like the Column View, but it is frustrating that when I move to another folder, the Back button does not return to the directory where I previously was, but to the root of the Column View.

Steps to reproduce:
1. Set the view to Column View.
2. Use the left pane to navigate to C:\ from the Drives list.
3. Navigate to C:\Program Files (x86)\Microsoft\Edge (or whatever else).
4. Use the left pane to navigate to the Downloads folder from the Favorites list.
5. Press the Back button.
6. It returns to the C:\ folder, rather than C:\Program Files (x86)\Microsoft\Edge.

### Requirements

- All opened directories in the Column View should be kept so that after clicking the Back button, the navigation should return to the deepest directory visited before.

### Files Version

2.4.25

### Windows Version

Windows 11 Pro 22H2 22621.1105

### Comments

_No response_

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #11128 

**Details**
All opened directories in the Column View are now kept after clicking the Back or Forward button.
However, it is hard to keep focus, so the root directory is focused after clicking the button.

**Validation**
How did you test these changes?
- [X] Built and ran the app
- [X] Tested the changes for accessibility

### CODE REVIEW

**Comment by yaira2** [comment]
Does this help for #6902?

**Comment by hishitetsu** [comment]
I tried, but #6902 has not been improved.

**Comment by hishitetsu** [comment]
I have converted this PR to draft as it seems to make #6902 more unpredictable.

**Comment by hishitetsu** [comment]
Ok, #6902 has not been improved yet, but has returned to the same behavior as before. It looks like another, more complicated fix is needed to fix #6902, so I have returned it to ready for review status.

**Comment by ferrariofilippo** [comment]
> Ok, #6902 has not been improved yet, but has returned to the same behavior as before. It looks like another, more complicated fix is needed to fix #6902, so I have returned it to ready for review status.

#9769 code might be useful to fix #6902

**Comment by hishitetsu** [comment]
@ferrariofilippo Thank you, but the problem with #6902 is that the path of each column has to be saved on exit as tab information. This seems more difficult than with the back/forward buttons.

**Comment by ferrariofilippo** [comment]
> @ferrariofilippo Thank you, but the problem with #6902 is that the path of each column has to be saved on exit as tab information. This seems more difficult than with the back/forward buttons.

That code used to open all the baldes up to the root folder, we might save the first and the last one and then use that algo to achieve our goal

**Comment by hishitetsu** [comment]
Right now we can only store one path as tab information, but if we can extend that, we can certainly use this code.
Anyway, #6902 is a similar but different problem to this one, so I think this PR is ok.

**Comment by yaira2** [comment]
In addition to the focus, the opened directories aren't selected

**Comment by hishitetsu** [comment]
Sorry, is "selected" different than "focused"?

**Comment by hishitetsu** [comment]
Ah, I understand. I guess I need to fix it a bit more.

**Comment by hishitetsu** [comment]
I close this PR as it should be addressed along with #7589.

**Pull request closed without merging**
