### PR TITLE
Implement BulkConcurrentObservableCollection

### LINKED ISSUE #3166: Prevent rectangle selection while enumerating files
**TODO**
Processing rectangle selection while enumerating files would cause enumerating on a modified collection and crash apps for `System.InvalidOperationException: Collection was modified; enumeration operation may not execute`.

Therefore, rectangle selection should be disabled during files enumeration.

Also, any enumeration operation to `ItemViewModel.FilesAndFolders`, `GridView.Items` and `DataGrid.Items` should ensure that there's no one modifying `ItemViewModel.FilesAndFolders` (could ensure this via using `ItemViewModel.updateDataGridSemaphore`).

### PR DESCRIPTION
**Pull request by hez2010**
- Implement BulkConcurrentObservableCollection (reader-first) to make access to FilesAndFolders thread-safe
- Add `AddRange`, `InsertRange` and `RemoveRange` for further optimization
- Thanks to BulkConcurrentObservableCollection, there's no need of synchronization while accessing to FilesAndFolders anymore

Note: language resource changes are generated by compiler.

Fixes #3166

### CODE REVIEW

**Comment by gave92** [comment]
@hez2010 I'm getting duplicate/unsorted results when navigating to c:\windows\system32 ang hitting "refresh"
image

**Comment by gave92** [comment]
[@hez2010 bonus question: since now you have an "AddRange", "InsertRange", etc, could you use those instead of firing a Collection.Reset in EndBulkOperation? Would solve the "flashing" issue with gridview]

**Comment by hez2010** [comment]
@gave92 Fixed in 017817d

**Comment by hez2010** [comment]
> ~[@hez2010 bonus question: since now you have an "AddRange", "InsertRange", etc, could you use those instead of firing a Collection.Reset in EndBulkOperation? Would solve the "flashing" issue with gridview]~ Nevermind, I don't think gridview/datagrid supports those?

Unfortunately both GridView and DataGrid don't support those bulk operations, so we have to fire a Reset in EndBulkOperation.

**Review by gave92 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@hez2010 Can you resolve the merge conflicts?

**Comment by hez2010** [comment]
@yair100 Done

**Review by yair100 — APPROVED** [review]

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@hez2010 Thank you!

**Pull request merged**
