### PR TITLE
Implement traditional list view

### LINKED ISSUE #1368: need to add traditional list view
**Is your feature request related to a problem? Please describe.**
The Files UWP doesn't have the traditional list view.  The list view looks like the traditional Details view.  While it matches the list view of things like OneDrive.com, it doesn't match the traditional list view.  The list view maximizes window space to see the most content.

**Describe the solution you'd like**
The Files UWP doesn't have the traditional list view.  The list view looks like the Details view.  While it matches the list view of things like OneDrive.com, it doesn't match the traditional list view.  

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

### PR DESCRIPTION
**Pull request by jaigak**
Implements and closes #1368

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Here's the current design. I'm yet to add icons or implement the context menu. Please give suggestions on the design.

திரைப்பிடிப்பு (40)

**Comment by XPoppyX** [comment]
In list view the scroll is horizontal, right?

**Comment by Jaiganeshkumaran** [comment]
@XPoppyX I haven't touched that yet but shouldn't be hard to implement.

**Comment by XPoppyX** [comment]
and the current name of "List View" will be changed to "Details View"? after all that is the real name according to the windows file explorer

**Comment by Jaiganeshkumaran** [comment]
@XPoppyX I'm not sure what to do since there's already code that says list view.

**Comment by yaichenbaum** [comment]
image
@Jaiganeshkumaran The expected UI is to look like this...

**Comment by jaigak** [comment]
@yair100 I will do that once I fix all the implementation for interaction. Currently, they don't work.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran How is progress coming along on this pull request?

**Pull request closed without merging**
