### PR TITLE
Add search chip design with resources

### PR DESCRIPTION
**Pull request by duke7553**
Design feedback is welcome here

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@duke7553 Can you share a screenshot & description what this changes?

**Comment by XPoppyX** [comment]
### Proposal 1:

default     Captura de pantalla 2021-03-18 221052
mousehover     focus-selected

**CornerRadius**="0,4,4,0"
**BorderBrush**="Transparent"
**Remove**: "Search your files"
**Height**="30"      (_This is to avoid the empty space between the top border of the bar and the button.  I don't know if there is a better solution_)

------------

### Proposal 2:

If you want to keep the "Search your files"

Captura de pantalla 2021-03-18 232015
Captura de pantalla 2021-03-18 232053

_**CornerRadius**="0,4,4,0"_
**Font**="12" (_For font size consistency_)
**StackPanel Spacing**="10"
**Height**="30"      (_This is to avoid the empty space between the top border of the bar and the button. I don't know if there is a better solution_)
**BorderBrush**="Transparent"

**Comment by yaichenbaum** [comment]
@XPoppyX Proposal 2 looks pretty good.

**Comment by duke7553** [comment]
@XPoppyX I think the color difference is important so users don't think the whole bar is search. Maybe we can tweak the color instead of remove it?

**Comment by XPoppyX** [comment]
This is how it looks without removing the border

Captura de pantalla 2021-03-19 173648

**Comment by d2dyno1** [comment]
I'd be better if it just said "Search..."

**Comment by duke7553** [comment]
@d2dyno1 Can you explain why?

**Comment by d2dyno1** [comment]
@duke7553 "Search your files" sounds bit out of place. Majority of users are used to seeing "Search..." and it is pretty self explanatory

**Comment by duke7553** [comment]
I'm going to go back to the drawing board with this idea so we can get some more community feedback. Thank you to everyone who provided input here!

**Comment by d2dyno1** [comment]
It looked pretty good! I'd imagine it extending to ~1/4 of the pathbox size and retract when unfocused (to the size presented in [this](https://github.com/files-community/Files/pull/4166#issuecomment-803117126) image)

@duke7553 You should ask around for feedback in #design channel on the server.

**Pull request closed without merging**
