### PR TITLE
Advanced search

### LINKED ISSUE #4813: Add search filters
**Is your feature request related to a problem?**
It is not possible to filter the search results. 

**Describe the solution**
Use a menu to filter results.
This menu, visible after the searchbar, show the filters (date, size, extension, picture, video, ...)
This menu will require research to be complete but simple, practical and beautiful. 

| Capability | Priority | 
| - | - | 
|  Show when a search is open | Must |
| Apply changes with a refresh | Must | 

**Additional comment**
I created a pull request that implements a minimal menu to better show the concept #4812.
Filter

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
Add filters for the search bar.
Closes #4813

**Details of Changes**
Add a button after the searchbar, only visible when the searchbar is enabled.
The menu adds filter for the date.

More options will come later, but be careful not to overload the ui. The visual will be improved.

**Screenshots (optional)**
filter

### CODE REVIEW

**Comment by TailyFair** [comment]
Just an idea, but maybe filter should be in search results? Since you most likely would want to use this when initial search returns too many results?

**Comment by cinqmilleans** [comment]
We can display the filter menu button on the results page and relaunch the filter when we modify.

**Comment by yaichenbaum** [comment]
Please open an issue to discuss this change, once it's approved, the conversation here will be unlocked.

**Comment by cinqmilleans** [comment]
@yair100 Here is news of this issue. I am trying to imagine the best organization for the filter popup. This will take a few more days. Afterwards, I will post screenshots to validate the principle before implementation.

**Comment by cinqmilleans** [comment]
This functionality has been replaced by #4813. So I close this pr.

**Pull request closed without merging**
