### PR TITLE
Fix Issue#11963

### PR DESCRIPTION
**Pull request by CodeAnk2829**
@yaira2  This is my first contribution. Please review my PR and merge it if the mentioned issue has been resolved.

### CODE REVIEW

**Comment by hecksmosis** [comment]
Please submit a PR following the pull request template so that it is easier to review by contributors

**Comment by yaira2** [comment]
@CodeAnk2829 thank you for the PR, please use the pull request template so that we can review your contribution.

**Comment by CodeAnk2829** [comment]
> @CodeAnk2829 thank you for the PR, please use the pull request template so that we can review your contribution.

@yair100 Sorry for this. Actually I'm a new contributor and hence unaware of the required pull request template. Can you please guide me, where would find it?

**Comment by yaira2** [comment]
When you navigate to the [pull request](https://github.com/files-community/Files/pulls) page, there is an option to open a new pull request. If you follow this process, there will be a template to fill out and it'll walk you through the steps for opening a proper pull request.

**Pull request closed without merging**
