### PR TITLE
Added tab dividers back

### LINKED ISSUE #4348: [Enhancement] Add back dividers between tabs
**Is your feature request related to a problem?**
With the UI overhaul released, it's rather difficult to tell your tabs apart, due to a lack of elevation or indication of where one tab ends and the other begins.

**Describe the solution**
Add small dividers between inactive tabs (similar to those seen on chrome and edge).

**Describe alternatives you've considered**
Slightly elevate inactive tabs in color to better distinguish between them.

**Additional comment**
Current Design:
image

Proposed Design:
image

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Itemize resolved / related issues by this PR.
- Closes #4348 

**Details of Changes**
Add details of changes here.
- Added back the divider between tabs

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image

### CODE REVIEW

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@winston-de It looks like the last tab has a divider overlaying on top of it, can you change it so that the divider is transparent for the last tab?

**Comment by winston-de** [comment]
@yair100 I think it makes sense to keep it, it adds a divider between the last tab and new tab button.
It's also how WinUI does it.
image

**Comment by yaichenbaum** [comment]
@winston-de That's a good point, however, it should only be visible when the last tab isn't selected.

**Comment by winston-de** [comment]
@yair100 Good idea

**Pull request merged**
