### PR TITLE
Fix: Fixed an issue where the file list would scroll up when refocusing the window

### LINKED ISSUE #13220: Bug: Files scrolls to the top when window is refocus
### Description

*

### Steps To Reproduce

1. Open a scrollable directory
2. Scroll down
3. Click off the window
4. Click on the window
5. See scrolled to the top

### Requirements

- Keep scroll position

### Files Version

2.5.22.0

### Windows Version

10.0.22621.2134

### Log File

[debug.log](https://github.com/files-community/Files/files/12388912/debug.log)

### PR DESCRIPTION
**Pull request by MyoMinHein1246**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #13220 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by QuaintMako — APPROVED** [review]
LGTM and works fine on my computer.

**Comment by hishitetsu** [comment]
The following step will cause the file list to scroll up:
1. Select the item at the top of the list
2. Deselect the item
3. Unfocus the app window
4. Refocus the app window

**Comment by yaira2** [comment]
@MyoMinHein1246

**Comment by MyoMinHein1246** [comment]
@yaira2 Sorry for late response. I have got a lot on my plate recently. But I will work on this real soon. 😊

**Comment by MyoMinHein1246** [comment]
I looked further into it, and apparently, the file list scrolls to the last selected (or currently if there's one) item every time it get focused. Unfortunately, I still cannot find any fixes. 😭 The only thing I could find was to not let the user focus the file list, which obviously worsen the user experience. I need help.😔👀

**Pull request closed without merging**
