### PR TITLE
Display SharePoint folder in sidebar for each Tenant

### LINKED ISSUE #1310: Add SharePoint sync directories
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To add SharePoint sync directories like is available on the default explorer.

**Describe alternatives you've considered**
The alternative at the moment is to use the default Windows Explorer.

**Additional context**
Please find attached screenshot 

Untitled

### PR DESCRIPTION
**Pull request by AndyMDoyle**
Closes #1310 

Because it is possible to sync an unlimited number of SharePoint libraries for any number of tenants, I have followed Explorer and add a single sidebar entry for each tenant. This maps to the a folder that contains the folders representing each document library/sync point.

image

### CODE REVIEW

**Comment by gave92** [comment]
@yair100 sorry I don't have SharePoint to test this.

**Comment by yair100** [comment]
> @yair100 sorry I don't have SharePoint to test this.

I guess we are going to have to take a chance with this.

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@AndyMDoyle LGTM

**Comment by AndyMDoyle** [comment]
If no one else has SharePointto test with, is it worth putting behind an experimental setting?

The logic is almost a direct rip of the One Drive logic using the full trust process to check for registry keys.

**Comment by gave92** [comment]
@AndyMDoyle I don't think it's worth it. Plus can't be worse than 1.2.2 update lol.

**Pull request merged**
