### PR TITLE
Improvements to codebase

### PR DESCRIPTION
**Pull request by d2dyno1**
Just a couple of suggestions of mine \:)

future proofing

### CODE REVIEW

**Comment by gave92** [comment]
This is the change that was discussed in #3861, right? For the moment I don't really see the point of this since we have the FolderSettingsViewModel as the sender arg. We'd only need to do this if we ever move that event out of FolderSettings.

**Review by duke7553 — COMMENTED** [review]
@d2dyno1 Could you give a reason for this change? What is your rationale because I thought we agreed on the current method with the last PR?

**Comment by d2dyno1** [comment]
@duke7553 I've made this PR if we ever wanted in the future to move the `FolderSettings_LayoutPreferencesUpdateRequired` outside of `ModernShellPage`

**Comment by gave92** [comment]
Thanks @d2dyno1 I'm closing this for now since with the current code there is no particular reason to change. If we end up changing things we'll totally consider this.

**Pull request closed without merging**
