### PR TITLE
color progressbar red if free diskspace low

### PR DESCRIPTION
**Pull request by lampenlampen**
color the progressbar red if disk space is low.

__Open Questions__

1. Currently the threshold is to 10%. So, if more than 90% is used, the progress bar is red.

Because the changes are so small, i didn't open an issue before.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@lampenlampen Thanks for opening this pull request, there is already an open discussion (#3540), but we haven't approved this change for development yet.

**Comment by lampenlampen** [comment]
I see.

Feel free to close 👍.

**Comment by yaichenbaum** [comment]
@lampenlampen I think the work you did will be helpful to do what we last discussed in #3540. Do you want to continue working on this issue?

**Comment by lampenlampen** [comment]
Since i have some exams in the next month, i'm not sure if i will be able to work on it.

**Comment by yaichenbaum** [comment]
@lampenlampen Thank you for laying the foundation in this PR, we implemented this change in #4409.

**Pull request closed without merging**
