### PR TITLE
Improved header background in details layout

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by winston-de** [comment]
I was thinking we could make a style for the buttons, so that it would be easier to make changes in the future.

**Comment by yaichenbaum** [comment]
> I was thinking we could make a style for the buttons, so that it would be easier to make changes in the future.

Being that this is the only change for now, wouldn't a style be a little overkill?

**Comment by winston-de** [comment]
@yair100 Yeah, it can probably be done in another PR. It will be a good to have eventually though since there may be a lot more header items in the future.

**Review by winston-de — APPROVED** [review]

**Comment by yair100** [comment]
> @yair100 Yeah, it can probably be done in another PR. It will be a good to have eventually though since there may be a lot more header items in the future.

The WinUI DataGrid will hopefully be ready by then, if not, then we will probably want to make this more future proof and flexible.

**Pull request merged**
