### PR TITLE
Provide dragged files as StorageFile when possible

### LINKED ISSUE #6697: dragging and dropping to other apps
With the exception of File Explorer (explorer.exe), other apps can not accept drag and drop operations of files from Files window.

I tested this and the file type is shown as "Files.Filesystem.StorageItems.SystemStorageFile" type

image

Is there any way to maybe expose this as a "StorageFile" type?

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6697

**Details of Changes**
Add details of changes here.
- Provide dragged files as StorageFile when possible. Fixes dropping to some UWP apps, e.g Snip and Sketch.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by BanCrash** [comment]
@gave92 Do you test it with any app that didn't work with last Files release? I've tested with Email app and it doesn't work with this commit nor the last release.

**Comment by gave92** [comment]
I've tried with snip & sketch. Without this PR is not working, could you confirm? I'll take a look to the main app.

**Comment by BanCrash** [comment]
> I've tried with snip & sketch. Doesn't work on main but it's working with this PR, could you confirm? I'll take a look to the Email app.

@gave92 Yep, I have your same result (last release not working but your PR does).

**Review by BanCrash — APPROVED** [review]
Since this fixes the issue you said, I don't see any reason to not merge this. LGTM.

**Pull request merged**
