### PR TITLE
Fix: Fixed an issue preventing Home to open in Files when clicking on This PC

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...

~This PR removes leftover code from FilesLaucher related to selected item highlight (removed in #11509). Allows to remove a 500ms delay before opening folders.~
Also fixes an issue for which opening MyComputer from desktop did not open Files Home.

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?

### CODE REVIEW

**Comment by hishitetsu** [comment]
Instead of removing file selection code, I think we should keep the file selection functionality by moving Launcher to a separate repository and reinstating the GPL code.

**Comment by gave92** [comment]
IIRC someone was not happy with that solution on the basis that since Launcher executable is bundled with Files all Files code woud have to be published with GPL (file selection was not working well regardless).

**Comment by hishitetsu** [comment]
I think a separate repository would solve the licensing issue.
@0x5bfa what do you think?

**Comment by 0x5bfa** [comment]
Definitely should, like already seven zip do.

**Comment by gave92** [comment]
Happy to hear that. In the meantime this PR just fixes an issue for which opening ThisPC from desktop did not open a new Home tab in Files

**Comment by hishitetsu** [comment]
> I concur. In the meantime this PR just fixes an issue for which opening ThisPC from desktop did not open a new Home tab in Files

This reverts changes made in #11890. Which is better?

**Comment by hishitetsu** [comment]
@ferrariofilippo fyi

**Comment by gave92** [comment]
NB: This PR restores opening Files Home when user clicks ThisPC on the desktop (Files set as default).

Open "real" This PC shell folder (current main):

image

Or open Files Home (this PR and before #11890):

image

Which is the desired behaviour?

**Comment by yaira2** [comment]
> Open "real" This PC shell folder (current main):

This makes more sense to me but either way is fine.

**Pull request closed without merging**
