### PR TITLE
CI: Add Files Build GitHub Actions

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Description

Add a GitHub Action pipeline for building & testing Files. We should use GitHub Actions more instead of Azure Pipeline to be more integrated.

### PR Checklist
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related: #11649
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Ready for review.

**Comment by 0x5bfa** [comment]
Test is not build this will be phase two, I suppose. We have to run in those 3 conditions first.

**Comment by yaira2** [comment]
Is there a way to hide the warnings when reviewing the code changes?

**Comment by 0x5bfa** [comment]
Yeah. suppress warning output in msbuild outputs.

**Pull request closed without merging**
