### PR TITLE
Do not trigger selection rectangle with touch

### LINKED ISSUE #2349: Don't show selection rectangle on touch input
**Describe the bug**
the selection rectangle shows up while using the touchscreen to scroll in the items view

**To Reproduce**
1. Open a folder with many items or decrease the window size until the scrollbar appears
2. Use the touch screen to scroll up and down

**Expected behavior**
Don't show selection rectangle while using the touchscreen in scrollable folders

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.630
 - App version: v0.20.0.0

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2349 

This PR disables drag selection with touch input to not interfere with list scrolling

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 Is it posible to keep the selection rectangle on touch devices but only when the user holds down for a few seconds?

**Comment by gave92** [comment]
Perhaps, but in general it may be a bit difficult to trigger the selection rectangle on touch as you have to click outside listed items. I was so thinking that for now it's better to disable it.
(I don't own a touchscreen device though, I'm not able to test this)

**Comment by yaichenbaum** [comment]
@gave92 In that case it might be better to disable it for now, but eventually we will want to implement long touch + drag since touch users will want a way to select multiple items.

**Review by yaichenbaum — APPROVED** [review]

**Comment by gave92** [comment]
"eventually we will want to implement long touch + drag since touch users will want a way to select multiple items"
An alternative way for touch would be a long press that triggers a "multiple selection mode" where checkboxes appear next to items
image

**Comment by yaichenbaum** [comment]
@gave92 That's a nice idea, can you add it to #2008?

**Comment by yair100** [comment]
> Perhaps, but in general it may be a bit difficult to trigger the selection rectangle on touch as you have to click outside listed items. I was so thinking that for now it's better to disable it. (I don't own a touchscreen device though, I'm not able to test this) What do you think?

@gave92 I don't recall the exact setup we had when this was last discussed, but in the latest version of Files, there are scenarios where there is enough room outside the file area. Do you have any pointers to be able to implement #17961.

**Pull request merged**
