### PR TITLE
Files.Uwp -> Files.App

### PR DESCRIPTION
**Pull request by hez2010**
Let's rename from Files.Uwp to Files.App given that we are migrating to WindowsAppSDK.

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by smarquespt** [comment]
Not sure if it's related but now we have 2 projects at crowdin:

image

**Comment by yaichenbaum** [comment]
It's most likely related, can I just remove Files.App?

**Comment by smarquespt** [comment]
I think you should. Thanks

**Pull request merged**
