### PR TITLE
Code Quality: Fixed an issue where folder background image would remain when navigating to Home page

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Open a folder that has a custom background image.
2. Navigate to Home.
3. See the background image disappears.

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]
LGTM

**Review by 0x5bfa — COMMENTED** [review]
Isn't this a bit odd?
Why not just clear the value of the property to null instead of calling the method?

**Comment by hishitetsu** [comment]
> Isn't this a bit odd? Why not just clear the value of the property to null instead of calling the method?

The setter of `FolderBackgroundImageSource` is private.

**Review by 0x5bfa — APPROVED** [review]
Alright, I'll think of how to flash current state during navigation.
LGTM, code wise.

**Pull request merged**
