### PR TITLE
Feature: Added "send to" menu when right clicking a file

### LINKED ISSUE #7350: Add the "Send to" option
### What's the Problem?

Hello :-) Hope you're fine. I wrote last time caus I couldn't open directly a folder (expect when I'm not in the folder, when I right clik on it) with VSCode or PowerShell7. Now I see that I can open a folder even if I'm already in. If last time I was wrong and did'nt see it, forgive please.
Now, there is a feature that make me use the native Files Explorer( FE) : the **send to option**. You don't put it in the app.

### Solution/Idea

Please insert the send to option. I got a lot to say about how very Amazing is your application. **Seriously, you're doing a GOOOD JOB guys**. If I could ongreats you with money... But I can now. May God Bless you more and give you what you need.

### Alternatives

Redesign if possible the windows that appear on right clik on a document: for example you can put **Edit New Print** in the same line.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |

### Files Version

2.0.34.0

### Windows Version

Windows 11 Dev

### Comments

Screenshot (3)

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7350

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hecksmosis** [comment]
@yaira2 Does it appear?

**Comment by gave92** [comment]
Can't test this but send to menu was turned off because it locks the app if you have disconnected network drives iirc. Haven't checked in a long time.

**Comment by yaira2** [comment]
@gave92 are you comfortable releasing to preview to see if this is still an issue?

**Comment by gave92** [comment]
Fairly sure it's still an issue but probably impacts only few users.

**Pull request merged**
