### PR TITLE
Fix: Fixed issues with drag & drop from Files to other apps

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.

This PR should solve the issues we have when dragging items from Files to other apps. This should e.g work for UWP apps, the inbox Mail app, File explorer & other win32 apps.
Note: it references System.Windows.Forms, it's not mandatory but it makes things much simpler. If this works we can worry about removing all references to it later.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaira2** [comment]
Fixes #10171?

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by gave92** [comment]
Mmm it looks like this fixed drag&drop to some apps (WhatsApp) but breaks others (WordPad). And both fail to drag&drop to notepad or xshell (#10171)

**Comment by yaira2** [comment]
What do we need to fix this issue?

**Comment by gave92** [comment]
I'm stumped. Best to revert this for now on stable anyway.

**Pull request merged**
