### PR TITLE
Add "Close tabs to the left" and "Close others" to tab context menu

### LINKED ISSUE #7714: "Close tabs to the left" and "Close others" in tabs context menus
### What's the Problem?

It would be nice in my opinion to have the "close tabs to the left" and "close other tabs" commands in the right-click tab menus, since there is already "close tabs to the right".
These entries are often found in browsers and other tabbed applications, and some users may find them useful.

### Solution/Idea

If this feature is approved, I can open a pull request because the code is not very complex and I've already implemented it on my Dev version.

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to have more options to manage open tabs | Must |

### Files Version

2.1.0.0 Dev

### Windows Version

Windows 10 21H1 19043.1466

### Comments

_No response_

### PR DESCRIPTION
**Pull request by manfromarce**
**Resolved / Related Issues**
Closes #7714 .

**Details of Changes**
- Added "Close tabs to the left" item, which is disabled when the selected tab is the first tab
- Added "Close others" item, which is disabled when there is only one tab open
- Added English and Italian localizations for the new voices.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by cinqmilleans** [comment]
@manfromarce My remarks. I have only analyzed the style so far.
1) MultitaskingTabsHelpers.cs. Bad indentation (lines 29 and 45 have extra space)
2) It makes more sense to have the Left command before the Right command, like in Firefox for example.
3) x:Uid="HorizontalMultitaskingControlCloseTabsToTheLeft". Now we prefer helpers:ResourceString which allows not to reuse the text (in several places or if the code is modified). 
4) We can write your code more simply by using Linq. For example, here is before/after. (We can do the same for Right and Other).

```
public static void CloseTabsToTheLeft(TabItem clickedTab, IMultitaskingControl multitaskingControl)
{
	int index = MainPageViewModel.AppInstances.IndexOf(clickedTab);
	List<TabItem> tabsToClose = new List<TabItem>();

	for (int i = 0; i < index; i++)
	{
		tabsToClose.Add(MainPageViewModel.AppInstances[i]);
	}

	foreach (var item in tabsToClose)
	{
		multitaskingControl?.CloseTab(item);
	}
}

public static void CloseTabsToTheLeft(TabItem clickedTab, IMultitaskingControl multitaskingControl)
{
	if (multitaskingControl is not null)
	{
		var tabs = MainPageViewModel.AppInstances;
		var currentIndex = tabs.IndexOf(clickedTab);

		tabs.Take(currentIndex).ToList().ForEach(tab => multitaskingControl.CloseTab(tab));
	}
}

public void CloseTabsToTheLeft(object sender, RoutedEventArgs e)
{
	MultitaskingTabsHelpers.CloseTabsToTheLeft(((FrameworkElement)sender).DataContext as TabItem, this);
}

public void CloseTabsToTheLeft(object sender, RoutedEventArgs e)
	=> MultitaskingTabsHelpers.CloseTabsToTheLeft(((FrameworkElement)sender).DataContext as TabItem, this);
		
private void MenuItemCloseTabsToTheLeft_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
{
	TabItem tabItem = args.NewValue as TabItem;

	if (MainPageViewModel.AppInstances.IndexOf(tabItem) == 0)
	{
		MenuItemCloseTabsToTheLeft.IsEnabled = false;
	}
	else
	{
		MenuItemCloseTabsToTheLeft.IsEnabled = true;
	}
}

private void MenuItemCloseTabsToTheLeft_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
{
	TabItem tabItem = args.NewValue as TabItem;
	MenuItemCloseTabsToTheLeft.IsEnabled = MainPageViewModel.AppInstances.IndexOf(tabItem) > 0;
}
```

**Comment by yaichenbaum** [comment]
@manfromarce before we merge this, can you add your agreement to #7625?

**Review by gave92 — APPROVED** [review]

**Comment by gave92** [comment]
Nice work, just remember to never edit RESW files directly with the exception of "en-US". For other languages translations go into the "XLF" files.

**Comment by manfromarce** [comment]
> @manfromarce before we merge this, can you add your agreement to #7625?

Okay, I agreed.

> Nice work, just remember to never edit RESW files directly with the exception of "en-US". For other languages translations go into the "XLF" files.

Sorry, I wasn't sure which one to edit for translations. Now I know.

**Comment by yaichenbaum** [comment]
@manfromarce can you open a new pr to change "Close others" to "Close other tabs"?

**Comment by manfromarce** [comment]
Yes, I will do

**Pull request merged**
