### PR TITLE
Code Quality: Improved the code quality of the customization properties page

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Description

I've done this before in https://github.com/files-community/Files/pull/11421 and I reverted to avoid adding off-topic changes(although it was accepted change). But here you are again.

### Motivation and Context

- Fix UI that was created for out-dated window style
- Improve readability and maintainability of those codes

### Details of change

- Update UI to maximize GridView.
- Update divider to use Border instead of MenuFlyoutSeparator
- Update divider to use DividerStrokeDefaultBrush, which is expected, instead.
- Add Commands to the ViewModel.
- Remove events in the View.
- Remove event handling codes in View's code-behind.

### Self-check list

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?

### Screenshots

Light
image

Dark
image

### CODE REVIEW

**Comment by ferrariofilippo** [comment]
I've just found a little UI-issue related with properties (it is caused by localization and happens in preview as well). You may inlcude it in this PR.

**Comment by onein528** [comment]
This was fixed by #11672.

**Comment by 0x5bfa** [comment]
@yair100 Ready for review.

**Review by yair100 — APPROVED** [review]
LGTM

**Pull request merged**
