### PR TITLE
Appcenter fixes 3

### PR DESCRIPTION
**Pull request by gave92**
"A few" fixes for appcenter issues

### CODE REVIEW

**Review by yair100 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/files-community/files) found an issue: Complex Method

It's currently on:
[Files\Filesystem\FilesystemOperations\Helpers\FilesystemHelpers.cs:89-184
](https://github.com/files-community/files/blob/3c85452459dd5d63e499cb8c1e47a0a926f27ff9/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs#L89-L184)Commit 3c85452459dd5d63e499cb8c1e47a0a926f27ff9

**Comment by gave92** [comment]
~With #3290 some of this changes are no longer necessary~ Edit: nevermind

@yair100 Should be ok , and that code factor issue was there before 👍

**Comment by yair100** [comment]
> @yair100 Should be ok , and that code factor issue was there before 👍

Sounds good, can you resolve the merge conflicts?

**Comment by gave92** [comment]
@yair100 no sorry, I'll be away for 1.5 weeks

**Comment by yair100** [comment]
> @yair100 no sorry, I'll be away for 1.5 weeks

No worries, I think I solved them, I am just testing in VS to make sure the build works.

**Review by yair100 — APPROVED** [review]

**Comment by gave92** [comment]
Wait

**Comment by yaichenbaum** [comment]
> Wait, last commit you made undoes one of the fixes. I'd keep the "ElementAtOrDefault" part ;)

I thought I broke something there because it wasn't working 😂.

**Pull request closed without merging**
