### PR TITLE
Added support to display custom folder icons

### LINKED ISSUE #519: Show custom folder icons
Is it possible to display custom folder icons?.
file_expl

### LINKED ISSUE #2083: Add support for Colorize extension
<! -
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

RECONOZCO LO SIGUIENTE ANTES DE CONTINUAR:
1. Si elimino toda esta plantilla y sigo mi propio camino, el equipo central puede cerrar mi problema sin más explicaciones o compromisos.
2. Si enumero varios errores / inquietudes en este único problema, el equipo central puede cerrar mi problema sin más explicación o compromiso.
3. Si escribo un problema que tiene muchos duplicados, el equipo central puede cerrar mi problema sin más explicación o compromiso (y sin necesariamente perder tiempo para encontrar el número de identificación duplicado exacto).
4. Si dejo el título incompleto al presentar el problema, el equipo central puede cerrar mi problema sin más explicaciones o compromisos.
5. Si presento algo completamente en blanco en el cuerpo, el equipo central puede cerrar mi problema sin más explicación o compromiso.

¿Todo bien? ¡Entonces proceda!
->

** ¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ex. Siempre me frustra cuando

Re: Mi solicitud esta basada en una función que me gustaría que implementaran.

** Describe la solución que te gustaría **
Una descripción clara y concisa de lo que quieres que suceda.

Re: Me gustaría que implementaran al hacer click derecho sobre una carpeta poder cambiar el color de las carpetas para tener un mejor orden ya que esto ayuda a recordar que archivo tenemos en dicha carpeta.

** Describe las alternativas que has considerado **
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

Re: Ya que uso una herramienta en el explorador de Windows para cambiar las carpetas de color llamada Colorize pero en el explorador Beta no funciona esta aplicación

** Contexto adicional **
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí. Ej .: ¿Qué tipo de dispositivo / diseño de interfaz de usuario y versión de la aplicación?

image

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2083, fixes #519

### CODE REVIEW

**Comment by gave92** [comment]
@XPoppyX could you verify if this PR works for the use-case you reported in #519?

**Review by duke7553 — COMMENTED** [review]
@gave92 Does the WinRT StorageFolder.GetThumbnailAsync() return custom folder icons? Maybe we could check if that method returns a non-default thumbnail and display it for folders as well. I know we currently don't use it anywhere because we use our custom folder icons, but this use case would be reasonable if at all feasible.

**Comment by gave92** [comment]
It returns both default and custom folder icons

**Comment by duke7553** [comment]
@gave92 Ok you're right! I missed that.

**Review by duke7553 — DISMISSED** [review]
Couldn't have done it better myself!

**Comment by XPoppyX** [comment]
@gave92 works for me, it just doesn't show custom icons from folder shortcuts

**Comment by gave92** [comment]
@XPoppyX thanks for the feedback. 
Regarding the shortcuts this was expected. Even for file shortcuts we show the icon of _the destination_ and not of the shortcuts itself

**Comment by XPoppyX** [comment]
> Regarding the shortcuts this was expected. Even for file shortcuts we show the icon of _the destination_ and not of the shortcut itself

I have not changed the shortcut icon, it is the destination folder icon that is not displayed

**Comment by gave92** [comment]
Thanks @XPoppyX I can too confirm this.

**Review by yaichenbaum — DISMISSED** [review]

**Review by duke7553 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Can you fix the merge conflict?

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
:shipit:

**Pull request merged**
