### PR TITLE
Revert "After pasting, focus all pasted files/folders instead of just one"

### PR DESCRIPTION
**Pull request by yaichenbaum**
Reverts files-community/Files#9299

### CODE REVIEW

**Comment by yaichenbaum** [comment]
FYI @IgorKordiukiewicz

**Comment by IgorKordiukiewicz** [comment]
Yeah, I tried to fix it but since the files changes are processed separately, I don't think there is a way to reset `itemsAdded` properly.

**Comment by jiejasonliu** [comment]
> I don't think there is a way to reset `itemsAdded` properly.

Yeah, unfortunately that's exactly why I never implemented this when I implemented selecting singular files.

If interested, there's the potential solution of keeping track of the items that are pasted before it's flattened into separate requests, then you can check if those items are a subset of `itemsAdded` and then select the items and reset the list then.

**Pull request merged**
