### PR TITLE
Added Latest Build Flag, Downloads flag

### PR DESCRIPTION
**Pull request by AlfarexGuy2019**
Added a flag which shows the total downloads and the latest available build of files.

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added Downloads flags, build flags
- Fixed nothing.

**Validation**
How did you test these changes?
Changes to `readme.md` cannot be tested in app.

**Screenshots (optional)**
Add screenshots here.
[N/A]

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@AlfarexGuy2019 Can you share a screenshot of the change?

**Comment by AlfarexGuy2019** [comment]
Of course!
Before:

image

After:

image

**Comment by yaichenbaum** [comment]
@AlfarexGuy2019 It looks good! The one thing I would change is to remove the download count as that isn't a very accurate indicator considering the other locations that Files is available for download.

**Comment by AlfarexGuy2019** [comment]
We can add one for the store too!

**Comment by yaichenbaum** [comment]
> We can add one for the store too!

Is there an API for that?

**Comment by AlfarexGuy2019** [comment]
> > We can add one for the store too!
> 
> Is there an API for that?

I think so. i saw one in some msft repository

**Comment by BanCrash** [comment]
Could be this the API needed for adding support for having microsoft store downloads count? 
https://docs.microsoft.com/en-us/windows/uwp/monetize/access-analytics-data-using-windows-store-services
https://docs.microsoft.com/en-us/windows/uwp/monetize/get-app-installs

**Comment by yaichenbaum** [comment]
Closing this pull request due to inactivity.

**Pull request closed without merging**
