### PR TITLE
Feature: Add Copy, Cut and Delete RichCommands

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related to #11481 

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaira2 — DISMISSED** [review]

**Comment by yaira2** [comment]
Thank you

**Comment by cinqmilleans** [comment]
A few comments.
* Completely remove the commands from the ToolbarViewModel, and use the commands in the xaml.
* Implement IsExecutable (observable) to avoid having to handle it in the xaml.

**Comment by hecksmosis** [comment]
Oh ok, I think I'm going to open anew pr when this is merged and do this for all the other richcommands that got implemented without IsExecutable

**Comment by yaira2** [comment]
Looks like these commands are showing as secondary items instead of primary items.

**Pull request merged**
