### PR TITLE
Added support for collapsing widgets on the homepage

### PR DESCRIPTION
**Pull request by yair100**
**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Known issues**
Additional options flyout overlaps with content. The solution is to move the flyout to the expander header. Support should also be added to keep track of the expanded state.

**Screenshots (optional)**
image

### CODE REVIEW

**Comment by d2dyno1** [comment]
@yair100 The state of expanders is not preserved between instances and on app restart

**Comment by yair100** [comment]
> @yair100 The state of expanders is not preserved between instances and on app restart

Tracking that in #7286

**Comment by d2dyno1** [comment]
> > @yair100 The state of expanders is not preserved between instances and on app restart
> 
> Tracking that in #7286

Nah, if you'd like to I could implement it and push it to this branch so #7286 is closed with this one.

**Comment by yair100** [comment]
> > > @yair100 The state of expanders is not preserved between instances and on app restart
> > 
> > 
> > Tracking that in #7286
> 
> Nah, if you'd like to I could implement it and push it to this branch so #7286 is closed with this one.

Go ahead 👍

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
