### PR TITLE
Make log files easier to identify #1550

### PR DESCRIPTION
**Pull request by oleitao**
**Details of Changes**
- Changed log output file extension to .log

**Validation**
- [x] Verify if debug.log was created in C:\Users\XXXXX\AppData\Local\Packages\FilesDev_et10x9a9vyk8t\LocalState\debug.log
- [x] Verify if debug_fulltrust.log was created in C:\Users\XXXXX\AppData\Local\Packages\FilesDev_et10x9a9vyk8t\LocalState\debug_fulltrust.log

**Screenshots (optional)**
Capture

### CODE REVIEW

**Comment by d2dyno1** [comment]
Great! Make sure to also update the issue templates and references where the `debug.txt` and `debug_fulltrust.txt` were used.

**Comment by oleitao** [comment]
> ...update the issue templates ... are used.

Can you give me some details about what templates you are talking about?

**Comment by d2dyno1** [comment]
@oleitao https://github.com/files-community/Files/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by oleitao** [comment]
> @oleitao https://github.com/files-community/Files/blob/main/.github/ISSUE_TEMPLATE/bug_report.md


name | about | title | labels | assignees
-- | -- | -- | -- | --
Bug report | Use the .log extension instead of .txt |   | bug |  

**Explain the bug** Use the .log extension instead of .txt. The log extension is used by many applications to distinguish log files from regular text files.

**To reproduce**

1. Go to `%localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\`
2. Delete debug.txt and debug_fulltrust.txt files
3. Start Files
4. Verify if debug.txt and debug_fulltrust.txt files are created on `%localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\`

**Expected behavior** If files debug.txt and debug_fulltrust.txt doesn't exist create them, otherwise if they already exist check if their content are well writed with app interaction commands logs.

**Logfile** 
Capture1

Capture2


- You can access it from Settings->About->Open log location. or
- Copy the debug.txt and debug_fulltrust.txt from the following directory, and upload the files here. `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`


**System Information**

- OS Version: [e.g. Windows 10 20H2 19042.867]
- App version: [e.g. v1.3.1.0]

**Comment by pklion** [comment]
I think you just need to change the following:
### To reproduce
1. Go to %localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\
2. Delete **debug.txt** and **debug_fulltrust.txt** files
3. Start Files
4. Verify if **debug.txt** and **debug_fulltrust.txt** files are created on %localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\

**Comment by oleitao** [comment]
> I think you just need to change the following:
> 
> ### To reproduce
> 1. Go to %localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\
> 2. Delete **debug.txt** and **debug_fulltrust.txt** files
> 3. Start Files
> 4. Verify if **debug.txt** and **debug_fulltrust.txt** files are created on %localappdata%\Packages\FilesDev_et10x9a9vyk8t\LocalState\

@pklion yes, that's already done

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@oleitao Thank you!

**Pull request merged**
