### PR TITLE
Feature: Added support for displaying all network folders on the sidebar

### LINKED ISSUE #8304: Feature: Display all network folders on the sidebar
### What's the Problem?

Network drives folder

### Solution/Idea

List of available network drives (PC's) instead of folder with all of them.

Now:
NowDrives

Should be:
networkDrives
 

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |

### Files Version

_No response_

### Windows Version

_No response_

### Comments

_No response_

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #8304

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Open Files.
2. Wait a moment. You can continue to use the app while loading network folders.
3. Network folders will be displayed on the sidebar.

### CODE REVIEW

**Review by 0x5bfa — APPROVED** [review]
We should use IAsyncEnumerable in the future while current implementation doesn't allow for now, and it's out of scope of this PR.

**Comment by hishitetsu** [comment]
This PR displays network computers instead of network locations added as shortcuts. Should both be displayed?

**Comment by yaira2** [comment]
> This PR displays network computers instead of network location shortcuts. Should both be displayed? Explorer displays only network computers in the sidebar, but Files doesn't have any other locations to display network location shortcuts.

Should we try both and adjust based on feedback?

**Comment by yaira2** [comment]
Small chance but does this help for #13087?

**Comment by hishitetsu** [comment]
> Small chance but does this help for #13087?

No, that is the problem with loading quick access items, not network locations or computers.

**Comment by hishitetsu** [comment]
> > This PR displays network computers instead of network location shortcuts. Should both be displayed? Explorer displays only network computers in the sidebar, but Files doesn't have any other locations to display network location shortcuts.
> 
> Should we try both and adjust based on feedback?

Shouldn't I have changed it to show both network locations and network computers?

**Comment by yaira2** [comment]
If we only show network computers, where would we show locations? On the home page?

**Comment by hishitetsu** [comment]
> If we only show network computers, where would we show locations? On the home page?

There are no places to display it now, but I think it should be displayed on the home page. Maybe we should create a widget for it.
https://github.com/files-community/Files/issues/5135

**Comment by yaira2** [comment]
That sounds fair, in that case we can leave this PR as is.

**Pull request merged**
