### PR TITLE
Feature: Lazy load Git properties for better performance

### LINKED ISSUE #13182: Bug: Hidden Git columns are still being calculated
### Description

The data for the Git columns is calculated even when the columns are hidden. This leads to unnecessary resource consumption and should be an easy way to improve performance in Git repos.

### Steps To Reproduce

1. Hide all the Git columns in the Details layout
2. Observe that the memory isn't freed up

### Requirements

- only load Git data for visible columns
- free up data if a column is hidden

### Files Version

v2.5.21

### Windows Version

Windows 11

### Log File

NA

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #13182 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [X] Are there any other steps that were used to validate these changes?
   Git properties will not be loaded in the following cases.
      * The layout is other than the details layout.
      * All Git columns are hidden in the details layout.
   When the above cases are no longer met, Git properties loading will begin.

### CODE REVIEW

**Comment by hishitetsu** [comment]
I think it is more efficient to retrieve all Git properties at the point of showing one Git property rather than retrieving a value each time, since accessing the Git repository has great impact on performance.

**Comment by yaira2** [comment]
By default we only show two of the Git columns, I guess with this change we should hide all of them for better performance.

**Comment by hishitetsu** [comment]
I see, it may take some time, but I'll see if there is a better way.

**Comment by hishitetsu** [comment]
I did a little research and found that Git properties are retrieved together as commit information except for status, so I'm afraid that not initializing properties that are not displayed will not improve performance.

image

**Comment by yaira2** [comment]
How about hiding the columns by default (except for status)?

**Comment by hishitetsu** [comment]
> How about hiding the columns by default (except for status)?

Performance can be improved if commit information is not retrieved. However, if status and commit information are retrieved at different times, the total processing time will increase because the repository is accessed twice.

**Comment by hishitetsu** [comment]
@yaira2 status and commit information can now be loaded at different times. Also, the default git column to display is now status only.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by hishitetsu** [comment]
I don't know, but if you fix the layout to something other than the details layout and there are still performance problems, there might be other causes. Git properties shouldn't be loaded other than the details layout.

**Comment by yaira2** [comment]
I'm having a tough time reproducing the issue consistently, interestingly it's mainly happening in the same folder but even that doesn't repro consistently.

**Pull request merged**
