### PR TITLE
Change wording to "Pin to Favorites"

### LINKED ISSUE #4317: Change wording to "Pin to Favorites"
Suggestion: change the terminology slightly to more closely relate "Favorites" to pinning. 

At present the commands to pin are (depending on what right-click menu is used):
* "Pin to sidebar"
* "Pin directory to sidebar"

Suggested alternative:
* "Pin to Favorites"

Note that Favorities is capitalised as its the name of part of the UI. 

**Describe alternatives you've considered**
Also considered "Add to Favorites", but Windows Explorer uses the term "Pin" so I went with that.

**Additional comment**
Windows Explorer calls the area "Quick access" which is an OK alternative name. One advantage of that term is that it avoids the 2 spellings of "favorites" and "favourites", but that is not a big issue.

### PR DESCRIPTION
**Pull request by oleitao**
**Resolved / Related Issues**
- Closes [#4317](https://github.com/files-community/Files/issues/4317)

**Details of Changes**
Changed the terminology on commands "Pin to sidebar", "Pin directory to sidebar" to "Pin to Favorites"

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao Can you remove the old string? Also, can you revert the changes to the string files to make the review easier (with the exception of en-US)?

**Comment by oleitao** [comment]
> @oleitao Can you remove the old string? Also, can you revert the changes to the string files to make the review easier (with the exception of en-US)?

@yair100 please verify if requested changes are all right

**Comment by yaichenbaum** [comment]
@oleitao It looks like the string files are still modified, besides for the en-US resource files, can you revert the changes to the other resource files?

**Comment by oleitao** [comment]
> @oleitao It looks like the string files are still modified, besides for the en-US resource files, can you revert the changes to the other resource files?

> Can you remove the old string?

I @yair100  removed BaseLayoutItemContextFlyoutPinToSidebar and BaseLayoutContextFlyoutPinDirectoryToSidebar from MultilingualResources  folder


> Also, can you revert the changes to the string files to make the review easier (with the exception of en-US)?

As well as reverted removed BaseLayoutItemContextFlyoutPinToSidebar and BaseLayoutContextFlyoutPinDirectoryToSidebar from all Strings folders  with exception of en-US

> (with the exception of en-US)

**Comment by yaichenbaum** [comment]
@oleitao It doesn't look like your changes got pushed, can you try again?

**Comment by tsvietOK** [comment]
@oleitao There is should be changed only two files: ContextFlyoutItemHelper.cs and Strings\en-US\Resources.resw

**Comment by oleitao** [comment]
> @oleitao There is should be changed only two files: ContextFlyoutItemHelper.cs and Strings\en-US\Resources.resw
> And resolve conflicts, please.

@tsvietOK please check my last changes as your resquested

**Comment by tsvietOK** [comment]
> > @oleitao There is should be changed only two files: ContextFlyoutItemHelper.cs and Strings\en-US\Resources.resw
> > And resolve conflicts, please.
> 
> @tsvietOK please check my last changes as your resquested

Why 30 files are changed in this PR?

**Comment by oleitao** [comment]
> > > @oleitao There is should be changed only two files: ContextFlyoutItemHelper.cs and Strings\en-US\Resources.resw
> > > And resolve conflicts, please.
> > 
> > 
> > @tsvietOK please check my last changes as your resquested
> 
> Why 30 files are changed in this PR?

Because i did two commits. And I've to revert all changes to the begin point.
And apply my changes only to ContextFlyoutItemHelper.cs and Strings\en-US\Resources.resw

**Review by tsvietOK — APPROVED** [review]

**Pull request merged**
