### PR TITLE
Update Hungarian language

### PR DESCRIPTION
**Pull request by szabolcstarnai**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related #8066

**Details of Changes**
Add details of changes here.
- Added translations for strings in Hungarian

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@szabolcstarnai before we merge this, can you add your agreement to #7625?

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by szabolcstarnai** [comment]
Done 😄

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
> Done 😄

Thank you!

**Pull request merged**
