### PR TITLE
Feature: Removed toolbar from homepage

### LINKED ISSUE #16577: Feature: Hide toolbar when in homepage
### What feature or improvement do you think would benefit Files?

Currently, the toolbar displays "home" when in the homepage:

Image

This isn't really necessary as "Home" is already displayed in the address bar and also the side pane. The toolbar should be hidden when inside the homepage for maximum UI simplicity

### Requirements

- Hide toolbar when in homepage

### Files Version

3.8.1.0

### Windows Version

10.0.22631.4541

### Comments

_No response_

### PR DESCRIPTION
**Pull request by Lamparter**
**Resolved / Related Issues**

- Closes #16577

**Steps used to test these changes**

1. Opened Files
2. Saw toolbar is hidden

### CODE REVIEW

**Comment by 0x5bfa** [comment]
ShowToolbar is completely different setting here. I don't think this works when you switch between tabs.

**Comment by yaira2** [comment]
> ShowToolbar is completely different setting here. I don't think this works when you switch between tabs.

This is correct

**Comment by Lamparter** [comment]
> ShowToolbar is completely different setting here. I don't think this works when you switch between tabs.

It does work

**Comment by yaira2** [comment]
This will cause the toolbar to show even if the user turned it off from settings.

**Comment by yaira2** [comment]
@Lamparter you can do this by modifying the toolbar visibility in `MainPage.xaml`.
```xml
Visibility="{x:Bind converters:MultiBooleanConverter.AndConvertToVisibility(SidebarAdaptiveViewModel.PaneHolder.ActivePaneOrColumn.InstanceViewModel.IsPageTypeNotHome, ViewModel.ShowToolbar), Mode=OneWay}" />
```

**Comment by 0x5bfa** [comment]
Well, I would do the same as what I do for displaying "Home" inside Toolbar.

**Comment by yaira2** [comment]
Looking good! Can you please remove the header from the toolbar control now that it's no longer used?

**Comment by Lamparter** [comment]
What do you mean?

**Comment by yaira2** [comment]
In `InnerNavigationToolbar.xaml`.

**Pull request merged**
