### PR TITLE
Ability to directly move an item to another directory

### LINKED ISSUE #946: Ability to directly move an item to another directory
Please add an option to directly move an item to another directory similar to the "Move to" option in File Explorer's ribbon.

### PR DESCRIPTION
**Pull request by esibruti**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #946

**Details of Changes**
Add details of changes here.
- Added option to move items.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Observation**
I need someone to test this feature because I was testing it and my Visual Studio started having problems. Does anyone mind testing for me?
Edit: I've already managed to solve the problem.

### CODE REVIEW

**Comment by esibruti** [comment]
@gave92 Don't you mind helping me? It's giving me error in the code that I can't solve by myself...

**Comment by gave92** [comment]
@esibruti what issue are you facing? On a first try this PR is working for me.

**Comment by gave92** [comment]
Hi @esibruti, I've simplified code a bit and reverted changes to xlf files (they make reviewing PRs pretty annoying). Are you still experiencing an issue? If it was this one: `//Problem - The collection contains item(s) that can't be converted to read-only form.'` the solution would have been: `dataPackage.SetStorageItems(items, false); <- note the false here` but it's not necessary with my edits.

**Comment by gave92** [comment]
@yair100 could you confirm whether this was what you had in mind for #946? As it currently is (don't know if @esibruti had something in mind) I don't see the added value with respect to simply cut/paste. Perhaps a submenu should be added with a bunch of common destinations/recently visited folders (the explorer Send To menu as a rough idea).

**Comment by esibruti** [comment]
@gave92 in fact, I picked up a lot of code from a previous attempt to resolve this issue. Tomorrow, hours from Portugal, I will test the changes. Thank you for your help :)
I had in mind to make a menu like you said earlier, where you have varied locations or recently used locations... I'll show you tomorrow a sketch made in Paint that shows the idea. That's why the pr is still in draft. But it turns out... I don't know how to make dialogs... I wanted to use the mockup of the decompress zip files dialog but I don't know how to make dialogs. Wouldn't it be a problem for them to teach me how to do that?
But yes, that was the idea, just as you said Gave.
Once again, thanks for the help in the code.

**Comment by yair100** [comment]
> @yair100 could you confirm whether this was what you had in mind for #946? As it currently is (don't know if @esibruti had something in mind) I don't see the added value with respect to simply cut/paste. Perhaps a submenu should be added with a bunch of common destinations/recently visited folders (the explorer Send To menu as a rough idea).

@gave92 yeah, I approved it to start a discussion but there doesn't seem to be enough interest to continue exploring this.

**Comment by esibruti** [comment]
@yair100 So does it mean it's not worth continuing with this pr?
Because with that, we can add the function of creating shortcut, it could send it to a bluetooth device or else to the folder of an open tab or the secondary panel... there are many ideas that could be developed with this function.
If you let it continue, and if @gave92 can also help me with the dialogs and the code, we can create a very good and innovative feature here.

**Comment by yair100** [comment]
> @yair100 So does it mean it's not worth continuing with this pr?

Yeah, let's hold off on this for now. As a side note, we're focusing on improving the reliability of Files 2.0 right now so if you're looking for things to work on, it would be great if you can help with fixing bugs 🙂

**Comment by esibruti** [comment]
@yair100 So in this case, I'm not going to delete this branch. Later, we can pick up this work that's here.

**Pull request closed without merging**
