### PR TITLE
Feature: Added Support for Proton Drive

### LINKED ISSUE #12851: Feature: Add support for "Proton Drive" (cloud drive)
### What feature or improvement do you think would benefit Files?

It's still in closed beta on windows but I got access and can provide all necessary data (and a temporary test account if necessary).
Proton Drive -> https://proton.me/drive
Information to the roadmap -> https://proton.me/blog/proton-drive-roadmap

Uses following folder:
`C:\Users\%username%\Proton Drive\<ProtonUsername>`

### Requirements

- This proposal will make the Proton Drive folder visible under "Cloud Drives".

### Files Version

2.5.11.0

### Windows Version

10.0.22621.1928

### Comments

If you want to implement it (and I would be very grateful about that:) and test it, feel free to contact me via [Discord](https://discord.com/users/95664603219482625).

### PR DESCRIPTION
**Pull request by nephi-duff**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12851 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Ensure Proton Drive is installed
   2. Open app ...
   3. Expand "Cloud Drives"
   4. Observe "Proton Drive" in the list
   5. Add a "test" folder in the Proton Drive web UI.
   6. Wait for sync, observe test folder in app.

**Screenshots (optional)**
Screenshot 2023-09-19 195633

Screenshot 2023-09-19 195627

### CODE REVIEW

**Comment by nephi-duff** [comment]
> If you open Proton drive in the cloud drive section, which folder (path) gets opened?

It opens the "my_drive" folder or something similar. You don't have to drill once you click "Proton Drive" in the side bar.

**Comment by hez2010** [comment]
Does Proton Drive allow to be installed to a customized path other than ProgramFiles? If yes we may need to change the detector to use a value from registry instead of the default ProgramFiles.

**Comment by nephi-duff** [comment]
> Does Proton Drive allow to be installed to a customized path other than ProgramFiles? If yes we may need to change the detector to use a value from registry instead of the default ProgramFiles. 
Good point. I'll look into it later today.

**Comment by gave92** [comment]
Hi! Please see https://github.com/HorseBandit/Files/pull/3 for a simpler approach for detecting Proton Drive. It's the same way we use already for detecting MEGA, iCloud, Amazon & others.

**Comment by nephi-duff** [comment]
> Hi! Please see https://github.com/HorseBandit/Files/pull/3 for a simpler approach for detecting Proton Drive. It's the same way we use already for detecting MEGA, iCloud, Amazon & others. No need to detect installed location or rely on proton's config files.

Looks great, thanks @gave92

**Review by gave92 — APPROVED** [review]

**Comment by yaira2** [comment]
@nephi-duff thank you for your contribution.

**Pull request merged**
