### PR TITLE
ItemViewModel: Remove circular dependency with IShellPage

### PR DESCRIPTION
**Pull request by duke7553**
Improves code quality. Unfortunately, no positive impact on memory usage.

### CODE REVIEW

**Comment by d2dyno1** [comment]
`ItemViewModel` has `FolderSettingsViewModel` - which has `IShellPage` instance so there is still circular dependency

**Comment by d2dyno1** [comment]
Looks fine to me

**Review by tsvietOK — CHANGES_REQUESTED** [review]
Resolve conflicts, please.

**Review by tsvietOK — APPROVED** [review]

**Review by d2dyno1 — APPROVED** [review]

**Comment by gave92** [comment]
Is it just me or after this Recycle Bin is broken? :)

**Pull request merged**
