### PR TITLE
Improve preview pane design

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
#4396 

**Details of Changes**
Updated design, as discussed.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
image
image

### CODE REVIEW

**Comment by tsvietOK** [comment]
There is wrong video duration displayed.
image
image

**Comment by tsvietOK** [comment]
What about to add tooltip or word wrap to the item name? 
image

**Comment by winston-de** [comment]
> There is wrong video duration displayed.
> image
> image

@tsvietOK The video duration issue is fixed in #4431.



> What about to add tooltip or word wrap to the item name?
> image

Good idea! I'll do it for the type as well.

**Comment by winston-de** [comment]
Here's how it looks with wrapping
image

**Comment by tsvietOK** [comment]
What about long item path?

**Comment by winston-de** [comment]
It did have scrolling, but I guess since the values are stacked vertically it makes more sense to wrap them instead.
image

**Review by tsvietOK — APPROVED** [review]

**Pull request merged**
