### PR TITLE
Add folder properties to ribbon, right-click menu

### LINKED ISSUE #49: right clicking in blank area
right clicking on a blank area should have a few options such as

- [x] new items
- [x] open powershell (maybe only for users who will choose a setting for advanced options)
- [x] open properties for the directory

### PR DESCRIPTION
**Pull request by jeffsieu**
Adds the ability to view folder properties.

Screenshots:
image
image

Closes #49

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@jeffsieu I would like to include this in the next release, would you be able to resolve the merge conflicts?

**Comment by jeffsieu** [comment]
@yair100 Sure

**Comment by jeffsieu** [comment]
Alright, done.

**Comment by yaichenbaum** [comment]
Thank you!

**Comment by yaichenbaum** [comment]
It appears to only be on the photo view, did you add it to the regular view as well?

**Comment by jeffsieu** [comment]
Hmm, I did test this on the regular list view.

**Comment by yaichenbaum** [comment]
I am fairly certain it used to work there as well, possibly when you merged in the new changes it messed it up?

**Comment by jeffsieu** [comment]
Oh oops, I think it got added under "New", due to some error in copy pasting 😅

**Pull request merged**
