### PR TITLE
Increased the touch target size for the chevrons on the breadcrumb bar

### LINKED ISSUE #1695: Increase the size of the touch target for the chevron on the Breadcrumb Bar levels

### PR DESCRIPTION
**Pull request by yair100**
Fixes #1695

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Fyi @mdtauk.

**Comment by lukeblevins** [comment]
@yair100 Was this change in your other PR?

**Comment by yaichenbaum** [comment]
@duke7553 No.

**Comment by lukeblevins** [comment]
@yair100 Some of these aren't the same as what's in this PR?
image

**Pull request closed without merging**
