### PR TITLE
Fix context menu

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fix context menu items not all appearing
- Fix app crashing when invoking context menu items

**Details of Changes**
Add details of changes here.
- Context menu enumeration must happen on a STA thread
- Context menu items must be invoked on the same thread the menu was created in

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by hez2010** [comment]
I also noticed this issue and have the fix in #9865 :)

**Comment by gave92** [comment]
Not enough unfortunately. That fixes the missing items but clicking any item will crash the app due to context menu item being invoked on a different thread from where the context menu was created.

**Comment by hez2010** [comment]
Seems that the underlaying RCW got disposed early.

```
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Vanara.PInvoke.Shell32.IContextMenu.InvokeCommand(CMINVOKECOMMANDINFOEX& pici)
   at Files.App.Shell.ContextMenu.InvokeItem(Int32 itemID)
   at Files.App.Helpers.ShellContextmenuHelper.<LoadMenuFlyoutItem>g__InvokeShellMenuItem|1_2(ContextMenu contextMenu, Object tag)
   at Files.App.Helpers.ShellContextmenuHelper.<>c__DisplayClass1_0.<LoadMenuFlyoutItem>b__7(Object x)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1.Execute(Object parameter)
   at ABI.System.Windows.Input.ICommand.Vftbl.Do_Abi_Execute_3(IntPtr thisPtr, IntPtr parameter)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IControlOverridesMethods.OnPointerReleased(IObjectReference _obj, PointerRoutedEventArgs e)
   at Microsoft.UI.Xaml.Controls.Control.OnPointerReleased(PointerRoutedEventArgs e)
   at Microsoft.UI.Xaml.Controls.Control.Microsoft.UI.Xaml.Controls.IControlOverrides.OnPointerReleased(PointerRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.IControlOverrides.Do_Abi_OnPointerReleased_3(IntPtr thisPtr, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at WinRT.EventSource__EventHandler`1.EventState.<GetEventInvoke>b__1_0(Object obj, T e)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by gave92** [comment]
Should be fixed

**Comment by hez2010** [comment]
> Should be fixed

Great. I've removed my (incomplete) fix from #9865 to avoid the merge conflict.

**Comment by gave92** [comment]
> Should be fixed
Works for u as well? Great!

Unfortunately now the app does not close anymore xD (process stays open)

**Review by yaichenbaum — APPROVED** [review]
LGTM
In the future, we might want to add some code comments but this is fine as is 🚀

**Comment by gave92** [comment]
> LGTM
> In the future, we might want to add some code comments but this is fine as is 🚀 

Sorry about that, tricks like this should totally be documented:
> Context menu enumeration must happen on a STA thread
Context menu items must be invoked on the same thread the menu was created in

**Pull request merged**
