### PR TITLE
Native ARM64 Support

### LINKED ISSUE #3365: .NET error
This issue was previously reported by another user but since then closed. I have the same issue now, thus reposting the error. Would greatly appreciate help on this.

Describe the bug

FilesFullTrust.exe - .NET Framework Initialization Error
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll could not be loaded

See error message:
files-screenshot-errormessage

The message pops up three times in a row in overlapping dialogs.

I am not receiving this message in any other programs.

Files Version 1.1.5.0 did not resolve the issue.
Resetting the app did not help.
I am on Windows Insider Build 210115-1423, but the Problem existed for a while already.
I am on Windows on Arm on a Surface Pro X.

debug.txt content from last launch:

`2021-01-25 12:14:52.0375|INFO|GetClassFullName|App launched|`
`2021-01-25 12:14:52.5244|INFO|GetClassFullName|Drive added: C:\, Fixed|`
`2021-01-25 12:16:43.3654|INFO|GetClassFullName|Running on ARM: True|`

mscoreei.dll exists in folder C:\Windows\Microsoft.NET\Framework64\v4.0.30319 with file version 4.8.4161.0 
All users or group have at least "Read & execute" permission

_Originally posted by @kn0xit in https://github.com/files-community/Files/issues/2860#issuecomment-766751233_

### PR DESCRIPTION
**Pull request by gus33000**
**Resolved / Related Issues**

- Closes #3365 
- Related #64 #1247 #2860

**Details of Changes**

This pull request brings full ARM64 native support to the Files application. This improves greatly the user experience for ARM64 users as well as overall performance and resource usage of the application, in environments were power optimizations matter the most. It has been verified working on an ARMv8 device running in ARM64 context under Windows 11 Build 22499 for ARM64 Processors. This pull request achieves this by:

- Converting the Files.Launcher project to the newly released .NET 6
- Fixing API calls that were broken due to ABI changes with newer .NET versions
- Migrating away from the deprecated System.Management library (more information available here: https://github.com/dotnet/runtime/issues/45143) and instead using the supported Microsoft Management Infrastructure (MMI) library
- Apply a set of project configuration workarounds due to case sensitive MSBuild scripts for Windows Application Packaging Projects and an incompatibility with newer .NET releases
- Updating the CI pipeline files and ensuring they work on azure pipeline (The regular non release pipeline has been tested working)
- Enabling ARM64 support for all project components in the solution via configuration
- Enabling ARM64 support for Custom Open Dialog and registering it inside Files.Launcher*

*~~This feature does not seem to work, the option reverts by itself and it looks like the component never gets registered. I am not too sure about the status of this feature. The code to register the components looked like it was meant for X86 only and surely would not work on AMD64 or anything else, due to it attempting to register x86 first, which would not work on X64 or ARM64 packages, maybe this needs to be looked into. I doubt this is an issue caused by my PR.~~

Turns out it this was caused by a different issue fixed in the last commit. The CustomOpenDIalog component however does not get built by the CI. Referencing the project inside Files.Launcher.csproj makes it build however the xcopy task fails which halts the build process. I believe this issue is not caused by my PR considering the revert commit makes it like before, which is copy the file if it exist or ignore.

**Validation**

- [x] Built and ran the app
- [ ] Tested the changes for accessibility (Does not apply here)
- [x] Tested the non release CI pipeline 
- [x] Ensured ACL dialogs were working as well as MTP device detection due to MMI changes 

**Screenshots (optional)**

Screenshot (13)
Screenshot (14)
Screenshot (15)
Screenshot (16)

### CODE REVIEW

**Comment by gus33000** [comment]
I have reverted 9d5d7e5 because there seem to be an issue with the pipeline setup in this repository where the C++ component does not actually get queued for build, it did on my tests, which is a bit weird. I can remove said commit once this issue is fixed however once again, in my tests, the pipeline worked on my azure devops instance, so I do not understand this issue. (Moreover, it appears the custom file dialog functionality ain't quite working anyway)

**Comment by gus33000** [comment]
Screenshot (7)

QuickLook detection confirmed working, as well as device detection on ARM64.
Context Menus work, icons too, ACL dialog as well.

https://user-images.githubusercontent.com/3755345/141674354-6161c64e-50f4-4b2e-a447-0eb6646aedb0.MOV

**Comment by gus33000** [comment]
Custom file open dialog was verified working by manually registering it (given the option is hidden in the app) and building a package locally (given CI does not build the component). Video below

https://user-images.githubusercontent.com/3755345/141683689-ec930928-fb1a-457f-b043-4f8c930a472b.MOV

.

**Review by yaichenbaum — APPROVED** [review]
Really nice work! Thank you ❤️

**Review by duke7553 — APPROVED** [review]
Great work, Gus! I'll take care of moving to System.Text.Json in a future PR.

**Comment by yaichenbaum** [comment]
@gus33000 is this working for you in release mode?

**Comment by gus33000** [comment]
> @gus33000 is the full trust process working for you in release mode?

Yes it is, see all of my videos posted above.

**Comment by gave92** [comment]
@gus33000 could you take a look at the changes made to DeviceWatcher.cs?
I believe this:
https://github.com/files-community/Files/blob/fe684bcffc5dc947142619c510c23921ba758131/Files.Launcher/DeviceWatcher.cs#L43
should be:
```cs
CimInstance obj = e.NewEvent.Instance.CimInstanceProperties["TargetInstance"].Value
```

**Comment by gus33000** [comment]
> @gus33000 could you take a look at the changes made to DeviceWatcher.cs? I believe this:
> 
> https://github.com/files-community/Files/blob/fe684bcffc5dc947142619c510c23921ba758131/Files.Launcher/DeviceWatcher.cs#L43
> 
> 
> should be:
> ```cs
> CimInstance obj = e.NewEvent.Instance.CimInstanceProperties["TargetInstance"].Value
> ```

Looking into it now, just woke up so that might take some time

**Comment by gus33000** [comment]
@gave92 Had a look with a debugger, you're right looks like an issue stepped in here. I'm going to do a PR to address this. Thanks for shedding light on this!
image

**Comment by gave92** [comment]
Thanks, with the current code I'm getting NullReferenceException as e.NewEvent.Instance.CimInstanceProperties does not have Name / DeviceID properties (but it has a TargetInstance property of type win32_logicaldisk)

**Pull request merged**
