### PR TITLE
Cache folder sizes

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
The size of the folders is recalculated at each display. It should be cached. #7327

**Details of Changes**
The size of the folders is kept in cache, as well as the sub-folders limited to 3 levels. When the size is displayed from the cache, it is recalculated asynchronously and the corrected value is displayed when available. The cache is cleaned of disconnected disks.

Cache is not persisted between sessions but I will try to add this feature later.

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by cinqmilleans** [comment]
@yair100 @d2dyno1 I made a major commit to this pr:
1) The code that handles folder sizes has been moved to a new service. Benefits: less static and more isolation. This will also improve this part (persistence, memory, ...)
2) Total size is displayed when nothing is selected #7961. 
3) The cache is completely emptied when you deactivate the ShowFolderSize option.

**Comment by BanCrash** [comment]
> @yair100 @d2dyno1 I made a major commit to this pr:
> 
> 1. The code that handles folder sizes has been moved to a new service. Benefits: less static and more isolation. This will also improve this part (persistence, memory, ...)
> 2. Total size is displayed when nothing is selected [Always display the size in the status bar when ShowFolderSize is enabled #7961](https://github.com/files-community/Files/issues/7961).
> 3. The cache is completely emptied when you deactivate the ShowFolderSize option.

Hi @cinqmilleans , thanks for letting us know. I don't have much free time those days since I'll have an important exam in 2 weeks, but I started the review with some tests this morning with the old version. I will restart the reviewing process with the new version tomorrow.

**Comment by BanCrash** [comment]
@cinqmilleans could you resolve conflics please?

**Comment by BanCrash** [comment]
@cinqmilleans you are merging main branch, but currently the base branch in this PR is infrastructure.

@yair100 is this PR supposed to target infrastructure?

**Comment by yaichenbaum** [comment]
@BanCrash `main`

**Review by BanCrash — APPROVED** [review]
LGTM

@cinqmilleans as a feature request for a future PR (if you want), I suggest to reuse the cached size value when opening folder properties (just in case you didn't have it already planned).

**Comment by cinqmilleans** [comment]
@BanCrash Thank you and yes it is already planned.

**Comment by cinqmilleans** [comment]
@BanCrash I would like to thank you for your review work. It's hard work and not recognized enough.

**Comment by BanCrash** [comment]
> @BanCrash I would like to thank you for your review work. It's hard work and not recognized enough.

Thank you, I appreciate it 😄 Thank you for your work on these PRs too, I'm waiting for your filters to make some reorganization of my files 😉

**Pull request merged**
