### PR TITLE
CommandPrompt Activation

### PR DESCRIPTION
**Pull request by FelixZacher**
# Description

I added the "AppExecutionAlias" `files.exe`, so the app can be launched from any command prompt.

In the folder `%localappdata%\Microsoft\WindowsApps` is now `files.exe` created, which helps #236.

I also did some testing with opening files in the current directory from the cmd, but there is currently a race condition between the app startup and the `PopulateDrivesListWithLocalDisks`-method, which does not populate the list fast enough. At a normal start from the cmdline, it always crashes, in the debugger with a breakpoint not. This only occurs if files wants to show the current directory.

# Questions

I would love some input on the cmdline-protocoll: Which commands, ...

PS:
The code as is does not support open in a directory, but works, in that it opens files. Don't know if you want to merge this as whole or as little parts.

### CODE REVIEW

**Comment by lampenlampen** [comment]
# Do not merge

Please do not merge. Code is broken.

**Comment by lampenlampen** [comment]
I added a parser and implemented the command:

```
files.exe -Directory C:\Users
```

!!!The crash is not fixed!!!

**Comment by duke7553** [comment]
@lampenlampen Would threading be a way out of the race condition?

**Comment by lampenlampen** [comment]
I'm currently trying to convert the list to a task-based approach, so we can await them.

**Comment by duke7553** [comment]
@lampenlampen The WIP branch for the settings view model might simplify/remove some of the list items.

**Comment by lampenlampen** [comment]
I had a look at the branch and i basically had the same idea. You can have a look at https://github.com/lampenlampen/files-uwp/commit/496a84e2c2f0efd7e3f6f4571d97bd297a13ce01.

I extracted all "drives"-related things to it's own class and added an `Drives`-property to the `SettingsViewModel`.

Please leave a short answer, if you want to refactor these yourself or i can go ahead.

**Comment by duke7553** [comment]
Your implementation looks better than mine! For now, don't worry about my branch, as I can refactor those changes later

**Comment by duke7553** [comment]
@lampenlampen I probably won't have the time to make any refactors myself until Friday at the earliest, so if you can that would be excellent!

**Review by lukeblevins — APPROVED** [review]
Looks great. We should now work on ironing out that race condition. @lampenlampen said he would look into it.

**Comment by lampenlampen** [comment]
@duke7553 I saw that your are using "mvvmlight" and `ViewModelBase`. I had a brief look at their github repo, but docu is a bit rare there. Can you point me to something, that explains `ViewModelBase`.

**Comment by lukeblevins** [comment]
This sounds like a question for @yair100 😀

**Comment by yaichenbaum** [comment]
I would check out http://www.mvvmlight.net/

**Pull request merged**
