### PR TITLE
Improve layout mode switching

### PR DESCRIPTION
**Pull request by gave92**
Avoids reloading the folder contents when switching from ListView to Tiles or Grid view and between different GridView sizes.
Also fixes changing layout mode in search page

### CODE REVIEW

**Review by yair100 — DISMISSED** [review]

**Comment by gave92** [comment]
@yair100 with the animations when switching from datagrid to tilesview I see items with the wrong icon (e.g files with a folder icon) then it fades to the correct one

**Comment by yair100** [comment]
> @yair100 with the animations when switching from datagrid to tilesview I see items with the wrong icon (e.g files with a folder icon) then it fades to the correct one

Do you think this can be fixed by only showing the "add item" animation?

**Comment by gave92** [comment]
Perhaps I'd just wait to add animations, when switching layout there's an ugly moment in which you see a gray background to the items. We'd probably need to fix that anyway before thing to animations.

ezgif com-gif-maker

**Comment by mdtauk** [comment]
That odd refresh, perhaps you could have a placeholder icon until the grid item content has loaded

**Comment by gave92** [comment]
@yair100 sorry this turned out bigger than I thought.
Switching layout mode or gridview size doesn't trigger a refresh anymore even between Datagrid and TilesView

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Amazing job!

**Pull request merged**
