### PR TITLE
Updated portuguese (PT) translation

### PR DESCRIPTION
**Pull request by esibruti**
**Details of Changes**

- Updated pt-PT strings

### CODE REVIEW

**Review by afonsojramos — DISMISSED** [review]

**Comment by afonsojramos** [comment]
Thank you for the retroactive changes! Looks good to me @yair100

**Review by afonsojramos — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@afonsojramos @veryprofessionaldodo thank you for helping review these pull requests, it's a major help to have issues ironed out so that when we're ready, someone from the team can just take a quick look and approve since all required changes have already been made 🚀

**Comment by afonsojramos** [comment]
@yair100 you got it! I'll try to get a bit more involved in this project with time! 🚀

**Comment by esibruti** [comment]
> Sorry @esibruti , been a little busy and I didn't see I had another PR waiting for review. I will check this not later than tomorrow (hopefully today).

That way, I updated the pr with changes from the last few days and that's how new strings are translated.

**Review by BanCrash — APPROVED** [review]

**Comment by yair100** [comment]
> @yair100 you got it! I'll try to get a bit more involved in this project with time! 🚀

@afonsojramos looking forward!

**Pull request merged**
