### PR TITLE
Code Quality: Improved the way of instancing OpacityIconModel

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title.

## PR Checklist

- [x] **Development**: #4180
- [ ] **Approval**: Have discussed with and got approval from the team[^1]
- [x] **Tests**: Tested accessibility on the local end
- [x] **Deployment**: Deployed the app on the local end
- [ ] **Localization**: Modified en-US string resources[^2]
- [ ] **Co-authors**: _N/A_

## Screenshots

_N/A_

[^1]: If the request hasn't been agreed by the team, this work might be rejected. Make sure that you get approval from the team before opening any PR related the request.
[^2]: If you removed any en-US string resources, make sure that there are no references of those resources. When you add a new en-US string resources, do not make any changes on other languages' resources; [Crowdin](https://crowdin.com/project/files-app) will do that, instead.

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by hishitetsu** [comment]
@0x5bfa @yaira2 This change prevents the context menu from being displayed.
image

**Comment by yaira2** [comment]
I reverted the PR

**Comment by yaira2** [comment]
@0x5bfa in the future, please use the official pull request template so we can confirm the changes were properly tested.

**Comment by 0x5bfa** [comment]
i've tested around changes since the last happening like this other than this kind of change. I'll make sure. Sorry!

**Pull request merged**
