### PR TITLE
await to check the double-click on selected item when renaming

### LINKED ISSUE #2967: Double clicking on name of selected items always enters "rename" mode
**Describe the bug**
When I select an item in the files list (details view), file or folder, and then double click on the name, instead of opening the file or opening the folder, it goes into rename mode where I can change the name. This does not happen when clicking anywhere else in the area of the selected item, only in the area of the "name" column.

**To Reproduce**
Open any folder location, switch to "Detail view", select a file or folder by single clicking it, then double click in the "Name" column area of selected item. 
The "Rename" mode will be initiated where you can alter the items name, instead of opening the item.

**Expected behavior**
I expect an item to open when double clicking it, selected or not.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home, Version 20H2, OS Build 19042.746, Windows Feature Experience Pack 120.2212.551.0
 - App version: 1.0.0.0
 - Hardware:
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	12.0 GB (11.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Additional context**
No change in context, misbehaviour is constant.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5808293/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5808294/debug.txt)

### PR DESCRIPTION
**Pull request by xwnb**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #2967

**Details of Changes**
Add details of changes here.
- [x] Prevent rename when double-click on selected item (further commit based on #5635)

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by xwnb** [comment]
please help review it at your convenience. Thanks @gave92 .

**Comment by gave92** [comment]
@xwnb I've pushed a couple of changes, I hope you don't mind. Changes:
- Fix an issue where double-clicking on an already selected file would open it but also start renaming
- Consider keyboard selection as a valid "first click" for triggering rename (like explorer does)

**Review by gave92 — APPROVED** [review]

**Comment by xwnb** [comment]
It still starts renaming when double-click on a selected item.

**Comment by xwnb** [comment]
Is the timer necessary? @gave92

**Comment by xwnb** [comment]
I make a change for `IntervalSampler`.  `DateTime` will be influenced by the system date setting. Maybe `Stopwatch` is more reliable.

**Comment by gave92** [comment]
I'd revert the last two commits because:
- 0010c86: causes double clicking on a selected item to also trigger rename
- 96a2393: I don't think it's worth it, user is not likely to change datetime settings every 500ms. Also changing `DateTime.Now` to `DateTime.UtcNow` would probably accomplish the same thing without having to run a timer.

**Comment by xwnb** [comment]
https://github.com/files-community/Files/commit/0010c8650b56309b0fa0b55f1a100e574dfcd38a : Based on the previous commit, `preRenamingItem` will be reset when double-click to open a folder. when `Debounce()` delay invoked, there is a double-check `preRenamingItem`. I think it can work well on this case and be more stable and elegant than the Timer.

https://github.com/files-community/Files/commit/96a2393f8934e6de1baa3772c216b01c517b020e: Consider the situation: click item and then change the date time, not the time zone. I think the time measurement won't work well. That's why I perfer using Stopwatch to measure time if I need Timer or Samper.

**Comment by gave92** [comment]
> 0010c86: I've tested it and I can confirm that the issue is present: double clicking a selected item will also start rename. That's because the double tapped event is fired _before_ the first item click event and resetting preRenaming item has no effect.

> 96a2393: could be a valid point but where IntervalSampler is used we don't need any particular precision

**Comment by xwnb** [comment]
0010c86: It is a little different on my machine. I saw the double-tapped fired and then call `NavigationHelpers.OpenSelectedItems`, which then invoke ResetRenameDoubleClick to set preRenamingItem==null and the tapDebounceTimer.Stop(). Even though the action in `tapDebounceTimer.Debounce` is invoked after 500ms, the double-check will avoid the call of renaming.

https://user-images.githubusercontent.com/45145954/128384337-f914b370-d9cd-4084-8ba0-127bf9b858d2.mp4

96a2393: it can be reverted.

**Comment by gave92** [comment]
This is what happens if I double click on a selected file: file opens but rename is also triggered.

ezgif com-gif-maker

**Comment by xwnb** [comment]
👍

**Comment by gave92** [comment]
b5ff4c2: reverted my change about setting preRenamingItem in SelectionChanged as it creates issues in ColumnView.

**Review by gave92 — APPROVED** [review]
Looks like it's working pretty well, thank you!

**Pull request merged**
