### PR TITLE
Feature: Added option to hide the Send To menu

### LINKED ISSUE #12546: Feature: Add option to hide "send to" menu
### What feature or improvement do you think would benefit Files?

I would like being able to choose which entries show up in each context menu ; although, as this may not be compatible with the current way context menus have been implemented, or as it may require quite the effort, I would like to ask for an option to hide the "Send to" entry, as it looks out of place, and as I personally find no use in its presence (although this last bit is completely subjective).

### Requirements

- This suggestion will allow for further customisation
- This proposition would bring cohesion to the UI
- This feature could de-clutter each context menu, for those who find no use in the option.

### Files Version

2.4.71.0

### Windows Version

Windows 10 (22H2): 19045

### Comments

The fact that the 'Send to' entry does not feature an icon is what makes it stand out negatively. If none of the aforementioned options were to be implemented or implementable, I definitely think giving it an icon would add to the continuity and cohesion of the Files app's user interface.

Alternatively, one could follow the registry entries that determine whether 'Send to' should be enabled or not. This way, for those which have disabled it already (using third party software like WinaeroTweaker for instance), there would be no redundant setting to toggle.

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12546...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Confirm the Send To menu only shows when the setting is enabled
   2. Test in the widgets as well

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hishitetsu** [comment]
Support for widgets isn't working well.
I think it would work to check the settings here instead.
https://github.com/files-community/Files/blob/d6cbb280425f26b49a5cd4fd04f7431b81387f84/src/Files.App/Helpers/ShellContextMenuHelper.cs#L330-L331

**Comment by hishitetsu** [comment]
Both widgets. All widgets and the sidebar use this method to generate a context menu.

**Comment by yaira2** [comment]
@hishitetsu can you check again?

**Comment by hishitetsu** [comment]
> @hishitetsu can you check again?

It still doesn't work well. I'll look into it.

**Comment by hishitetsu** [comment]
@yaira2 This PR should fix the widgets problem.
https://github.com/files-community/Files/pull/12684

**Review by hishitetsu — APPROVED** [review]
LGTM

**Pull request merged**
