### PR TITLE
Add necessary UIA name binding for datagrid header control

### LINKED ISSUE #5078: a11y: list items for selecting folders, drives and recents have no automation name.
Hello.

i am using the latest version of files app built from the latest codebase.

list items mentioned in title are not readable by the screenreader.

It would be great if you add corresponding names on them.

### PR DESCRIPTION
**Pull request by chingucoding**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5078

**Details of Changes**
Add details of changes here.
- Added missing binding for AutomationProperties.Name property on button inside datagrid header control

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]
Thank you!

**Comment by yaichenbaum** [comment]
@chingucoding whoops, I was a little too fast on that one. #5078 was about widgets on the home page. Each item on the widget page is a ListViewItem.

**Comment by chingucoding** [comment]
I'm a bit confused now what the issue is. If you go to them using narrator, they are read out correctly. Is it about them not being able to be visited using tab navigation?

**Comment by yaichenbaum** [comment]
@chingucoding I'm not sure myself, I guess we should go back to #5078 to see if they can provide more info.

**Pull request merged**
