### PR TITLE
Added more file types to the new file menu

### LINKED ISSUE #2192: Add Office programs to the New menu in the Context (right click) menu
**Is your feature request related to a problem? Please describe.**
Basically, File Explorer has a really useful feature that Files UWP doesn't have which allows the user to easily create Word, PowerPoint, Excel, etc files in the current directory right from the New menu in the context (right click) menu.

**Describe the solution you'd like**
Depending if Office is installed on the user's device, show the Office programs within the New menu of the context menu.

**Describe alternatives you've considered**
Why yes, there are alternatives to achieve this by saving the file to the directory, simply allowing the ability to right click, select New, and selecting Microsoft Word Document, etc would be greatly beneficial for the user.

**Additional context**
image
image

### LINKED ISSUE #2492: Create a "New (generic) file"
**Is your feature request related to a problem? Please describe.**
You can just create a "Text document", a "Folder" and a "Bitmap Image".

**Describe the solution you'd like**
I think it would be very great if you could create a "File" which is a generic file, without any extensions and, if you want to insert an extension, just write "Name.Ext"

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2492
Fixes #2192

image

The file type are fetched from the windows registry and are the same the user sees in the shell context menu. Some may be missing as some file types require launching a program to be created (e.g. Access db files).
This PR also adds a "Create generic file" which allows to create any file type by typing the extension.

The additional file types are added to:
- The New right-click context menu
- The navigation bar New file menu
- The add file dialog

image

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 Should we remove the add file dialog and start using inline editing when creating files the same way File Explorer does it?

**Comment by gave92** [comment]
@yair100 You mean this one right? I think inline editing would be nice, if possible I'd like *not* to address it in this PR though :)

**Comment by yair100** [comment]
> @yair100 You mean this one right? I think inline editing would be nice, if possible I'd like _not_ to address it in this PR though :)
> 
> 

Yes, that is what I was refereeing to. I also think that should be kept separate from this pull request, I just wanted to bring it up since it was related to the changes here.

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Great work!

**Pull request merged**
