### PR TITLE
Command ToggleSelect

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
* Add Command ToggleSelect for (de)select distant items with the keyboard.
* Use hotkey Ctrl+Space.
* Works on all SelectorItem controls, including layout items.
* Works well with Ctrl+Up/Down/Left/Right to focus items with the keyboard without moving in the list/grid (native hotkeys).

- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
Use Ctrl+Up/Down/Left/Right for moving in list/grid. Use Ctrl+Space for (de)select distant items.

**Screenshots (optional)**

https://user-images.githubusercontent.com/46631671/227733686-0fed1665-2ade-48df-9b87-9137f7cf4eff.mp4

### CODE REVIEW

**Comment by yaira2** [comment]
What happens in column layout?

**Comment by cinqmilleans** [comment]
It works the same way. There is no checkbox, but the row is (de)selected. This has the same effect as Ctrl+left click. This command has no relation to our implementation of MultiSelect. This is a command that switches the state of a SelectorItem, the base class implemented by all native controls that have an IsSelected property.

**Comment by ferrariofilippo** [comment]
> It works the same way.

Sometimes Files crashes beacause of an unhandled exception (Columns Layout)
[debug.log](https://github.com/files-community/Files/files/11071267/debug.log)

**Comment by cinqmilleans** [comment]
@ferrariofilippo I was unable to reproduce the problem. I doubt that pr is the cause. It's a simple hotkey to simulate Ctrl+left click. The issue probably existed before.

**Review by yaira2 — APPROVED** [review]
This is cool!
LGTM

**Pull request merged**
