### PR TITLE
Open Files on Windows StartUp

### LINKED ISSUE #5579: Add option to open Files on Windows startup
**Is your feature request related to a problem?**
No

**Describe the solution**
On Windows 10, if you usually work with the same set of folders, instead of having to reopen them manually every time you sign into your account, you can enable an option that allows File Explorer to remember and resume your opened folders at startup automatically. This would be a great addition to Files to promote productivity.

**Describe alternatives you've considered**
Going back to the File Explorer which already does this.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to quickly get back to their files after closing Files | Should |

**System Information**
 - OS Version: 10.0.19044.1149
 - App version: Version: 1.9.15.0

**Additional comment**
N/A

### PR DESCRIPTION
**Pull request by esibruti**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5579 

**Details of Changes**
Add details of changes here.
- Adds the option for Files to start running at Windows startup

image

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by esibruti** [comment]
@gave92 I need your help. RequestEnableAsync() doesn't seem to work. It completely blocks Files. Could you give me a little help?

**Comment by gave92** [comment]
Commit 113911c should fix the issue (using `.Result` on an async Task is often a good way to get a deadlock). Also made so the Toggle gets disabled if the startup task state is DisabledByPolicy or DisabledByUser.

**Comment by gave92** [comment]
Commit 113911c should fix the issue (using `.Result` on an async Task is often a good way to get a deadlock). Also made so the Toggle gets disabled if the startup task state is DisabledByPolicy or DisabledByUser.

**Comment by esibruti** [comment]
@gave92 I just tested it and it's working. You are the greatest. Thank you Gave

**Review by gave92 — APPROVED** [review]

**Pull request merged**
