### PR TITLE
Expand the ribbon

### PR DESCRIPTION
**Pull request by oleitao**
That PR start the implementation of a ribbon toolbar. On this first commit is only UI defined and need more work to implement all features on that new toolbar.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao Thank you for opening this PR! Files used to have a ribbon but we moved away from this design, while this is great work, it doesn't align with our current plans for Files. To prevent future misunderstandings, it's best to always best to wait for an issue to be approved before opening a PR.
That being said, depending on the implementation, we can bring look into bringing back the ribbon to Files. Can you share screenshots of what you were working on?

**Comment by XPoppyX** [comment]
I think that it would not be bad if the ribbon returns, because I suppose that you will add more and more buttons in the navigation bar, at that moment is when it will start to look ugly with so many buttons, and in a ribbon you can add all the options / buttons that are useful without looking ugly since you can collapse it. It depends on the opinion of all of you, maybe you have other ideas.

**Comment by oleitao** [comment]
> @oleitao Thank you for opening this PR! Files used to have a ribbon but we moved away from this design a little over a year ago, while this is great work, it doesn't align with our current plans for Files. To prevent future misunderstandings, it's best to always best to wait for an issue to be approved before opening a PR.
> That being said, depending on the implementation, we can bring look into bringing back the ribbon to Files. Can you share screenshots of what you were working on?



Untitled1
Untitled2
Untitled3

**Comment by yaichenbaum** [comment]
@oleitao Was your idea for a simple toolbar, or were you planning to implement a full ribbon?

**Comment by oleitao** [comment]
> @oleitao Was your idea for a simple toolbar, or were you planning to implement a full ribbon?

@yair100 i'm thinking about to implement a full ribbon.

**Comment by yaichenbaum** [comment]
@oleitao Yeah, so that's not really part of the plan right now. We were planning on adding smart actions to the toolbar that would change depending on what was selected.

**Comment by d2dyno1** [comment]
> @oleitao Yeah, so that's not really part of the plan right now. We were planning on adding smart actions to the toolbar that would change depending on what was selected.

:eyes:
When are you planning to do that? How is that going to work? Is anyone assigned to this? @yair100 
I can try doing the backend stuff

**Comment by yaichenbaum** [comment]
@d2dyno1 I wanted to move existing options there first (layout/selection), the selection flyout should show whenever there is at least one item in a directory. The layout flyout should always be visible with the exception of the home option.

**Comment by jordan-msftfan** [comment]
Is that Files is now planning a simple toolbar that will be included in the new UI update? @yair100

**Pull request closed without merging**
