### PR TITLE
Some UI fixes

### LINKED ISSUE #5477: Settings in compact overlay not responsive
**Explain the bug**
Write a clear description of what the bug is.

**Expected behavior**
It should be horizontally and vertically scrollable to access the buttons

**Screenshots**
image

**System Information**
 - OS Version: Windows 11 21H2 22000.71
 - App version: v1.9.0.0

**Additional comment**
Restarting the app and/or the PC doesn't solve the problem

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5477

**Details of Changes**
Add details of changes here.
- disable selection follows focus in properties dialog
- fix issue where group header sub text would be invisible in light mode
- compact settings dialog for window widths < 641 pixels 
- disable settings in compact overlay (because the window is too small for it to work)
- fix mica control elevation with toolbar and content
- make colored icon accent color slightly lighter in light mode
- fix preview pane background brush to look less out of place
- fix item width for zoomed out view in details view
- remove conditional xaml for windows 11 background brush to fix startup crash
- fix issue where sidebar can't be resized with keyboard
- fix toggling sidebar expanded state with keyboard
- collapse widgets toolbar option label to match others

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image
image

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de can you remove the string for the label?

**Comment by winston-de** [comment]
> @winston-de can you remove the string for the label?

I think it should be kept in so that it will still show in the event the menu overflows

**Comment by yaichenbaum** [comment]
Good point!

**Review by yaichenbaum — APPROVED** [review]
Great work! LGTM

**Comment by gave92** [comment]
Fully white titlebar on n Windows 10 after this PR.. was this expected?
image

**Pull request merged**
