### PR TITLE
Fix drives loading

### PR DESCRIPTION
**Pull request by tsvietOK**
For me removing changes added in 02971da228fde684d2128b0a0802e0b3def6fc70 by @duke7553 fixing issue #563 . Another way to fix that, just remove "await" from dispatcher. Problem somewhere in dispatcher. And when try-catch catched an error "Element not found", drives did not load.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
I think that change was done to fix an issue where the app was crashing for many users. Are you sure this won't bring back that issue?

**Comment by tsvietOK** [comment]
@yair100 May be there was another crash reason?

**Review by lukeblevins — CHANGES_REQUESTED** [review]
While this may fix the issue, we should instead focus on deferring the loading of drives until the UI thread is created instead of always/never loading them.

**Comment by duke7553** [comment]
@tsvietOK Thanks for narrowing down the issue, though-this information can be used to provide a solution for the drives not loading.

**Comment by tsvietOK** [comment]
@duke7553 What do you mean under "instead of always/never loading them"? And why do you want to load drives after UI thread started?

**Comment by duke7553** [comment]
The current implementation will never load the drives list if the UI thread isn't available. We know if an exception is thrown, then the UI thread doesn't exist. iirc the reason we have to populate the drives collection on the UI thread is to prevent occasional crashes on startup.

Therefore, I think the best approach here would be to handle the [catch] by deferring the drives from loading until the page is loaded. Right now, we simply never load the drives if the UI thread doesn't exist yet.

**Comment by tsvietOK** [comment]
@duke7553 I don't agree with current implementation. We can load drives in any time, so when binded collection "sideBarItems" will be changed, ModernSidebar will display drives automatically Try-catch block is unneeded.

**Comment by duke7553** [comment]
@tsvietOK Since we have no definitive evidence that the current implementation fixed any crashes, I'll approve this change because it fixes a bug.

**Review by lukeblevins — APPROVED** [review]

**Pull request merged**
