### PR TITLE
Reduced items in VisualTree for GridViewLayout

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by gave92** [comment]
On shortcut files is now visible the windows shortcut arrow

image

**Comment by yaichenbaum** [comment]
@gave92 I removed the Windows shortcut overlay in favor of the custom one. Do you know why there were two of them to being with?

**Comment by gave92** [comment]
Overlay is not only the arrow icon, it's any folder overlay e.g Google Drive sync status

**Comment by gave92** [comment]
I confirm you can suppress the windows arrow for shortcuts with the following in ItemViewModel.cs, line 667 *and* line 704
```cs
if (!matchingItem.IsShortcutItem)
{
    matchingItem.IconOverlay = fileIconInfo.Overlay;
}

**Comment by yaichenbaum** [comment]
> I confirm you can suppress the windows arrow for shortcuts with the following in ItemViewModel.cs, line 667 _and_ line 704
> 
> ```cs
> if (!matchingItem.IsShortcutItem)
> {
>     matchingItem.IconOverlay = fileIconInfo.Overlay;
> }
> ```

I am trying to align the icons for consistency.

**Comment by yaichenbaum** [comment]
@gave92 The icon overlay is now aligned.

**Review by gave92 — APPROVED** [review]

**Pull request merged**
