### PR TITLE
Update README.md with correct documentation link

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by BanCrash** [comment]
@yair100 I suppose there is some reason to merge this to DataGrid branch instead to main, right?

**Comment by yair100** [comment]
> @yair100 I suppose there is some reason to merge this to DataGrid branch instead to main, right?

Whoops 😂

**Review by BanCrash — APPROVED** [review]

**Comment by BanCrash** [comment]
@yair100 don't merge this yet please, when changing the branch there were added another modification that I didn't see.

**Review by BanCrash — APPROVED** [review]
@yaichenbaum okay now it's completely reviewed. LGTM, I like the new style!

**Pull request merged**
