### PR TITLE
NavBar improvements step 1

### PR DESCRIPTION
**Pull request by yair100**
- Moved the navigation buttons to the left of the path bar
- Fixed spacing of the toolbar buttons

### CODE REVIEW

**Comment by d2dyno1** [comment]
Could you share a screenshot?

**Comment by yaichenbaum** [comment]
@d2dyno1 This PR is part of a larger effort to redesign the navbar area, but this is what it looks like so far.
image

**Comment by gave92** [comment]
LGTM (actually it looks horrible but it's part of the plan right? 🤣)

**Review by gave92 — APPROVED** [review]

**Comment by d2dyno1** [comment]
> LGTM (actually it looks horrible but it's part of the plan right? )

tbh I like this one more

**Comment by yaichenbaum** [comment]
> LGTM (actually it looks horrible but it's part of the plan right? 🤣)

Exactly 😆

**Comment by d2dyno1** [comment]
> > LGTM (actually it looks horrible but it's part of the plan right? rofl)
> 
> Exactly

Hmm. How will the final version of this redesign look alike?

**Comment by yaichenbaum** [comment]
@d2dyno1 There are several parts to this design change including #3184, there are also plans to add some shadows around the app. It's hard to describe how it will look, but this concept should give you the basic idea.
image

**Comment by gave92** [comment]
Ooof every time I see one of this mockups I cry for the lost sidebar extending all the way to the top 😂. Aware of the reason behind the change my gut says otherwise.

**Comment by yaichenbaum** [comment]
@gave92 What don't you like about the sidebar extending to top?

**Comment by gave92** [comment]
I meant I don't like too much the current design where the sidebar is *not* extented to the top. When the sidebar is made acrylic I miss the "old" design.

**Comment by yaichenbaum** [comment]
@gave92 Oh good, then I am sure you will like the new design when #3184 is merged 😄

**Comment by R3voA3** [comment]
I see that little progress circle in the bottom right. Will this replace this progress bar which indicates that the folder is being loaded? I'd appreciate that.

**Comment by yaichenbaum** [comment]
@R3voA3 The progress circle is just a concept, don't read much into it.

**Comment by R3voA3** [comment]
> @R3voA3 The progress ring is just a concept, there isn't anything planned to change there.

Too bad =(

**Comment by SOI7** [comment]
> @d2dyno1 There are several parts to this design change including #3184, there are also plans to add some shadows around the app. It's hard to describe how it will look, but this concept should give you the basic idea.
> image

That has... everything I wanted 😲Even the W10X quick actions below the navbar

**Comment by gave92** [comment]
@yair100 one thing I noticed is that with the navigation buttons on the same row as the address bar on my screen the address bar becomes very cramped (in dual pane even more so and almost unusable). Just saying that this change should probably adapt with the window width.

**Comment by yaichenbaum** [comment]
@gave92 It's something to look into, I am curious if this is really an issue or not because the dual screen feature is mainly used on larger screens. Regardless, I plan on reducing the size of the text in the nav bar, so that should help with this issue.

**Comment by gave92** [comment]
Thanks, it's simply that currently I can use the dual pane feature with no issue, but with this change it gets a little awkward. Thinking that the search button and the others are going to also be moved into the same row.. :)

**Comment by yaichenbaum** [comment]
@gave92 The only other button that's going to be moved is the search button, it's something we should start discussing to find possible solutions. Thank you for bringing it up.

**Comment by h38d7v** [comment]
Wondering if you have considered adding the title of the app (and logo) to the top left of the NavBar. Probably good from a branding point of view, but also would be consistent with a lot of the other 'modern' apps. At the moment it sort of looks like the app is called 'favourites'. :) Screenshot below for example.

image

**Comment by R3voA3** [comment]
Not really sure where the title and logo would fit since the Tabs are taking the space and soon the nav bar.
Also, they should not try to be consistent with Microsoft apps since that's impossible :D

**Comment by SOI7** [comment]
The Win32 Explorer doesn't use a logo or a title anyway, so as it is now Files is consistent with the legacy file browser

**Comment by R3voA3** [comment]
@yair100 Any chance to see a screenshot? I need to see where

`          <target state="new">Browse</target>
        </trans-unit>
        <trans-unit id="RecentLocations" translate="yes" xml:space="preserve">
          <source>Recent locations</source>
          <target state="new">Recent locations</target>`

Is used so I can properly translate it.

**Comment by h38d7v** [comment]
Here is two good examples I think. Adding a title to the top of the navbar doesn't get in the way of tabs, or the navbar items.

image

Also here: https://www.behance.net/gallery/74300939/Windows-10-File-Explorer

**Comment by tsvietOK** [comment]
@R3voA3 
image

**Comment by yaichenbaum** [comment]
> Wondering if you have considered adding the title of the app (and logo) to the top left of the NavBar. Probably good from a branding point of view, but also would be consistent with a lot of the other 'modern' apps. At the moment it sort of looks like the app is called 'favourites'. :) Screenshot below for example.
> 
> image

Thanks for bringing this up, it seems like Microsoft is moving back towards this trend, but as mentioned above, it wouldn't fit into our design right now.

**Pull request merged**
