### PR TITLE
Code Quality: Continued work of applying one class per file

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Motivation and Context

Obvious reasons.

### PR Checklist
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

### Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Ready for review.

**Comment by 0x5bfa** [comment]
@yaira2 can you review?

**Comment by 0x5bfa** [comment]
@yair100 @d2dyno1 Can you review?

**Review by d2dyno1 — APPROVED** [review]
lgtm!

**Pull request merged**
