### PR TITLE
Fix: Don't show Pin/Unpin for items in recycle bin

### PR DESCRIPTION
**Pull request by Hark64**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
-Related to #10921 

**Validation**
How did you test these changes?
- [X] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by QuaintMako** [comment]
@Hark64 I believe the work done here is not on the up to date `main` branch. PR #10921 has already been merged. Instead of adding back l.559 and l.569, you should remove l.986 and l.998 after rebasing your branch with `main`.

**Review by QuaintMako — CHANGES_REQUESTED** [review]
@Hark64 I believe the work done here is not on the up to date `main` branch. PR #10921 has already been merged. Instead of adding back l.559 and l.569, you should remove l.986 and l.998 after rebasing your branch with `main`.

**Comment by Hark64** [comment]
Sorry I'm a little confused. I thought I did remove  l.986 and l.998 here.

**Review by QuaintMako — APPROVED** [review]
LGTM.

**Review by gave92 — APPROVED** [review]

**Pull request merged**
