### PR TITLE
Feature: Added detection for Seadrive cloud

### LINKED ISSUE #9758: Support SeaFile cloud drive
### What's the Problem?

_No response_

### Solution/Idea

Add cloud drive integration for **[Seafile](https://www.seafile.com/en/home/)** (https://www.seafile.com/en/home/). "Seafile is an open source file sync & share solution" (from their website).

### Alternatives

Seafile provides a "Drive Client" (https://www.seafile.com/en/download/), which in V2 builds on top of the "Cloud Files" API (https://docs.microsoft.com/en-us/windows/win32/cfapi/cloud-files-api-portal) in Windows 10+ and integrates natively with File Explorer.

### Priorities

_No response_

### Files Version

2.3.7.0

### Windows Version

Windows 10 Pro 21H2

### Comments

_No response_

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #9758

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaira2** [comment]
Thank you for the PR, can you add this to the documentation site as well?

**Comment by hecksmosis** [comment]
Yeah, forgot to do it

**Comment by hecksmosis** [comment]
It's basically the same as #10890

**Review by yaira2 — COMMENTED** [review]
LGTM

**Pull request merged**
