### PR TITLE
Code Quality: Document entire repository

### PR DESCRIPTION
**Pull request by Lamparter**
_Similar_ to #15652, I've taken the time to document the entire repository.
However, unlike the previous PR, this is far less descriptive codebase documentation and so is far less likely to become outdated.

To be honest, I wonder whether this might be more viable:
> I guess we should xml comments and generate api docs from it (I know there's a tool for it).

That might be a good idea, but it's down to @yair100 to express his plans for documentation.

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
Gotta appreciate the effort. Just a nit: I read that it's unnecessary c.q. unrecommended to mix headers and formatting.

**Comment by Lamparter** [comment]
> unrecommended to mix headers and formatting.

@Jay-o-Way what do you mean?

**Comment by Jay-o-Way** [comment]
I mean using `#` _and_ `code` formatting
```md
# `text`
```

**Comment by Lamparter** [comment]
Ah yes. I just used it to specify the directory.

**Comment by 0x5bfa** [comment]
So just let you know, I disagree with this idea. No one sees Strings dir, for example. Files codebase follows a normal MVVM design pattern, anyone can understand what's in these folders. Just the source is complicated, not the structure.

**Comment by yaira2** [comment]
Let's discuss this proposal in #16364

**Comment by 0x5bfa** [comment]
@yaira2 @Lamparter i think we can close this for now, we haven't made a solid decision how to document the source code.

**Pull request closed without merging**
