### PR TITLE
Switch folder context menu to use CommandBarFlayout

### PR DESCRIPTION
**Pull request by gave92**
**Details of Changes**
Add details of changes here.
- Use CommandBarFlayout for empty space context-menu
- Remove unused dependencies

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by winston-de — APPROVED** [review]
Lgtm

**Comment by yaichenbaum** [comment]
@gave92 Can you share a screenshot?

**Comment by yaichenbaum** [comment]
@gave92 Are there any primary commands in the new menu?

**Comment by gave92** [comment]
None, it looks the same as the current menu but uses the same control as the items context menu.

**Comment by yaichenbaum** [comment]
LGTM

**Pull request merged**
