### PR TITLE
Code Quality: Downgrade LiteDB to fix transaction issue

### LINKED ISSUE #15157: My Files Crash when I open folders
### Description

My Files doesn't stop crashing randomly when I open folders with it and it's not on a specific folder but it happens completely randomly but it's when I do an action on it

### Steps To Reproduce

open Files
and do any action that is not related to the app settings

### Requirements

- e.g. Fix crash that occurs when... when I open folders with

### Files Version

when I open folders with

### Windows Version

22H2

### Log File

image

### LINKED ISSUE #15172: Bug: Increased crashes in v3.3.1 (preview)
### Description

When there are too many files in a folder, opening the folder will be jammed.

### Steps To Reproduce

When there are too many files in a folder, opening the folder will be jammed.

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.3.1.0

### Windows Version

10.0.22635.3495

### Log File

[debug.log](https://github.com/files-community/Files/files/14970556/debug.log)

### LINKED ISSUE #15203: Bug: Increased crashes in preview version
### Description

It just crashed when I opened a folder, but I was using normally for a time..

Worth stacktrace:
```cs
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Files.App.Server.Database
ILayoutPreferencesDatabaseClassMethods.GetPreferences (IObjectReference _obj, String filePath, Nullable`1 frn)
Files.App.Data.Models
LayoutPreferencesManager.GetLayoutPreferencesForPath (String path)
Files.App.Data.Models
LayoutPreferencesManager.GetLayoutType (String path, Boolean changeLayoutMode)
Files.App.Views
HomePage.DrivesWidget_DrivesWidgetInvoked (Object sender, DrivesWidgetInvokedEventArgs e)
Files.App.UserControls.Widgets
DrivesWidget.Button_Click (Object sender, RoutedEventArgs e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

### Steps To Reproduce

1. Use normally for a time
2. Open a folder
3. Crash

### Requirements

Fix crash that occurs when I open a folder.

### Files Version

3.3.2.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15003460/debug.log)

### PR DESCRIPTION
**Pull request by hez2010**
**Resolved / Related Issues**
We hit https://github.com/mbdavid/LiteDB/issues/2435 which results in Files crashing. As a workaround, we may use `Shared` connection instead of `Direct`. It may slow down the query speed, but it no longer crashes.
   Closes #15203
   Closes #15172
   Closes #15157

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaira2** [comment]
> It may slow down the query speed, but it no longer crashes.

Do you have any idea how much of a difference it makes?

**Comment by hez2010** [comment]
In my simple test 100 times of insertion and query (200 ops in total) regressed from 0.01 seconds to 0.2 seconds.

**Comment by hez2010** [comment]
Maybe we can instead downgrade to LiteDB v5.0.17?

**Comment by yaira2** [comment]
Sounds like downgrading is the best option for now

**Pull request merged**
