### PR TITLE
GitHub: Create config.yml

### PR DESCRIPTION
**Pull request by Jay-o-Way**
This will prevent any blank issues to be created. As seen in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Resolved / Related Issues**
> in order to properly manage the issues, we have to close issues that don't follow the issue templates.

https://github.com/files-community/Files/issues/12312#issuecomment-1540577114

**Validation**
How did you test these changes?
- Neither needed or possible :)

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
Having that said: What if there is an issue that really does not fit into one of the three [bug, code, feature] templates? For example: I would like to polish MD files, with help of MS [Learn Authoring Pack](https://learn.microsoft.com/contribute/how-to-write-docs-auth-pack) (for VS Code). What to do then?

**Review by yaira2 — APPROVED** [review]
I was looking for a way to do this but wasn't able to figure it out, thank you!

**Comment by Jay-o-Way** [comment]
You're welcome. I _am_ curious what you would advise for my question above here, though.

**Comment by yaira2** [comment]
> Having that said: What if there is an issue that really does not fit into one of the three [bug, code, feature] templates? For example: I would like to polish MD files, with help of MS [Learn Authoring Pack](https://learn.microsoft.com/contribute/how-to-write-docs-auth-pack) (for VS Code). What to do then?

Feature is best

**Pull request merged**
