### PR TITLE
Fix: Fixed a bug where dropdown flyouts opened in the wrong location

### LINKED ISSUE #14965: Bug: ComboBox list shift to the right when clicked on
### Description

When clicking on a ComboBox list (list of selectable items) in Settings, the list moves away from under the cursor.

https://github.com/files-community/Files/assets/87632612/f9ab3841-c470-4430-a10c-33a00bfc5cb2

### Steps To Reproduce

1. Open Settings
2. Click on any ComboBox 
3. List moves to the right and is not at the same location as it was before.

### Requirements

Would be better if the list stays under the mouse cursor on being clicked.

### Files Version

Latest dev build (3.2.7.0)

### Windows Version

22631.3296

### Log File

[debug.log](https://github.com/files-community/Files/files/14611969/debug.log)

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title.

## PR Checklist

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #14965
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Go to Settings dialog
   2. Go to General or Appearance page.
   3. Select another item in ComboBox
   4. See the width changed.

## Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@TheChilledBuffalo

**Comment by TheChilledBuffalo** [comment]
@0x5bfa Hey, thank you very much for working on this issue. But I'm afraid I can't test this out because I'm away from my dev machine atm and will be for at least the next two weeks. I'm really sorry about that....

**Comment by 0x5bfa** [comment]
Nah, no problems at all.
Yair is also unavailable for the next several days.

I also thank you for bringing this up to us!

**Comment by yaira2** [comment]
image

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
