### PR TITLE
[TEST] An awesome PR

### PR DESCRIPTION
**Pull request by gave92**
**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by gave92** [comment]
@yair100

**Comment by yaichenbaum** [comment]
@gave92 can you adjust the azure release pipeline to run on prs?

**Comment by gave92** [comment]
@yair100 I think I did, but I'm somewhat ignorant of Azure :)

**Comment by yaichenbaum** [comment]
@gave92 looks good! Can you try triggering it `/azp run`?

**Comment by yaichenbaum** [comment]
@gave92 can you try triggering it again?

**Pull request closed without merging**
