### PR TITLE
[infra] Update project structure to have src and tests folder

### PR DESCRIPTION
**Pull request by chingucoding**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related #7236

**Details of Changes**
Add details of changes here.
- Moved source code projects into a src folder
- Moved interaction tests project into tests folder

**Validation**
How did you test these changes?
- [X] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@chingucoding can you take care of the merge conflicts?

**Comment by yaichenbaum** [comment]
@chingucoding what do you think is the best process to make sure this doesn't interfere with the other open PRs?

**Comment by chingucoding** [comment]
> @chingucoding can you take care of the merge conflicts?

Done



> @chingucoding what do you think is the best process to make sure this doesn't interfere with the other open PRs?

That's a very tough question. Since this PR is not really time critical, we could wait until all current PRs are merged and new PRs should be based off of this project structure. Not sure what the best way to communicate or implement this. Or we merge this and try to solve merge conflicts on all PRs which hopefully won't be too difficult since it's mostly moving files around.

**Comment by yaichenbaum** [comment]
@cinqmilleans are you okay with updating your PRs after this is merged?

**Review by yaichenbaum — APPROVED** [review]

**Pull request merged**
