### PR TITLE
Show selected items size details when selecting by dragging the mouse

### LINKED ISSUE #9075: Update the selected item counter while using rectangle selection
### Description

Files has an item counter and a cumulative file size indicator inside of folders, this works correctly when selecting multiple items through keyboard shortcuts, however when the user uses the cursor to drag a box to select multiple items, said counters are only displayed when the user stops dragging.

### Steps To Reproduce

1. Open a folder with more than 1 items inside
2. Drag a box with the mouse to select the files inside of the folder without letting go of mouse1.
3. Look at the bottom of the window and notice that the item and cumulative file size counters are missing.
4. Let go of mouse1 and see that the counters appear.

### Expected behavior

When selecting multiple files by drawing a box with the mouse, the item and cumulative file size counters should update in real time with each new item selected/deselected.

### Files Version

2.1.50.0

### Windows Version

Windows 10 LTSC 19044

### Relevant Assets/Logs

Example

### PR DESCRIPTION
**Pull request by IgorKordiukiewicz**
**Resolved / Related Issues**
Closes #9075 

**Details of Changes**
When selecting items by dragging the mouse, the selected items size details are now shown.

**Validation**
- [x] Built and ran the app

**Screenshots**

https://user-images.githubusercontent.com/25117425/171218690-a250daa4-0cda-43a4-b100-888ab0ccfa08.mp4

### CODE REVIEW

**Comment by gave92** [comment]
Mmm fairly sure we don't call SelectionChanged to avoid performance issues in big folders

**Comment by yaichenbaum** [comment]
> Mmm fairly sure we don't call SelectionChanged to avoid performance issues in big folders

I seem to recal that we did this in the past but reverted the change because of performance issues.

**Comment by IgorKordiukiewicz** [comment]
Updated, so now `SelectionChanged` is called only when selected items have changed.

**Comment by yaichenbaum** [comment]
@IgorKordiukiewicz is this ready for review?

**Comment by yaichenbaum** [comment]
@gave92 should we move forward with this, if not, what do you want to do here?

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@IgorKordiukiewicz thank you!

**Pull request merged**
