### PR TITLE
Moved FileSystemDialog to Files.Backend

### PR DESCRIPTION
**Pull request by d2dyno1**
**Details of Changes**
- This PR moves MVVM related classes to Files.Backend and prepares FileSystemDialog for design refresh.

**Validation**
- [x] Built and ran the app

### CODE REVIEW

**Comment by d2dyno1** [comment]
It won't build

**Review by yaichenbaum — DISMISSED** [review]

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
