### PR TITLE
Code Quality: Added empty view models of Widgets

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title. This is 0st stage of introduction of view models to Widgets.

## PR Checklist

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related #14760
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   _None_

## Screenshots

_None_

### CODE REVIEW

**Comment by yaira2** [comment]
Should we also register the ViewModels to the views?

**Comment by 0x5bfa** [comment]
Done.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
This phased approach will allow us to review each change separately, making code review faster and hopefully reduce the risk of new issues.

**Pull request merged**
