### PR TITLE
Improved behavior when entering restricted characters

### LINKED ISSUE #7967: Automatically delete/discard illegal filename characters when *pasting* a string on a *new* file/folder
### What's the Problem?

In Files Explorer, every time when you paste a string that contains: 

- :
- &
- "
- ?
- <
- (>)
- (#)
- {
- }
- % 
- ~
- /
- \

It will automatically delete the string **and** displays the following message
> file names can't contain the following characters: & " ? < > # { } % ~ / \.

If the user tries again by deleting and pasting the same string, File Explorer will automatically post the string of text without those characters as if the user didn't copy them in the first place. (see video 2)

Currently, Files (Community) does not support this feature, but this idea could help people like for example: a student that is organizing their folders when an instructor releases new materials by the week. Small but significant features that are in Files Explorer should be implemented into Files (Community) so the program could be seen as a replacement to the venerable but dated Files Explorer.

https://user-images.githubusercontent.com/88814097/151285775-efbd8a5d-b18a-402c-81e8-f786b8d13c9f.mov

https://user-images.githubusercontent.com/88814097/151285778-d48a250b-6266-464d-8c5c-05aeecf8c354.mov

### Solution/Idea

When the user pastes a string when naming a new file/folder with these illegal filename characters:

- :
- &
- "
- ?
- <
- (>) 
- (#) 
- {
- }
- % 
- ~
- /
- \

It should automatically delete the string **and** displays the following message
> file names can't contain the following characters: & " ? < > # { } % ~ / \.

If the user tries again by deleting and pasting the same string, Files should automatically post the string of text without those characters as if the user didn't copy them in the first place. (see video 2)

### Alternatives

There is currently no alternative to what I describe other than not implementing it, it's a small feature but it could help some people.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to not manually delete a copied text that has an illegal filename character(s) when naming files/folders | Must |
| If the user tries again by deleting and pasting the same string, Files (Community) will automatically post the string of text without those illegal filename characters as if the user didn't copy them in the first place, just like Files Explorer. | Must/Should |

### Files Version

Version: 2.1.2.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 OS Build 19043.1466

### Comments

_No response_

### PR DESCRIPTION
**Pull request by szabolcstarnai**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7967 

**Details of Changes**
Add details of changes here.
Made handling pasting restricted characters the same as Windows File Explorer

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Windows File Explorer

https://user-images.githubusercontent.com/75786375/152790846-9215364a-a332-45c4-bb02-4209258817e0.mp4

Files

https://user-images.githubusercontent.com/75786375/152790877-94cfd0c5-3820-4a8d-af5a-738304beb158.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@szabolcstarnai thank you for the pr, what do you think about creating a helper or putting the code in BaseLayout so that we only need to handle the logic once?

**Comment by yaichenbaum** [comment]
> I found a bug, if you change the layout to Column, you cannot change it to anything else I couldn't figure out what causes this yet

I can reproduce the bug in the store version as well

**Comment by yaichenbaum** [comment]
@szabolcstarnai the behavior doesn't seem to work as expected, it appears that the full file name is being removed. I recommend removing the characters on the text changed event where we currently handle the logic.

**Comment by szabolcstarnai** [comment]
I think the TextChanging event is better beacuse it occurs synchronously before the new text is rendered.

https://user-images.githubusercontent.com/75786375/153677129-ba69378c-3711-4142-99dd-e961f954f724.mp4

This happens if I use the TextChanged event.

Also I think now the behavior works more like the stock File Explorer.

**Comment by lightningHoneypot** [comment]
> **Resolved / Related Issues** Items resolved / related issues by this PR.
> 
> * Closes [Automatically delete/discard illegal filename characters when *pasting* a string on a *new* file/folder #7967](https://github.com/files-community/Files/issues/7967)
> 
> **Details of Changes** Add details of changes here. Made handling pasting restricted characters the same as Windows File Explorer
> 
> **Validation** How did you test these changes?
> 
> * [x]  Built and ran the app
> * [ ]  Tested the changes for accessibility
> 
> **Screenshots (optional)** Windows File Explorer
> 
>  windows.mp4 
> Files
> 
>  files.mp4

Nice, my feature request is being worked on :D 👍
But a bit of a concern when comparing the videos windows.mp4 and files.mp4
In windows.mp4, one can clearly see that when one pastes a string with illegal characters, Files Explorer will _delete the illegal characters **AND** paste the strings without the illegal characters in question and displays the error message_.
On files.mp4, it seems that one has to Ctrl + V twice just to do the same thing like what windows.mp4 has shown.

Is it still there in this final pull request? Or has it been fixed? (Sorry I don't have much coding experience aside from python stuff in university classes, I really wish that I could know how C# and C++ works) 🙇‍♂️

**Comment by gave92** [comment]
@szabolcstarnai thanks for this contribution! I've pushed some changes to make this simpler and to fix the issue noticed by @lightningHoneypot. @yair100 could you check if it behaves as desired?

**Review by gave92 — APPROVED** [review]

**Comment by lightningHoneypot** [comment]
Yayyy!

**Review by yair100 — APPROVED** [review]

**Pull request merged**
