### PR TITLE
Improved sidebar loading speed

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by gave92** [comment]
Could someone test if this PR is beneficial for the issue of the sidebar being slow to load / appearing several seconds after app start?

**Comment by BanCrash** [comment]
@gave92 I will test this not later than tomorrow (hopefully today)

**Comment by yaichenbaum** [comment]
@gave92 after comparing the two side by side, I believe these changes do make a positive impact.

**Comment by BanCrash** [comment]
> @gave92 after comparing the two side by side, I believe these changes do make a positive impact.

Yep, on my tests the results are the same.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
