### PR TITLE
Code Quality: Bring properties window to foreground on loaded

### LINKED ISSUE #13697: When opening empty folder in Files, property window for a drive (Right-click>Properties) moves to background & stays there
### Description

When using the current Store version (3.0.1.0), when you open a folder in Files that is empty, then right-clicking a drive and opening the drive properties puts the info window into the background, so the main Files window always stays on top. Even clicking the info window lets it only flash up for a moment, but doesn't bring it to the foreground. 

### Steps To Reproduce

1. Open Files.
2. Go to a folder on your system that has no files or sub-folders inside. Removing files doesn't work, it has to be empty when you enter the folder. 
3. Right-click a drive in the sidebar. 
4. Click 'Properties' ("Eigenschaften" in German).
5. The popup window opens, but immediately moves behind the main Files window.
6. Clicking the info window in the background doesn't move it to the foreground.

### Requirements

- Let Files open the Properties window in the foreground and don't steal focus off it. 

### Files Version

3.0.1.0

### Windows Version

23H2 (22635.2700)

### Log File

Not needed

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Resolved / Related Issues

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #13697 

### Steps used to test these changes

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Open Files app
2. Open file properties window
3. See brought to foreground

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@yaira2 Found easy one 😄

**Comment by yaira2** [comment]
Did this fix the issue for you? On my end it's still an issue.

- Open an empty folder
- Right click a drive from the sidebar and open properties
- The main window takes the focus

**Comment by yaira2** [comment]
We had a similar issue with widgets (see #11433).

**Comment by 0x5bfa** [comment]
When I first try to repro, I removed existing files and I thought it fixed (it sure poped up to the foreground).
@yaira2 I did the same thing but no progress here. I seemed to have been wrong...

**Pull request closed without merging**
