### PR TITLE
Fix: Fixed System.TypeInitializationException in FileTagsDatabase

### LINKED ISSUE #15601: Bug: System.TypeInitializationException: The type initializer for 'Files.App.Utils.FileTags.FileTagsDatabase' threw an exception.
Sentry Issue: [FILES-APP-2B](https://files-org.sentry.io/issues/5478011341/?referrer=github_integration)

```
System.Runtime.InteropServices.COMException: None
  ?, in Package IPackageStaticsMethods.get_Current(IObjectReference _obj)
  ?, in static FileTagsDatabase()

System.TypeInitializationException: The type initializer for 'Files.App.Utils.FileTags.FileTagsDatabase' threw an exception.
  ?, in static FileTagsHelper()+() => { }
  ?, in void ItemViewModel.SetFileTag(ListedItem item)
  ?, in async Task ItemViewModel.LoadExtendedItemPropertiesAsync(ListedItem item)+(?) => { }
  ?, in async Task<FilesystemResult> FilesystemTasks.Wrap(Func<Task> wrapped)
...
(1 additional frame(s) were not displayed)

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
```

### PR DESCRIPTION
**Pull request by hishitetsu**
This prevents crashes due to the exception, but the tags feature doesn't work properly in that case.
It may be better to define the registry key statically instead of using `Package.Current`, though migration is required.

**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15601 

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Comment by hez2010** [comment]
I'm wondering under what circumstances can this throw an exception?
Is someone trying to run Files as an unpackage app?

**Comment by hishitetsu** [comment]
You may be right, or it may be a bug of Windows. But as long as the exception is occurring, I think we should take care of it.

**Comment by hez2010** [comment]
I think the issue is not caused by end users but instead by developers. 
Someone tried to build and launch Files from VS without selecting `Files.Package` and encountered this exception. 
I don't think it's worth adding complexity to Files to address this subtle issue. Even if we fix this issue, they will immediately encounter into another exception because umpackaged deployment is not supported at all.

**Comment by 0x5bfa** [comment]
If we can detect if unpackaged, we could close main window and show only classic message dialog saying *Unpackaged launching is unsupported, build from Files.App (Package) project* at least.

**Comment by hishitetsu** [comment]
> I think the issue is not caused by end users but instead by developers. Someone tried to build and launch Files from VS without selecting `Files.Package` and encountered this exception. I don't think it's worth adding complexity to Files to address this subtle issue. Even if we fix this issue, they will immediately encounter another exception (which is hidden by this one) because unpackaged deployment is not supported at all.

In that case, wouldn't an exception report be sent to Sentry?

**Comment by 0x5bfa** [comment]
Same if you click exe directly in installed path

**Comment by yaira2** [comment]
> I think the issue is not caused by end users but instead by developers. Someone tried to build and launch Files from VS without selecting `Files.Package` and encountered this exception. I don't think it's worth adding complexity to Files to address this subtle issue. Even if we fix this issue, they will immediately encounter another exception (which is hidden by this one) because unpackaged deployment is not supported at all.

@hez2010 Sentry is only on the release version of Files so this has to be coming from a packaged app.

**Review by yaira2 — APPROVED** [review]

**Comment by yaira2** [comment]
If it helps, we can try logging additional info about that state of the app to try figuring out how this occurs.

**Pull request merged**
