### PR TITLE
Fix: Fixed an issue with opening files with multiple extensions

### LINKED ISSUE #15164: Bug: File with double extensions don't open correctly
### Description

I have only test this with `.zip.txt` but I assume to affects others too.

### Steps To Reproduce

1. Create txt file with `.zip.txt` extension
2. Open file
3. VS code shows the path is

image

When it should be
image

### Requirements

- Make sure to only open files as the last extension type (.txt)

### Files Version

3.3.1.0

### Windows Version

10.0.22621.3387

### Log File

[debug.log](https://github.com/files-community/Files/files/14961949/debug.log)

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15164

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Created a zip file named "a.zip"
2. Created a text file named "a.zip.txt"
3. Set default text editor to VS Code and confirmed that the file opened correctly

### CODE REVIEW

**Comment by yaira2** [comment]
@Josh65-2201 can you confirm if this solves the issue for you?

**Comment by Josh65-2201** [comment]
It's working

**Comment by yaira2** [comment]
This seems to cause a regression when opening items within zip files.

**Comment by Josh65-2201** [comment]
Opening items in a zip is working correctly for me. Is the a specific type that's causing issues?

**Comment by yaira2** [comment]
Merging with #16102

**Pull request closed without merging**
