### PR TITLE
Revert "Code cleanup" and "CodeMaid"

### PR DESCRIPTION
**Pull request by winston-de**
Reverts files-community/Files#4502 and #4499
This fixes several performance regressions that are in the main branch.

This also includes a run of CodeMaid, which did not seem to cause any issues.

### CODE REVIEW

**Comment by d2dyno1** [comment]
Does it fix them?

**Comment by winston-de** [comment]
No

**Comment by winston-de** [comment]
~~#4499 Can't be reverted right now, I think we may have to merge this revert in order to revert the other.~~
image

@yair100 What do you think?

Nvm I can revert it manually in VS.

**Comment by winston-de** [comment]
OK, reverting both prs resolves the issue.

**Comment by yaichenbaum** [comment]
@winston-de Do you know what part of those changes messed things up?

**Comment by winston-de** [comment]
> @winston-de Do you know what part of those changes messed things up?

@yair100 no, but I'm trying to figure it out.

**Review by yair100 — APPROVED** [review]

**Review by yair100 — APPROVED** [review]

**Pull request merged**
