### PR TITLE
Feature: Added support for setting jfif files as the wallpaper

### LINKED ISSUE #14527: Feature: Add support for jfif files to be set as wallpaper
### What feature or improvement do you think would benefit Files?

Jfif files are currently not supported to be set as wallpaper through Files App, It might be handy for people with pictures having that extension

### Requirements

- Since it is already available on the default file explorer, it will get the Files App closer to fully substitute it

### Files Version

3.1.1.0

### Windows Version

Windows 10

### Comments

_No response_

### PR DESCRIPTION
**Pull request by MrFrawsty**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #14527 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?

- [x] Are there any other steps that were used to validate these changes?
   1. Open app 
   2. Navigate to file with .jfif extension
   3. Right click, select set as wallpaper
   4. Verify desktop wallpaper was set
   5. Rotated both left and right, both work as expected

### CODE REVIEW

**Comment by yaira2** [comment]
I think this also unlocks the option to rotate this file format, can you check that it's working correctly?

**Comment by MrFrawsty** [comment]
Just verified that also works as expected.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by hishitetsu** [comment]
The merge is not reflected in the main branch for some reason 🤔

**Comment by yaira2** [comment]
@MrFrawsty can you open another PR?

**Comment by MrFrawsty** [comment]
Yes in just a few minutes

**Pull request merged**
