### PR TITLE
Fix broken sticky header in details view

### LINKED ISSUE #5360: the bottom scrollbar almost hides the last file n the detail view
**Explain the bug**
the bottom bar almost hides the last file in the detail view. the area available to interact with the file ends up being half of what it should be.

**To reproduce**
1. Go to a folder with many files
2.  activate details view
3. reduce the window until the bottom scrollbars appear.
4. go to the last file and you will see that the area available to interact with the file is reduced because of the bottom scrollbar.

**Expected behavior**
the bottom scrollbar should not reduce the area available to interact with the last file or there should be an empty area so that the opening of the bottom scrollbar does not overlap with the last file.

**Logfile**
i think in this case is not necesary. if necessary, let me know and I will upload it without any problem.

**Screenshots**
imagen
imagen

**System Information**
 - OS Version: Edición	Windows 10 Pro
                      Versión	21H1
                      Instalado el	‎18/‎12/‎2020
                      Compilación del sistema operativo	19043.1052
                      Experiencia	Windows Feature Experience Pack 120.2212.2020.0

 - App version: 1.5

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related #4643
- Closes #5360 (scrollbar now hidden until hovered over or horizontal scrolling is invoked)

**Details of Changes**
Add details of changes here.
- Fix issue where the header wouldn't always show when scrolling vertically
- Update header buttons to use winui 2.6 styling
- Update column sizes when the view area is resized

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de It looks like the header has an alignment issue in this PR.
image

**Comment by winston-de** [comment]
Thanks, this should be fixed now.

**Comment by yaichenbaum** [comment]
@winston-de Now it looks like there is a little too much space for the icon column.

**Comment by winston-de** [comment]
> @winston-de Now it looks like there is a little too much space for the icon column.

Can you send a screenshot please? Seemingly it works on my machine :tm:.
image

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
