### PR TITLE
Feature: Added a new option to remove checkboxes under folder settings

### PR DESCRIPTION
**Pull request by Krytan**
showcheckbox
This changes adds a new feature "show checkboxes", turn it off to remove checkboxes completely   

**Validation**
How did you test these changes?
 1. Go to settings 
 2. Click on Folders 
 3. Under Display a new setting "Show checkboxes" should be automatic on
 4. Turn it off and  if **show-checkboxes-when-selecting-items** is on it will automatic turn it off too
 5. Now you shouldn't see any checkboxes

### CODE REVIEW

**Comment by yaira2** [comment]
@Krytan we don't have plans to implement this right now.

**Comment by Krytan** [comment]
@yair100 Alright remember me whenever you decide to implement it keep in mind that it is completely compatible with show-checkboxes-when-selecting-items also in the future a good idea would be having show-checkboxes-when-selecting-items in a sub menu of show checkboxes.

**Comment by Krytan** [comment]
I saw that this feature was a request #12024 from a user so I decided to work on it

**Comment by Krytan** [comment]
@yair100 True sure let me know in what issue I can work on

**Comment by yaira2** [comment]
@Krytan do you want to look at #12037?

**Comment by Krytan** [comment]
@yair100 Yes I am working on it

**Pull request closed without merging**
