### PR TITLE
Feature: RichCommands Paste

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
Copy the pr #11670, approved but the checks fail for an unknown reason.
I split the pr, this part is only Cut/Copy. This is the second and final part, the Paste command.

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Comment by yaira2** [comment]
@cinqmilleans can you fix the conflicts?

**Review by yaira2 — DISMISSED** [review]
Thank you

**Comment by yaira2** [comment]
@cinqmilleans do the tests past if you run them locally?

**Comment by hishitetsu** [comment]
I figured out why the test fails.
If you select an item and press the copy button and then the paste button, a conflict dialog appears instead of automatically renaming and copying the item. The test doesn't assume that a dialog will appear.
Also, the paste button cannot be pressed when any file is selected.

**Comment by cinqmilleans** [comment]
Regarding the 2nd difference, it is voluntary. The toolbar buttons should always have the same behavior as in the context menu. If a folder is selected, I can paste into it with the toolbar. Currently, you have to go through its contextual menu or open the folder.

Regarding the dialog box, I corrected that.

**Comment by cinqmilleans** [comment]
The collision issue already exists in the current application.
1) Open a folder containing a folder and a file.
2) Copy the file
3) Open the context menu of the sub-folder (same parent as the copied file).
4) Paste into folder.
5) A collision popup appears. However, there is no real collision.

In this pr, copying in the same folder (deselecting everything), does not display a popup but automatically renames the file.
The problem seems to come from FilesystemHelpers.GetCollision(). That's another issue for another pr, if the issue is confirmed.

**Comment by hishitetsu** [comment]
Sorry, I misunderstood a bit. The test fails because it expects the folder to be pasted in the same location as the original folder.
In File Explorer, the paste button in the toolbar copies the folder in the opened folder, not in the selected folder. It is also available while a file is selected. I think it should work the same as Explorer i.e. current Files.

The behavior of the conflict dialog was certainly not changed.

**Comment by hishitetsu** [comment]
Maybe two commands are needed: paste to current folder and paste to selected folder.

**Comment by cinqmilleans** [comment]
It's done.

**Comment by hishitetsu** [comment]
Thank you. It is much better, but there is still one point where the behavior is different.
When I open a context menu without item selection, the paste button is disabled. It should be enabled and work the same way as the paste button on the toolbar.

**Comment by cinqmilleans** [comment]
You are right. I added this. Thank you.

**Comment by hishitetsu** [comment]
Nice. Everything seems to be working as expected.

**Pull request merged**
