### PR TITLE
Added subtle listview animation

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by d2dyno1** [comment]
Could you share a video? :eyes:

**Comment by BanCrash** [comment]
@yair100 when and where is this animation executed? I've tried it but I didn't see any difference on the places that I've tried.

**Comment by yair100** [comment]
> @yair100 when and where is this animation executed? I've tried it but I didn't see any difference on the places that I've tried.

@BanCrash in the details and column layouts.

**Comment by BanCrash** [comment]
> > @yair100 when and where is this animation executed? I've tried it but I didn't see any difference on the places that I've tried.
> 
> @BanCrash in the details and column layouts.

When loading / entering a folder, right?

I've should searched what meant subtle before, for some reason I thought it means something else :sweat_smile:

**Comment by yair100** [comment]
> > > @yair100 when and where is this animation executed? I've tried it but I didn't see any difference on the places that I've tried.
> > 
> > 
> > @BanCrash in the details and column layouts.
> 
> When loading / entering a folder, right?
> 
> I've should searched what meant subtle before, for some reason I thought it means something else 😅

@BanCrash yeah, unfortunately I wasn't able to get it working when refreshing a folder but maybe I'll get that another time. The idea is that the animation is there, but barely noticeable.

**Review by BanCrash — APPROVED** [review]
LGTM

**Pull request merged**
