### PR TITLE
Fixed an issue where the text in the properties dialog would get cut off in some languages

### LINKED ISSUE #2410: Make text in the properties dialog responsive
When using the German localisation, the right attribute text is cut off due to the window being too narrow.

image

### PR DESCRIPTION
**Pull request by yair100**
- Fixed an issue where the text in the properties dialog would get cut off in some languages.
- Changed the "ok" button in the properties dialog to "apply"

Fixes #2410

### CODE REVIEW

**Comment by d2dyno1** [comment]
"Apply" is inconsistent with Windows design guidlines

**Comment by yaichenbaum** [comment]
> "Apply" is inconsistent with Windows design guidlines

Do you have a link?

**Comment by d2dyno1** [comment]
@yair100 #1838 (#1851)

**Comment by yair100** [comment]
> @yair100 #1838 (#1851)

Do you have any links regarding the guidelines? The links you shared are regarding the order, not the text.

**Comment by d2dyno1** [comment]
https://docs.microsoft.com/en-us/windows/win32/uxguide/win-property-win#guidelines

> OK buttons
> For owner property windows, the OK button means apply the pending changes (made since the window was opened or the last Apply), and close the window

-

> Apply buttons
> For owner property sheets, the Apply button means apply the pending changes (made since the window was opened or the last Apply), but leave the window open

If we want to keep the Apply button, it must not close the window, it should only save the changes.

**Comment by yaichenbaum** [comment]
> https://docs.microsoft.com/en-us/windows/win32/uxguide/win-property-win#guidelines
> 
> > OK buttons
> > For owner property windows, the OK button means apply the pending changes (made since the window was opened or the last Apply), and close the window
> 
> > Apply buttons
> > For owner property sheets, the Apply button means apply the pending changes (made since the window was opened or the last Apply), but leave the window open
> 
> If we want to keep the Apply button, it must not close the window, it should only save the changes.

That's a good point, we should probably have all three buttons.

**Review by lukeblevins — APPROVED** [review]
changes LGTM

**Pull request merged**
