### PR TITLE
Added sample weather widget as optional package

### PR DESCRIPTION
**Pull request by winston-de**
#4115 
This widget is provided entirely through an optional package. 

image
image

To test it:
1. set config to release
2. Deploy the solution
3. Manually deploy SampleWidget project
4. Launch files

The sample widget can only be deployed after Files has been deployed, or else it will throw an error.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de A couple notes, how does this work before #4116 is done? Also, this widget should be kept separate from Files. We can create a separate repo for it since it's a good sample.

**Comment by winston-de** [comment]
@yair100 I dont think we can keep the optional packages completely separate from this repo, since the winmd files outputted by the sample project have to be referenced by the Files project in order to compile.

Also, this doesn't have to be merged immediately, I think it will be useful for testing. I'll mark it as draft.

**Comment by d2dyno1** [comment]
I could work on the weather's appearance and backend.

**Comment by FireCubeStudios** [comment]
> I could work on the weather's appearance and backend.

make it not webview

**Comment by d2dyno1** [comment]
@FireCubeStudios I have something similar in mind:

des3

**Comment by winston-de** [comment]
@yair100 My idea worked. It is possible to completely separate the optional packages from the main Files repo. Even better, despite what I previously thought, it doesn't even require any modifications to the build pipeline. All that has to be done is add a reference to a nuget package which contains the metadata outputted by the widget build.

**Comment by winston-de** [comment]
Here's the link to the repo.
https://github.com/winston-de/WidgetSample/
The nuget package but published and referenced (also unlisted) so it should work.
If you'd like, I can transfer ownership over to you.

**Comment by Jaiganeshkumaran** [comment]
Weather widgets are everywhere these days. Why does Files now need a weather widget? What's the use?

**Comment by d2dyno1** [comment]
@Jaiganeshkumaran See #4115

**Comment by winston-de** [comment]
For the time being, I will close this because there isn't much use for this. However, I do think optional packages warrant further investigation in the future as a way to allow for components of Files to be developed, installed, and published separately, reducing build times, install size, and making the project easier to maintain.

**Pull request closed without merging**
