### PR TITLE
Fix for Files crashing when attempting to access unmounted ISO

### PR DESCRIPTION
**Pull request by igoragm**
Expanded the catch clause in StorageFileExtension to include a wider range of exceptions & logged out the error message.

### CODE REVIEW

**Comment by gave92** [comment]
@igoragm thanks for your contributions!
Please note that the proposed solution (as it is) won't solve the linked issue:
`Directory.GetParent(value).FullName` will throw NullReferenceException in that case because you are already at the root of the drive (`Directory.GetParent` will return null)

**Comment by igoragm** [comment]
@gave92 thanks for your reply. 
You are right, what I've handled was accessing folders within an unmounted ISO but I haven't handled accessing files which does result in an exception of its own. In fact I'm not even sure this component handles opening the files at all, I will have to check and make the appropriate changes.

**Comment by yaichenbaum** [comment]
@igoragm Thank you for your help on this.

**Comment by gave92** [comment]
@igoragm thanks for the help! The original issue has been fixed in #2269 as part of a larger rework of exception handling.

**Comment by igoragm** [comment]
Great! Thanks for the info.

**Pull request closed without merging**
