### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by sthivaios** [comment]
@yair100 I have also made some updates on Crowdin. I am not extremely familiar with GitHub so I do not know how to make one of these posts like your's to make it clear that I have updated some translations for Greek.

**Comment by yaichenbaum** [comment]
@sthivaios thank you! Crowdin automatically opens these pull requests so there isn't anything more for you to do 🙂

**Comment by sthivaios** [comment]
> @sthivaios thank you! Crowdin automatically opens these pull requests so there isn't anything more for you to do 🙂

Oh, yep, here is the comment we were talking about on Discord. Ok, about the Crowdin thing, sure. Btw, it was "90% Done" with the translation. I did the rest and now only 2 terms are left that I didn't translate, because there wasn't a possible way (at least that is what I think) to translate them in a way that would actually make sense in Greek.

**Comment by sthivaios** [comment]
Here is a screenshot

image

**Comment by yaichenbaum** [comment]
That's alright, someone will probably suggest something at some point.

**Comment by sthivaios** [comment]
> That's alright, someone will probably suggest something at some point.

Yeah, I guess they will do, it just doesn't make sense to me. I told my mom how I translated one of the two and she burst out laughing. It just doesn't make sense to translate that in Greek. Like, my native language is Greek, so hearing phrases like that sounds like someone from another country put that on google translate and said it.

**Pull request merged**
