### PR TITLE
Slight tweak to the tab design

### PR DESCRIPTION
**Pull request by yair100**
Added a border to the selected tab

### CODE REVIEW

**Comment by tsvietOK** [comment]
Can you post updated design?

**Comment by yaichenbaum** [comment]
Before:
image
After:
image

**Review by tsvietOK — APPROVED** [review]

**Comment by d2dyno1** [comment]
@yair100 how about a dropshadow instead of this outline? 
image

**Comment by yaichenbaum** [comment]
@d2dyno1 There is already a drop shadow, it looks like the screenshot didn't capture it.

**Pull request merged**
