### PR TITLE
Fix: Fixed issue where type column wasn't translated

### LINKED ISSUE #10320: Bug: Localization switching back to Default on DetailsBrowser
### Description

When opening a view in Details Browser, when the view is done loading, all the items localization switch back to the default language.

### Steps To Reproduce

1. Go into Settings and set any language other than default (to better see the issue)
2. Switch back to any tab and open a folder with several different object.
3. Observe the localization going from selected language to the default language.

### Steps to fix

- The localization stays to the default language.

### Files Version

Version : 2.3.48.0 OS

### Windows Version

W11 21H2 Version: 10.0.22000.1098

### Relevant Assets/Logs

BrokenLoca

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
The column Type is displayed in the Windows language. This is because ViewModel replaces the value of ItemType (which is created and located by Files) with the value DisplayType (which is managed by Windows). This pr removes this override so that the display is the one created by Files. Closes #10320.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Review by QuaintMako — DISMISSED** [review]
LGTM.

**Comment by yaichenbaum** [comment]
The overrides from Windows are usually better, this is the before and after
image

image

**Comment by cinqmilleans** [comment]
We have several choices:
1) Do not modify anything. The column will always display in the Windows language. Users using Files in a different language are probably extremely rare. In addition, they are accustomed to or understand the Windows language.
2) Select a list of cases to deal with ourselves (Folder, ...) and not manage the others.
3) Improve our code to better handle all cases. It requires a lot of work and knowing all the files.
4) Manage everything ourselves as it is currently done.

I propose 1) which requires no work and satisfies the user.

**Comment by yaichenbaum** [comment]
> Do not modify anything. The column will always display in the Windows language. Users using Files in a different language are probably extremely rare. In addition, they are accustomed to or understand the Windows language.

What would this look like?

**Comment by cinqmilleans** [comment]
It's closed this pr and continue as before. The column appears in the Windows language. For most users this does not change anything because Windows and Files will be in the same language.

**Pull request closed without merging**
