### PR TITLE
Add security tab to properties #1647

### PR DESCRIPTION
**Pull request by oleitao**
**Details of Changes**
Add details of changes here.
- Added security tab to properties on folders properties

**Screenshots (optional)**
Capture

### CODE REVIEW

**Comment by XPoppyX** [comment]
Proposal for the icon:
**EA18**

ea18

**Comment by tsvietOK** [comment]
What is the purpose of this PR? As i understand, it is empty for now...

**Comment by oleitao** [comment]
> What is the purpose of this PR? As i understand, it is empty for now...

@tsvietOK  yes. As you can read on [1647](https://github.com/files-community/Files/issues/1647) there you don't have nothing more than that description to create new Security tab.

**Comment by tsvietOK** [comment]
I guess when user requests to add some feature, it means feature should be implemented with at least minimum functionality. Thank you for your PR, but empty Security tab is useless. There is two ways now, first is to implement minimum Security functionality. Second, keep your code as it is, but hide tab at all, so in the future this feature could be done by someone else.

**Comment by oleitao** [comment]
> first is to implement minimum Security functionality.

Do you have any suggestions? Or can i implement that panel based on Windows 10 File Explorer?

**Comment by yaichenbaum** [comment]
@oleitao The best thing would be to hide the tab for now, we want to have a discussion about how implement this feature. We feel that rather than basing it off of File Explorer, we should see what we can do to improve the feature.

**Comment by yaichenbaum** [comment]
@zeealeid @mdtauk do you have any ideas how we can design the security tab? We can technically copy the UX that's found in File Explorer, but I wonder if we can do something different that's also easier to use.

**Comment by mdtauk** [comment]
> @zeealeid @mdtauk do you have any ideas how we can design the security tab? We can technically copy the UX that's found in File Explorer, but I wonder if we can do something different that's also easier to use.


The Security Tab is like a dashboard.  So a visual representation would be useful here.  

The Group or User Names - should perhaps look like users, so maybe look to Fluent UI

**Comment by yaichenbaum** [comment]
@mdtauk Michael West just made a really nice concept which I think will be great for the first implementation. Feel free to add your feedback.
image

**Comment by mdtauk** [comment]
> @mdtauk Michael West just made a really nice concept which I think will be great for the first implementation. Feel free to add your feedback.
> image

Looking really good to me.  Unless those CheckBoxes are interactive, it may be worth using a glyph instead of the control.  The original dialog does the permission assignments in another dialog.

Also the permissions grid could be justified right and left, so it is centred in the dialog.

**Comment by yaichenbaum** [comment]
@mdtauk The check boxes will be interactive.

**Comment by mdtauk** [comment]
> @mdtauk The check boxes will be interactive.

Ah, so how does it handle Elevation?

**Comment by yaichenbaum** [comment]
@mdtauk The user will need to click a button that will launch the UAC prompt before anything in the security tab is displayed.

**Comment by mdtauk** [comment]
> @mdtauk The user will need to click a button that will launch the UAC prompt before anything in the security tab is displayed.

Ok that is fair enough then!

**Comment by yaichenbaum** [comment]
@oleitao Are you still working on this?

**Comment by oleitao** [comment]
> @oleitao Are you still working on this?

@yair100 yes i'm still working on that PR

**Comment by yaichenbaum** [comment]
> > @oleitao Are you still working on this?
> 
> @yaichenbaum yes i'm still working on that PR

@oleitao Can you mark this as a draft?

**Comment by oleitao** [comment]
> > @oleitao Are you still working on this?
> 
> @yair100 yes i'm still working on that PR

That my last re-design of Security Properties. Please send your feedback.

Capture2

**Comment by oleitao** [comment]
Hi @yair100 I've an question about how to manage users, groups, permissions over files and folders. 
So, to deal with permissions over files and folder i think the best approach is to use [OpenLDAP](https://sourceforge.net/projects/openldapwindows/) as an server running on background. On settings should have an option to restore factory RBAC in order to the user (as administrator) reset all permissions and preventing undesired permissions.
However, that feature using LDAP will require to install OpenLDAP with Files. 
Give me some feedback if that this approach as i described is approved or someone have another better approach?

**Comment by yaichenbaum** [comment]
@oleitao We shouldn't require users to install another application together with Files to get this kind of feature.

**Comment by yair100** [comment]
> > > @oleitao Are you still working on this?
> > 
> > 
> > @yair100 yes i'm still working on that PR
> 
> That my last re-design of Security Properties. Please send your feedback.
> 
> Capture2

@oleitao The design is looking pretty good! Keep the reference design in mind so that the final version looks as close as possible to it.

**Comment by oleitao** [comment]
> @oleitao We shouldn't require users to install another application together with Files to get this kind of feature.

@yair100 can you give some details how you suggest to do that?

**Comment by yaichenbaum** [comment]
@oleitao The best option is to build the features into Files itself. If needed, we can elevate the FullTrustProcess.

**Comment by yaichenbaum** [comment]
@oleitao How is development on this going so far?

**Comment by oleitao** [comment]
> @oleitao How is development on this going so far?

Hi @yair100 at the moment i've stoped the development because i've no time.

**Comment by yair100** [comment]
> > @oleitao How is development on this going so far?
> 
> Hi @yair100 at the moment i've stoped the development because i've no time.

Thanks for the update, we are working on this feature ourselves.

**Pull request closed without merging**
