### PR TITLE
Fixed icon for Close Pane button

### LINKED ISSUE #8466: Missing close pane icon
### Description

Missing close pane icon in toolbar. 

### Steps To Reproduce

_No response_

### Expected behavior

There should be an icon of closing pane

### Files Version

Version: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

image

### PR DESCRIPTION
**Pull request by konradsikorski**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #8466 

**Details of Changes**
Add details of changes here.
- Fixed an icon by changing the Glyph

**Validation**
How did you test these changes?
- [X] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image

### CODE REVIEW

**Review by yair100 — APPROVED** [review]
LGTM

**Comment by yaichenbaum** [comment]
@konradsikorski before we merge this, can you add your agreement to #7625?

**Comment by d2dyno1** [comment]
Can you fix conflicts?

**Comment by konradsikorski** [comment]
@yair100 agreement added

**Comment by yaichenbaum** [comment]
@konradsikorski can you resolve the merge conflicts?

**Pull request closed without merging**
