### PR TITLE
Move drag area to MainPage

### LINKED ISSUE #5476: Unable to move the files app on windows 10
**Explain the bug**
Trying to move around the app on the latest update (1.9) as you can see in the screenshot
Untitled

**To reproduce**
try to move the app around from anywhere within the above screenshot

**Expected behavior**
Should be able to move from anywhere on the top bar

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6862348/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6862349/debug_fulltrust.log)

**Screenshots**
Screenshot above

**System Information**
 - OS Version: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎19/‎05/‎2021
OS build	19043.1147
Experience	Windows Feature Experience Pack 120.2212.3920.0

 - App version: 1.9

### LINKED ISSUE #5487: Bug report: Switching the color mode crashes the app
**To reproduce**
1. Go to settings
2. Change the theme
3. See error

**System Information**
 - OS Version: Windows 11 22000.100
 - App version: v1.9

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5476
- Closes #5487

**Details of Changes**
Add details of changes here.
- Moved the drag area to MainPage (on `main` + Windows 10 I cannot drag the window by the titlebar)
- Fixes crash when changing app theme

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 I'm getting an issue when building the app in debug mode.

image

**Comment by gave92** [comment]
Mmm can't reproduce that.. @winston-de could you check if it's the same for you?

**Comment by gave92** [comment]
@yair100 could you check if the latest commit fixes the issue?

**Comment by yair100** [comment]
> @yair100 could you check if the latest commit fixes the issue?

It's working fine now, lgtm!

**Review by yair100 — APPROVED** [review]

**Pull request merged**
