### PR TITLE
Fixed crash that would occur when checking for updates

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fix crash when checking for updates. IUpdateService methods are supposed to be called from the UI thread.
- Wait for file transfers to complete before terminating process
- Restored call to UpdateTagsDb()

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by hez2010** [comment]
I don't think all code in `InitializeAppComponentsAsync` should run on the UI thread. This will make the Window slower to show.
How about making IUpdateService only run on the UI thread?

**Comment by yaichenbaum** [comment]
The check for update code could also be deferred until everything else is loaded.

**Comment by gave92** [comment]
The code in initializeblabla() is not called all on ui thread. There's a Task.Run in there. Update check is deferred untill everything else is loaded.

**Review by hez2010 — APPROVED** [review]
LGTM

**Pull request merged**
