### PR TITLE
Translations Update

### PR DESCRIPTION
**Pull request by esibruti**
**Details of Changes**
Add details of changes here.
- Minor update in the Portuguese (Portugal) language
- Minor update in the Greek language
- Minor update in the English (Great Britain) language
- Minor update in the French language
- Minor update in the Turkey language
- Small correction in the Portuguese (Brazil) language
- Big update in the Japanese (Japan) language
- Big update in the Korean (Korea) language
- Big update in the Czech (Czech Republic) language
- Minor update in the Italian (Italy) language

### CODE REVIEW

**Comment by esibruti** [comment]
Now I will wait for PR #5919

**Comment by esibruti** [comment]
@yair100 @gave92 Don't accept it yet... I have to resolve the conflicts... I have to finish sooner...

**Comment by BanCrash** [comment]
> @yair100 @gave92 Don't accept it yet... I have to resolve the conflicts... I have to finish sooner...

You can convert it back again as draft, on the top right, below reviewers.

**Comment by esibruti** [comment]
> ‎Você pode convertê-lo novamente como rascunho, no canto superior direito, abaixo dos revisores.‎



> > @yair100 @gave92 Don't accept it yet... I have to resolve the conflicts... I have to finish sooner...
> 
> You can convert it back again as draft, on the top right, below reviewers.

@BanCrash But will I still be able to fix conflicts later?
Edit: forget it, i already know how to do

**Comment by esibruti** [comment]
Ok, now it's ready!

**Comment by esibruti** [comment]
> @esibruti can you revert the machine translated strings?

@yair100 The best thing is to close this PR... It will be a lot of work and it will be very confusing

**Pull request closed without merging**
