### PR TITLE
Code Quality: Moving registry database to Files.App

### PR DESCRIPTION
**Pull request by hez2010**
**Resolved / Related Issues**

Fixes all `COMException` crashing issues caused by CsWinRT. Particularly, `LayoutPreferenceDatabase` and `FileTagsDatabase`.

### CODE REVIEW

**Comment by hez2010** [comment]
> @hez2010 can you add steps we can use to test these changes?

No behavior changes as this is basically a copy-paste from Files.App.Server to Files.App

**Review by 0x5bfa — APPROVED** [review]
Can't we have both to easily revert when the package's issue fixed instead of deleting classes?

Code changes are looking good.

**Comment by hez2010** [comment]
> Can't we have both to easily revert when the package's issue fixed instead of deleting classes?

I made this change in about 20 minutes. It's almost a copy-paste and fixing namespace thing. 
We are using registry now, so we don't need to move it to the server project as registry is thread safe. Thus, I don't think we want to revert this PR in the future.

**Review by hishitetsu — APPROVED** [review]
I confirmed that it works fine. LGTM

**Pull request merged**
