### PR TITLE
chore: optimized images

### LINKED ISSUE #5105: Image from readme is too big to open it
The preview image from the readme is too big to open it in the GitHub app

### PR DESCRIPTION
**Pull request by Zerotask**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5105

**Details of Changes**
Optimized images with tinypng.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@Zerotask Does this affect the quality or sharpness in any way?

**Comment by Zerotask** [comment]
@yair100 No, the quality is the same.

**Review by yair100 — DISMISSED** [review]
LGTM

**Comment by yaichenbaum** [comment]
@Zerotask Can you solve the build issue?

**Comment by Zerotask** [comment]
@yair100 I don't think I caused the problem. Can you check that?

**Comment by yaichenbaum** [comment]
The problem is because certain icon files need to match exactly, it looks like those files were compressed differently.

**Comment by Zerotask** [comment]
What exactly has to match and why? I did not change the width or height and if 2x the same images will be copied to the same destination, as the pipeline error says, this looks like a mistake to me.

**Comment by tsvietOK** [comment]
I guess icons in Files/Assets should match icons in Files.Package?

**Comment by Zerotask** [comment]
> I guess icons in Files/Assets should match icons in Files.Package?

But why 2x the same images and what is the criteria? The file size? Looks pretty strange for me such a behaviour. I could understand it, if it checks width and height, but I didn't change that.

**Comment by yaichenbaum** [comment]
> > I guess icons in Files/Assets should match icons in Files.Package?
> 
> But why 2x the same images and what is the criteria? The file size? Looks pretty strange for me such a behaviour. I could understand it, if it checks width and height, but I didn't change that.

The packaging behavior is very specific, it's possible they need the same hash.

**Comment by tsvietOK** [comment]
@Zerotask Yes, it will fix this issue. Just update all icons in FIles.Package/Assets from Files.Assets.

**Comment by Zerotask** [comment]
Okay, but this is pretty strange to me. The error also indicates that the root of the problem is something else.
I recommend having a centralized folder for images instead of duplicate folders.
Optimizing images shouldn't really cause such problems.

> @Zerotask Yes, it will fix this issue. Just update all icons in FIles.Package/Assets from Files/Assets.

I copied the smaller amount of images from FIles.Package/Assets to Files/Assets. Hope this will fix the CI/CD problem.

**Review by tsvietOK — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@Zerotask Thanks for the PR, would you happen to know how much space was saved with these optimizations?

**Comment by Zerotask** [comment]
@yair100 approx. 6.55 MB saved.

**Comment by yair100** [comment]
> @yair100 approx. 6,55 MB saved.

That's great! Thank you 🙂

**Pull request merged**
