### PR TITLE
Code Quality: Use LoadIconWithoutOverlayAsync for Drives Widget

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
Related to #14499

### CODE REVIEW

**Comment by yaira2** [comment]
@foxnoodles @Mantej-Singh if you have Visual Studio, can you see if this fixes #14499?

**Comment by Mantej-Singh** [comment]
I do have Visual Studio, but i don't know how to run or test this fix

**Comment by Mantej-Singh** [comment]
Good work.
image

Working as expected.

**Comment by yaira2** [comment]
@Mantej-Singh thanks for checking! Can you check again with the latest commit and confirm if it's still good?

**Comment by Mantej-Singh** [comment]
on it!!

**Comment by Mantej-Singh** [comment]
@yaira2 
Nope, it did not work
image

**Comment by yaira2** [comment]
The underlying issue is that the requested icon size (256) is missing from the ico file. Requesting a smaller icon size would reduce the quality of the other icons so that's not really an option.

**Comment by yaira2** [comment]
@Mantej-Singh is there any difference with the latest commit? If this doesn't help, we'll merge these changes as is and continue tracking the issue in #14499.

**Pull request merged**
