### PR TITLE
Fix: Update thumbnail when rotating image

### LINKED ISSUE #11631: Bug: Rotate Image does not refresh icon thumbnail
### Description

Using the "Rotate Left" or "Rotate Right" action from the flyout menu and toolbar does not refresh the icon, while the rotation is actually applied to the image.

### Steps To Reproduce

1- Select an image and use the "Rotate" action from the flyout menu or the tool bar.
2- See the image is actually rotated if opened, but the icon is not refreshed.

### Steps to fix

- The image icon is properly refreshed.

### Files Version

Version 2.4.40 Dev

### Windows Version

W10 Home 22H2 19045.2251

### Log file

[debug.log](https://github.com/files-community/Files/files/10929936/debug.log)

### PR DESCRIPTION
**Pull request by QuaintMako**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #11631

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots**
rotation

### CODE REVIEW

**Comment by QuaintMako** [comment]
Any idea of manipulation that would require a refresh of the selected icons I could try to ensure everything works as expected?

**Comment by yaira2** [comment]
> Any idea of manipulation that would require a refresh of the selected icons I could try to ensure everything works as expected?

1. Changing a folders thumbnail

**Comment by QuaintMako** [comment]
1. Changing a folders thumbnail

Works as expected.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
