### PR TITLE
Fix: Crash caused by useless predicate.

### LINKED ISSUE #15124: Bug: Crash at 3.3.1 when saving"Sync layout and sorting preferences across directories option"
### Description

The apps crashes at 3.3.1 when saving"Sync layout and sorting preferences across directories option".

### Steps To Reproduce

1. Open settings
2. Toggle "Sync layout and sorting preferences across directories"

### Requirements

Fix crash that occurs when the option is saved.

### Files Version

3.3.1-preview

### Windows Version

Version	10.0.22631 Build 22631

### Log File

[debug.log](https://github.com/files-community/Files/files/14891330/debug.log)

### PR DESCRIPTION
**Pull request by gumbarros**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
  Not approved, but I think a crash should be fixed👀, this closes #15124

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [X] Are there any other steps that were used to validate these changes?
1. Open settings
2. Toggle the option

https://github.com/files-community/Files/assets/52143624/f9e3f7c6-522d-48e9-af53-4a72fc379151

**Additional info**
This is the stacktrace of the crash
```cs
2024-04-05 20:19:11.0801|Error|System.Runtime.InteropServices.COMException (0x80131509)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Files.App.Server.Database.ILayoutPreferencesDatabaseClassMethods.ResetAll(IObjectReference _obj, LayoutPreferencesFilterPredicate predicate)
   at Files.App.Server.Database.LayoutPreferencesDatabase.ResetAll(LayoutPreferencesFilterPredicate predicate)
   at Files.App.Helpers.LayoutPreferencesDatabaseManager.ResetAll(Func`2 predicate)
   at Files.App.ViewModels.Settings.LayoutViewModel.ResetLayoutPreferences()
   at Files.App.ViewModels.Settings.LayoutViewModel.set_SyncFolderPreferencesAcrossDirectories(Boolean value)
   at Files.App.Views.Settings.LayoutPage.LayoutPage_obj1_Bindings.UpdateTwoWay_15_IsOn()
   at Files.App.Views.Settings.LayoutPage.LayoutPage_obj1_Bindings.LayoutPage_obj1_BindingsTracking.<RegisterTwoWayListener_15>b__19_0(DependencyObject sender, DependencyProperty prop)
   at ABI.Microsoft.UI.Xaml.DependencyPropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr dp)
```

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@hez2010 Can you take a look?

**Comment by 0x5bfa** [comment]
I think this has occurred during debugging and clicking Continue multiple times fix this issue.

**Comment by hishitetsu** [comment]
This occurs even when not in debugging. Removing the predicate would be sufficient here, but #14911 seems to cause this issue in the first place.

**Review by hez2010 — APPROVED** [review]
LGTM. 
BTW I suggest adding logging for Files.App.Server as well to catch all unhandled exceptions (in the following pr). Otherwise, any exception will reflected as `COMException` without any exception message in Files.App.

**Comment by gumbarros** [comment]
> I think this has occurred during debugging and clicking Continue multiple times fix this issue.

No, I found the crash at the Preview version (the video shows the problem fixed)

**Comment by hez2010** [comment]
This is caused by the `predicate` cannot be converted to `Expression` as the `predicate` contains invocations to clients. 

Can you also remove the unused predicate in `ApplyToAll` as well?

**Comment by gumbarros** [comment]
> Can you also remove the `predicate` parameter from `ApplyToAll` as well? Then I think we can remove the type `LayoutPreferencesFilterPredicate` as well (from both the code and Package.appxmanifest).

Done

**Review by hez2010 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
