### PR TITLE
Added Mica material (part 1)

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added Mica backdrop setting to host pages and made brushes transparent, and added new brushes as needed

Nothing is hard coded, so it should be possible to create a theme that doesn't use Mica.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image
image

### CODE REVIEW

**Comment by mdtauk** [comment]
Mica should be on by default IMO, and if someone wants an acrylic sidebar, the setting can do that.

**Comment by AcidRain9** [comment]
I believe the acrylic sidebar should remain with this

**Comment by winston-de** [comment]
> I believe the acrylic sidebar should remain with this

Using acrylic in the sidebar is something that winui design has moved away from, and it doesn't really make sense to use it with Mica. Also, an acrylic sidebar will still be achievable using a custom theme.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
