### PR TITLE
Feature: Added support for filtering current directory when typing into search box

### LINKED ISSUE #14391: Feature: Filter current directory when typing into search box
### What feature or improvement do you think would benefit Files?

This feature is an absolute must-have for me: imagine a list of thousands of files, typing just "test" in the filter zone will display all the files or folders containing "test" in their name, it soooo useful, I'm using this search zone dozen times a day!

I'm still using [QTTabBar](http://qttabbar.wikidot.com/), but it's no more maintained, and bugs appear in Win11 23H2 after using ViVeTool for disabling the default Windows tabs.

### Requirements

1. Typing query into the search box should filter the items in the current directory
2. The dropdown menu should keep the existing behavior and continue to display suggestions
3. Pressing enter should start a full search
4. Removing the focus from the search box currently resets the search text, this behavior should be changed so that users can keep the current filter without keeping the focus on the search box.

### Files Version

v3.1

### Windows Version

10.0.22631.2861

### Comments

file-filter

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #14391 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Comment by yaira2** [comment]
This is working well 🎉 

Would it make sense to supporting filtering search results as well?

**Comment by yaira2** [comment]
There are some weird behaviors in the columns view but I don't think it's a blocking issue.

**Comment by hishitetsu** [comment]
I found that sorting after filtering will remove the filtering. I'll fix it.

**Comment by hishitetsu** [comment]
> I found that sorting after filtering will remove the filtering. I'll fix it.

Fixed.

**Review by 0x5bfa — APPROVED** [review]
Looks good codewise.

**Comment by yaira2** [comment]
@hishitetsu what about grouping?

**Comment by hishitetsu** [comment]
> @hishitetsu what about grouping?

There should be no problem.

**Comment by yaira2** [comment]
Nice work!

**Pull request merged**
