### PR TITLE
Code quality: Introduced WidgetsPageContext

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Details**
This PR introduces `WidgetsPageContext` which will be needed to use `RichCommands` from the `WidgetsPage`
This context will be useful to implement features such as `Open Properties`, `Copy`, ..., which requires the right clicked item
Once it will be merged, I'll remove `TagsContext` from #11598 since it won't be needed anymore

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by ferrariofilippo** [comment]
@cinqmilleans can you review this?

**Comment by cinqmilleans** [comment]
I will look at this tomorrow.

**Comment by cinqmilleans** [comment]
My remarks. The result is below.
* Fields should not start with underscore.
* emptyTaggedItemsList can be renamed to emptyTaggedItems (don't use type in variable name if not needed)
* emptyTaggedItems should be IImmutableList
* IsAnyItemRightClicked has a more logical location above RightClickedItem.
* SelectedTaggedItems.set can be simplified, set => selectedTaggedItems = value?? emptyTaggedItems;
* SelectedTaggedItems should be IReadOnlyList or even IImmutableList. The user cannot modify it or reuse an old instance that he stored before his change.
* Use ObservableObject.SetProperty to simplify updates.
*  Use named tuples to avoid deconstruction.

Which disturbs me.
* Using a tuple in a public signature should be avoided. Maybe use a class but that's minor.
* SelectedTaggedItems should not be editable by the caller. The context should watch itself to update. Use set if it changes the state (if the caller can use it to change the selection) and not to be notified of a change.

```
internal class WidgetsPageContext : ObservableObject, IWidgetsPageContext
{
	private static readonly IImmutableList<FileTagsItemViewModel> emptyTaggedItems
		= Enumerable.Empty<FileTagsItemViewModel>().ToImmutableList();

	public bool IsAnyItemRightClicked => rightClickedItem is not null;

	private WidgetCardItem? rightClickedItem = null;
	public WidgetCardItem? RightClickedItem => rightClickedItem;

	private CommandBarFlyout? itemContextFlyoutMenu = null;
	public CommandBarFlyout? ItemContextFlyoutMenu => itemContextFlyoutMenu;

	private IReadOnlyList<FileTagsItemViewModel> selectedTaggedItems = emptyTaggedItems;
	public IReadOnlyList<FileTagsItemViewModel> SelectedTaggedItems
	{
		get => selectedTaggedItems;
		set => selectedTaggedItems = value ?? emptyTaggedItems;
	}

	public WidgetsPageContext()
	{
		HomePageWidget.RightClickedItemChanged += HomePageWidget_RightClickedItemChanged;
	}

	private void HomePageWidget_RightClickedItemChanged(object? sender, (WidgetCardItem Item, CommandBarFlyout Flyout) e)
	{
		if (SetProperty(ref rightClickedItem, e.Item, nameof(RightClickedItem)))
			OnPropertyChanged(nameof(IsAnyItemRightClicked));

		SetProperty(ref itemContextFlyoutMenu, e.Flyout, nameof(ItemContextFlyoutMenu));
	}
}
```

**Comment by 0x5bfa** [comment]
> Fields should not start with underscore.

We use fields starts with underscore. 
- Defined in our guideline.
- name will be conflicted with arguments, so that we have to add ’this.’.

**Comment by 0x5bfa** [comment]
Are you still working on? Once conflicts fixed, I’d review the PR.

**Comment by ferrariofilippo** [comment]
> Are you still working on? Once conflicts fixed, I’d review the PR.

Actually, once we decide how to support RichCommands with parameters I'll close this one and TagsContext PR

**Pull request closed without merging**
