### PR TITLE
Fixed an issue where drag and drop would sometime crash the app

### LINKED ISSUE #2023: Allow drag and drop from other apps
**Is your feature request related to a problem? Please describe.**
Yes. I'm always frustrated when, for example, I've got a zip file open with WinRar, I can't drag and drop and I'm forced to use the default (ugly) windows file, explorer.

**Describe the solution you'd like**
I'd like to be able to select a file, drag and drop it, from/to an external app or website, and to be able to move files using drag-and-drop directly in the Files app.

**Describe alternatives you've considered**
I've considered nothing that better and that fast so far

### PR DESCRIPTION
**Pull request by yair100**
Fixes #2023

### CODE REVIEW

**Review by lukeblevins — DISMISSED** [review]
Haven't found any issues with this solution yet, and we can always drop this if/when the drag and drop issues are fixed natively.

**Comment by gave92** [comment]
Uops made mistake when merging, please hang on

**Comment by yaichenbaum** [comment]
@gave92 Do you want to reopen this pull request from your end since it's really your work?

**Comment by gave92** [comment]
@yair100 nah I don't mind :)

**Comment by yair100** [comment]
> @yair100 nah I don't mind :)

Ok, you might need to approve it for me 😃

**Comment by gave92** [comment]
Ok I was looking at how to translate the "Drop here" text that appears if possible, then it should be ready

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Great work!

**Pull request merged**
