### PR TITLE
Improve performance of watcher, operations and props loading

### PR DESCRIPTION
**Pull request by hez2010**
**Details of Changes**
- Remove unnecessary semaphore
- Added AsyncManualResetEvent to unblock threads
- Insert a bunch of cancellation points for props loading to cancel eagerly before heavy I/O operations
- Remove SQLite naming cache because it harms navigation speed and introduced inconsistency (displayName may change), but only brings little benefit, which doesn't worth
- Parallelize copy, cut and remove preparation process

File creation is usually a combination of creation (creating a file handle) and modification (writing initial content), given that `UpdateFileOrFolderAsync` is slow, we introduced performance regression unexpectedly in #5992. This PR also aims to resolve the performance issue of `UpdateFileOrFolderAsync`:

- Lowered priority of file update
- Avoid checking sync status for folders don't support sync
- Parallel update

Contributes to #4180

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Before:

https://user-images.githubusercontent.com/14960345/131966691-ecc1ab97-2142-453f-a298-a0a5386ff157.mp4

https://user-images.githubusercontent.com/14960345/131804143-bd7540e0-f681-4340-937b-72102559b68e.mp4

After:

https://user-images.githubusercontent.com/14960345/131804160-21e3f693-4781-4a6d-adf2-1bcb9e152beb.mp4

https://user-images.githubusercontent.com/14960345/131966708-fc3a024d-6f81-453c-9270-ce28cd43f8f2.mp4

### CODE REVIEW

**Comment by zsh2401** [comment]
Wonderful Effect!

**Comment by hez2010** [comment]
@gave92 Improvements I planned to do have done. This PR is ready for review now.

**Review by winston-de — APPROVED** [review]
lgtm

**Comment by winston-de** [comment]
Probably also closes #5822

**Comment by yaichenbaum** [comment]
> Probably also closes #5822

It doesn't seem to load thumbnails much faster.

**Comment by yaichenbaum** [comment]
@hez2010 great work!

**Comment by hez2010** [comment]
@yair100 This PR somehow makes icon loading higher priority than extended props loading, so it does contribute to #5822

**Comment by josh-65** [comment]
They are faster but still not as fast as file explorer. So maybe it could still be improved.

**Pull request merged**
