### PR TITLE
GitHub: Remove artifacts older than 24 hours automatically

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Resolved / Related Issues

*Planned internally*

### Steps used to test these changes

Trigger the CI in the main branch later

### CODE REVIEW

**Comment by 0x5bfa** [comment]
This is failing because deleting all artifacts result in a massive request of GitHub API. @yaira2 do you already have an access token or can you create an access token in this organization settings?

**Comment by yaira2** [comment]
Is there a benefit to this over setting the retention?

**Comment by 0x5bfa** [comment]
Didn’t say the organization is running out of Actions storage pool?
If setting Retention Setting to 1 day or something and everything is gonna be fine, it’s fine with me but I thought you want to remove artifacts published within 10 days (you set it to 15 days previously and now 5 days).
if we have this we don’t think about storage anymore when we are uploading other things in the future tho.

**Comment by yaira2** [comment]
> Shared storage consists of Actions artifacts and Packages usage. This graph shows the account's storage usage in GB-months. Removing stored artifacts will not reduce this number, but it will lower its rate of growth. To see your account's current storage, download a usage report.

It doesn't seem that changing the retention or deleting the existing artifacts will make a difference. These are our options
- Find a way to pass the package to the testing job
- Require manually triggering the action
- Merge the testing job together with the build job

**Comment by 0x5bfa** [comment]
Sigh, I said it’s on the docs. Deleting of course makes difference since it free up spaces.
I don’t recommend to merge two jobs btw

**Pull request closed without merging**
