### PR TITLE
Added options to hide/show sections on the sidebar

### LINKED ISSUE #5285: Feature request: Add options to hide/show sections on the sidebar
**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will add settings to hide/show sections on the sidebar | Must |
| This proposal will show an option to hide sections on the sidebar when right clicking on them | Must |

### PR DESCRIPTION
**Pull request by oleitao**
**Resolved / Related Issues**
- Closes #5285

**Details of Changes**
- Added right-click on sidebar sections option to remove sections from sidebar
- Added option on settings panel what sections should be hide/show on sidebar

**Validation**
- [x] Right-click on each sidebar sections and select option 'Unpin from sidebar' to remove from sidebar
- [x] Select on settings panel sections to be hide/show

Edition: Windows 10 Pro
OS build: 19042.1052

### CODE REVIEW

**Comment by gave92** [comment]
@yair100 should the user be able to hide the "favorites" section as well? Would this hide the home item too?

**Comment by yair100** [comment]
> @yair100 should the user be able to hide the "favorites" section as well? Would this hide the home item too?

@gave92 I don't think so, this feature request was intended so that users can hide the other sections.

**Comment by gave92** [comment]
This is how it would appear when hiding the favorites section (home item still visible):
image

**Comment by yaichenbaum** [comment]
Yeah, the favorites section should always be visible.

**Review by gave92 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@gave92 How does it work with defaults? Like the first time WSL is detected, the setting for WSL should be turned on...

**Comment by yaichenbaum** [comment]
@oleitao Instead of the menu saying "Unpin from sidebar", can you change it to say "Hide library section", "Hide network section" etc?

**Comment by gave92** [comment]
> How does it work with defaults?

All sidebar sections are show by default with the exception of WSL

> Like the first time WSL is detected, the setting for WSL should be turned on...

Oh no no =)

**Comment by yaichenbaum** [comment]
@gave92 In that case we can turn it on by default without any weird side affects.

**Comment by gave92** [comment]
> Instead of the menu saying "Unpin from sidebar", can you change it to say "Hide library section", "Hide network section" etc?

Done!

> In that case we can turn it on by default without any weird side effects.

Done!

**Review by yair100 — APPROVED** [review]
Great work! LGTM

**Comment by yaichenbaum** [comment]
@oleitao It looks like the WSL section is hidden even when the setting it turned on.

**Comment by gave92** [comment]
The wsl section is always hidden unless any wsl drives are detected.

**Comment by yaichenbaum** [comment]
It looks like my WSL setup stopped working after updating to Windows 11.

**Pull request merged**
