### PR TITLE
Feature: Add Xaml Styler GitHub Action

### LINKED ISSUE #7499: Add Xaml Styler step to devops pipeline
Add Xaml Styler step to devops pipeline to make sure the xaml is formatted correctly. https://www.nuget.org/packages/XamlStyler.Console

### PR DESCRIPTION
**Pull request by heftymouse**
This will have to be added as a separate pipeline in the ADO portal. This was done to make it clearer what exactly is failing without having to look at logs.

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7499

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaira2** [comment]
Instead of failing, can we push a commit to the PR?

**Comment by heftymouse** [comment]
That can certainly be done

**Comment by onein528** [comment]
Maybe Files pipelines should be split for specific functions. And inject all into job group. This files that you added doesn't work properly because Yair configure that yml file as Azure Pipeline.

**Comment by yaira2** [comment]
@heftymouse are you still working on this?

**Comment by heftymouse** [comment]
I'm still working on this, apologies for the delay

**Comment by yaira2** [comment]
@heftymouse do I need to do anything to activate the action?

**Review by yaira2 — APPROVED** [review]
LGTM

**Review by 0x5bfa — APPROVED** [review]
LGTM. It was a great job, looking commit messages😄

**Pull request merged**
