### PR TITLE
Fixed: Draging files over items select them

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related: #6768 

**Comments**
- I fixed the bug delaying the selection at the end of the timer. This way, the hovered item is selected just before it's opened.
- There's still a problem with `ColumnsLayout`, where items have `SelectedStyle` even when they're not. I believe the bug affects `ListViewBase` since the code is the same as in `GridViewBase`, where the feature is working.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by yaichenbaum** [comment]
> There's still a problem with ColumnsLayout, where items have SelectedStyle even when they're not. I believe the bug affects ListViewBase since the code is the same as in GridViewBase, where the feature is working

Doesn't DetailsLayout use ListViewBase as well?

**Comment by ferrariofilippo** [comment]
If you hover over a folder for 1s while dragging an item, Files selects it and opens it.
If you use `DetailsLayout` this is not a problem, because Files loads a new pane.
With `ColumnsLayout`, the selected folder is opened in a new pane, but the previous one remains open. The bug happens here.

**Comment by ferrariofilippo** [comment]
I just found out that you have already tracked this issue in #9594

**Comment by yaichenbaum** [comment]
https://github.com/files-community/Files/issues/9594 is a different issue

**Pull request merged**
