### PR TITLE
Fix: Fixed an issue where the setting control margin is a bit off

### PR DESCRIPTION
**Pull request by 0x5bfa**
## PR Checklist

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   _None_

## Screenshots

After|Before
---|---
image|image

### CODE REVIEW

**Comment by 0x5bfa** [comment]
You can notice that the Header position is bit off. so fixed.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
Does this also affect the properties window?

**Comment by 0x5bfa** [comment]
Of course. Also fix that problem in properties windows.

**Pull request merged**
