### PR TITLE
Use the .log extension for log files instead of .txt

### PR DESCRIPTION
**Pull request by jaigak**

### CODE REVIEW

**Review by seltinusjulio — APPROVED** [review]
Good idea

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Is there any reason to make this change?

**Comment by jaigak** [comment]
@yair100 The only reason I changed the extension was to make the log file more identifiable for non-technical users.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Unless users are asking for this I don't think there is much of a reason to do it...

**Pull request closed without merging**
