### PR TITLE
Feature: Allows to change library icon

### LINKED ISSUE #9445: The customise option in properties is not visable for librarys
### Description

File explorer allows changing the icon witch files use to do but now doesnt show the section on the properties window

### Steps To Reproduce

_No response_

### Expected behavior

Customise section like for folders should show

### Files Version

2.3.0.0

### Windows Version

10.0.19043.1685

### Relevant Assets/Logs

Not relevant

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title

## PR Checklist

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #9445
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   _None_

## Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
There's an issue where the adding library location OpenDialog will open based on the main window not the properties window and there's duplicated background brush on the libraries page. Fixed in my local branch about less than 100 line changes, could I push?

**Comment by yaira2** [comment]
Did you validate these changes? I seem to recall there being an issue where it didn't work to modify the icons for libraries.

**Comment by 0x5bfa** [comment]
I found issues

- Libraries page won't enumerate
- Icon cannot be customized

**Comment by yaira2** [comment]
It works in File Explorer but we disabled it in Files because of those issues.

**Comment by 0x5bfa** [comment]
I know Win32API functions to enumerate library locations and to set original icon to a folder but I'm not sure how large this PR will be if I fix.

**Comment by 0x5bfa** [comment]
I have not expected this, so let me close this PR as for now.

**Pull request closed without merging**
