### PR TITLE
Code Quality: Move Resources dir to Assets

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title.

## PR Checklist

- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   - opened the details pane and confirmed the information was correctly displayed
   - opened the properties window and confirmed the information in the details page was correctly displayed

## Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Assets folder is mess and I’d like to get them have this simple structure:

```
Assets/
 Libraries/ (DLL and EXE files)
 Images/ (icon images)
 Resources/ (reg files and json files)
```

**Comment by yaira2** [comment]
I usually view `Assets` as reserved for images and the like.

**Comment by 0x5bfa** [comment]
But those resources are already there except those json files.

the folder will look like after packaged:
```
Assets/
 AppTiles (app icons, no changes)
 Images (archive logos, fluent icons)
 Libraries (DLL,EXE)
 Resources (reg files, json files)
``` 

Current structure doesn’t provide identical folders for each purpose.

https://learn.microsoft.com/en-us/windows/uwp/app-resources/images-tailored-for-scale-theme-contrast#qualify-an-image-resource-for-scale-theme-and-contrast

**Comment by 0x5bfa** [comment]
In the future I want to put 7z DLL files in Libraries dir

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
For testing, we need to test the features that rely on the moved resources. This includes the details pane and properties window.

**Comment by yaira2** [comment]
I tested these changes (added to the PR description) and I can confirm it's working as expected.

**Pull request merged**
