### PR TITLE
Eureka?

### LINKED ISSUE #6469: Maintain Sidebar state
### Description

Settings allow for sections in the sidebar to be toggled on and off. It is desirable to maintain tsidebar stat (expanded / collapsed) between sessions. Currently closing the application when maximized does not maintain current state and all panels open minimized.

### Steps To Reproduce

- Set a default folder and set 'show drives section' to true.
- Expand drives
- maximize window and close app
- relauch app and drive section is collapsed

### Expected behavior

expanded / collapsed state should be maintained regardless of window state

### Files Version

2.0.13.0

### Windows Version

Windows 11

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6469

**Details of Changes**
Add details of changes here.
- This should fix the annoying issue for which sidebar sections are not correctly expanded on app start. Could someone verify?

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 this looks good, it's a bit hard to test in a debug build since the issue is intermitent but I think it's safe to merge the changes.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by cinqmilleans** [comment]
@gave92 Well done and thank you. It was a very annoying bug. I tried to fix this bug but was unsuccessful.

**Comment by gave92** [comment]
Trick was to expand sections only when they have at least one subitem.

**Pull request merged**
