### PR TITLE
Fix: Fixed an issue where right clicking empty space didn't clear selection

### LINKED ISSUE #12402: Bug: Right clicking blank space doesn't clear selected item
### Description

Right clicking a blank space isn't clearing the selected items, this is causing an issue where the context menu has the wrong list of options.

### Steps To Reproduce

1. Select some files
2. Right click a blank space
3. See that the items are still selected

### Requirements

- Clear items when right clicking a blank space

### Files Version

v2.4.82

### Windows Version

Windows 11

### Log file

NA

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12402 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app
   2. Selected some items
   3. Right click on white space

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by ferrariofilippo** [comment]
I think that would be the expected behaviour by most users

**Comment by yaira2** [comment]
I tested column layout again, it's not working if a single folder is selected but it does work if multiple folders are selected.

**Comment by ferrariofilippo** [comment]
Ok, I'll look into this as soon as I can

**Pull request merged**
