### PR TITLE
Fix: Fixed issue where tags loaded slowly

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Since #10250 file tags are loaded noticeably slower. This PR restores the previous code. LiteDB dependency is downgraded to v4 as v5 does not handle concurrent access from multiple processes for packaged apps.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by hez2010** [comment]
Even with LiteDB v4, it still does not work and causes crashing on multiple files instance startup. 
How about replacing LiteDB with SQLite?

**Comment by gave92** [comment]
I can't reproduce the issue with v4. Lite sb should not lock the file with shared connection mode. SqLite is even worse for concurrency iirc.

**Comment by hez2010** [comment]
Try open two files instances and then do file operation (such as Copy, Move, Delete...) on one.

**Comment by hez2010** [comment]
The problem was here before we bump the LiteDB: https://github.com/files-community/Files/pull/10008#pullrequestreview-1144304212

**Comment by gave92** [comment]
Have you verified with this PR? Code is a bit different from #10008.
> Try opening two files instances and then do file operation (such as Copy, Move, Delete...) on one.

Appears ok for me

**Comment by hez2010** [comment]
I think we need to test the LiteDB manually (maybe somewhere other than Files) to make sure a dbfile can be opened from different processes without any issue.

**Comment by gave92** [comment]
The problem in #10008 was this one:
image

**Comment by gave92** [comment]
> I remembered that after merging https://github.com/files-community/Files/pull/10008 we were not able to do the above things until https://github.com/files-community/Files/pull/10250 got merged. Maybe something has changed later.

I'll take this as "I've tested your PR and it does not crash so it's worth more testing" :)

> I think we need to test the LiteDB manually (maybe somewhere other than Files) to make sure a dbfile can be opened and operated from different processes simultaneously without any issue.

Good idea 👍

**Comment by gave92** [comment]
Here is a console program that runs a bunch of read/write to the DB. Launching the exe a few times concurrently appears OK. Let me know if you want to run more tests.
[LiteDBTest.zip](https://github.com/files-community/Files/files/10098361/LiteDBTest.zip)

**Comment by hez2010** [comment]
> Here is a console program that runs a bunch of read/write to the DB. Launching the exe a few times concurrently appears OK. Let me know if you want to run more tests. [LiteDBTest.zip](https://github.com/files-community/Files/files/10098361/LiteDBTest.zip)

Well seems that the concurrency issue no longer persists. It's good to me.

**Comment by gave92** [comment]
Wow I've just tried the test app with LiteDB v5 and read/write perfo is _awful_ when using Shared mode (1 second per each write). That is probably the cause of slow loading of tags. Yuk LiteDB v5!

**Review by hez2010 — APPROVED** [review]
LGTM.

**Pull request merged**
