### PR TITLE
Package: Localized application description

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Motivation & Context

- Localize English more

### PR Checklist

- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
This description is shown in the Settings app on Windows 10 and 11.

**Comment by yaira2** [comment]
Where?

**Comment by 0x5bfa** [comment]
I forgot, but I remember it is probably shown when you refer app info in the Settings app.

As you can see, this appears to users and can be localized https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-description

**Comment by 0x5bfa** [comment]
If you think it is not needed, I'm fine with that and then close.

**Comment by yaira2** [comment]
I wonder if we can remove it all together, is it a required value in the manifest?

**Comment by 0x5bfa** [comment]
Yes. Required field.

https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-visualelements

image

**Pull request closed without merging**
