### PR TITLE
Show localized names for system folders

### LINKED ISSUE #1226: Show localised (localized) names for system folders
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer, it will show the localized name instead of the real name for system folders such as Users folder.

2020-06-25 11-13-34_Trim

**Describe the solution you'd like**
Files UWP should show to localized name instead of the real name for system folders.

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**
Closes #1226

### CODE REVIEW

**Review by duke7553 — APPROVED** [review]
Looks good to me 👍

**Comment by gave92** [comment]
@duke7553 doesn't this slow down folder loading? it's calling the fulltrust process for every folder.
(I haven't tried though, the performance hit may be negligible)

**Comment by duke7553** [comment]
@gave92 Isn't this what we already do for loading thumbnails on files?

**Comment by gave92** [comment]
@duke7553 the difference is that thumbnails are loaded in `LoadExtendedItemProperties` while this calls the fulltrsut process during `AddFolder`

**Comment by duke7553** [comment]
@gave92 Hmm... you're certainly correct about that.

Would it be appropriate to load the localized names on an ad-hoc basis through LoadExtendedItemProperties() ?

**Comment by gave92** [comment]
If it's moved to `LoadExtendedItemProperties` you don't even need the fulltrustprocess, but can just use the StorageFile `DisplayName`.
Downside is that you briefly see the untranslated name

**Comment by duke7553** [comment]
@Jaiganeshkumaran Can you make the changes based on what @gave92 suggested?

**Comment by gave92** [comment]
@Jaiganeshkumaran do you have any update on this? We are getting close to releasing V1 and it would be nice if this was included :)

**Comment by d2dyno1** [comment]
@Jaiganeshkumaran

**Comment by gave92** [comment]
@duke7553 moving loading the localized name to LoadExtendedItemProperties unfortunately means that folders may end up not sorted in alphabetical order ("**P**ictures" becomes "**I**mmagini" in italian e.g.). Not sure if it's less bad:
- to slow down loading a bit and get the name during AddFolder
- to reorder items during LoadExtendedItemProperties
- to have items not sorted by display name

**Comment by Jaiganeshkumaran** [comment]
@gave92 Maybe instead of adding directly to the main observable collection, we could add it to a temp list during enumeration, then LoadExtendedItemProperties and then put them in the main observable collection

**Comment by gave92** [comment]
@Jaiganeshkumaran that would delay showing the contents to the user a lot :(
Plus 99%+ of folders have a DisplayName identical to the non-localized name so we'd be slowing down most folders for nothing.

**Comment by Jaiganeshkumaran** [comment]
@gave92 Then what to do?

**Comment by gave92** [comment]
Good question :)

**Comment by Jaiganeshkumaran** [comment]
We could have a list of predefined folders with localized names like built-in folders and only load for them

**Comment by gave92** [comment]
Yeah that would work or we could cache the association between Name and DisplayName (#2655 could help with that)

**Pull request closed without merging**
