### PR TITLE
Codebase: Remove more unnecessary usings

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Removes unnecessary using directives until I make an action to do this

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hecksmosis** [comment]
The action for this is in progress

**Comment by 0x5bfa** [comment]
Can you split up with 'Git Changes' window? You can revert unstaged changes from there.

**Comment by hecksmosis** [comment]
Do you mean splitting the pr up?

**Comment by 0x5bfa** [comment]
Yes.

**Comment by hecksmosis** [comment]
Ok, will do

**Comment by yaira2** [comment]
@hecksmosis we don't really need to remove all the usings at once as, it's preferred (and less time consuming) to remove them once we're already editing a file as opposed to opening dedicated PRs.

**Comment by hecksmosis** [comment]
I'm closing this for now, will reopen by chunks

**Pull request closed without merging**
