### PR TITLE
Fix copy/move to zip file

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fix copy/move to zip file

**Details of Changes**
Add details of changes here.
- Fixes some file operations involving zip files, which broke in #8809
- Copy to zip, Move to zip, Create (and Rename) inside zips must use StorageFile operations

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by winston-de** [comment]
May not be caused by this PR, but I'm getting the "Drive unplugged NotAFolder" error whenever I try and open a zip file. Works fine in the latest preview version however.

**Comment by gave92** [comment]
Shouldn't affect listing zip contents, could you check on `main`?

**Comment by winston-de** [comment]
Yeah, same issue on main.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by gave92** [comment]
@winston-de can't reproduce the issue neither here nor main. It's something that has been reported by users though, if you have the time we could try to debug it sometime.

**Comment by winston-de** [comment]
Sorry haven't had much time, I'll try and debug it later tonight

**Comment by DiabeticAnna** [comment]
I can offer steps to reproduce, versions

- Firefox 99.0.1 (64-bit)
- Windows 11 21H2 build 22000.613
- Version: 2.1.24.0 
- OS Version: 10.0.22000.613

1. Download a ZIP file from any website. 
2. Select file from Firefox downloads drop down (Ctrl +J)

Error:
image

Clicking "Show in folder" and opening using Windows File Explorer Recreates the same error. Manually locating .zip file in Files recreates the same error. 

Debug Log: https://pastebin.com/Vfm37fF8

**Comment by yaichenbaum** [comment]
> May not be caused by this PR, but I'm getting the "Drive unplugged NotAFolder" error whenever I try and open a zip file. Works fine in the latest preview version however.

This is a known issue that needs to be fixed but it's not related to these changes.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
