### PR TITLE
Preview pane improvements 2

### LINKED ISSUE #3446: Preview pane should say no item selected when there's no selected item
Today preview pane says no details available / no preview available but when there's no selected item it should say "No item selected. Please select one to view it's details and preview"

### PR DESCRIPTION
**Pull request by winston-de**
### to-do
- [ ] Folder previews #3400 
- [x] Shortcut previews
- [x] Move preview pane code-behind to a view model
- [x] Show thumbnails when no preview control/extension exists
- [x] Fix issue where preview pane doesn't show in search results
- [x] Allow attempting to load as text file even if file has no extension
- [ ] Reduce text cutoff
- [ ] Automatically preview readmes when no file is selected (#3502)
- [ ] Add option to open preview pane by default
- [ ] Cache file property list from json file to reduce inefficiency 
- [ ] Improve code quality for adaptive pane
- [ ] Enable opening links from markdown and web preview
- [x] Try to fix and re-implement code previews, if not possible remove altogether
- [x] Attempt to add shadow for pane
- [x] Don't try and load hidden items
- [x] Show different message when no item is selected #3446 

Closes #3446

Thumbnail preview:

### CODE REVIEW

**Comment by d2dyno1** [comment]
Item tiles with names for folder preview would be perfect!

**Comment by winston-de** [comment]
I was able to get the shadow effect working, which was requested in the original PR.
Should I keep it?

image

**Comment by yaichenbaum** [comment]
@winston-de Can you try casting the shadow on the preview pane?

**Comment by winston-de** [comment]
@yair100 From the content pane, right?

**Comment by yair100** [comment]
> @yair100 From the content pane, right?

Right

**Comment by winston-de** [comment]
@yair100 
image

**Comment by winston-de** [comment]
Also, I'm trying to load the thumbnail for shortcut previews, but currently the function for sending the request to the full trust process is located in ItemViewModel. Would it be alright if I moved it to it's own helper class?

**Comment by yaichenbaum** [comment]
@winston-de I know it's not directly connected to the preview pane, but what if shadows were added to the navigation and status bar?

**Comment by winston-de** [comment]
Yes, though right now it doesn't work well at all if the preview pane also has a shadow because the elevations for the preview pane and content would be inconsistent. I'll work on using a drop shadow instead.

For now, here's what the shadows for the nav toolbar and status bar would look.
image

**Comment by yaichenbaum** [comment]
@winston-de Once the paddings/margins and margins are sorted out, I think would look pretty good.

**Comment by winston-de** [comment]
@yair100 I remember you saying something about changing the properties icon so it wasn't the same as the icon for the preview pane. I found one that I think would work, but it doesn't seem to be in the current sheet.

https://raw.githubusercontent.com/microsoft/fluentui-system-icons/master/assets/Wrench/SVG/ic_fluent_wrench_24_regular.svg

**Comment by yair100** [comment]
> @yair100 I remember you saying something about changing the properties icon so it wasn't the same as the icon for the preview pane. I found one that I think would work, but it doesn't seem to be in the current sheet.
> 
> https://raw.githubusercontent.com/microsoft/fluentui-system-icons/master/assets/Wrench/SVG/ic_fluent_wrench_24_regular.svg

That looks good.

**Comment by winston-de** [comment]
I think I'll have to update the fluent ui glyphs font currently in Files to use it though.

**Comment by yaichenbaum** [comment]
@winston-de That's probably out of scope for this PR, but it would be great if you could make that change.

**Comment by winston-de** [comment]
Alright, I redid the shadows with ```DropShadowPanel```s instead, because they work much better and require a lot less code. However, I'm not certain if the opacity, blur radius, and offset values are the best.

@yair100 Do you have any input?

image

**Comment by yaichenbaum** [comment]
@winston-de Can you try copying the values from the sidebar? By the way, you might want to merge the latest from `main` to see how the shadows will work with the recent changes.

**Comment by winston-de** [comment]
Here it is with the values from the sidebar shadow.

image

**Comment by yaichenbaum** [comment]
@winston-de That looks good, I am looking into using different colors there as well so that should help the shadow stand out a little more.

**Review by yair100 — APPROVED** [review]
Great work! LGTM

**Pull request merged**
