### PR TITLE
Fix: Fixed ArgumentException in PathNormalization.NormalizePath

### LINKED ISSUE #15499: Bug: PathNormalization.NormalizePath ArgumentException
### Description

**PathNormalization.NormalizePath (String path)**
System.ArgumentException: The path is empty. (Parameter 'path')

### Steps To Reproduce

Unknown

### Requirements

- Resolve crash

### Files Version

v3.4.4

### Windows Version

Windows 11

### Log File

```csharp
System.IO
Path.GetFullPath (String path)
Files.App.Helpers
PathNormalization.NormalizePath (String path)
Files.App.Utils
WSLDistroManager.TryGetDistro (String path, WslDistroItem& distro)
Files.App.Helpers
NavigationHelpers.GetSelectedTabInfoAsync (String currentPath)
Files.App.Helpers
NavigationHelpers.UpdateTabInfoAsync (TabBarItem tabItem, Object navigationArg)
Files.App.Helpers
NavigationHelpers.Control_ContentChanged (Object sender, TabBarItemParameter e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15499

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

- Untested

### CODE REVIEW

**Review by hishitetsu — COMMENTED** [review]
This would certainly prevent crashes, but I'm wondering what string would cause `LocalPath` to be empty in the first place.

**Comment by yaira2** [comment]
This needs an answer from someone with more knowledge than me 🙂

**Comment by hishitetsu** [comment]
I would really like to know what strings cause the crash, but I think it would be good to merge this for now and see what happens.

**Comment by hishitetsu** [comment]
It might be useful, but I am concerned about privacy to log the path as it is.

**Pull request merged**
