### PR TITLE
Feature: Added `ctrl + alt + c` shortcut to copy path with quotes

### PR DESCRIPTION
**Pull request by niklasb22**
**Resolved / Related Issues**
- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
Closes: #12545 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Select item and use `ctrl + alt + c` shortcut
   2. Confirm the path is copied to the clipboard with quotes

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by 0x5bfa — COMMENTED** [review]
LGTM in terms of codebasel except one thing.

> Are there any other steps that were used to validate these changes?
Please wwrite down.

**Comment by yaira2** [comment]
@niklasb22 thank you for your contribution. We were still reviewing the details on #12545 and deciding if we should move forward with the feature proposal. I think that at this point, it doesn't hurt to include this option, but can you try changing the modifier key from `ctrl + shift` to `alt`?

**Comment by yaira2** [comment]
It might also be worth creating a separate action for this so that both options are shown in the command palette.

**Comment by yaira2** [comment]
@niklasb22 we're ready to move forward with this feature. The changes look good but one thing I would suggest doing differently, instead of adding a modifier key, it might be best to create a separate action with a different shortcut.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
