### PR TITLE
Tentative fix for ftp crash

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- For #5556

**Details of Changes**
Add details of changes here.
- Added a null check to ftp, should help with #5556 but needs to be verified by the user

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 should we merge this and see if helps?

**Review by yaichenbaum — APPROVED** [review]

**Comment by gave92** [comment]
Yeah I meant to merge it and see if the use confirms that the issue is fixed with the next update. I'd just leave the issue open.

**Comment by yaichenbaum** [comment]
@gave92 it doesn't appear to have fixed the issue 🤔

**Comment by gave92** [comment]
For who? You can reproduce?

**Comment by yaichenbaum** [comment]
> For who? You can reproduce?

I tested on a Windows 10 device.

**Comment by gave92** [comment]
Could you send me the logs? 🤔

**Comment by yaichenbaum** [comment]
> Could you send me the logs? 🤔

The issue appears to be resolved.

**Pull request merged**
