### PR TITLE
Expand drag area spacing in details view columns

### LINKED ISSUE #8722: Expand drag area on item coloums
### What's the Problem?

Trying to change the width on item coloums really difficult as the drag area is very small

image

### Solution/Idea

Widen the drag area

### Alternatives

*

### Priorities

_No response_

### Files Version

_No response_

### Windows Version

_No response_

### Comments

_No response_

### PR DESCRIPTION
**Pull request by itsWindows11**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #8722

**Details of Changes**
Add details of changes here.
- Expanded drag spacing, dragging should be easier.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.
image
https://user-images.githubusercontent.com/81253203/163782248-7759e9a4-2056-43f5-977f-7d4c892af575.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Is there a way to do this without shrinking the fill area of the header?
image

**Comment by itsWindows11** [comment]
What do you mean by header area?

**Comment by yaichenbaum** [comment]
I'm talking about the hover background.

**Comment by itsWindows11** [comment]
Oh I understand now, yeah we could make the width bigger.

**Comment by itsWindows11** [comment]
@yair100 should look fine now, can you check?

**Comment by yaichenbaum** [comment]
@itsWindows11 the issue with the splitter adding space between the line and hover background of the column header is still there.
image

**Comment by itsWindows11** [comment]
The revert commits were accidental and so I had to redo everything.

**Review by yair100 — APPROVED** [review]

**Review by puppetsw — COMMENTED** [review]
lgtm

**Pull request merged**
