### PR TITLE
Added a right click context menu to the horizontal tab control

### PR DESCRIPTION
**Pull request by yair100**
image
Part of #260.

### CODE REVIEW

**Comment by d2dyno1** [comment]
Looks good 👍

**Review by gave92 — DISMISSED** [review]
This adds a new tab at the end of the tab row right?
Would be nice if it added the new tab right next to the clicked tab

**Comment by yaichenbaum** [comment]
> This adds a new tab at the end of the tab row right?
> Would be nice if it added the new tab right next to the clicked tab

That would be a nice enhancement, do you have any ideas how we can find out which tab was right clicked on?

**Comment by gave92** [comment]
@yair100 The following should do the job
```cs
private async void NewTabMenuItem_Click(object sender, RoutedEventArgs e)
{
    var tabItem = ((FrameworkElement)sender).DataContext as TabItem;
    var index = MainPage.AppInstances.IndexOf(tabItem);
    await MainPage.AddNewTabByPathAsync(typeof(ModernShellPage), "NewTab".GetLocalized(), index + 1);
}
```
!EDIT!
This will easily trigger an (existing) bug that makes the app crash, to reproduce:
1) right click on the first tab and select "add new tab"
2) right click on the first tab and select "add new tab" (again)
3) navigate to a folder
4) crash with NullReferenceException in `SetSelectedTabInfoAsync`

**Comment by gave92** [comment]
New options work fine but I can still repro the bug described above with the "new tab" menu
ezgif com-gif-maker

**Comment by yaichenbaum** [comment]
> This will easily trigger an (existing) bug that makes the app crash, to reproduce:

@gave92 I removed the part that inserts the tab next to the one that was right clicked. This should solve the issue while we continue to look for a better solution.

**Review by gave92 — APPROVED** [review]

**Pull request merged**
