### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by meziantou**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@meziantou thank you for opening all these PRs. I just wanted to confirm that you're building the source and testing these changes?

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by meziantou** [comment]
Yes, I build the code and start the app. Maybe I do not test all the paths as I do not know the app correctly yet. I hope you'll add automated tests, so we can avoid regressions when changing the code.

**Comment by yaichenbaum** [comment]
> Yes, I build the code and start the app. Maybe I do not test all the paths as I do not know the app correctly yet. I hope you'll add automated tests, so we can avoid regressions when changing the code.

@meziantou we'd like to add automated tests at some point, but we've been focusing primarily on general stability and optimizations like these.

**Pull request merged**
