### PR TITLE
Fix: Fixed COMException in MainWindow.EnsureWindowIsInitialized

### PR DESCRIPTION
**Pull request by hishitetsu**
https://files-org.sentry.io/issues/5653153316/?project=4507376940351488

**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Review by 0x5bfa — COMMENTED** [review]
If frame isn't initialized correctly, shouldn't we close window and show simple message dialog box to notify why closed.

**Comment by hishitetsu** [comment]
The message of the exception is `The operation identifier is not valid. The WinUI Desktop Window object has already been closed.`
This error often occurs in other places, and we try to ignore all of them.
https://github.com/files-community/Files/pull/15600
https://github.com/files-community/Files/pull/15638
https://github.com/files-community/Files/pull/15864

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by 0x5bfa** [comment]
LGTM.

**Pull request merged**
