### PR TITLE
Update id-ID

### PR DESCRIPTION
**Pull request by jovanzers**
**Details of Changes**
- Update Indonesian translation

### CODE REVIEW

**Comment by jovanzers** [comment]
Maybe add Crowdin link in readme?

**Comment by yaichenbaum** [comment]
There is already a link in the ready

**Comment by jovanzers** [comment]
Ah sorry didn't see the badge label
I have a question, in the Approved translation many of them are incorrect, should I open an issue in all of them? Or is there a better way?

**Comment by yaichenbaum** [comment]
Is it not possible to edit approved translations?

**Comment by jovanzers** [comment]
Unfortunately that's not possible, I can only suggest a translation because my role in Crowdin is Contributor not Manager.

As an example:
image
I have suggested the correct translation, but the old translation is still selected as the approved translation.

**Comment by yaichenbaum** [comment]
Can you try again now?

**Comment by jovanzers** [comment]
Working on it, thank you!

**Pull request closed without merging**
