### PR TITLE
Do not show customize properties tab for Libraries, fix Library creation

### LINKED ISSUE #6909: Customization tab in library properties crashes files
### Description

The app crashes when trying to customise a library from the properties window

### Steps To Reproduce

1. right click a library
2. properties
3. customization

### Expected behavior

This should open a panel to change the library icon or add folders

### Files Version

2.0.34.0

### Windows Version

Windows 11 22000.318

### Relevant Assets

_No response_

### LINKED ISSUE #6973: Unable to create libraries
### Description

When try to create a library a pop out opens where I can enter the name (there is no text for the header part should probably add "enter the library name") nothing happen when clicking ok.

### Steps To Reproduce

_No response_

### Expected behavior

It should create and show the library in the sidebar

### Files Version

2.0.36.0

### Windows Version

10.0.19043.1348

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7556869/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7556870/debug_fulltrust.log)

### LINKED ISSUE #7003: Trying to pin a Network Device to Favorites crashes the app
### Description

I usually have my network devices pinned in the Favourites (NAS, NUC, Pi etc) and not folders from those devices.
Trying to drag the device from 

### Steps To Reproduce

1. Click on Network drives
2. Click on Network
3. Wait for devices to load (anyway this could be sped up somehow? :D )
4. Drag device from listed devices to Favorites

image

### Expected behavior

Device being added to Favorites-list

### Files Version

2.0.34.0

### Windows Version

Windows 11 Pro 21H2 22000.318

### Relevant Assets

[debug_fulltrust.log](https://github.com/files-community/Files/files/7574412/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7574413/debug.log)

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6909
- Closes #6973 
- Closes #7003

**Details of Changes**
Add details of changes here.
- Hidden customize properties tab for Libraries (#6909)
- Added ShellLibrary2 to fix a couple of bugs of Vanara implementation (#6973)
- Add a default folder (documents) when creating a new library, otherwise it won't be shown on Files sidebar (#6973)
- Added missing string resources for Create Library dialog (#6973)
- Check if the path is not null before adding an item to favorites (#7003)

Other:
- Do not use StorageFile in Fulltrust logger.. keeps throwing "Wrong thread" exceptions and does not log

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by winston-de** [comment]
Hmm, the library section in the sidebar isn't populating for me in this pr. Any idea why?

image

**Comment by gave92** [comment]
Full trust process crash I'd say (no sidebar icons either), you get a log file?

**Comment by winston-de** [comment]
Looks like the exception is occurring when initialization the ftp
From debug.log
```
2021-11-21 14:09:26.9042|WARN|BuildConnection|Could not initialize FTP connection!
	System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x60
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x36
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x16
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0x9
   at Files.Helpers.AppServiceConnectionHelper.<BuildConnection>d__8.MoveNext() + 0x13d
```

**Comment by gave92** [comment]
Are you sure this only happens with my PR? This looks like the issue some people were getting due to some versions of VS acting up.

**Comment by winston-de** [comment]
No, looks like this happens on main as well. However because of this I can't test your pr.
Also no, nothing gets outputted to the ftp log file at all; not even any of the info logs.

**Comment by gave92** [comment]
No problem, are you on VS 2019? I think what has been written in the docs: https://files.community/docs/contributing/building-from-source was to solve your same issue, @yair100 may remember more.

**Comment by winston-de** [comment]
No I was using 2019. However, it doesn't work on 2022 either.

**Comment by gave92** [comment]
Have you tried the magic trick if deleting the .nugget folder? :)

**Comment by BanCrash** [comment]
Sorry @gave92 for the delay, I'm being overbusy those weeks :/

I will try to expend some free time tomorrow for reviewing this.

**Comment by winston-de** [comment]
> Have you tried the magic trick of deleting the .nuget folder? :)

Sorry for the delay, the ftp still didn't work after deleting .nuget.

**Review by BanCrash — APPROVED** [review]
LGTM

**Pull request merged**
