### PR TITLE
Fix: Prevent Visual Studio from stopping when deleting an item

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
In debug, Visual sSudio stops at a Win32Exception necessary to know if the recycle bin can be used. This pr disables Visual Studio stops for this exception.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Review by QuaintMako — APPROVED** [review]
LGTM.

**Comment by yaira2** [comment]
1. How can I reproduce this issue?
2. Can you tell Visual Studio to ignore it locally? I'm not sure we should add this to the code.

**Comment by cinqmilleans** [comment]
Open Files in Debug mode, select a file, press Delete. Visual Studio stops at a Win32Exception. The code can only raise an exception regardless of the result. It is probably not possible to do otherwise.

It's fine for Visual Studio to break for a Win32Exception, but not this one. Developers shouldn't change the options, just definitely point out not to stop at this exception.

**Comment by yaira2** [comment]
I can't reproduce this
Fyi @d2dyno1

**Comment by QuaintMako** [comment]
I can reproduce it, do you have the right exceptions activated in Visual Studio?

**Comment by yaira2** [comment]
How can I check?

**Comment by QuaintMako** [comment]
> How can I check?

Visual Studio, Press Ctrl+Alt+E and check if the Win32Exceptions are checked.

In case: https://learn.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022#tell-the-debugger-to-break-when-an-exception-is-thrown

**Comment by yaira2** [comment]
It's checked but it's possible I ignored this specific error.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
