### PR TITLE
Feature: Added an option to disable auto scroll when navigating up

### LINKED ISSUE #14282: Feature: Allow disabling automatic scrolling to parent folder
### What feature or improvement do you think would benefit Files?

I go in and out of folders often, and the way that it scrolls to the folder I entered is mildly annoying when I want to go to different folders quickly. It also just looks jank while trying to load all the icons and then jumping to the folder

### Requirements

Add a setting in Files to disable this behavior

### Files Version

3.0.15.0

### Windows Version

10.0.22621.2861

### Comments

_No response_

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #14282...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open folder and navigate up the file tree
   2. Confirm the parent folders get selected and scrolled into view
   3. Open `settings > folders` and turn off the option to auto scroll
   4. Confirm the setting works as expected

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hishitetsu** [comment]
Is the expression "Scroll to parent folder" correct? I think it should be "originally opened folder", not "parent folder".

**Comment by yaira2** [comment]
> originally opened folder

It works if you navigate up multiple times even if the folder wasn't originally opened.

**Comment by hishitetsu** [comment]
I want to clarify the issue.
If you navigate up from `C:¥foo¥bar` to `C:¥foo`, Files selects `bar` and scrolls to it.
I think it is strange to call `bar` the parent folder.

**Comment by yaira2** [comment]
Good point, I’ll fix this in another PR.

**Pull request merged**
