### PR TITLE
Feature: Added SeerPro support

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related #8052... (this PR doesn't include switching between files)

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Install and open SeerPro
   2. Use space bar to toggle preview from Files

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hishitetsu** [comment]
Shouldn't there be an option to switch between QuickLook and Seer?

**Comment by yaira2** [comment]
I'm undecided, we'll definitely want an option once we add a built-in preview feature but until then, I'm not sure if there is a valid use case where a user has both apps installed at the same time.

**Comment by hishitetsu** [comment]
There may be situations where the user would like to select a preview tool if we support PowerToys Peek, but it certainly may not be necessary just yet.

**Review by hishitetsu — APPROVED** [review]
LGTM

**Review by hishitetsu — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
> There may be situations where the user would like to select a preview tool if we support PowerToys Peek, but it certainly may not be necessary just yet.


We can work around this by putting PowerToys Peek as the last if statement, this way, if another provider is detected we know it's preferred.

**Pull request merged**
