### PR TITLE
Refactor code to prepare for multi panes

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
The code was designed to use only one type of right panel, the preview pane. The nomenclature, settings, view models, events have not been designed to display others. You should have a generic pane that can display the preview or other content. 

**Details of Changes**
This pr refactors to make it very easy to display other content in the right panel. Only one panel can be displayed.
The code is modified a lot to change names and structure I tried, as always, to make the code cleaner than I found. 

Unfortunately, the settings names have been changed and the user will lose the previewpane settings. Apart from that, there is no change for users, only for developers. 

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by cinqmilleans** [comment]
I'll fix the merge tomorrow.

**Comment by cinqmilleans** [comment]
@yair100 This pr is no longer maintainable because the base code has changed too much. I will start over in a new branch. I therefore close this pr.

**Comment by yaichenbaum** [comment]
@cinqmilleans can you target the infrastructure branch?

**Comment by cinqmilleans** [comment]
@yair100 This is my project but this branch does not compile for me. I am looking for the cause of the problem.

**Comment by yaichenbaum** [comment]
Infrastructure doesn't build yet, it still needs some work until we get to that point.

**Pull request closed without merging**
