### PR TITLE
Create files and folder as admin

### LINKED ISSUE #5956: Can't create files on protected folders
### Description

Just wanted to note i am currently being unable to directly create files or folders on windows protected folders i.e (C:/, C:/Windows)

Is there any way to run 'Files' app with UAC prompt atm?

### Steps To Reproduce

1. Open Files app
2. Head to any windows folder i.e (C:/Windows)
3. Try to create any folder or file there (Right click, New)
4. Give it a name and press enter
5. The folder/file won't be created

### Expected behavior

Heading to the desired system protected folder and creating a new file expecting UAC prompt to pop-up, giving it a name and successfully create it

### Files Version

v1.5.0.0

### Windows Version

Windows 10 Education 21H1 19043.1165

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5956

**Details of Changes**
Add details of changes here.
- Added possibility to create files and folders as admin. This was the last file operation missing this ability.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by winston-de** [comment]
I can't seem to get the ftp to launch as admin. The launch as admin dialog in Files shows up, as does the uac prompt, but selecting allow for both doesn't seem to launch files as admin, as the status bar doesn't show that the ftp is elevated and a new file doesn't appear.

**Comment by yaichenbaum** [comment]
> I can't seem to get the ftp to launch as admin. The launch as admin dialog in Files shows up, as does the uac prompt, but selecting allow for both doesn't seem to launch files as admin, as the status bar doesn't show that the ftp is elevated and a new file doesn't appear.

I think you need to try in a directory like `C:\Windows\System32`.

**Review by yaichenbaum — APPROVED** [review]

**Review by winston-de — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 great work!

**Pull request merged**
