### PR TITLE
Added ability to horizontally scroll in new details view

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Itemize resolved / related issues by this PR.
- Related: #4643 

**Details of Changes**
Add details of changes here.
- Added ability to scroll horizontally in the new details view
- The minimum initial width of the view is 800 to prevent columns from getting too squished
- Added the ```Microsoft.Toolkit.Uwp.UI.Behaviors``` package to utilize the sticky header behavior

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by winston-de** [comment]
Alright, this should be ready now

**Comment by yaichenbaum** [comment]
@winston-de Can you test this in release mode?

**Comment by winston-de** [comment]
@yair100 Huh it doesn't work, thanks for pointing that out.

**Comment by winston-de** [comment]
It look like the issue was with the sticky headers behavior, it works fine when that's removed. Is it alright if the header isn't sticky, for the time being at least?

**Comment by yaichenbaum** [comment]
@winston-de We might need to add `Microsoft.Toolkit.Uwp.UI.Behaviors` to the `default.rd.xml` file.

**Comment by winston-de** [comment]
@yair100 Thanks, that seems to have fixed it

**Review by yair100 — APPROVED** [review]
Great work!

**Pull request merged**
