### PR TITLE
Fix: Fixed an issue where changing icons didn't work when admin access was required

### LINKED ISSUE #14893: Bug: Admin prompt doesn't show when trying to change shortcut icon
### Description

*

### Steps To Reproduce

1. Open Start menu programs folder
2. Open shortcut icon properties
3. Try change icon
4. See nothing happen when clicking OK
    - Windows File Explorer will ask for admin to change it

### Requirements

- Show admin required prompt before changing icon

### Files Version

3.2.6.0

### Windows Version

10.0.22621.3155

### Log File

[debug.log](https://github.com/files-community/Files/files/14475584/debug.log)

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #14893

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Comment by yaira2** [comment]
The script works when I run manually, but for some reason it's not working from start process.

**Review by 0x5bfa — COMMENTED** [review]
I think there's execution policy.

**Comment by yaira2** [comment]
> I think there's execution policy.

There is that, but I already have it bypassed on my device so there must be another reason.

**Comment by yaira2** [comment]
This is ready for review

**Pull request merged**
