### PR TITLE
Download update in background

### PR DESCRIPTION
**Pull request by puppetsw**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...

**Details of Changes**
Add details of changes here.
- Changed update service to download available update in the background before showing the Update button. When the update has finished downloading the button shows to install the update.
- MSIX bundle is downloaded to the application folder.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by puppetsw** [comment]
Would it be better to use Path.GetTempPath for the download location instead of the app folder?

**Comment by yaichenbaum** [comment]
@puppetsw does this work for the store version as well?

**Comment by puppetsw** [comment]
> @puppetsw does this work for the store version as well?

No, only the sideload version at the moment.

**Comment by yaichenbaum** [comment]
> MSIX bundle is downloaded to the application folder.

How did this work before?

**Comment by puppetsw** [comment]
> > MSIX bundle is downloaded to the application folder.
> 
> How did this work before?

The package manager downloaded it to whereever it does internally using the appinstaller. This PR takes that away and we handle it manually, so we can do it in the background.

**Comment by yaichenbaum** [comment]
What happens if the app is closed before the download finishes?

**Comment by puppetsw** [comment]
> What happens if the app is closed before the download finishes?

At the moment it is just terminated and starts again (not resume) at startup.

**Review by yaichenbaum — APPROVED** [review]

**Pull request merged**
