### PR TITLE
Feature: Added keyboard accelerator to open folder in dual pane

### LINKED ISSUE #10907: Feature: Shortcut to open selected folder in Secondary Pane
### What feature or improvement do you think would benefit Files?

Adding a shortcut to open a folder in the secondary pane would help make the secondary pane more useful, and accelerate its use without having to go into the context menu and selecting the option manually. Similar to the use of Ctrl + Enter to open a folder in a new tab.

### Requirements

- `ctrl` + `shift` + `enter` should open folder in new pane

### Files Version

2.4.8.0

### Windows Version

Version	10.0.22621 Build 22621

### Comments

_No response_

### PR DESCRIPTION
**Pull request by QuaintMako**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #10907 
- Related to #9895 

**What has been done**
- Made the process to open a folder in the dual pane into a method inside `NavigationHelpers`.
- Added the keyboard accelerator to both Grid View and Details View. (Not in Column View).
- Added a null check in `FileList_PreviewKeyDown` for each view.
- Did some minor cleaning and refactoring.
- Fixed the missing icon on the flyout menu to open in dual pane option. (Used the one from the Settings)

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots**

With icon:
IconFlyoutMenu

Without icon:
image

### CODE REVIEW

**Comment by QuaintMako** [comment]
Several points to be discussed :
- Should be add back an icon to the flyout menu? One was defined but not working. I think it looks better with one. 
  - If yes, is the icon currently added suited?
- Should the accelerator be avalaible for the Column View as well?

**Comment by hecksmosis** [comment]
I think Yair said to not add one

**Comment by QuaintMako** [comment]
> I think Yair said not to add one

Indeed, but since one was defined before, I decided to give it a shot nonetheless. I find it better looking, but it's a matter of taste. I'm adding a second picture without to show it before hand.

**Comment by yaira2** [comment]
If it's already there we might as well keep it.

**Comment by QuaintMako** [comment]
Welp, wrong commands and I managed to erase my work... Welp, will redo it when I'm not sleep deprived. My bad.

**Pull request closed without merging**
