### PR TITLE
Feature: Increased maximum volume label length to 128 characters for UDF images

### LINKED ISSUE #12901: Feature: Increase maximum read volume length to 128 characters (64 characters Unicode) for UDF File Systems
### What feature or improvement do you think would benefit Files?

The use case for this request is to see a more complete description of mostly optical media volume labels. Most optical media these days uses Blu-Ray disc to distribute 4K movies. Some movies have titles that exceed 32 bytes of data. Especially movies of a series. Take for instance, The Lord of the Rings movies.
"The Lord of the Rings - The Fellowship of the Ring" (50 characters)
"The Lord of the Rings - The Two Towers" (38 characters)
"The Lord of the Rings - Return of the King" (42 characters)
These titles are all truncated and look unprofessional in such display cases.

### Requirements

- This proposal will properly show volume labels that require more than 32 characters to fully and more accurately display a volumes label according to the contents stored therein.

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3155

### Comments

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12901

NB: added a new nuget dependency (DiscUtils.Udf) as winapi GetVolumeInformation only returns up to 32 chars. I won't raise a fuss if PR is refused due to this :)

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Mount attached ISOs
   2. Check UDF formatted ISO label is > 32 characters

**Screenshots (optional)**
Screenshot 2023-07-10 003322

[udf_long_name.zip](https://github.com/files-community/Files/files/12021489/udf_long_name.zip)

### CODE REVIEW

**Comment by yaira2** [comment]
> added a new nuget dependency (DiscUtils.Udf) as winapi GetVolumeInformation only returns up to 32 chars. I won't raise a fuss if PR is refused due to this :)

I think adding this functionality is worth taking another dependency, how large is the package?

**Comment by gave92** [comment]
Around 350KB, I've added the minimum needed for dealing with UDF.
image
The full library has more functionality, e.g create and extract ISO files and VHD disks.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
@gave92 is this working for you?

**Pull request merged**
