### PR TITLE
Fix: Fixed issue where thumbnails had the wrong aspect ratio

### LINKED ISSUE #6373: Bug: Folder thumbnails have a black background
### Description

The first time thumbnails are displayed for each folder, they are displayed with a black background.
image

### Steps To Reproduce
1. Clear thumbnail cache in Windows
2. Open Files and navigate to any directory with folders
3. Observe error
4. Refresh directory and observe the black background is gone

### Expected behavior
- Black background should never show

### Files Version

Version: 2.0.13.0

### Windows Version

Version: 10.0.22000.194

### LINKED ISSUE #9129: Bug: Thumbnails are displayed in the wrong aspect ratio
### Description

Issue #8128 is back. Thumbnails of images are cropped into squares.

Fixed in #5717, reintroduced (probably) in #5842.

### Steps To Reproduce

1. Navigate to a folder with images
2. Switch to any grid layout
3. See that image thumbnails are displayed as squares

### Expected behavior

- Thumbnails should display with the correct aspect ratio in the grid layouts

### Files Version

main (2.2.5)

### Windows Version

OS Version: 10.0.19043.1110

### PR DESCRIPTION
**Pull request by yair100**
**Resolved / Related Issues**
Fixed an issue where large thumbnails were not displaying with the correct aspect ratio.
- Closes #9129

Also fixes the issue where folder thumbnails had a black background
- Closes #6373

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by lukeblevins — APPROVED** [review]

**Comment by ferrariofilippo** [comment]
@yair100 bug is still there in properties windows

**Comment by yaira2** [comment]
@ferrariofilippo we need to do some work on converging the thumbnail code, if you want to help with this, I think a good place to start would be to create a xaml control that we can reuse across the different layouts.

The control should have a way to set the thumbnail source from a BitmapImage as well as a source for an icon overlay.

@QuaintMako was also looking into this so perhaps you can work together.

**Comment by ferrariofilippo** [comment]
> @QuaintMako was also looking into this so perhaps you can work together.

If she agrees there's no problem

**Comment by QuaintMako** [comment]
@ferrariofilippo you can look into it by yourself, I have been focused on the PRs and the refactoring of the Views lately. I haven't made much progress on the thumbnail issue for now. If you want to work together still, you can hit me on the Files' Discord ^^

**Pull request merged**
