### PR TITLE
Improved drag and drop with virtual storage items

### LINKED ISSUE #6941: I can't drag files to other apps
### Description

I can drag single file to other app.
But if I select 2 files and drag, the app will not getting files
This problem appeared 1 month ago.

### Steps To Reproduce

_No response_

### Expected behavior

The other app get the multiple files.

### Files Version

Version: 2.0.35.0 OS Version: 10.0.22499.1010

### Windows Version

Windows 11 Dev 1000.22499.1010.0

### Relevant Assets

_No response_

### LINKED ISSUE #8420: Not performing simple cut/copy/paste drag n' drop
### Description

Hello,
I am trying to use this great app but the copy/cut/paste/drag n' drop etc don't seem to work.
Also, it does not show the small images/tiles of .ico files
I have tested at least on 3 different computers, all windows 11 and the issue is there on all them since installation.
What could it be?
Thank you

### Steps To Reproduce

simple copy and paste not work
simple cut and paste not work
drag n' drop not work
not showing tiles/preview of .ico files

### Expected behavior

simple copy and paste 
simple cut and paste
drag n' drop 
Show preview .ico files

### Files Version

Versão: 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Windows 11 21H2 22000.527

### Relevant Assets/Logs

Untitled - 1

### PR DESCRIPTION
**Pull request by lukeblevins**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6941 
- Closes #8420 

**Details of Changes**
Add details of changes here.
- Create the concept of virtual storage item to help with dragging outside of Files app window to another app

## Special thanks to "High Caffeine Content" (@steventroughtonsmith) for making this and future PRs possible

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Review by yair100 — APPROVED** [review]

**Review by d2dyno1 — APPROVED** [review]

**Comment by lukeblevins** [comment]
@yair100 Is this ready to be merged?

**Comment by yair100** [comment]
> @yair100 Is this ready to be merged?

I think we should wait for Gave.

**Comment by gave92** [comment]
Sorry can't review it on depth right now but looks good to me (actually, this trick is genius, does it work for copy/paste?). I'd make a couple of minor changes but it can wait a different PRs 👍.

**Review by gave92 — APPROVED** [review]

**Comment by gave92** [comment]
Ouch I think this breaks dropping file into UWP apps (e.g Unigram), can someone double-check?

**Comment by lukeblevins** [comment]
@gave92 Yikes. We'll have to look into this and I will refund the sponsor over PayPal if needed.

**Comment by gave92** [comment]
At worst we could put a settings switch called like "use drag&drop compatible mode" to use the old behavior if a user needs to drop to uwp apps..

**Pull request merged**
