### PR TITLE
Code Quality: Use protocol launch for open and save file dialogs

### PR DESCRIPTION
**Pull request by gave92**
Use protocol launch for open and save file dialogs. Reason: on Windows Preview command line launch is currently broken. Files Launcher also uses protocol instead of command line.

@0x5bfa could you check if this works for you?

### CODE REVIEW

**Review by 0x5bfa — APPROVED** [review]
LGTM both for Save and Open, thank you!
I'm working on UI parts for now.

Actually I rolled my Windows back to the latest stable and alias is also working.

**Comment by gave92** [comment]
Sorry also pushed a small change so file open/save dialog always spins up a separate Files instance.

**Comment by 0x5bfa** [comment]
It seems that those dialogs are opened as Files app process, but they probably should be opened in the host window process, such as Notepad or Edge? Is that possible to open as a child process?

**Comment by gave92** [comment]
Maybe with CreateProcess instead of ShellExecute but then I can't use protocol launch.

**Comment by 0x5bfa** [comment]
It must be an issue with Windows and after having gone back from Insider to Stable, it just fixed. Maybe that version was malfunctioned. In that case, can we use alias launch as the primary way of launching and use protocol launch as another way of launching in case of failing.

I mean grouped in task bar. It currently opens in Files task bar icon.

**Comment by gave92** [comment]
Aah will try with https://stackoverflow.com/questions/13924264/grouping-separate-processes-in-the-windows-taskbar

**Comment by gave92** [comment]
Yayy sort of:
image

**Comment by 0x5bfa** [comment]
Wow, it's amazing!

I believe yes!

**Pull request merged**
