### PR TITLE
Feature: Removed number of open tabs from the app title

### LINKED ISSUE #16517: Feature: Don't show tab count on taskbar
### What feature or improvement do you think would benefit Files?

hi
**files items or tabs on windows taskbar (the taskbar that show start menu button , time & date , opening programs icons)**

Image

the image explain what i mean in this feature

### Requirements

remove the tabs amount
resize the folder/file icon
remove the word "files"
display the folder/file name + small icon only

### Files Version

3.7.11.0

### Windows Version

10.0.19045.5198

### Comments

_No response_

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #16517

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Review by hishitetsu — COMMENTED** [review]
image

Explorer has information on the number of tabs in the window title. Should we really delete this information?

Btw, this Explorer window title in Japanese is broken lol

**Comment by 0x5bfa** [comment]
We should remove "- Files" alternatively

**Comment by yaira2** [comment]
Notepad and Terminal don't display the number of tabs, but Microsoft Edge does. In any case, it's a minor change and we can bring it back if there is user demand.

**Comment by yaira2** [comment]
> We should remove "- Files" alternatively

@0x5bfa I think it's important for the app name to always be included in the title.

**Pull request merged**
