### PR TITLE
Can now reorder tabs.

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Review by lukeblevins — CHANGES_REQUESTED** [review]
The reordering would probably work, but to my knowledge it requires extra logic to handle dropping in a tab. Have you tested for this?

**Comment by yaichenbaum** [comment]
Dropping in a tab from another windows does not work, like you said it requires extra logic but reordering tab in the same window works fine with the pr.

**Comment by duke7553** [comment]
It is good practice to disable anything that requires extra work until it’s implemented. Thanks for the PR btw.

**Review by lukeblevins — COMMENTED** [review]
Doesn’t reordering work with drag and drop disabled?

**Comment by yaichenbaum** [comment]
No.

**Comment by lukeblevins** [comment]
@yair100 Thanks for your work. After testing this PR, I notice that the TabView doesn't yet support proper reordering. (Regardless of the CanReorderItems property) I'll submit a request this property to the appropriate repo.

**Comment by yaichenbaum** [comment]
Great, looking forward, by the way whats the status with the store app?

**Pull request closed without merging**
