### PR TITLE
Fixed an issue where trying to move a parent directory to a child directory would crash the app

### PR DESCRIPTION
**Pull request by Don-Vito**
Closes: https://github.com/files-community/Files/issues/1546
Closes: https://github.com/files-community/Files/issues/1545

Breaking change: do not proceed to Deletion during Move
if Copy failed (to prevent data loss)

### CODE REVIEW

**Comment by Don-Vito** [comment]
@gave92 - I was really hesitating if to put the check only there or rather in `FilesystemOperations.MoveAsync` so all the cases are covered.

WDYT?  If I move it to `FilesystemOperations` I guess I will need to return a null storage history.

**Comment by gave92** [comment]
I agree it's better to move it to FilesystemOperations.
This is an example taken from FilesystemOperations.RenameAsync() which looks similar to what you're doing here
```cs
if (Path.GetFileName(source.Path) == newName)
{
    errorCode?.Report(FilesystemErrorCode.ERROR_ALREADYEXIST);
    return null;
}```

**Comment by Don-Vito** [comment]
> example taken from FilesystemOperations.RenameAsync(

Thanks! Doing it right now :smile:

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@Don-Vito Great work! LGTM

**Pull request merged**
