### PR TITLE
Code Quality: Removed Vanara from SeerProProvider class

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Summary

As the title.

### Resolved / Related Issues

- https://github.com/files-community/Files/issues/15000

### Steps used to test these changes

1. Install SeerPro
2. Launch it from Start and check if it's now in system tray
3. Launch Files
4. Select an image file
5. Enter <kbd>Space</kbd>
6. See SeerPro preview launches and the image is shown

Messaging is doing well:
image

### CODE REVIEW

**Comment by yaira2** [comment]
@0x5bfa are the preview working properly for you?

image

**Comment by 0x5bfa** [comment]
Crap, sorry i put opening pr first.
I'm testing shell preview first rn.

**Comment by 0x5bfa** [comment]
Now ready for review.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
