### PR TITLE
Test PR, please ignore

### PR DESCRIPTION
**Pull request by heftymouse**
**Resolved / Related Issues**
- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...

**Validation**
How did you test these changes?
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
@crutkas @jaimecbernardo @ethanfangg @niels9001
this is awesome! 🤑🤑 We should use this too!

**Comment by 0x5bfa** [comment]
@heftymouse  Can you de-format and @yaira2 can send a comment?

**Comment by 0x5bfa** [comment]
Works pretty good.

**Comment by 0x5bfa** [comment]
CI not working…

**Comment by yaira2** [comment]
> CI not working…

@heftymouse is this something that needs to be handled in the formatting action?

**Comment by heftymouse** [comment]
Not that I'm aware...

**Comment by 0x5bfa** [comment]
I found a so regarding this issue.

https://stackoverflow.com/questions/71695198/github-actions-does-not-get-triggered-on-commits-or-prs-created-by-github-action

**Comment by heftymouse** [comment]
I see, we'll have to figure out how to authenticate with git using the app token then. Even though basic auth credentials are set in the URL, GitHub still recognises it as github-actions[bot] pushing it

**Comment by 0x5bfa** [comment]
We should make it to be able to call the CI from another workflow via workflow_call.

**Pull request closed without merging**
