### PR TITLE
About page redesign

### LINKED ISSUE #3372: Add a "copy" button to the About screen to quickly copy and environment/version information to make reporting easier
It would be great to have a "Copy" button, that would copy not only the current Files version, but also the OS version to make reporting issues easier.

### LINKED ISSUE #5388: Improve Button Hover Effect in About Section
**Is your feature request related to a problem?**
After exploring the app for a while after a fresh update, I found out that the About Section's button, which can be accessed through Settings > About (Submit Feedback, Release Notes, Documentation, etc), hover effects are alike with Windows 10 hover effect, however it would be great if there are some improvements on the hover effect.

Saw:

https://user-images.githubusercontent.com/69080584/125009047-fb88f700-e08d-11eb-8e89-93a29a4527fc.mp4

Expected:
Improve Button Hover Effect in About Section

**System Information**
- OS Version: Windows 10 21H1 OS Version 2009 (Build 19043.1081)
- App version: v1.5.62.0

### PR DESCRIPTION
**Pull request by yair100**
image

Closes #5388, closes #3372

### CODE REVIEW

**Comment by d2dyno1** [comment]
Third Party licenses section will get refresh too?

**Comment by yaichenbaum** [comment]
> Will Third Party Licenses section get a refresh too?

@d2dyno1 that's the plan.

**Comment by winston-de** [comment]
Can anyone else reproduce this weird entrance animation?

https://user-images.githubusercontent.com/59544401/125120192-fd12e900-e0a6-11eb-8e98-5b3ca6bb911f.mp4

Also, you may already be aware, but the animation when expanding/collapsing causes the "Third Party Licenses" text to overlap with the licenses.

https://user-images.githubusercontent.com/59544401/125120283-17e55d80-e0a7-11eb-8be8-4d98cbe207c1.mp4

**Comment by yaichenbaum** [comment]
> Can anyone else reproduce this weird entrance animation?
> 
>  2021-07-09-111130.mp4 
> Also, you may already be aware, but the animation when expanding/collapsing causes the "Third Party Licenses" text to overlap with the licenses.
> 
>  2021-07-09-111308.mp4

That isn't specific to this PR, but it's something to look into.

**Review by winston-de — APPROVED** [review]

**Comment by stanleyowen** [comment]
Hi @yair100, I think that 'Helpful Resources' or 'Helpful Links' may be more specific rather than 'Useful Links'. How about your opinion?

**Comment by yair100** [comment]
> Hi @yair100, I think that 'Helpful Resources' or 'Helpful Links' may be more specific rather than 'Useful Links'. How about your opinion?

@stanleyowen I think `Helpful links` sounds better, do you want to make this change?

**Comment by stanleyowen** [comment]
Ah okay `Helpful links` sounds better, however I think I can't do this changes as I am not get used to edit it on Visual Studio Code 😅.

**Pull request merged**
