### PR TITLE
Update Files.ja-JP.xlf

### PR DESCRIPTION
**Pull request by pklion**
I'm back! :)
Because I'm busy (even now), I couldn't translate new sentences.
If I have a time, I would be happy to translate.

**Resolved / Related Issues**
N/A

**Details of Changes**
- Fixed strange Japanese translation

**Validation**
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
N/A

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@pklion thank you for opening this PR, we're currently in the middle of making a number of changes to the resource files so we're going to hold off on merging this PR. Thank you for your patience and understanding.

**Comment by pklion** [comment]
OK. I understand.
Thank you for remembering me, and also please note that I'm not using Multilingual App Toolkit Extension so I could not build .resw file.

**Comment by yaichenbaum** [comment]
> OK. I understand.
> Thank you for remembering me, and also please note that I'm not using Multilingual App Toolkit Extension so I could not build .resw file.

We prefer generating the resw file oursevles so no worries 🙂

**Comment by onein528** [comment]
@pklion LGTM. Are you Japanese(I am Japanese :)? Thank you for updating my previously translated resource(afbc37ef498d710f0c181c72188ed0cf0bcdc1f0).

**Comment by 0x5bfa** [comment]
@yair100 Have you finished organizing translation resources?

This branch in  this PR has conflict. So do you want to close this?
**I can provide improved ja-JP translation resources and I will open another PR.**

**Comment by pklion** [comment]
Should I resolve conflicts if I could?
Though I don't know how to do...

**Review by d2dyno1 — DISMISSED** [review]

**Review by 0x5bfa — APPROVED** [review]

**Review by 0x5bfa — APPROVED** [review]
good work.
- Delete `state-qualifier="tm-suggestion"` property.
- Change the translated target from a verb to a noun.
- Update statements with an easy-to-understand Japanese translation.

**Comment by yair100** [comment]
@yair100 Have you finished organizing translation resources?

@onein528 I haven't finished them yet, but if the PR is ready, we can get this merged.

**Comment by onein528** [comment]
> @onein528 I haven't finished them yet, but if the PR is ready, we can get this merged.

Good. I think it’s ok to marge this.
And I provide new changes and improvements on other PR.

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
