### PR TITLE
Add global.json to force sdk 6.0.100

### LINKED ISSUE #7592: FilesFullTrust has stopped working
### Description

When I try to access the themes folder from Files, or when I try to go anywhere in the %appdata% folder FilesFulltrust stops working.
And when I try to copy and paste the path to the themes directory Files says that it doesn't exist.

### Steps To Reproduce

Open Files
Copy and paste: %appdata%\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\Themes
For it says it does not exist
#------------------------------------------
Open Files
Go to %appdata%\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\Themes
try to copy and paste, or delete 
It crashes for me

### Expected behavior

I expect not to get the FilesFullTrust error and that I can copy and paste in every directory I have permission to do so.

### Files Version

Version: 2.1.0.0 OS Version: 10.0.19043.1466

### Windows Version

Windows 10 21H1 19043.1466

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7861662/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7861663/debug.log)

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Expected to close #7592

**Details of Changes**
Add details of changes here.
- Add global.json to force sdk 6.0.100

This change should force the Store to build the app using sdk 6.0.100 like CI does. This apparently is mandatory or fulltrust process will crash (at least on windows 10).

NOTE: adding this file to the repo will cause building the app to fail unless the exact version of the sdk is installed. This is annoying for contributors, if possible I'd only use it when submitting a new version to the Store.

### CODE REVIEW

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 the store recompiles the app on their servers, will this help for that?

**Comment by gave92** [comment]
I'm hoping it does, I have no experience with the Store.

**Comment by yaichenbaum** [comment]
@gave92 I'll test it out and if it doesn't work, we can revert the change.

**Comment by yaichenbaum** [comment]
@gave92 it failed the pipeline.

**Comment by gave92** [comment]
Store pipeline is getting the wrong sdk version in "UseDotNet" step.

**Comment by gave92** [comment]
@yair100 what .yml configuration file is used for store release? You need to  do the same change that was done in #7422

**Comment by yaichenbaum** [comment]
@gave92 it's the release pipeline so it was already done 🤔

**Comment by gave92** [comment]
Gah found it

**Comment by yaichenbaum** [comment]
> Gah found it

Ha! It was changed but only for the sideload release.

**Pull request merged**
