### PR TITLE
Show Adaptive Layout as a separate layout in toolbar

### LINKED ISSUE #9131: Show Adaptive Layout as a separate layout in toolbar
### What's the Problem?

Switching between adaptive layout and "fixed" layout is not clear. Currently to re-enable adaptive layout you have to click on the active layout which is not really obvious. If adaptive layout is enabled, clicking on the active layout will activate the override but there's no indication of anything happening.

### Solution/Idea

Show Adaptive layout option as a separate layout button on the toolbar.
- It highlights if adaptive mode is active, regardless of the "guessed" layout
- Clicking on any layout will override the adaptive layout
- It gets disabled if "Enable individual preferences for folders" is disabled

image

### Alternatives

Show it as a toggle switch below the layouts (similar to the hidden items switch).

### Priorities

_No response_

### Files Version

main (2.2.5)

### Windows Version

OS Version: 10.0.19043.1110

### Comments

_No response_

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #9131

**Details of Changes**
Add details of changes here.
- Added separate button on toolbar for Adaptive layout mode
- Simplify layout-related code

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots (optional)**
Add screenshots here.
image

### CODE REVIEW

**Comment by gave92** [comment]
@yair100 is this something you'd include for v2.3?

**Comment by yair100** [comment]
> @yair100 is this something you'd include for v2.3?

I would wait until after the release to merge this.

**Comment by yaichenbaum** [comment]
It looks like switching to the column view prevents switching back to adaptive.

**Comment by gave92** [comment]
Yep, I have problems switching from columns to adaptive so I've disabled the button in that case. if you wish I can look more into it.

**Comment by yaichenbaum** [comment]
> Yep, I have problems switching from columns to adaptive so I've disabled the button in that case. if you wish I can look more into it.

It's up to you, personally I found it a bit confusing that I couldn't change the layout to adaptive.

**Comment by gave92** [comment]
Issue should be solved 💪. Uff layout mode code is way too complex xD

**Review by yair100 — APPROVED** [review]
LGTM

**Pull request merged**
