### PR TITLE
Fix: Fixed issue where directly opening library would invoke explorer.exe

### PR DESCRIPTION
**Pull request by SakuraKade**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...

Fixes issue #14302

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app.
   2. Navigate to `~\AppData\Roaming\Microsoft\Windows\Libraries`.
   3. Open any of the `.library-ms` files.

### CODE REVIEW

**Comment by SakuraKade** [comment]
I have no idea how to rebase anymore, So I just squashed the commits.

**Comment by SakuraKade** [comment]
Still working on the git tree and will re-open when ready

**Comment by SakuraKade** [comment]
Done, made it a single commit.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
