### PR TITLE
feat: Uri activation with path

### PR DESCRIPTION
**Pull request by FelixZacher**
allows to activate the app via uri and specify a path.

```
files-uwp:///C:/windows
```

1. The drive letter must be uppercase
2. forward slashes `/` must be used.

### CODE REVIEW

**Comment by tsvietOK** [comment]
@lampenlampen Seems like your patch get function "Open in new windows" broken. Please, check it.

**Comment by yaichenbaum** [comment]
Don't we already support it using `files`?

**Comment by FelixZacher** [comment]
@tsvietOK Will have a look. Thanks 👍
@yair100 We only support the commandline with `files.exe -Directory ""` and to start the app with the uri `files-uwp:`. This adds support to open the app in a folder via uri `files-uwp:///C:/users`.

This is useful for other uwp apps, because they can then start files with `Launcher.LaunchUriAsync()`, because starting another process is prohibited by default.

**Comment by lampenlampen** [comment]
Okay now i learned, we already support this 🤣.

**Pull request closed without merging**
