### PR TITLE
Inconsistent naming of duplicate file/folder

### LINKED ISSUE #1352: Auto-renaming items with numbers in the name has weird results
**Auto-renaming after copying of duplicate file is not consistent across different folder names.**
Copying a file with the same name as an existing file doesn't rename the new file correctly.

**To Reproduce**
**Scenario 1:**
1. Create new folder called "abc.123.2020-HD"
2. Copy the newly created folder "abc.123.2020-HD"
3. Paste it in the same directory as the source file.
4. Check the name of the newly renamed/copied/duplicate file.

**Scenario 2:**
1. Create new folder called "abc.123.Year(2020)-HD"
2. Copy the newly created folder "abc.123.Year(2020)-HD"
3. Paste it in the same directory as the source file.
4. Check the name of the newly renamed/copied/duplicate file.

**Expected behavior**
**Scenario 1:**
The expected file name of the duplicate file should have been appended by "(2)" at the very end of the file name.
**Scenario 2:**
The expected file name of the duplicate file should have been appended by "(2)" at the very end of the file name instead of incrementing the (2020) value to (2021).

**Screenshots**
 **Scenario 1:**
image

 **Scenario 2:**
image

**Desktop:**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.11.0]

### PR DESCRIPTION
**Pull request by Raithlin**
…erent folder names

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #1352

**Details of Changes**
Add details of changes here.
- Added end of line check ($) to the regex filter when searching for a duplicate (n) at the end of the file or folder name. Duplicate files or folders will only have (n) at the end of the name, and not in the middle as the issue highlighted. This fix resolves that issue.

**Validation**
How did you test these changes?
- [x]  Ran tests through Regex Tester. Given that the only change is a regex match filter, no other changes were made.
- [ ] Built and ran the app (I was unable to build the app as received directly from GitHub, so couldn't do this)

### CODE REVIEW

**Comment by gave92** [comment]
Hi, thanks for this contribution. Unfortunately I'm not able to reproduce the linked issue. For me duplicating a folder named "something" simply results in a folder "something - Copy" being created. Is it different for you? Are you able to reproduce the issue (without this change)?

**Comment by gave92** [comment]
Hi, unfortunately this would not fix the linked issue. The function GenerateUniquePath() is not called in that scenario. The new name is actually selected by the system.

**Comment by Raithlin** [comment]
Yes, I figured this out after I was able to build and test. The issue remains (I can replicate the issue) and I am trying to figure out where the renaming actually happens.

**Comment by gave92** [comment]
> I can replicate the issue

Funny I can't (also on main), when duplicating a folder the new name simply has "- Copy" appended at the end.
Are you trying in a local or network folder?
If you wish we can talk on discord, I'll point you where the renaming happens.

**Comment by Raithlin** [comment]
Perfect. I'll find you on Discord.

**Review by Jeremias1229 — APPROVED** [review]

**Pull request closed without merging**
