### PR TITLE
Rotate multiple images

### PR DESCRIPTION
**Pull request by puppetsw**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes ...

**Details of Changes**
Add details of changes here.
- Added ability to select multiple images and rotate left/right.
- Added ability to select multiple images and set as desktop background (create slideshow) Currently only works on primary monitor.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Demo**
demo

### CODE REVIEW

**Comment by puppetsw** [comment]
@yair100 would it be good to change the "set as background" text on the toolbar to "set as slideshow" when multiple images are selected?

**Comment by yair100** [comment]
> @yair100 would it be good to change the "set as background" text on the toolbar to "set as slideshow" when multiple images are selected?

Either that or we can display a different button altogether.

**Comment by yaichenbaum** [comment]
@puppetsw is this ready for review?

**Comment by yaichenbaum** [comment]
What's the behavior if you have multiple file types selected in addition to the image?

**Comment by puppetsw** [comment]
> What's the behavior if you have multiple file types selected in addition to the image?

The button should remain hidden.

**Review by yair100 — APPROVED** [review]

**Pull request merged**
