### PR TITLE
feat: Prelaunch app content & properly redirect to pre-launched instance if available

### PR DESCRIPTION
**Pull request by lukeblevins**
**Resolved / Related Issues**
- Should help in many cases with #2568 -- since we now properly preload the initial app UI, rather than just an empty window
- Redirect properly to pre-launched AppInstance if available

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] ~~Tested the changes for accessibility~~

In a simulated prelaunch scenario, the app resumes from suspend almost instantly and displays the app UI with minimal/no splash screen shown.

**Please note:** The changes to Program.cs are tentative due to the high risk of regressions in functionality. ~~Additionally, an issue is present where trying to open more app instances after being redirected to the initial pre-launched instance won't work. Your feedback and suggestions here are very welcome.~~ **(Fixed)**

### CODE REVIEW

**Comment by duke7553** [comment]
Steps to simulate load from prelaunch state with VS:
0.) Clone this PR
1.) Debug > Other Debug targets > Debug UWA Prelaunch
2.) Wait for app to fully load into memory and appear in task manager under "background apps"
3.) "Detach All" from VS Debug menu
4.)  Launch "Files - Dev" from the Start menu, taskbar, or other shell surfaces (Take notice of drastically improved speed)

**Comment by yaichenbaum** [comment]
@duke7553 this seems to be failing in release mode.

**Comment by lukeblevins** [comment]
@yair100 Not sure why it would fail given I didn't modify the sln file. Can you test again and provide the debug output? Is the build failing or does it fail to deploy and run?

**Comment by yaichenbaum** [comment]
@duke7553 it builds fine but it crashes when running it.

**Comment by yair100** [comment]
> @yair100 Not sure why it would fail given I didn't modify the sln file. Can you test again and provide the debug output? Is the build failing or does it fail to deploy and run?

It appears to be working after clearing and rebuilding the solution.

**Comment by yaichenbaum** [comment]
@zhuxb711 we noticed you used to use pre launch in RX Explorer, did you run into any issues with support multiple instances?

**Comment by zhuxb711** [comment]
@yair100 RX-Explorer removed it because the startup accelerating is not obvious.

Prelaunch is called by Windows. And whether it calls it is unpredictable. On the user side, they might not be able to aware it.

Besides, I'm not sure when my app will be suspended during prelaunch. So I have to make everything executed sync until MainPage is loaded.

I know VS could simulate prelaunch. But if you could not check this function in published app then you just introduced an unpredictable bug and it might lead to crash for unknown reason (After all, there are lots of bugs in UWP framework)

**Comment by zhuxb711** [comment]
RX-Explorer removed this feature years ago. I'm not sure if this feat capable with multi-instance. RX might not support multi-instance at that time.

**Comment by yair100** [comment]
> @yair100 RX-Explorer removed it because the startup accelerating is not obvious.
> 
> Prelaunch is called by Windows. And whether it calls it is unpredictable. On the user side, they might not be able to aware it.
> 
> Besides, I'm not sure when my app will be suspended during prelaunch. So I have to make everything executed sync until MainPage is loaded.
> 
> I know VS could simulate prelaunch. But if you could not check this function in published app then you just introduced an unpredictable bug and it might lead to crash for unknown reason (After all, there are lots of bugs in UWP framework)

Hopefully there won't be any surprises after publishing this in the store, I guess we'll find out how this works in the long run.

**Review by yair100 — APPROVED** [review]
Great work! LGTM

**Pull request merged**
