### PR TITLE
Change TogglePlaybackAccelerator keyboard shortcut

### LINKED ISSUE #7705: Change ctrl + alt + p to something easier
### What's the Problem?

Hi I'm loving the program but I'm missing a key feature for me. When I'm moving through my sample library I would like to listen quickly to the audio. Right now I just move with the up and down keys and play by pressing CTRL + ALT + P, but that shortcut is just too hard. Thank you

Screenshot

### Solution/Idea

I would be great if we could change that shortcut to "space bar" for example or having an autoplay function.

### Alternatives

I've tried QuickLook but for some reason doesn't play files that are inside of Google Drive, if they are in the desktop for example it works fine, although the audio glitches a little bit sometimes and you have to replay the sample.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

_No response_

### Windows Version

_No response_

### Comments

_No response_

### PR DESCRIPTION
**Pull request by kbuno**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7705  

**Details of Changes**
Changed TogglePlaybackAccelerator shortcut to Ctrl+Space for ease of access as discussed in #7705

**Validation**
How did you test these changes?
- [X] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@kristoferbuno before we merge this, can you add your agreement to #7625?

**Comment by kbuno** [comment]
> @kristoferbuno before we merge this, can you add your agreement to #7625?

@yair100 added 😄

**Comment by d2dyno1** [comment]
Won't this conflict with QuickLook integration?

**Comment by yaichenbaum** [comment]
> Won't this conflict with QuickLook integration?

@d2dyno1 it depends on how the QuickLook shortcut was implemented but if done correctly, it should cause any issues.

**Comment by yaichenbaum** [comment]
@kristoferbuno I just tested the change and it seems that it only works when the preview pane is focused, can you add code behind to handle this like the rest of the shortcuts in the app?

**Comment by d2dyno1** [comment]
@kristoferbuno can you update on this?

**Pull request closed without merging**
