### PR TITLE
Downgrade dotnet SDK to 6.0.100

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fixes an issue causing the fulltrust process to crash on start

**Details of Changes**
Add details of changes here.
- Forces Azure to use SDK version 6.0.100

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by gave92** [comment]
@R3voA3 this should fix the issue you raised on Discord (empty sidebar & no drives). Not sure if you're able to verify by testing [the Azure build](https://dev.azure.com/filescommunity/db556b89-8bf0-4c03-8053-434c8f8714ff/_apis/build/builds/9669/artifacts?artifactName=drop&api-version=6.0&%24format=zip) (which you'd need to sign yourself), if not we can wait for @yair100 to create a signed version.

**Comment by R3voA3** [comment]
Seems to be working now. Thanks for the quick fix.

**Comment by yaichenbaum** [comment]
Doesn't the included framework package need to be updated to fix this?

**Review by yair100 — COMMENTED** [review]
LGTM

**Review by yair100 — APPROVED** [review]

**Pull request merged**
