### PR TITLE
Removed extra control from MainPage visual tree

### PR DESCRIPTION
**Pull request by yair100**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by d2dyno1** [comment]
Could you include details of changes?

**Comment by yaichenbaum** [comment]
> Could you include details of changes?

- Removed extra border control
- Cleaned up columns

**Review by d2dyno1 — DISMISSED** [review]
Will conflict with `infra_shpg` but it's fine since it'll be rewritten

**Comment by d2dyno1** [comment]
Can you resolve conflicts? @yair100

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
