### PR TITLE
Fixed a bug where enter key does not work to confirm delete action

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Also, can you make the delete button before the cancel button? I'm suggesting this because according to Windows User Interface Guidelines it is recommended to keep the primary button first.

**Comment by generalguy41** [comment]
Can you add Space as well? Does the same thing as Enter, just a different method.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran @generalguy41 Both of those can be done, can you open an issue for each of them?

**Comment by generalguy41** [comment]
@yair100 My original ticket #877 has the Space request. Should I split that further along with the arrow keys?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran @generalguy41 Don't worry about the tickets, I will push the changes soon.

**Review by lukeblevins — APPROVED** [review]
Looks good to me. Great work, everyone!

**Pull request merged**
