### PR TITLE
Rich command: NewTab + DuplicateTab

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
Here are 2 new commands. For other navigation controls, I'm going to need a context to get the current IMultitaskingControl.

There were 2 keyboard shortcuts for NewTab (Ctrl+T and Ctrl+Shift+K). The second has been deleted but can be put back if necessary.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by yaira2** [comment]
We should support both shortcuts.

**Comment by cinqmilleans** [comment]
Ok. I will implement the custom commands. This will allow to easily have several Hotkeys for the same action. I will update this pr after committing the custom commands. This pr is therefore pending.

**Comment by cinqmilleans** [comment]
There was no need for a second hotkey because I confused 2 commands. Ctrl+Shift+K is for DuplicateTab and not NewTab. Of course, the multiple hotkeys will have other uses. I updated this pr which can be reviewed.

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
