### PR TITLE
FTP!

### LINKED ISSUE #1342: FTP Support
Related #1059?

**Is your feature request related to a problem? Please describe.**
There's not great FTP support in Windows, it'd be great for File Explorer solution like this to just expose the ability to connect to a remote server and browse it like any other network storage.

**Describe the solution you'd like**
It'd be great to be able to have an FTP/remote section and add server/credentials to connect to a remote FTP server and browse/interact with it like a regular directory.

**Describe alternatives you've considered**
There's other clients out there, but would be nice to just have something integrated into shell and Files UWP seems like a great way to pave the future for that.

**Additional context**
Should just be another connection under network or something similar?

### PR DESCRIPTION
**Pull request by hez2010**
# Built-in FTP support
This PR aims to add support to FTP and FTPs.

Closes #1342

## TODO
- [x] Auto detect TLS/SSL settings - must
- [x] Enumeration and navigation - must
- [ ] Path bar integration - must
- [ ] Network credentials support
  - [ ] Ask credentials before connecting - must
  - [ ] Remember network credentials - better to have
  - [ ] Windows hello integration - not goal
- [ ] Filesystem operations:
  - [ ] Copy and paste (akas. download and upload) - must
  - [x] Delete and rename - must
  - [ ] Move and cut - better to have
- [ ] Properties integration: statistics, owner, hash (if server supports), and permissions - better to have
- [ ] Cache integration - better to have
- [ ] Background transfer even when files is closed - better to have
- [ ] Enumeration and file operations abstract layer for better maintainability - not goal
- [ ] SFTP - not goal

### CODE REVIEW

**Comment by d2dyno1** [comment]
Closes #1342
Closes #2407

**Comment by hez2010** [comment]
> Closes #1342
> Closes #2407

It only closes #1342, SFTP is a protocol over SSH and completely different from FTP.

**Comment by hez2010** [comment]
> How's progress going?

Just don't have too much time on it recently. I'm planning to implement remaining things next week.

**Comment by yaichenbaum** [comment]
@hez2010 Thanks for the update! If it's ready in the next couple of weeks, we should be able to include it in the next update.

**Comment by hez2010** [comment]
@yair100  Do you think I should close this PR for now? I may push some unfinished work, which will trigger unnecessary CI. 
I can reopen the PR once it's ready for review.

**Comment by yaichenbaum** [comment]
@hez2010 I don't think the pipeline runs on draft PRs.

**Comment by hez2010** [comment]
I want to split this PR into two PRs. One is to remove `IStorageItemWithPath` and use `IStorageItem` for all cases (contributes to #4180, so operations of a file itself (`Remove`, `Rename`, and `GetBasicProperties`) could be implemented by just `class XxxStorageItem : IStorageItem`), another one is to implement FTP after the previous one done.

**Comment by d2dyno1** [comment]
Looking forward to removal of `IStorageItemWithPath`!

**Comment by yaichenbaum** [comment]
@hez2010 Thanks for the update!

**Pull request closed without merging**
