### PR TITLE
Use named pipe instead of appservice

### PR DESCRIPTION
**Pull request by gave92**
@yair100, @winston-de if you've got time, could you test if this PR would fix the issues people are experiencing on newer Windows Insider builds? (E.g. only basic items in context menu, no shortcut files, etc..)

[Even if it works, it may still better to _not_ merge this and wait for Microsoft to fix the issue, unless this method proves beneficial for stability/speed]

### CODE REVIEW

**Comment by winston-de** [comment]
@gave92 It works!

**Comment by duke7553** [comment]
@gave92 Great minds think alike. I was just researching alternative IPC methods for the FullTrustProcess and was going to suggest the idea of a named pipe to you.

**Comment by gave92** [comment]
Thanks @duke7553, actually got the idea of using named pipes from Rx-Explorer 😅. Anyway I haven't tested this much yet but it looks to be working, let me know if you like the changes and if you think it'd make sense to merge this.

**Comment by gave92** [comment]
Has anyone experienced #3855? I'd be curious to know if this PR could fix it.

**Comment by winston-de** [comment]
> Has anyone experienced #3855? I'd be curious to know if this PR could fix it.

@gave92 yeah, I had that issue quite a bit. And it does seem to be fixed with this pr.

**Comment by yaichenbaum** [comment]
@gave92 This seems to not only solve the issue on insider builds, but it seems to also reduce the latency when right clicking on items.

**Review by yair100 — APPROVED** [review]

**Comment by duke7553** [comment]
@gave92 I'm noticing that changing the layout mode while thumbnails are being loaded results in a hang with output being flooded with a System.OperationCanceledException exception: 
image

I'm also trying to reproduce a bug where thumbnails load in blurry and the FullTrustProcess completely dies 😀

**Comment by gave92** [comment]
@duke7553 I'm pretty sure both issue existed before this PR :) The first is due to the use of cancellationtoken to stop LoadExtendedItemProperties, the second due to an AccessViolationException that sometimes is thrown in the FTP when loading thumbnails.

**Pull request merged**
