### PR TITLE
Fix CS1998 warnings (async method lacks 'await')

### PR DESCRIPTION
**Pull request by meziantou**

### CODE REVIEW

**Review by d2dyno1 — DISMISSED** [review]

**Comment by gave92** [comment]
Please merge #7078 before this one, it makes most of the edits here unneeded.

**Comment by yaichenbaum** [comment]
@meziantou can you resolve the merge conflicts?

**Comment by meziantou** [comment]
I've rebased the branch. There is not much too do with the recent changes. It should be easier to review :)

**Review by gave92 — APPROVED** [review]
Thanks a lot @meziantou

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
