### PR TITLE
Update Files.fr-FR.xlf

### PR DESCRIPTION
**Pull request by yair100**
Reverted changes from @scls19fr

### CODE REVIEW

**Comment by cinqmilleans** [comment]
@yair100 Why this pr? The translations were correct but this pr adds empty texts.

**Comment by yair100** [comment]
> @yair100 Why this pr? The translations were correct but this pr adds empty texts.

This is a necessary step as part of the move the MIT. Would you be interested in translating these strings?

**Comment by cinqmilleans** [comment]
Yes, but it will be the same translation.  It's the only suitable one.

**Comment by yaichenbaum** [comment]
> Yes, but it will be the same translation. It's the only suitable one.

I think that's fine @scls19fr, can you confirm?

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
