### PR TITLE
Preview pane improvements

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Move preview pane to main page
- Added properties listed in #4487
- Switched to rounded rectangle aka pill for resizer
- Added a brush for the preview pane bg so that it can be themed with an acrylic brush
- Implement minimum sizes
- cache properties list to improve performance
- Disable preview pane for very small window sizes (since it doesn't really work anyway)
- switch to toggle button for preview pane button in nav toolbar
- Added button to show preview for online only items in cloud drives to help prevent downloading them unintentionally
- Added progress ring while loading preview
- Updated design

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image

### CODE REVIEW

**Comment by R3voA3** [comment]
https://user-images.githubusercontent.com/17484252/122638384-0afecb00-d0f4-11eb-90ff-6d804045f2e8.mp4

There is this weird text animation when filling the preview pane which moves the text up a bit. I feel like this should get removed. What do you think?

**Comment by winston-de** [comment]
> There is this weird text animation when filling the preview pane which moves the text up a bit. I feel like this should get removed. What do you think?

That's the default animation when items are added to the ListView. I think it makes the transition smoother when opening the pane and when switching the selected item. However, I am open to removing it if others think it should be removed as well.

**Comment by mdtauk** [comment]
I know this is a weird and niche ask, but is there any value in tying the direction of the animated transition, to the relative position of the item being tapped?

So in list and details view, the next item you click would be either above or below the current item.
In the grid views the next item could be above, below, to the left or right.

**Comment by winston-de** [comment]
> I know this is a weird and niche ask, but is there any value in tying the direction of the animated transition, to the relative position of the item being tapped?
> 
> So in list and details view, the next item you click would be either above or below the current item.
> In the grid views the next item could be above, below, to the left or right.

It is possible, but why though?

**Comment by mdtauk** [comment]
> > I know this is a weird and niche ask, but is there any value in tying the direction of the animated transition, to the relative position of the item being tapped?
> > So in list and details view, the next item you click would be either above or below the current item.
> > In the grid views the next item could be above, below, to the left or right.
> 
> It is possible, but why though?

I just thought it would be neat if the preview pane transition felt linked and relative to the actions you are taking in the icon view :)

A little attention to detail that would feel nice.

**Comment by yaichenbaum** [comment]
> I know this is a weird and niche ask, but is there any value in tying the direction of the animated transition, to the relative position of the item being tapped?
> 
> So in list and details view, the next item you click would be either above or below the current item.
> In the grid views the next item could be above, below, to the left or right.

One idea would be to use a connected animation for the item icon.

**Comment by yaichenbaum** [comment]
@winston-de It looks a little off to have the round corners on the preview pane, can you try reverting that?

**Comment by mdtauk** [comment]
> > I know this is a weird and niche ask, but is there any value in tying the direction of the animated transition, to the relative position of the item being tapped?
> > So in list and details view, the next item you click would be either above or below the current item.
> > In the grid views the next item could be above, below, to the left or right.
> 
> One idea would be to use a connected animation for the item icon.

The transitions are in two different panes, so not sure if a connected animation makes sense, as you wouldn't want any text or icon moving from the list/grid view, over to the Preview/Details pane.

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@winston-de Can you resolve the merge conflicts?

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@winston-de Great work!

**Pull request merged**
