### PR TITLE
Fix: Fix possible null exception with renaming items

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
  https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2349352020u/overview

### CODE REVIEW

**Review by hishitetsu — COMMENTED** [review]
I believe NullReferenceException occurs if this `textBox` is null. Line 235 checks to see if `textBox` is null, but this code is executed in either case.

https://github.com/files-community/Files/blob/39d1744546e87b05abeeea3c2303cd41d04af34f/src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs#L253-L254

**Comment by yaira2** [comment]
Would you suggest wrapping that in an if statement?

**Comment by hishitetsu** [comment]
> Would you suggest wrapping that in an if statement?

That's would be good.

**Review by hishitetsu — APPROVED** [review]
LGTM

**Review by hishitetsu — APPROVED** [review]

**Pull request merged**
