### PR TITLE
Added the option to use middle click to scroll

### LINKED ISSUE #4495: Scroll with middle mouse click
**Describe the solution**
Clicking the middle mouse button should toggle scroll mode, like how it works in a web browser. This would make navigating large directories a bit easier, IMO.

### PR DESCRIPTION
**Pull request by d2dyno1**
**Resolved / Related Issues**
- Closes #4495

**Details of Changes**
- Added middle mouse click to scroll.

**Validation**
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@d2dyno1 Can this be added to the other layout modes?

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you change the mouse cursor when this feature is toggled? Additionally, is there a way to only toggle this when clicking in a blank area?

**Comment by d2dyno1** [comment]
> Can you try using the extension from the WCT (https://docs.microsoft.com/en-us/windows/communitytoolkit/extensions/FrameworkElementExtensions#cursor) instead?

I don't know if that's possible ([Link for reference](https://docs.microsoft.com/en-us/windows/communitytoolkit/extensions/scrollviewerextensions#changing-cursor-type))

**Comment by yaichenbaum** [comment]
@d2dyno1 is there a way to only toggle this when clicking in a blank area?

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
