### PR TITLE
Fix archive extraction

### LINKED ISSUE #9694: When using files to decompress zip, files crash.
### Description

When decompressing the zip using the decompression function that comes with files, the files will crash.

### Steps To Reproduce

_No response_

### Expected behavior

。

### Files Version

2.3.6.0

### Windows Version

Win11 22H2 Preview 25174.1010

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9300493/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9300494/debug_fulltrust.log)

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #9694

**Details of Changes**
Add details of changes here.
- Fixed crash when extracting archives (in Release Mode): relevant changes are to the [SevenZipSharp](https://github.com/gave92/SevenZipSharp) lib (in particular never share IInArchive instance between threads/Task.Run)
- Fixed crash when opening pw protected archives (1665013614u)
- Show archive details in preview pane even if Files is not set to open those formats

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by Chaython** [comment]
Can we replace the 7zip with pzip? Peazip supports more formats such as zstd

**Comment by gave92** [comment]
Not unless peazip offers some programmatic interface to browse/extract/edit archives, which does no appear to be the case. For zstd in particular I think we could switch to https://github.com/mcmilk/7-Zip-zstd.

**Comment by Manu99it** [comment]
> Not unless peazip offers some programmatic interface to browse/extract/edit archives, which does not appear to be the case. For zstd in particular I think we could switch to https://github.com/mcmilk/7-Zip-zstd.

Is there any plan to switch to 7-zip-zstd? With explorer I am used to tc4shell that could compress and extract zstd. It is so much faster compared to deflate or rar I can't live without it

**Pull request merged**
