### PR TITLE
📓 Updated HUN

### PR DESCRIPTION
**Pull request by KristofKekesi**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@KristofKekesi Can you solve the merge conflicts?

**Comment by KristofKekesi** [comment]
Yeah. I will mention you when it's done.

**Comment by KristofKekesi** [comment]
@yair100 done.

**Comment by yaichenbaum** [comment]
@KristofKekesi It looks like there are still some conflicts.

**Review by yair100 — APPROVED** [review]

**Pull request merged**
