### PR TITLE
Fix file size calculation

### PR DESCRIPTION
**Pull request by tsvietOK**
Before
image
After
image

### CODE REVIEW

**Comment by tsvietOK** [comment]
Is it better to move file size calculation to separate (static) class? And which class?

**Comment by yaichenbaum** [comment]
What is this supposed to fix? Comparing the file sizes to what I see in File Explorer it looks like it matches.

**Comment by tsvietOK** [comment]
@yair100 Check files larger then 3GB.

**Comment by yaichenbaum** [comment]
Does this work to detect the size of folders as well?

**Comment by tsvietOK** [comment]
@yair100 No, it is just file size algorithm modification.

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
:shipit:

**Pull request merged**
