### PR TITLE
[Experiment] Improve enumeration performance by delaying loading of extended item properties until after enumeration has completed

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Delay loading of extended item properties until after enumeration has completed

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

This seems to decrease the enumeration speed, but I'm not certain, would appreciate input on this.

### CODE REVIEW

**Comment by lukeblevins** [comment]
@winston-de @yair100 In my testing with this PR on my machine, I loaded System32 on both versions. Can confirm a 39% improvement in that initial load speed time calculated by the Stopwatch in ItemViewModel:
```
C:\Windows\System32:
713 ms - Winston's changes
1170 ms - Main branch
```

Perceived performance could be even better on different configurations, but it is difficult to quantify that.

**Review by lukeblevins — APPROVED** [review]
Approving this, but I'd like to see some more testing in other hardware configurations just so we know the impact of this PR vs the status quo.

**Comment by yaichenbaum** [comment]
@duke7553 it looks like this is still a draft, I'm curious what else Winston has in store for this PR...

**Comment by winston-de** [comment]
> @duke7553 it looks like this is still a draft, I'm curious what else Winston has in store for this PR...

Nothing more, sorry. I had it as a draft to get input as to whether it actually worked.

**Pull request merged**
