### PR TITLE
Fix: Fixed issue with navigating photos on Windows 10

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Partial revert #16102

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Comment by yaira2** [comment]
Fyi @hishitetsu, it turns out the NeighboringFilesQuery still works on Windows 10 so I added the conditional check I mentioned here https://github.com/files-community/Files/pull/16102#issuecomment-2318862961

**Comment by yaira2** [comment]
Should continue to function the way it did before #16102. The truth is #16102 was really only needed to fix a couple of niche cases, none of which were known to affect photos.

**Review by hishitetsu — APPROVED** [review]
> Should continue to function the way it did before https://github.com/files-community/Files/pull/16102. The truth is https://github.com/files-community/Files/pull/16102 was really only needed to fix a couple of niche cases, none of which were known to affect photos.

I'm wondering if that niche case applies to other photo apps, but there are no code issues, so it is fine to see how it goes.

**Comment by yaira2** [comment]
That's a fair point, we'll have to watch for feedback and adjust our approach if necessary.

**Pull request merged**
