### PR TITLE
Fixed crash when opening folders in GridView

### PR DESCRIPTION
**Pull request by yair100**
Fixed an issue where opening folder in the GridView layout would sometimes crash the app.

### CODE REVIEW

**Comment by tsvietOK** [comment]
@yair100 this PR not fixes first folder opening, it fixes crash on other folder opening(except first)

**Comment by tsvietOK** [comment]
By the way, dragndrop is not working(drop part).

**Comment by tsvietOK** [comment]
@yair100 dragndrop fixes: this [line](https://github.com/duke7553/files-uwp/blob/e27f216614778dc26c52a7a442ab844c3831ae7a/Files/Interacts/Interaction.cs#L937) replace "pastedItems" with "itemsToPaste". I think we can add this change to this PR.

**Comment by yaichenbaum** [comment]
@tsvietOK Have you tested that change and confirmed that it works?

**Comment by tsvietOK** [comment]
@yair100 Yes. Before this change if you try to move one folder onto another folder it copying it and after removing just copied folder. Now it works

**Comment by tsvietOK** [comment]
Logically, i don't think it is a good idea to delete just moved files:)

**Review by lukeblevins — APPROVED** [review]

**Pull request merged**
