### PR TITLE
Added an empty space where there are no columns in the DataGrid layout

### LINKED ISSUE #1040: Listview: add empty space where there is no column
**Before:** 
Anotación 2020-06-12 150354

**After:** 
Anotación 2020-06-12 1503542

### PR DESCRIPTION
**Pull request by gave92**
Fixes #1040

@XPoppyX could you verify whether this PR leads to the desired behaviour?

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 Can you check if the seperater between the headers on the content is missing for you?

**Comment by XPoppyX** [comment]
Selection:
select

------------
**file explorer:**

select2

**Comment by gave92** [comment]
Is it ok if the separator is like this?

image

**Comment by gave92** [comment]
@XPoppyX issue is only with drag-select right? just clicking should be ok

**Comment by XPoppyX** [comment]
yeah, and it's not an annoying issue, so it's okay I guess

**Comment by gave92** [comment]
@XPoppyX last commit should fix the issue you reported 👍

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Great work!

**Pull request merged**
