### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@andrii-bodnar why is this resetting strings back to English?

**Comment by andrii-bodnar** [comment]
@yair100 please click the [Upload translations](https://support.crowdin.com/github-integration/#uploading-translations-from-repo) button in the integration settings. Not all the translations that exist in the repo are in Crowdin for now. After that sync the integration.

By default, the translations stored on the repo are uploaded to Crowdin during the first synchronization only. Since the language mapping was not configured the first time, these translations were not uploaded.

**Comment by andrii-bodnar** [comment]
@yair100 also, I noticed that the Norwegian language has no translations. It should be changed to the Norwegian Bokmal in the Crowdin project target languages

**Comment by andrii-bodnar** [comment]
Or just set the language mapping for this language

**Comment by andrii-bodnar** [comment]
It is better to change the target language because the nb-NO code corresponds to the Norwegian Bokmal language. Then upload translations again and sync the integration.

**Comment by andrii-bodnar** [comment]
@yair100 the mapping should be like this:

```
no: nb-NO
```

**Comment by yaichenbaum** [comment]
Thank you

**Comment by yaichenbaum** [comment]
@andrii-bodnar that doesn't look right, it's creating a new file instead of using the existing one

**Comment by andrii-bodnar** [comment]
@yair100 please try to delete the l10n_main2 branch from the repo and try again to sync the integration

**Comment by andrii-bodnar** [comment]
@yair100 oh, I see, the new Norwegian file 🤔 
Let me check

**Comment by yaichenbaum** [comment]
That seems to have helped but it looks like strings are still being reset.

**Comment by andrii-bodnar** [comment]
@yair100 checking

**Comment by andrii-bodnar** [comment]
@yair100 UPD: now it looks good

**Comment by Andrulko** [comment]
The "_Export Approved Only_" was active in the project settings but none of the translations were approved. The option was temporarily disabled and now the PR contains translations 🎉

Do you want to keep that option enabled? If so, you can go a different route and validate all existing translations in a batch:

1) Open the integration settings: https://crowdin.com/project/files-app/apps/system/github
2) Click the arrow next to "_Sync Now_" and choose "_Upload Translations_", check the "_Approve added translations_" in appeared dialogue, then click "_Upload_" button.

All existing translations will be approved. You can activate "_Export approved only_" again.

Personally, I'd recommend to keep the option disabled, then you can review translations and when you find real proofreaders in each language, it will be safe to activate that option again 👌

**Comment by yaichenbaum** [comment]
@Andrulko it's setup correctly now, thank you for your help.

**Pull request closed without merging**
