### PR TITLE
Upgrade the FullTrustProcess to .NET 6 and CsWinRT

### PR DESCRIPTION
**Pull request by lukeblevins**
- In order to fix a weird Visual Studio bug with bundled dotnet 5 that prevents us from targeting ARM64, switch to .NET 6 
- Require it for building Files
- Drop support for regular ARM (likely needs Partner Center changes as well)
- Switch to System.Text.Json from Newtonsoft.Json
- Use CsWinRT

### CODE REVIEW

**Comment by lukeblevins** [comment]
@yair100 Any idea why the pipeline fails here?

**Comment by yaichenbaum** [comment]
@duke7553 It's failing because it's missing the build configurations.

**Comment by yaichenbaum** [comment]
@Panda-Sharp do you have any idea how we can fix the pipeline issue?

**Comment by Panda-Sharp** [comment]
> @Panda-Sharp do you have any idea how we can fix the pipeline issue?

@yair100 I wrote you on DIscord ;)

**Comment by duke7553** [comment]
Sorry to bother. Enjoy!

**Pull request closed without merging**
