### PR TITLE
Feature: Added thread selection option when creating archives

### LINKED ISSUE #15926: Feature: Don't use all CPU threads when compressing and decompressing
### What feature or improvement do you think would benefit Files?

7zip allow users to chose how many threads are used, while Files uses all of them. This makes compression/decompression faster but also lags out other programs especially when there playing audio.

### Requirements

- Set Files to leave 2 to 4 logical processor threads free
   - Alternate give user control on how many threads are used in settings

### Files Version

3.5.29.0

### Windows Version

10.0.22621.3737

### Comments

_No response_

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15926

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Comment by yaira2** [comment]
@Josh65-2201 before putting more work into this feature, can you confirm if it's working as expected?

**Comment by Josh65-2201** [comment]
It is

**Comment by yaira2** [comment]
Excellent! Do you have any feedback on the design?

**Comment by Josh65-2201** [comment]
Nope, look good and how I would expect it.

**Pull request merged**
