### PR TITLE
Code Quality: Fixed misconfigurations in Files.sln

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Resolved / Related Issues

*Reported internally, planned internally*

### Steps used to test these changes

1. Open Files.sln
2. No info bar pops up

**Well, I hate sln. I want slnx seriously 😭**

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@yaira2 this fixed the mid configuration message.

**Comment by yaira2** [comment]
It still an issue on my side

**Comment by 0x5bfa** [comment]
I think now fixed. I reopened VS many times but no warnings poped up.

**Comment by 0x5bfa** [comment]
Can you rerun the CI?

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
