### PR TITLE
Fix: Fixed crash that would occur when previewing PDFs in a RTL environment

### PR DESCRIPTION
**Pull request by Krytan**
image

In the picture you see the pdf priview in a RTL(Right To Left ) windows inviroment that's why the arrow start in the left side this is how people that speaks for example arabic, aramaic and hebrew see.
The bug was when viewing a PDF file using RTL and clicking in the left and right arrows the program would crash.

**Validation**
   A proper test would be using a windows environment with RightToLeft direction 
   You can simulate RTL  by going to pdfpreview.xaml And setting the FlowDirection to RightToLeft in FlipView and PipsPager 
   It should normally Crash if you don't use my fix version.

   1. Stand on a PDF file
   2. Have the preview panel open 
   3. Click the arrows to move between pages
   4. Should work fine in both LTR and RTL inviroments 

This should fix this bug #12037

### CODE REVIEW

**Comment by Krytan** [comment]
Useful information about the issue and changes: : The crash seems to be related to the default arrows in the flip-view not functioning properly when using a right-to-left FlowDirection. By default, the flowdirection is set to auto to support both left-to-right and right-to-left systems. However, the default arrows cannot be accessed or customized, so I created custom arrows that function similarly to the default arrows but with added functionality for right-to-left systems.

To test My changes, I changed the flowdirection from left-to-right (which works properly) to right-to-left (which was previously causing crashes), and it now works without crashing.

**Comment by Krytan** [comment]
Note:  1. arrows are shown when the preview tab is open by default, in a pdf file 
              before: they would only show if you hover the cursor over the pdf inside the preview tab
           
           2. Arrows layout is slight different from the default one.

Everything else should be the same

**Comment by yaira2** [comment]
@Krytan can you confirm if this is a platform issue with the flip view? I think a cleaner solution would be to hardcode the flow direction for the flip view so that it's left to right.

**Comment by Krytan** [comment]
oh aright yes that's correct since I could fix the issue by making a custom flipview rather than using the default flipview control buttons.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by Krytan** [comment]
@yaira2 Hello Yaira long time, can you assign me a new task I am looking to test my skills and continue contributing for files

**Comment by yaira2** [comment]
@Krytan thank you for reaching out, do you want to work on #8282?

**Comment by Krytan** [comment]
@yaira2 Sure,  it seems interesting thanks for quickly replying me back, I will try my best on the task

**Pull request merged**
