### PR TITLE
InfoBar to specify state of Open Files In Login functionality

### LINKED ISSUE #7679: Make it clear how to set Files to open at windows startup if consent dialog has been declined
### Description

I tried to set the app to start with Windows, but I accidently pressed on decline or something, now I can't set it to open with Windows.

### Steps To Reproduce

Set the app to start with windows, turning on the feature, press on no or decline on the next window. Now I can't turn it on again.

### Expected behavior

The turn on or off should be always available.

### Files Version

Version: 2.1.0.0

### Windows Version

Windows Version: 10.0.22000.434

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7875351/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7875352/debug_fulltrust.log)
Screenshot 2022-01-15 121709

### PR DESCRIPTION
**Pull request by esibruti**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7679 

**Details of Changes**
Add details of changes here.
- Added an infobar to make it clear to the user whether or not they can use the Open Files In Login feature and why if it is blocked.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image

image

### CODE REVIEW

**Comment by esibruti** [comment]
@gave92 Hi Gave, I have a problem here, I already asked Yair for help but he doesn't know either. We wanted that when there was no problem, that is, the option to turn on/off starting Files on Login was activated, the expandable content was hidden, that is, there was no blank space, if I made myself clear. I just needed you to help me with that part. But of course I'm open to suggestions to improve the code. You can help? Please?

**Comment by yaichenbaum** [comment]
@esibruti are you still working on this?

**Comment by esibruti** [comment]
@yair100 I've been doing a lot of work lately. I'll try to find free time to finish.

**Comment by yaichenbaum** [comment]
Closing due to inactivity

**Pull request closed without merging**
