### PR TITLE
Code Quality: Introduced IStorageSecurityService

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Summary

- Removal of Vanara reference (4 out of 37 files):
  - [x] SecurityViewModel
  - [x] SecurityAdvancedViewModel
  - [x] FileSecurityHelpers (to IStorageSecurityService)
  - [x] AccessControlPrincipal
- Removal of Utils namespace (9 out of 132 files):
  - [x] Utils/Storage/Security/*
  - [x] Utils/Storage/Helpers/FileSecurityHelpers

### Resolved / Related Issues

- https://github.com/files-community/Files/issues/14572
- https://github.com/files-community/Files/issues/15000

### Steps used to test these changes

1. Open Files
2. Go to security and advanced security pages
3. Confirm no crashes and problems occur
4. Add a new entry
5. Delete the entry

### CODE REVIEW

**Comment by Josh65-2201** [comment]
Compared to 3.5.4, I found
- Doesn't show principles/users name in both normal and advanced pages when opening properties.
- Doesn't save principles/users that are added
- Crashes when changing the owner (Before it shows a UAC for PowerShell admin)

**Comment by 0x5bfa** [comment]
Fixed most of them but one thing left; you’ll get a crash as soon as you add a new entry.
I’m not sure why this happens…

**Comment by 0x5bfa** [comment]
@Josh65-2201 I fixed everything. Would you mind check on your end as well?

**Comment by Josh65-2201** [comment]
I found that it won't save my other local user when added but does add system principles (Administrator and system) but makes them separate entries for the folder I'm applying to and one for subfolders/files. File explorer will include them as one entry.

**Comment by 0x5bfa** [comment]
You can't add an entry via their name such as '0x5bfa' or 'Josh'? It's weird though I tested.

I'm not sure I get what you meant but merging isn't available for now because it requires additional implementation (this lower layer's Windows API doesn't provide such rich features...)

If you can add/remove an entry and change owner without crash (and try them when you have insufficient permission such as 'Program Files/WindowsApps' and weird behavior, it's enough for this PR.

**Comment by Josh65-2201** [comment]
I'm using the security principles find now menu to try add a local account but it doesn't save it after clicking save and reopening the properties windows. This works on 3.5.6
image

As for the duplicate entries I found preview only add permission targeting the folder I have selected where now it's adding an entry for sub folders/files too. File Explorer set them all in the same permission but I'd say it fine for now as it better then 3.5.6.

**Comment by 0x5bfa** [comment]
1. I'll check again
2. Yeah I tried to make it look alike.

Before:
https://github.com/files-community/Files/blob/aa05b1a624be8a1b5df6875b8d14879db405c7f0/src/Files.App/Utils/Storage/Helpers/FileSecurityHelpers.cs#L194

After:
https://github.com/0x5bfa/Files/blob/b159fe4062f4843255c79a68eaf749fdb9c5b5ce/src/Files.App/Services/Storage/StorageSecurityService.cs#L224

Thank you for the testing, it've helped me a lot!

**Comment by yaira2** [comment]
@Josh65-2201 is your testing complete?

**Comment by 0x5bfa** [comment]
They found an issue with adding a new entry via user logon names. I’ll check later but everything else should be fine now.

**Comment by 0x5bfa** [comment]
All done.

**Comment by 0x5bfa** [comment]
@Josh65-2201 is it fine to review again?

**Review by Josh65-2201 — APPROVED** [review]
Working as expected

**Review by yaira2 — APPROVED** [review]

**Comment by 0x5bfa** [comment]
Thank you guys!

As a side note for the future reference, I maybe should've used 'Get(Set)SecurityInfo' but and 'Get(Set)NamedSeucurityInfo' doesn't require a handle of the specified file, which means this function would fail when access denied (not having READ_CONTROL), while CreateFileW to get a handle would fail before GetSecurityInfo.

**Review by hishitetsu — COMMENTED** [review]
The Access for the entry I added is "Read and execute" at first, but when I open Advanced permissions again, it is "Special". I think "Special" is correct from the beginning.

**Comment by 0x5bfa** [comment]
Is it something different from the stable build?

**Comment by Josh65-2201** [comment]
It always showing as read and execute for me in Preview and this branch

**Comment by 0x5bfa** [comment]
> The Access for the entry I added is "Read and execute" at first, but when I open Advanced permissions again, it is "Special". I think "Special" is correct from the beginning.

Please open that entry in File Explorer's dialog and expand permissions list for advanced ones to be shown and send a screenshot of it.

**Comment by hishitetsu** [comment]
I added Administrator. (Sorry for Japanese)
スクリーンショット 2024-07-12 105736

**Comment by 0x5bfa** [comment]
I mean this window. Make sure to click ‘Show advanced permissions’.

image

**Comment by hishitetsu** [comment]
Here it is.
image

**Comment by 0x5bfa** [comment]
😩 so this is basically I didn’t include SYNCHRONIZE access mask (?)
It very weird that Josh’s PC shows it Read & execute even after opening again.

**Comment by 0x5bfa** [comment]
@hishitetsu when you have time could you try to change this magic code

https://github.com/files-community/Files/blob/ad03647b90902695a0f97d5b699321b91ac01a8a/src/Files.App/Services/Storage/StorageSecurityService.cs#L225

to

```c#
0x20000000 | 0x80000000 /* GENERIC_EXECUTE and GENERIC_READ */
``` 

These generic access masks [covers SYNCHRONIZE access mask](https://learn.microsoft.com/en-us/windows/win32/secauthz/generic-access-rights).

**Comment by hishitetsu** [comment]
> @hishitetsu when you have time could you try to change this magic code

It works for me!
image
image

**Review by hishitetsu — APPROVED** [review]
LGTM

**Pull request merged**
