### PR TITLE
Update Files.de-DE.xlf

### PR DESCRIPTION
**Pull request by R3voA3**
Replaced _and_ with _&_ in the settings UI to gain some more space.

Does not solve #5215 but it's a start.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@R3voA3 Do you want to make this change to the en-us resource file as well?

**Comment by R3voA3** [comment]
Sure why not.

**Review by yair100 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@R3voA3 It looks like the app is failing to build, can you try fixing the build issue?

**Comment by BanCrash** [comment]
> No clue what's causing that and how to fix it. Perhaps it doesn't like & and it needs to be `&amp;` ?

@R3voA3 That's correct, I just downloaded your repo and changed `&` with `&amp;` and now it's compiling and working:

image
image

**Comment by R3voA3** [comment]
All ready @yair100

**Comment by yaichenbaum** [comment]
@R3voA3 can you update the string in the SettingsDialog xaml file?

**Comment by R3voA3** [comment]
@yair100 I am not sure what to change there since the content string does not point point to a translation. 

https://github.com/R3voA3/Files/blob/f1454d640bbf343c77f611deb8780f0ebc811d56/Files/Dialogs/SettingsDialog.xaml#L112

**Comment by yair100** [comment]
> @yair100 I am not sure what to change their since the content string to point to a translation.
> 
> https://github.com/R3voA3/Files/blob/f1454d640bbf343c77f611deb8780f0ebc811d56/Files/Dialogs/SettingsDialog.xaml#L112

You can just update the content to match the string.

**Review by yair100 — DISMISSED** [review]
LGTM

**Comment by R3voA3** [comment]
I translated all strings now and also fixed some inconsistencies. @yair100

**Comment by yaichenbaum** [comment]
@R3voA3 can you solve the merge conflicts?

**Review by yair100 — APPROVED** [review]

**Pull request merged**
