### PR TITLE
Fix: Fixed SourceGenerator build failure

### PR DESCRIPTION
**Pull request by Poker-sang**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related: https://github.com/files-community/Files/pull/11587#issuecomment-1566068664

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots**
image

### CODE REVIEW

**Comment by 0x5bfa** [comment]
We do not use Any CPU.

- Have to specify respective configurations in following file(Any CPU to x86, x64, arm64):

    https://github.com/files-community/Files/blob/main/Files.sln#L377-L406

- Have to make have exactly the same property as right one.

```xml
<LangVersion>latest</LangVersion>
<Nullable>enable</Nullable>
<IsTrimmable>true</IsTrimmable>
<Configurations>Debug;Release;Stable;Preview;Store</Configurations>
<Platforms>x86;x64;arm64</Platforms>
<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
```
SourceGenerator|Files.App.Storage
---|---
image|image

- May have to remove properties(OutputItemType="Analyzer" ReferenceOutputAssembly="false" )

    https://github.com/files-community/Files/blob/9fab8363a91ee3adb649b1a2a30353d1012ac88a/src/Files.App/Files.App.csproj#L116-L119

**Comment by Poker-sang** [comment]
@0x5bfa I am sorry. I understand what you mean, but these options must be specified. It is necessary for a SourceGenerator(analyzer) project. According to [MSDN](https://learn.microsoft.com/dotnet/csharp/roslyn-sdk/source-generators-overview).
```
OutputItemType="Analyzer" ReferenceOutputAssembly="false"

<IncludeBuildOutput>false</IncludeBuildOutput> 
<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules> 
```
And `IsTrimable` option is available only in .NET6 or greater can be used([MSDN](https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming)), this project is .netstandard2.0.

As for the AnyCPU config. I don't mean to use it. But if I use x86, x64 or arm64, it will build failed with `CSC: warning CS8034`

**Comment by 0x5bfa** [comment]
Thank you for telling those.

In any way, can you remove changes from PathBreadCrumb.xaml.cs? That is the issue now.

**Comment by Poker-sang** [comment]
> Thank you for telling those.
> 
> In any way, can you remove changes from PathBreadCrumb.xaml.cs? That is the issue now.

I can do it. But I'm concerned that someone has already developed based on the modified PathBreadCrumb.xaml.cs, which could lead to conflicts if I remove it.

**Comment by 0x5bfa** [comment]
No worries.

You can
- remove `[DependencyProperty<ToolbarViewModel>("ViewModel")] `
- add
    ```cs
    public ToolbarViewModel ViewModel
    {
    	get => (ToolbarViewModel)GetValue(ViewModelProperty);
    	set => SetValue(ViewModelProperty, value);
    }
    
    public static readonly DependencyProperty ViewModelProperty =
    	DependencyProperty.Register(nameof(ViewModel), typeof(ToolbarViewModel), typeof(PathBreadcrumb), new PropertyMetadata(null));
    ```

**Comment by Poker-sang** [comment]
> Unfortunately, adding Any CPU is not fundamental issue resolving.

hmm, actually we have already add AnyCPU config, this PR does not add a new config. And ms recommends to use AnyCPU in an analyzer project.

> No worries
Ok I will remove it. 

https://github.com/files-community/Files/blob/main/Files.sln#L377-L406

**Comment by 0x5bfa** [comment]
Oh really? Then keep it please sorry.

**Comment by Poker-sang** [comment]
> Can you link?

Sorry, I am not sure if it is mentioned in MSDN. But if you look at any repos, they all use AnyCPU. Such as [Roslyn](https://github.com/dotnet/roslyn) or [CommmunityToolkit](https://github.com/CommunityToolkit/dotnet).

**Comment by 0x5bfa** [comment]
@Poker-sang I am totally sorry for the inconvenience! Can you keep it(Revert the latest commit)?

**Comment by 0x5bfa** [comment]
@yaira2 '@Poker-sang' Find the way to make the compiler successful instead of discarding all changes.

**Comment by 0x5bfa** [comment]
@yaira2 '@Poker-sang' found the way to make the compiler successful instead of discarding all changes.

**Comment by Poker-sang** [comment]
No problem

**Comment by Poker-sang** [comment]
I only tested GitHub Action and it was successful, I don't know if Azure Pipeline will be fine, hopefully not.

**Review by 0x5bfa — APPROVED** [review]
LGTM. Thank you!🎉

**Comment by yaira2** [comment]
@Poker-sang thank you for the quick fix!

**Comment by 0x5bfa** [comment]
@yaira2

**Comment by Poker-sang** [comment]
> Oh really? Then keep it please sorry.
> 
> Can you link?

I think I know why it is configured with AnyCPU. As I said it is an analyzer project and will not be compiled into the application. The DLL it generates will only be loaded by the VS or dotnet compiler. So the target platform of the DLL depends on the CPU architecture of the computer where the code is compiled and not on the user's computer. For example, my computer should be configured with x64, while Azure server might use Arm64. for convenience and without specifying a particular configuration, AnyCPU is the best.

**Comment by 0x5bfa** [comment]
Oh thank you for the long response, and I finally fully understand the reason why. I will add that comment to the project file to mention that.

**Comment by 0x5bfa** [comment]
@Poker-sang Do you think we can change the attribution to following way?

```cs
option 1:
[DependencyProperty]
public ToolbarViewModel ViewModel { get; set; }

option 2 (this is optional):
[DependencyProperty(ViewModel_OnPropertyChanged())]
public ToolbarViewModel ViewModel { get; set; }

```

Inspiration:

image

**Comment by Poker-sang** [comment]
> Do you think we can change the attribution to following way?
Sure. It seems a way to have better readability. And we can even put comments on it.

**Comment by 0x5bfa** [comment]
It's nice to hear. Would you like to work on?

**Comment by Poker-sang** [comment]
Maybe we can open an issue first. And I will work on it in a few days. Are you in a hurry to need this?

**Comment by 0x5bfa** [comment]
Not at all, take your time please. Issued https://github.com/files-community/Files/issues/12889.

**Pull request merged**
