### PR TITLE
Added a hotkey for playing audio and video in the preview pane

### LINKED ISSUE #6287: Play back audio files in the preview pane via a hotkey
### What's the Problem?

Currently you are only able to play back audio in the preview pane by dragging your mouse to the play button.

### Solution/Idea

Having the ability to play audio files in the preview pane is really neat but what would make the experience even better is if you were able to playback the audio via a hotkey.

### Files Version

v2.0.13.0

### Windows Version

Windows 11 Pro (22000.194)

### Additional comment

_No response_

### PR DESCRIPTION
**Pull request by TomaszSteblik**
**Resolved / Related Issues**
- Closes #6287 

**Details of Changes**
- Added a keyboard accelerator in MediaPreview user control that plays media on "ctrl+alt+p " as suggested.

**Validation**
- [X] Built and ran the app.

### CODE REVIEW

**Comment by winston-de** [comment]
Would it be possible to change this to toggle instead of always playing? This way the media could be paused with the same hotkey used to play.

**Comment by TomaszSteblik** [comment]
Sure, it is done. I have put function for that in code-behind because I felt like it is more of a view responsibility. If you want me to change it to a command and put in a view-model just let me know.

**Review by winston-de — APPROVED** [review]
Lgtm

**Comment by yaichenbaum** [comment]
@TomaszSteblik can you add this new shortcut to the documentation site?c

**Pull request merged**
