### PR TITLE
Translation for zh-tw

### PR DESCRIPTION
**Pull request by timsu92**
**Resolved / Related Issues**

Itemize resolved / related issues by this PR.
- no anything related to zh-tw translation.
- here are some questions that I'm confused of while I was translating:
<details> <summary>expand me!</summary>

Translation item no. | Original String | My Question
:---------------------|:----------------|:---------------
150 | Empty recycle bin | Is "empty" a verb or an adj.?
188 | Empty recycle bin | Is "empty" a verb or an adj.?
209 | All in {0} | Not understand under what circumstances this is used.
222 | When launching an item from the jumplist | What is a "jumplist"?
318 | Drives | Does this mean all the hard drives, floppies, USB sticks, CD ROM...?
338,339,344,351,352,355,356,365,375,376,389 | [stuffs related to media properties] | I'm not familiar with these...
391~394 | Thumbnail Large/Small Path/Uri | I guess "large" and "small" mean the thumbnail's size right?
466 | Enable individual preferences for individual directories | Not understand under what circumstances this is used.

</details>

**Details of Changes**

Add details of changes here.
- Added translation for zh-tw
- Fixed improper file size unit in zh-tw

**Validation**

How did you test these changes?
- [ ] Built and ran the app ( I know how to build only, but now knowing how to run... )
- [ ] Tested the changes for accessibility ( same above... )

### CODE REVIEW

**Comment by XPoppyX** [comment]
> Is "empty" a verb or an adj.?

Yes, it is a verb (150 and 188)

> All in {0}: Not understand under what circumstances this is used.

When you select several items and Right click > Properties, In one part it says "**All in C: \ Users \ User Name \ Downloads**" for example, indicating that the items you selected are in that location.

> What is a "jumplist"?

A jump list means those folders you have opened recently. When you right-click a pinned item in the taskbar, it will show up.



> "Drives": Does this mean all the hard drives, floppies, USB sticks, CD ROM...?

Yes


> "Enable individual preferences for individual directories": Not understand under what circumstances this is used.

By enabling this option you will be able to order and use different view modes in each folder. If you disable it and put the view mode in "Details view" for example, all folders will be in "Details view". If you sort by name, all the folders will also be ordered like this

**Comment by XPoppyX** [comment]
@timsu92  It looks like your repository is outdated, and the strings don't match the current ones in `main`. Can you update it?

**Comment by timsu92** [comment]
@XPoppyX Umm... OK... It updates so fast...

**Comment by timsu92** [comment]
> A jump list means those folders you have opened recently...

What about no.220 "Always open a new instance"? Does that means to open in a new window?
According to no.285 "Always hides the vertical multitasking flyout...", it seems this means "tab". However, if this is true, it conflicts with "Open folder in a new tab"

**Comment by XPoppyX** [comment]
> What about no.220 "Always open a new instance"? Does that means to open in a new window?

Yes, it means open in a new window




> According to no.285 "Always hides the vertical multitasking flyout...", it seems this means "tab". However, if this is true, it conflicts with "Open folder in a new tab"

That's fine because it is for the option to show the tabs horizontally, that's why it says "Always hides the vertical multitasking flyout..."

**Comment by timsu92** [comment]
@XPoppyX OK! It's now translated. Thanks for your explanations!

**Comment by XPoppyX** [comment]
There are conflicts, can you fix it? or do you need help?

**Comment by timsu92** [comment]
OK, I'll do it as soon as I use a computer. Probably tomorrow. It's to hard to do it on a phone.

**Comment by timsu92** [comment]
I've solved the conflicts. However, CodeQL failed and I guess I can't really do something...

**Comment by XPoppyX** [comment]
Don't worry, you can ignore that

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@timsu92 Thank you!

**Pull request merged**
