### PR TITLE
Reduced font size for the drives widget space text

### LINKED ISSUE #2428: Avaibale space in storages are not completely shown in Spanish
As the words used in Spanish are longer than in English, the avaiable storage is not shown correctly
bug

### PR DESCRIPTION
**Pull request by yaichenbaum**
image
Fixes #2428

### CODE REVIEW

**Comment by gave92** [comment]
Should we also change the text wrapping to "NoWrap"?

**Comment by yaichenbaum** [comment]
> Should we also change the text wrapping to "NoWrap"? (just in case it's still too long)

It's fine if it wraps to the second line, and it won't get cut off anymore since I made the text smaller.

**Comment by gave92** [comment]
Ok so this won't happen anymore right? Even if the text wraps
image

**Review by gave92 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
> Ok so this won't happen anymore right? Even if the text wraps
> image

Correct.

**Comment by gave92** [comment]
Looks good [and no, I won't ask you to add "MaxLines="2"" just to be even more sure xD]

**Comment by yaichenbaum** [comment]
> Looks good [and no, I won't ask you to add "MaxLines="2"" just to be even more sure xD]

If it wraps more than 2 lines, then somethings wrong 😆,

**Review by gave92 — APPROVED** [review]

**Comment by gave92** [comment]
Aha you really didi it xD

**Pull request merged**
