### PR TITLE
Dispose Homepage on navigation

### PR DESCRIPTION
**Pull request by d2dyno1**
**Resolved / Related Issues**
- For #4180 

**Details of Changes**
YourHome.Dispose() is now called on navigation. It is possible to modify the code for any page to be disposed on navigation however that's not the case here. The problem with disposing every page but YourHome is that any other page is being reused and in YourHome's case, the widgets are created on navigation.
This PR fixes the issue where widgets weren't being disposed on navigaion and in Bundles case, it fixes a memory leak.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Review by lukeblevins — COMMENTED** [review]
This is a bit overkill, considering we can just call Dispose() in YourHome's OnNavigatingFrom override. The code looks good, but I'm not sure if we need the FrameExtensions at all unless there's another reason for it.

**Comment by d2dyno1** [comment]
@duke7553 we could call a function similar to `ICleanup.Clanup()` on other views.

**Comment by yaichenbaum** [comment]
@duke7553 Should we merge this?

**Comment by d2dyno1** [comment]
@yair100 could you review this one? It's fixing a memory leak :eyes:

**Review by cinqmilleans — CHANGES_REQUESTED** [review]
@yaichenbaum @d2dyno1 "using File.Extensions" is unused and useless in 2 files. "WidgetPage.xaml.cs" is better.

**Review by lukeblevins — APPROVED** [review]
Clever enough solution to call the Dispose() method, so I suppose

**Pull request merged**
