### PR TITLE
Fix: Fixed issue where the app would crash when displaying a large number of items

### LINKED ISSUE #14469: Bug: Files crashes when scrolling up and down in a folder with 800+ files
### Description

When scrolling up and down via keyboard in a folder with 800+ files Files sooner or later crashes

### Steps To Reproduce

1) Drop the files into an empty folder:

[create_test_files.bat.txt](https://github.com/files-community/Files/files/13943128/create_test_files.bat.txt)

2) Execute the file to create the number of files (and probably the file extensions play a role, too) needed for reproduction at my end.

3) Navigate into this folder again.

4) Click on the top most item.

5) Keep hitting the PageDown key. If the selection jumps to top again (another bug), click on the top item again, and keep pressing the PageDown key. After a few attempts Files crashes for me. Sometimes scrolling to the end and the start of the list via keyboard causes the crash. Sometimes using the scroll bar via mouse causes the crash.

This is of course not how I use Files, it is just the simplest way that I could find to reproduce a crash while scrolling through the list.

### Requirements

It should not crash. It seems like a race condition, perhaps in fetching the icons or other information.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

Since it crashed, and as far as I have seen, the log gets rewritten upon a new start, so I suspect it won't contain anything related to the crash.
[debug.log](https://github.com/files-community/Files/files/13943182/debug.log)

### LINKED ISSUE #14521: Bug: Crash with List View layout
### Description

The app crashes when I use the List View layout on the latest preview version 3.1.4.0, but only if the window is maximized. My folder contains more than 1000 files.

### Steps To Reproduce

1. open a folder with multiple files
2. change the layout to List
3. make sure app window is maximized 

### Requirements

when you maximize the window with list view on

### Files Version

3.1.4.0

### Windows Version

10.0.23619.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/14014711/debug.log)

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #14469
   Closes #14521

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Comment by Mantej-Singh** [comment]
Path is working fine on my PC
image

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
The downside of this change is that thumbnails take noticeably longer to load, is it possible to move up the thumbnail loading or will that contribute towards the crash?

**Comment by hishitetsu** [comment]
It appears that it can be done. I will look a little more and submit another PR.

**Pull request merged**
