### PR TITLE
Feature: Add pinned items to taskbar jumplist

### LINKED ISSUE #3311: Feature: Sync pinned favorites with taskbar jumplist
**Requirements**
- Sync pinned items in the right click menu on the taskbar with the favorites section on the sidebar
image

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #3311 
- Fixes issue with the home page cards were not updating when an item was pinned or unpinned in Explorer

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hecksmosis** [comment]
Fixed

**Comment by yaira2** [comment]
Unpinning an item in File Explorer updates the jumplist but it hides recent folders from the home page.

**Comment by hecksmosis** [comment]
> Unpinning an item in File Explorer updates the jumplist but it hides recent folders from the home page.

I can't reproduce this

**Comment by hecksmosis** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/55754091/224411927-0430e2c8-274c-4a40-957b-d1c0ee80191d.webm)
I still can't reproduce it

**Comment by yaira2** [comment]
Open a folder so that it gets added to recent folders.

**Comment by hecksmosis** [comment]
Oh sorry, misunderstood you, thought you talked about pinned folders. I'll try to fix it, but I probably won't be able to test it since I manually reset the pinned items a while ago

**Comment by hecksmosis** [comment]
This fix should work, can someone test it?

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
