### PR TITLE
added catalan translation. 2/3 completed

### PR DESCRIPTION
**Pull request by roguerrero1**
**Details of Changes**
I have translated into catalan some 2/3 of the program. I push it now just to check if everything's ok. It's a new language that didn't exist.
- Added files.ca.xlf

### CODE REVIEW

**Comment by gave92** [comment]
Looking great, thank you. I've just added the new language to the app's language list.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by yaichenbaum** [comment]
@roguerrero1 thank you!

**Comment by yaichenbaum** [comment]
@roguerrero1 can you take a look at #7625?

**Pull request merged**
