### PR TITLE
Added export/import options for settings

### LINKED ISSUE #1260: Add option to export\import settings
**Is your feature request related to a problem? Please describe.**
Not really. Many users use multiple Windows devices and it'd we really useful to sync settings with their Microsoft account.

**Describe the solution you'd like**
Use RoamingSettings for storing settings instead of LocalSettings (only app settings not pinned folders).

**Describe alternatives you've considered**
None.

### PR DESCRIPTION
**Pull request by d2dyno1**
**Resolved / Related Issues**
- Closes #1260

**Details of Changes**
- Adds options for exporting and importing settings file + fixes an issue where settings weren't respecting AppCenter.

**Known issues**
- Sidebar won't update shown sections after importing configuration. (Even though OnSettingChangedEvent is raised)

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by d2dyno1** [comment]
Translations are pending - need to know if the proposed design is good :+1:

**Comment by d2dyno1** [comment]
> Can you share a screenshot?

image

**Comment by yaichenbaum** [comment]
@d2dyno1 can you change it to say manage settings?

**Review by yair100 — CHANGES_REQUESTED** [review]

**Comment by d2dyno1** [comment]
@yair100 No issues!

image

**Review by yair100 — DISMISSED** [review]

**Comment by winston-de** [comment]
Just a thought: do settings (though not really settings) such as `LastSessionTabList` and `ContinueLastSessionOnStartUp` belong in settings.json? They aren't exposed to the user, and are just used internally.

**Comment by winston-de** [comment]
It looks like the app will crash on startup if the imported settings file is corrupted. So for example, if you replace a boolean in the settings file with a string, then import it, it will crash on startup. I think there should be some validation of the settings to avoid a crash.

**Comment by yaichenbaum** [comment]
@d2dyno1 can you make the changes Winston requested?

**Review by yair100 — APPROVED** [review]
Nice work!

**Comment by yaichenbaum** [comment]
> Sidebar won't update shown sections after importing configuration. (Even though OnSettingChangedEvent is raised)

@d2dyno1 I'm going to hold off merging this PR for now as I don't want to introduce new issues.

**Comment by d2dyno1** [comment]
> > Sidebar won't update shown sections after importing configuration. (Even though OnSettingChangedEvent is raised)
> 
> @d2dyno1 I'm going to hold off merging this PR for now as I don't want to introduce new issues.

Well, it's enough if user restarts the app. It works as expected + this PR fixes an issue with some UI areas not being updated after a setting has changed.

**Comment by yaichenbaum** [comment]
> Well, it's enough if user restarts the app. It works as expected + this PR fixes an issue with some UI areas not being updated after a setting has changed.

@d2dyno1 can you elaborate on what the issue with the sidebar actually is?

**Pull request merged**
