### PR TITLE
Fixed image thumbnails not appearing

### LINKED ISSUE #6130: Preview on PNG files not shown unless folder is opened in Explorer first
### Description

No previews appear on PNG file icons.
Screenshot 2021-09-15 153802

### Steps To Reproduce

1. Open any folder that contains png files
2. Set layout to Small/Medium/Large Icons

### Expected behavior

PNG file icons should have a preview

### Files Version

Version: 2.0.0.0 OS Version: 10.0.19043.1237

### Windows Version

Windows 10 Pro 21H1 19043.1237

### Relevant Assets

_No response_

### LINKED ISSUE #6512: Support for SageThumbs is broken
### Description

I use the app SageThumbs for showing thumbnails of PSD files in explorer and it kind of works with Files, but only with a few files. Some files do show the thumbnail as expected, some files doesn't show the thumbnail at the grid of files but do show the thumbnail in the "delete window" (see screenshot below), some other files doesn't show the thumbnail at all.
Using Microsoft Explorer works fine.

Captura de tela 2021-10-15 014157

### Steps To Reproduce

1. Install SageThumbs
2. Open a folder with PSD files inside

### Expected behavior

The thumbnails of PSD files are supposed to show, not an icon of a blank file.

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.194

### Relevant Assets

_No response_

### LINKED ISSUE #6966: Image file preview sometimes doesn't work
### Description

Image file preview sometimes doesn't work and only shows gray square.

### Steps To Reproduce

_No response_

### Expected behavior

Show image preview.

### Files Version

2.0.34.0

### Windows Version

10.0.22000.346

### Relevant Assets

Files:
obrazek

Windows File Explorer:
obrazek

### LINKED ISSUE #7770: Random images appearing when opening folders with lots of images
### Description

There are random images appearing when opening folders with lots of images, and any folder after that. For example if I open a folder with a cake's picture, and I open another folder, all the images' thumbnails of that folder become cakes.

### Steps To Reproduce

_No response_

### Expected behavior

Normally it should show the thumbnails of the actual images, but still show thumbnails of the previous folder's images.

### Files Version

Version: 2.1.2.0 OS Version: 10.0.22000.434

### Windows Version

Windows 11 21H2 22000.434

### Relevant Assets/Logs

I really don't think there is a log for this kind of problem.

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6512
- Closes #7770
- Closes #6130
- Closes #6966

Using "ThumbnailMode.DocumentsView" instead of "ThumbnailMode.SingleItem" appears to fix the missing thumbnails issue. Even #6512 (preview for .psd files) looks fixed. Could someone double-check?

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by gave92** [comment]
Lol, no exactly. All issues appear to be fixed because using DocumentsView causes an exception which causes the thumbnail to be loaded from fulltrustprocess (and that works)

**Comment by gave92** [comment]
It really does appear to be working. But I'd like a second PC opinion 😉.

**Comment by d2dyno1** [comment]
Maybe use fulltrust first and fallback to Windows.Storage?

**Comment by gave92** [comment]
That works as well (I've tried it in 56be3b4). IIRC, it was like that in the past but we moved away from it due to either perf issues or incorrect thumbnails being returned.

**Review by d2dyno1 — APPROVED** [review]

**Comment by naamiil** [comment]
Hello guys, can i open Thumbnails for a PDF files in ModernFiles?

**Pull request merged**
