### PR TITLE
Implemented drop to sidebar items

### LINKED ISSUE #1049: Possibility to drag and drop files into the sidebar
App version 0.9.2.0

### PR DESCRIPTION
**Pull request by soumyamahunt**
Fixes #1049.

3JyxBbHifS

### CODE REVIEW

**Comment by XPoppyX** [comment]
can you make them highlight when you drag over an item?
like this:
highlight

**Comment by soumyamahunt** [comment]
> can you make them highlight when you drag over an item?
> like this:
> highlight

I haven't been able to do that, would you like to have a crack at this??

**Comment by soumyamahunt** [comment]
@XPoppyX @yair100 reveal effect is now implemented:

3nIQIFjjps

**Comment by XPoppyX** [comment]
perfect 👍

**Review by yair100 — DISMISSED** [review]

**Comment by tsvietOK** [comment]
Why there is different actions for some folders?

**Comment by soumyamahunt** [comment]
> Why there is different actions for some folders?

I have implemented different actions based on Windows Explorer. In Windows Explorer, if the item you are dragging is in the same drive as the destination folder the operation will be to move the item otherwise the item will be copied.

**Review by tsvietOK — CHANGES_REQUESTED** [review]
Can't move or copy file. App crashing when drop file on side bar item.
```
2020-07-29 15:31:44.3932|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Interacts.Interaction.PasteItems(DataPackageView packageView, String destinationPath, DataPackageOperation acceptedOperation)
   at Files.Controls.SidebarControl.NavigationViewLocationItem_Drop(Object sender, DragEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```
image

**Comment by soumyamahunt** [comment]
> Can't move or copy file. App crashing when drop file on side bar item.
> 
> ```
> 2020-07-29 15:31:44.3932|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
>    at Files.Interacts.Interaction.PasteItems(DataPackageView packageView, String destinationPath, DataPackageOperation acceptedOperation)
>    at Files.Controls.SidebarControl.NavigationViewLocationItem_Drop(Object sender, DragEventArgs e)
>    at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
> ```
> 
> image

Can you share more detail on what you were trying to copy and to what path??

**Comment by tsvietOK** [comment]
@soumyamahunt 
image

**Comment by soumyamahunt** [comment]
@tsvietOK Is the error happens to you always?? I can't seem to reproduce it. Also the exception seems to be related to `StatusBarControl` and I haven't made any changes to it in this pr.

**Comment by tsvietOK** [comment]
I don't think it is a good idea to cancel user action (copy or move) if item already exists in folder.

**Comment by soumyamahunt** [comment]
> I don't think it is a good idea to cancel user action (copy or move) if item already exists in folder.

What do you think should be the default behaviour?? Currently if the item is already present in the folder, when dragging over the same folder the glyph would prompt the user it cannot be dropped. This is the implemented behaviour in every drag-drop scenario app wide.

**Comment by tsvietOK** [comment]
Oh, sorry, I misunderstood you. All ok.

**Comment by soumyamahunt** [comment]
> Oh, sorry, I misunderstood you. All ok.

What about the exception?? Are you still getting it??

**Comment by tsvietOK** [comment]
It is strange, but now i can't reproduce this issue anymore.

**Comment by soumyamahunt** [comment]
> It is strange, but now i can't reproduce this issue anymore.

I think it is related to `StatusBarControl`, not this pr.

**Review by tsvietOK — APPROVED** [review]

**Review by yair100 — APPROVED** [review]

**Pull request merged**
