### PR TITLE
Feature: Added support for Listary integration

### LINKED ISSUE #11765: Feature: API for third-party applications to get Files tab‘s path
### What feature or improvement do you think would benefit Files?

Is it possible for Files to add an API to get a tab's path? This will allow third-party applications to integrate with Files. For example, [Listary](https://www.listary.com/)'s [file application plugin](https://github.com/listary/Listary.FileAppPlugin) can get the folder opened in Files via this API, and then enable users to jump to the folder in file dialogs like this:

image

### Requirements

The API can be implemented as a URL protocol or a CLI argument.

For example, it can follow the [x-callback-url specification](https://x-callback-url.com/):
```
files-uwp://x-callback-url/get-tab-path?x-success=myapp://x-callback-url
```
Or just add a CLI argument:
```powershell
> files.exe --active-tab-path
C:\Windows
```

### Files Version

Version: 2.4.54.0

### Windows Version

Windows 11 22H2 22621.1413

### Comments

_No response_

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #11765...

**Validation**
How did you test these changes?
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Are we gonna create a new repo for this?

**Comment by yaira2** [comment]
@0x5bfa the plugin is available here https://github.com/files-community/Listary.FileAppPlugin.Files.

**Comment by yaira2** [comment]
The integration is working but I found that it breaks when you enable dual pane.

**Comment by gaoqiangks** [comment]
> @0x5bfa the plugin is available here https://github.com/files-community/Listary.FileAppPlugin.Files.

Will you say more words about how to use it?

**Comment by 0x5bfa** [comment]
We need a plugin to make Listary work.
It's on docs of Listary.

**Comment by hishitetsu** [comment]
> The integration is working but I found that it breaks when you enable dual pane.

In what way? The folder is opened in the active pane, so I don't see a problem.

**Comment by yaira2** [comment]
> > The integration is working but I found that it breaks when you enable dual pane.
> 
> In what way? The folder is opened in the active pane, so I don't see a problem.

I already resolved this, it ended up being an issue with the UI automation tool.

**Review by hishitetsu — APPROVED** [review]
Worked for me. LGTM

**Pull request merged**
