### PR TITLE
Bundled themes inside of the app

### PR DESCRIPTION
**Pull request by yair100**
The goal of this PR is to replace the themes addon by building them into the app.

### CODE REVIEW

**Comment by gave92** [comment]
Looks good. My only doubt is if it still makes sense to show the "open them folder" button given that install folder is protected so users can't add/remove/edit themes.

**Comment by yaichenbaum** [comment]
@gave92 would it be possible to provide an option to import themes or will the user still need access?

**Comment by gave92** [comment]
That folder is read only. If we wish users to have access we'd need to put themes in appdata folder like before (themes bundled in the app are ok inside InstalledLocation but app would need to fetch themes from appdata as well)

**Comment by yaichenbaum** [comment]
@gave92 made a couple changes, what do you think?

**Review by gave92 — APPROVED** [review]

**Comment by thierryntoh24** [comment]
I just redownloaded the app after a format and noticed this. Cool.
Thanks a ton, @yair100 . 🙂

**Pull request merged**
