### PR TITLE
Improved XAML on the Widgets

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by winston-de** [comment]
It looks like the storage sense button is being shown even when the drive isn't close to capacity.
image
Was this intended?

**Comment by yaichenbaum** [comment]
@winston-de That issue should be fixed.

**Review by winston-de — APPROVED** [review]
LGTM

**Comment by winston-de** [comment]
Wait I just noticed, the button hover visuals in dark mode are practically invisible.

**Comment by yaichenbaum** [comment]
@winston-de That's unrelated, can you open a separate issue?

**Pull request merged**
