### PR TITLE
Feature: Added "Run as admin" support for AHK files

### LINKED ISSUE #15250: Bug: Run as admin doesn't show on `.ahk` files
### Description

I was trying to open .ahk file as admin but couldn't because I couldn't see that option

### Steps To Reproduce

1. Make a .ahk file from new menu
2. Right the .ahk file

### Requirements

- Show run as admin option on .ahk files

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3447

### Log File

[debug.log](https://github.com/files-community/Files/files/15083371/debug.log)

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15250

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Right clicked "AHK" (auto hot key) file and confirmed the run as options were displayed

### CODE REVIEW

**Comment by hishitetsu** [comment]
Shouldn't we check to see if AutoHotKey is installed and only enable the option when it is?

**Comment by yaira2** [comment]
> Shouldn't we check to see if AutoHotKey is installed and only enable the option when it is?

We could do that but that's more compute power

**Review by hishitetsu — APPROVED** [review]
Fair enough. I was just asking to be sure. LGTM

**Comment by yaira2** [comment]
To be clear, it's very little compute power but I don't think it's really needed.

**Comment by hishitetsu** [comment]
Sorry, I didn't test it properly.
"Run as admin" works correctly, but "Run as another user" does not. AHK does not seem to support "Run as another user".

**Comment by yaira2** [comment]
Can you open an issue to track this? It should be a simple fix on my side.

**Comment by hishitetsu** [comment]
> Can you open an issue to track this? It should be a simple fix on my side.

https://github.com/files-community/Files/issues/15423

**Pull request merged**
