### PR TITLE
Added support for formatting drives

### LINKED ISSUE #359: Renaming of system drives.
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, every picked up local (not external) drive, including Network Drives, gets called "Local Disk". Allow us to rename them just like explorer.exe.

**Describe alternatives you've considered**
Also separate network shares. Also off topic, add support for Back and Forward buttons on mice.

### LINKED ISSUE #2235: Add support for Formatting and Editing Drives
Now, Files is very stable and has almost all the features. 
But, I have a problem to use it.
I can't format or edit drives. Please add support for editing drives.

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2235
Fixes #359?

This PR adds support for the "Format" context menu item and allows to change a drive name from Properties page

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 Using the built in format tool is fine for now but unless it gets an updated UI in the future, we will eventually want to build our own version that's fluent.

**Review by yaichenbaum — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Can you solve the merge conflicts?

**Review by yaichenbaum — APPROVED** [review]

**Comment by seohyun1108** [comment]
Is this feature coming in v.0.20?

**Comment by yaichenbaum** [comment]
@seohyun1108 Yes!

**Pull request merged**
