### PR TITLE
Chinese Traditional Translation

### PR DESCRIPTION
**Pull request by open3**
**Details of Changes**
Add details of changes here.
- Updated the translation file

**Validation**
How did you test these changes?
- [x] Built and ran the app

I'm sorry for I accidentally deleted the repository :(

### CODE REVIEW

**Comment by XPoppyX** [comment]
The file is a txt

**Comment by open3** [comment]
Fixed

**Comment by Rick-HM** [comment]
Are you sure? I see that the new file is a txt again
image

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
Thank you!

**Pull request merged**
