### PR TITLE
Added drill-in animation to homepage navigation

### PR DESCRIPTION
**Pull request by d2dyno1**
**Details of Changes**

This PR adds a drill-in animation transition to the home page.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots**

https://user-images.githubusercontent.com/53011783/112486518-3c2d6080-8d7c-11eb-8313-9bab3d9d865a.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@d2dyno1 This change hasn't been approved yet, can you share a screen recording of the animation?

**Comment by d2dyno1** [comment]
> @d2dyno1 This change hasn't been approved yet, can you share a screen recording of the animation?

The animation video is in the description. There's not much code but I wanted to show (additionally merge) how would this animation look like. @yair100

**Comment by yaichenbaum** [comment]
@d2dyno1 How does it look when first opening the app and when opening a new tab?

**Comment by d2dyno1** [comment]
https://user-images.githubusercontent.com/53011783/112493312-566a3d00-8d82-11eb-8127-74ff7c18b8c0.mp4


https://user-images.githubusercontent.com/53011783/112493342-5c601e00-8d82-11eb-9ce9-ca4a6a2ca775.mp4

**Comment by yaichenbaum** [comment]
@d2dyno1 The changes look good! In the future, make sure to open an issue first to prevent extra work in the event we don't merge your changes.

**Review by yair100 — APPROVED** [review]

**Pull request merged**
