### PR TITLE
MD5Hash Error (bug fix)

### PR DESCRIPTION
**Pull request by oleitao**
MD5Hash Error (bug fix) [[2914](https://github.com/files-community/Files/issues/2914)]

### CODE REVIEW

**Review by tsvietOK — CHANGES_REQUESTED** [review]
@oleitao This fix produces another bug. Open properties for some file, wait until md5 hash will be calculated
image
 go to Details tab and go back. 
image
There will be wrong md5 hash (always d41d8cd98f00b204e9800998ecf8427e, which is a hash of empty file).

**Comment by oleitao** [comment]
> @oleitao This fix produces another bug. Open properties for some file, wait until md5 hash will be calculated
> image
> go to Details tab and go back.
> image
> There will be wrong md5 hash (always d41d8cd98f00b204e9800998ecf8427e, which is a hash of empty file).

@tsvietOK After some tests the hash string is refreshed fine each time i switch between 'General' and 'Details' tabs. Please check if that bug is corrected.

**Comment by oleitao** [comment]
@tsvietOK  what about merge current issue [[4121] ](https://github.com/files-community/Files/pull/4121) with [[3722]](https://github.com/files-community/Files/issues/3722)?

**Comment by tsvietOK** [comment]
> @tsvietOK what about merge current issue [[4121] ](https://github.com/files-community/Files/pull/4121) with [[3722]](https://github.com/files-community/Files/issues/3722)?

@oleitao I think it is great idea!

**Comment by yaichenbaum** [comment]
@oleitao Can we get an update on this PR?

**Comment by oleitao** [comment]
> @oleitao Can we get an update on this PR?

@yair100 yes

**Comment by yaichenbaum** [comment]
@oleitao Great! Please reopen this PR whenever you're ready to continue working on it 🙂

**Pull request closed without merging**
