### PR TITLE
Fixed problem with migration to System.Text.Json

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related Issue #9881 
- Related Issue #9873 

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
Thank you for the quick fix!

**Comment by onein528** [comment]
@ferrariofilippo This related the following exception?:

image

**Comment by yaichenbaum** [comment]
Nope, that happens when the json file is empty

**Comment by onein528** [comment]
How can I fix?

**Comment by yaichenbaum** [comment]
It's expected to happen when debugging the app (the json file is replaced through the build pipeline).

**Comment by onein528** [comment]
Yeah, but I cannot open Files by occuring on app launching.

**Comment by yaichenbaum** [comment]
You should be able to ignore the exception and continue running.

**Pull request merged**
