### PR TITLE
Added shortcut to open terminal in current directory

### LINKED ISSUE #5607: Keyboard shortcut to open current/selected directory in terminal.
**Is your feature request related to a problem?**
Many programs such as VSCode have a global shortcut to open a terminal in the selected project or folder (typically <kbd>Ctrl</kbd> + <kbd>`</kbd>). While the native file explorer doesn't support this, I believe that it would be a convenient thing for Files to include.

**Describe the solution**
Add a keyboard shortcut to open the selected folder in the user's terminal of choice.

**Describe alternatives you've considered**
None.

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow the use of the keyboard to open the user's terminal. | Must |

**System Information**
 - OS Version: 11 22000.100
 - App version: 1.9.15.0

**Additional comment**
None

### PR DESCRIPTION
**Pull request by puppetsw**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5607

**Details of Changes**
Add details of changes here.
- Added shortcut key Ctrl+` to open default terminal in current working directory.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by d2dyno1** [comment]
@yair100 Right keyboard shortcut?

**Review by d2dyno1 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@d2dyno1 the correct shortcut would be <kbd>Ctrl</kbd> + <kbd>`</kbd>).

**Comment by yaichenbaum** [comment]
@puppetsw you can use the keyboard code instead virtual key, I believe we do this for a couple of other shortcuts throughout the app.

**Comment by puppetsw** [comment]
> @puppetsw you can use the keyboard code instead virtual key, I believe we do this for a couple of other shortcuts throughout the app.

@yair100 I might be missing something simple here, but I don't think this is possible to do through the KeyboardAccelerator method. The keycode for ` is 96, which is NumPad0 in the VirtualKey enum. Would we need to use the KeyDown event or something similar for this one?

**Comment by yair100** [comment]
> > @puppetsw you can use the keyboard code instead virtual key, I believe we do this for a couple of other shortcuts throughout the app.
> 
> @yair100 I might be missing something simple here, but I don't think this is possible to do through the KeyboardAccelerator method. The keycode for ` is 96, which is NumPad0 in the VirtualKey enum. Would we need to use the KeyDown event or something similar for this one?

It looks look it

**Comment by puppetsw** [comment]
Probably not the most elegant solution. But it seems to work. Maybe a shortcut manager or something would help and eliminate duplicate code between different pages.

**Comment by yaichenbaum** [comment]
@puppetsw can you try reverting the last commit and using this code instead? `case (true, true, false, true, (VirtualKey)192):`

**Comment by puppetsw** [comment]
> @puppetsw can you try reverting the last commit and using this code instead? `case (true, false, false, true, (VirtualKey)192):`

I think that would work, but the xaml doesn't seem to trigger the KeyAccelerator event with

```xml
<KeyboardAccelerator
    Key="{x:Bind AccentKey}"
    Invoked="KeyboardAccelerator_Invoked"
    IsEnabled="{x:Bind IsCurrentInstance, Mode=OneWay}"
    Modifiers="Control,Shift" />
```

With AccentKey being ```public readonly VirtualKey AccentKey = (VirtualKey)192;```

**Comment by yaichenbaum** [comment]
@puppetsw I don't think we need the KeyboardAccelerator to be declared in xaml

**Comment by yaichenbaum** [comment]
@puppetsw you might need to remove the shift modifier.

**Comment by puppetsw** [comment]
> @puppetsw you might need to remove the shift modifier.

I'll get back to this PR shortly. The problem I was having with it, is that the ` (accent key) isn't picked up by the KeyboardAccelerator events. So it's going to have to be handled in the PreviewKeyDown event. In my original commit I've put it in the CoreWindow keydown event, but I'll change this.

**Comment by yaichenbaum** [comment]
> > @puppetsw you might need to remove the shift modifier.
> 
> I'll get back to this PR shortly. The problem I was having with it, is that the ` (accent key) isn't picked up by the KeyboardAccelerator events. So it's going to have to be handled in the PreviewKeyDown event. In my original commit I've put it in the CoreWindow keydown event, but I'll change this.

Would it work to handle it with the rest of the shortcuts?

**Comment by puppetsw** [comment]
> > > @puppetsw you might need to remove the shift modifier.
> > 
> > 
> > I'll get back to this PR shortly. The problem I was having with it, is that the ` (accent key) isn't picked up by the KeyboardAccelerator events. So it's going to have to be handled in the PreviewKeyDown event. In my original commit I've put it in the CoreWindow keydown event, but I'll change this.
> 
> Would it work to handle it with the rest of the shortcuts?

Unfortunately it doesn't work with the existing KeyboardAccelerator_Invoked method (in the ModernShellPage, and ColumnShellPage)

**Comment by puppetsw** [comment]
Hmm the merge seems to have broken some things

**Comment by puppetsw** [comment]
I think I'm just going to close this PR and start a new branch. There are only 2 files that need to be changed.

**Pull request closed without merging**
