### PR TITLE
Add ability to jump to directory item by typing

### LINKED ISSUE #179: Go to letter
I would like to be able to go to a letter in files listing while pushing a letter
Meaning : select the first file in current list order to start with the letter
Thanks

### PR DESCRIPTION
**Pull request by jeffsieu**
# Changes

Allows the user to select an item in the directory by typing its first few characters.
Also fixes a bug where pressing enter upon renaming an item will both rename the item and launch it (file) or navigate into it (folder).

# Related issues

Closes #179 
Addresses an issue in #9

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Looks like there are some merge conflicts, can you go ahead and resolve them?

**Comment by yaichenbaum** [comment]
Everything looks good to me, one thing I would like to see added is if the user presses one letter and it jumps to it, if they press the letter again it should jump to the next item with that letter.

**Comment by jeffsieu** [comment]
@yair100 In this implementation, it will take consecutive characters typed and search for the first item lexicographically that contains the substring from the start.

For example:
With files "apple.txt" and "a.txt", typing "a" will select a.txt, typing "p" thereafter will select "apple.txt"

Currently the delay for the next character is set to 0.85s (probably needs a better way to be set). After which the current "jump" string is reset. Typing after the string is reset will initiate a new "jump" query.

**Comment by yaichenbaum** [comment]
I don't think it should be string based, how I imagined it would work is typing a letter would just go to the next item that starts with that letter. Maybe we should do it the way you did it but I am not sure yet, lets hear what Luke says.

**Comment by jeffsieu** [comment]
As of now, it's how it implemented in Windows Explorer I believe.

**Comment by yaichenbaum** [comment]
Are you sure? When I checked that was not how it worked in File Explorer.

**Comment by jeffsieu** [comment]
Yes, if you type consecutive letters in rapid succession, it will capture all of them and search based on that. But after a short delay, it will reset the string.

**Comment by jeffsieu** [comment]
@yair100 Oh, turns out, it's a combination of what we both said.

When typing a letter, the first file corresponding to that letter is selected.
If another letter is typed:
- If the letter is typed fast enough (e.g. < 1s later)
  - the letter will be appended to the search string
- if the letter is typed much later
  - the search string will be reset
  - if the letter is the same as the previous letter, go to the next item starting with that letter
    - else, go to the first word corresponding to that letter

I'll get to adding this part:
> if the letter is the same as the previous letter, go to the next item starting with that letter

**Comment by yaichenbaum** [comment]
This sounds more like the behavior I was looking for.

**Comment by jeffsieu** [comment]
@yair100 Alright, I've added it, please help me review the PR. Thanks!

**Comment by yaichenbaum** [comment]
From a usability end point it looks good, I will have @duke7553 go over the code and once he approves I will merge it in,

**Comment by yaichenbaum** [comment]
@jeffsieu Would you be able to resolve the merge conflicts on this one as well?
Thank you so much for all your contributions!

**Comment by jeffsieu** [comment]
@yair100 No problem

**Comment by yaichenbaum** [comment]
@jeffsieu did you get a chance to do this part "if the letter is the same as the previous letter, go to the next item starting with that letter else, go to the first word corresponding to that letter"?

**Comment by jeffsieu** [comment]
@yair100 Yes, I've added that in [here](https://github.com/duke7553/files-uwp/commit/382de396e2f2f2469fe648391befa413d6c9f777).

**Comment by yaichenbaum** [comment]
Hmm can you test it on the regular view? Same thing as the other issue, I am only seeing this behavior on the photo view.

**Comment by jeffsieu** [comment]
Oh gosh, seems like some issues happened with the merging, let me fix this

**Pull request merged**
