### PR TITLE
Add c# functionality "init" and "record"

### PR DESCRIPTION
**Pull request by cinqmilleans**
This pr enables the "init" and "record" functionality in C#.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by d2dyno1** [comment]
Can't we use C# 9?

**Comment by cinqmilleans** [comment]
I propose this while waiting to upgrade to c#9 but it would be better to upgrade to c#9 completely. If there are no obstacles, I agree to go.

**Comment by yaichenbaum** [comment]
> Can't we use C# 9?

We should definitely upgrade the c# version.

**Review by yaichenbaum — APPROVED** [review]

**Comment by d2dyno1** [comment]
Ok, so we're already using c#9

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
