### PR TITLE
Fix: Fixed FileNotFoundException in Recycle Bin watcher

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- https://files-org.sentry.io/issues/5610462140/events/0d15202895df4621bcde5b01ed4bc2e6/

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files ...
2. ...

### CODE REVIEW

**Review by 0x5bfa — COMMENTED** [review]
Only FileSystemWatcher.EnableRaisingEvents produces this exception when the path isn't locatable by CreateFile Win32 API, what about wrapping just it with SafetyExtention?

- https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.enableraisingevents?view=net-8.0
- https://github.com/dotnet/runtime/blob/9565550164fd63f1612141d221e04747d9742d4b/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L42

**Review by hishitetsu — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
@0x5bfa I don't think wrapping `EnableRaisingEvents` will help if the error doesn't occur until the watcher is already started.

**Comment by 0x5bfa** [comment]
Why not check before instancing it.

**Comment by yaira2** [comment]
We check on line 51 but that doesn't seem to help.

**Comment by 0x5bfa** [comment]
This method doesn't work sometimes lol I'm wondering why.
It produces not found exception when CreateFile fails. Do you think we should have our own checker using that function?

```c#
// bool StorageHelper.IfExists(string path);
HANDLE hFile = CreateFileW(path, ...);
if (hFile == -1) return false;
```

**Comment by yaira2** [comment]
It's something to look into

**Pull request merged**
