### PR TITLE
Code Quality: Migrated CopyFileFromApp and MoveFileFromApp to CsWin32

### PR DESCRIPTION
**Pull request by gumbarros**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Part of #14505, #15000 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Review by 0x5bfa — APPROVED** [review]
Great choice for the first step!

It looks very good!!
Replacing with it won't affect on behavior because both DllImport and CsWin32 use P/Invoke if the project can be build.

**Comment by 0x5bfa** [comment]
I think you can put more two DeleteFileFromApp and DeleteFolderFromApp.

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
> I think you can put more two DeleteFileFromApp and DeleteFolderFromApp.

Let's try to keep these PRs small in scope to make the review easier.

**Pull request merged**
