### PR TITLE
Feature: Update themes

### LINKED ISSUE #10281: Feature: Update themes
### What feature or improvement do you think would benefit Files?

Some themes (Modern House, Bound to Be Blue, Luxury Red) need to be updated to the latest schemas and/or be abandoned.

### Requirements

_No description provided_

### Files Version

Version: 2.3.12.0

### Windows Version

Windows 11 Insider Beta 22H2 22623.870

### Comments

Fixed by: #10275

### PR DESCRIPTION
**Pull request by Lamparter**
**Validation**
How did you test these changes?
- [ ] Built and ran the app
###### Could not build the app due to errors
- [ ] Tested the changes for accessibility
###### Could not build the app due to errors

Fixes: #10281 

**Description**
SUBJECT TO CHANGE DUE TO NEW FORMAT OF THEMES

@yair100:
> I'm working on a new format for themes
> The new format hasn't been finalized but instead of allowing you to override every brush, it'll only work for specific brushes and will be a lot easier to work with.

### CODE REVIEW

**Review by 0x5bfa — CHANGES_REQUESTED** [review]
Changes requested:

- Remove Files.Uwp.csproj
- Use tab indent instead of 4-spaces indent (community wants to use it)
- Revert changes of Files.sln

Also, I notice that Files no longer doesn't support old theme resources.

**Comment by yaichenbaum** [comment]
Can you link an issue discussing these changes?

**Comment by DeveloperWOW64** [comment]
> * Use tab indent instead of 4-spaces indent (community wants to use it)

Sure, but apparently spaced is MSFT standard.

**Comment by yaichenbaum** [comment]
We prefer tabs to be consistent with the default for c#

**Comment by DeveloperWOW64** [comment]
> We prefer tabs to be consistent with the default for c#

I'm sorry, but this is impossible.

**Comment by DeveloperWOW64** [comment]
> Also, I notice that Files no longer doesn't support old theme resources.

@onein528 Which themes have old resources?

**Comment by yaichenbaum** [comment]
Closing as we're starting to work on implementing the new theme system.

**Pull request closed without merging**
