### PR TITLE
Update build output paths

### PR DESCRIPTION
**Pull request by chingucoding**
**Resolved / Related Issues**
Ever wanted to EASILY clean all binaries? Fear no more as the build output now is not spread in different bin folders but rather in a single location, the `artifacts`

**Details of Changes**
- Removed old build output locations from project files
- Add directory.build.props file to inject new output path into project files
Fun fact, this file also allows to add a reference to packages in every project or add code analyzers for all projects more easily.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by gave92** [comment]
The `obj` folder is still created in each project folder, is this intended? Should  this be redirected as well (I think it's BaseIntermediateOutputPath)?

**Comment by chingucoding** [comment]
In my projects, I never did that. that's why I only directed the "bin" output to a different directory.

**Comment by gave92** [comment]
It's not building anymore for me on Debug + x64 (complains about the following missing file):
image

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@chingucoding thank you!

**Comment by xxxprolapsexxx** [comment]
xxx

вс, 25 июл. 2021 г., 22:25 Marco Gavelli ***@***.***>:

**Pull request merged**
