### PR TITLE
Resize cards in the drive widget dynamically 

### LINKED ISSUE #6398: The devices menu is not as wide as the folders menu on the homepage. [INSIDER 2.0.16]
### Description

image

As you can see, the folders menu is wider than the devices menu. It's kinda inconsistent imo.

### Steps To Reproduce

1. Install Build 2.0.16.
2. Open Files.
3. You can see it on the homepage itself.

### Expected behavior

In my opinion, the sizes of menus should be consistent.

### Files Version

v2.0.16

### Windows Version

Windows 11 21H2 Build 22000.194 (Stable Release)

### Relevant Assets

image

### PR DESCRIPTION
**Pull request by sumeshir26**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6398

**Details of Changes**
Add details of changes here.
- Made stretch of drives widget as "Fill"
- Minimum Width is 250

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@sumeshir26 thank you for opening this pull request, this issue was already resolved but we missed closing the issue. In the future, mention me on the issue so I can update you on the latest status.

**Comment by yaichenbaum** [comment]
@sumeshir26 can you keep the current size when there are only one or two drives?

**Comment by sumeshir26** [comment]
Ok

**Comment by sumeshir26** [comment]
@yair100 I'm not reallay sure how to do this, if you want, i will close this

**Comment by yaichenbaum** [comment]
@sumeshir26 we're doing something similar for the grid view layout, if you're still intrested, I can point you in the right direction.

**Comment by sumeshir26** [comment]
@yair100 Okay, that would be great!

**Comment by yaichenbaum** [comment]
@sumeshir26 it looks like we're using the AdaptiveGridView control from the Windows Community Toolkit and setting `StretchContentForSingleRow` to `False`.

**Comment by sumeshir26** [comment]
@yair100 Thank you, will commit changes soon

**Comment by sumeshir26** [comment]
@yair100 I couldn't figure out how to make it expand dynamicallay, but this PR does fix the original issue. This is ready for review

**Comment by yair100** [comment]
> @yair100 I couldn't figure out how to make it expand dynamicallay, but this PR does fix the original issue. This is ready for review

@sumeshir26 it looks like the drives get cut off on small window sizes and the size of the drives still don't line up with the folders.

**Comment by sumeshir26** [comment]
@yair100 The drives get cut off even on the current commit on `main`:
image

**Comment by yair100** [comment]
> @yair100 The drives get cut off even on the current commit on `main`

I'm seeing that now, but these changes don't seem to help for the other issue.

**Pull request closed without merging**
