### PR TITLE
Second branch

### PR DESCRIPTION
**Pull request by TyJOrtiz**
**Details of Changes**
Add details of changes here.
- Changed column view icon in navtoolbar to bitmapicon

**Validation**
How did you test these changes?
- [X] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@XPoppyX Do you think you can create a font icon instead of the png?

**Comment by XPoppyX** [comment]
@yaichenbaum Actually the icon used is E162 or E8C0 but from the new Segoe icons asset. If you are waiting for an update to use the new asset then you can leave this icon as is, or what you think?

**Comment by TyJOrtiz** [comment]
I have another question, i noticed there's a new change with the BaseLayout, it's rendered some of the existing code for ColumnView out of date (like selecting items and such), can someone bring me up to date?

**Comment by yair100** [comment]
> @yair100 Actually the icon used in this PR is E162 or E8C0 but from the new Segoe icons asset. If you are waiting for the windows update to use the new asset then you can leave the icon as is to avoid copy and paste the icon from segoe icons to custom-glyphs, or what you think?

I think it's best to use a custom icon since there isn't really any icon in either fonts that would fit for column view.

**Comment by XPoppyX** [comment]
@yaichenbaum what do you think of this? it is similar to the icon used in macOS for column view
Captura de pantalla 2021-04-27 194514

**Comment by yaichenbaum** [comment]
@XPoppyX Looks good to me!

**Comment by XPoppyX** [comment]
This is how it looks, it's ready for a PR

Captura de pantalla 2021-04-27 194857
Captura de pantalla 2021-04-27 194929
--------------
Context menu:
Captura de pantalla 2021-04-27 200252

**Comment by yaichenbaum** [comment]
@XPoppyX Thanks! Can you open a PR?

**Comment by yaichenbaum** [comment]
Merging with #4770.

**Pull request closed without merging**
