### PR TITLE
Changed selected tab color to make it easier to see

### PR DESCRIPTION
**Pull request by winston-de**
Before it was the same as the tab strip background, which made it harder to see.

image

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de What does it look like in light theme?

**Comment by winston-de** [comment]
> @winston-de What does it look like in light theme?

@yair100 

image

**Comment by winston-de** [comment]
Also, @yair100, currently the pointer over background for unselected tabs is currently the same as the tab strip background. Maybe it should be changed to something like this?

image

image

**Comment by yaichenbaum** [comment]
@winston-de That might be a little better than what I did in my PR, lets wait until that's merged before finishing this one.

**Comment by winston-de** [comment]
@yair100 Oh, great! I didn't realize your pr already added a pointer over effect to tabs.

**Review by yair100 — APPROVED** [review]

**Pull request merged**
