### PR TITLE
Fix: Fixed Ctrl+A in the rename textbox

### LINKED ISSUE #12040: Bug: Ctrl + A shortcut isn't selecting text when renaming files
### What feature or improvement do you think would benefit Files?

Hello, I work with the extensions of the files shown, when I press F2 to change the file name, I also press CTRL+A to edit the whole name of the file. Or copy the name of the file. 
On Windows Explorer, pressing F2 enables the change name for the file (files does this too) and then CTRL+A selects the entire text on the text box. 

image

### Requirements

- This proposal will achieve the functionallity of the combination CTRL+A to select the entire text inside the textbox

### Files Version

2.4.61.0

### Windows Version

10.0.19044.2728

### Comments

_No response_

### PR DESCRIPTION
**Pull request by hishitetsu**
_Targeted to the servicing branch_

**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12040 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Comment by ferrariofilippo** [comment]
I'm wondering if we should disable all the shortcuts when renaming items...

**Comment by hishitetsu** [comment]
> I'm wondering if we should disable all the shortcuts when renaming items...

Certainly. However, this fix is necessary anyway, since the code is intended to disable the ListView native shortcut and redirect to RichCommand.

**Review by QuaintMako — APPROVED** [review]
LGTM, it solves the issue.

**Comment by QuaintMako** [comment]
Regarding the disabling of all shortcuts when renaming, that is possibly a good idea. 
I'd suggest opening an feature request for it to open discussions around it.

**Comment by ferrariofilippo** [comment]
> Certainly. However, this fix is necessary anyway, since the problem here is not that Select All Items is invoked, but that Select All Text is not invoked. The code is intended to disable the ListView native shortcut and redirect to RichCommand.

I'm sorry probably I was not very clear. That comment meant that we could move `if (IsRenamingItem) return;` to the top of the method

**Comment by ferrariofilippo** [comment]
> Regarding the disabling of all shortcuts when renaming, that is possibly a good idea. I'd suggest opening an feature request for it to open discussions around it.

Just opened #12053

**Comment by hishitetsu** [comment]
> I'm sorry probably I was not very clear. That comment meant that we could move `if (IsRenamingItem) return;` to the top of the method

I see. I will address it that way later.

**Comment by hishitetsu** [comment]
> I'm sorry probably I was not very clear. That comment meant that we could move `if (IsRenamingItem) return;` to the top of the method

I addressed it.

**Pull request merged**
