### PR TITLE
Revert "Fixed issue with Files launcher not getting copied to output …

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Review by gave92 — APPROVED** [review]

**Comment by gave92** [comment]
The project format has not changed. Why should it cause issue when installing? Was that project being built before? Need to check an azure build where the launcher was working properly.

**Comment by yaichenbaum** [comment]
It stopped working when we switched to WinAppSdk (it worked when we removed ARM64). It started working again when this was removed (accidentally).

**Comment by gave92** [comment]
We still need this to fix the launcher though.. so is it an issue of building the FilesLuancher project for ARM64 then?

**Comment by yaichenbaum** [comment]
That's what it looks like, can we use a regular csproj for this?

**Comment by gave92** [comment]
CSproj if for CSharp, vcproj is for c++. Not sure why would the project format matter..

**Comment by yaichenbaum** [comment]
It's also possible the installation issue was from the changes to the pipeline

**Comment by gave92** [comment]
Perhaps we could go back to not build that project and just include the FilesLauncher.exe in the repository

**Comment by yaichenbaum** [comment]
Sounds like a good solution

**Pull request merged**
