### PR TITLE
Double click gridsplitter to resize columns to fit content

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- For #4643

**Details of Changes**
Add details of changes here.
- Double clicking the header divider should fit the column to width

@winston-de I was looking into implementing the above change and this is what I came up with.
This seems to work fine when the items are not too many (until list virtualization kicks in). What do you think?

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by winston-de** [comment]
What about approximately calculating the width based on the length of the string in listed item and font size? It may not be as accurate, but I'd imagine it would be more performant then measuring the width of each text block.

**Comment by gave92** [comment]
I thought that wouldn't work as it's dependent of font scaling, but I haven't tried.

**Comment by gave92** [comment]
3e6c283 -> done! Now only the first few textboxes are measured, the rest is calculated using the length of the string in listed item.

**Review by winston-de — APPROVED** [review]
lgtm

**Comment by gave92** [comment]
Sorry to ask to review again @winston-de I've noticed a few issues which I fixed:
- Fix crash when folder is empty
- Resized column size was not saved to folder preferences
- Column max width was not respected
- Added ability resize-to-fit all the columns while I was at it

**Review by winston-de — APPROVED** [review]

**Pull request merged**
