### PR TITLE
Update pl-PL

### PR DESCRIPTION
**Pull request by d2dyno1**
**Resolved / Related Issues**
/-

**Details of Changes**
- Updated pl-PL translations

**Validation**
- [ ] Built and ran the app

### CODE REVIEW

**Review by yair100 — DISMISSED** [review]
Thank you!

**Comment by yaichenbaum** [comment]
@d2dyno1 can you resolve the merge conflicts?

**Review by yair100 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@d2dyno1 looks like the pipeline is failing 🤔

**Comment by d2dyno1** [comment]
@yair100 anything left to do?

**Comment by yair100** [comment]
> @yair100 anything left to do?

The PR is still failing the pipeline.

**Comment by d2dyno1** [comment]
@yair100 Fixed!

**Review by yair100 — APPROVED** [review]

**Pull request merged**
