### PR TITLE
Fixed: Unable to extract archives from context menu

### LINKED ISSUE #10062: Bug: Unable to extract archives from context menu
### Description

When clicking on them they do nothing or crash Files

### Steps To Reproduce

1. Download a .zip file
2. Use extract buttons on toolbar or right click
3. Observe that nothing happens

### Steps to fix

- Extract items as expected

### Files Version

2.3.37.0

### Windows Version

10.0.22621.521

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9639249/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9639250/debug.log)

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #10062 

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Comments**
There was a problem with `ShowAsync` and all `Dialogs`, it could be easily fixed by moving to `TryShowAsync`
@Josh-65 could you try this out (I'm not sure if this is the only needed fix)?

### CODE REVIEW

**Comment by ferrariofilippo** [comment]
Ok, I've just seen that doing literally anything when extracting an archive crashes Files

**Comment by ferrariofilippo** [comment]
> Ok, I've just seen that doing literally anything when extracting an archive might crash Files Edit. This happens very few times

I think I may fix this by computing extraction on a different thread, is this the right approach?

**Comment by ferrariofilippo** [comment]
Testing more, I found out that:
- This crash does not leave any track: neither in logs nor in debug trace. There are no exceptions still, all threads stop.
- It seems that crash happens when too many UI events are raised (Decompression alone works fine. There MAY be issues when you start moving/resizing the window, click around, ....)

**Comment by ferrariofilippo** [comment]
I tested it again and everythings seems to work. I also recloned the branch for a brand new build and still everything worked.
Please, tell me if it is not working on your build

**Comment by Josh-65** [comment]
Seems to work now

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
