### PR TITLE
Feature: Disable warning when a new name is empty

### LINKED ISSUE #12140: Feature: Disable warning when a new name is empty
### What feature or improvement do you think would benefit Files?

When the dialog box to enter a new item name is displayed, the user is warned that the name is invalid from the beginning. I think it is confusing to users to get a warning when they have not done anything yet and it is obvious that the name should not be empty, so there is no need to warn.
The same can be said when creating a new tag.

image

### Requirements

Disable warning for invalid names when the name is empty.

### Files Version

2.4.66.0

### Windows Version

Windows 11 22H2

### Comments

_No response_

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12140

**Removed from**
- New Item Dialog
- New Archive Dialog
- New Shortcut Dialog

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app
   2. Open the menu to create a new file
   3. See that the warning is not displayed when the name is empty

### CODE REVIEW

**Comment by yaira2** [comment]
Should we target the servicing branch?

**Comment by ferrariofilippo** [comment]
I don't think this issue is that urgent

**Review by yaira2 — DISMISSED** [review]
LGTM

**Comment by ferrariofilippo** [comment]
> LGTM

What do you think about the two questions in the description?

**Comment by yaira2** [comment]
> Should we disable the tip also when the shortcut path is invalid?
> I believe we shouldn't remove that from tags. What do you think?

Is there any reason to handle it differently?

**Comment by ferrariofilippo** [comment]
> Is there any reason to handle it differently?

For the first one (shortcuts) I agree, we should not show the tip. It was not mentioned in the issue and I wanted to wait on some feedback to avoid wasting work
For tags, I don't think the warning is disturbing there, I mean it's not covering anything else (as the tip does)

**Comment by yaira2** [comment]
We can try without it then 👍

**Comment by hishitetsu** [comment]
I think this should be merged into the servicing brunch.

**Comment by hishitetsu** [comment]
And I think the tag warning should be removed. The problem is not that something is hidden, but that the warnings are just unnecessary and offensive to the user.

**Comment by ferrariofilippo** [comment]
> And I think the tag warning should be removed. The problem is not that something is hidden, but that the warnings are just unnecessary and offensive to the user.

I removed it for empty names but not for whitespaces

**Comment by ferrariofilippo** [comment]
> I think this should be merged into the servicing brunch. It is certainly not a breaking bug, but I think it is making the UX much worse.

I swapped it to `servicing` but the changes are like 3k lines (instead of something like 20). I think I should change back to `main`

**Comment by hishitetsu** [comment]
> I swapped it to `servicing` but the changes are like 3k lines (instead of something like 20). I think I should change back to `main`

Perhaps you have to create another branch based on the servicing branch and cherry-pick your commits into it.

**Pull request merged**
