### PR TITLE
Fix Download folder location

### LINKED ISSUE #384: Wrong Downloads folder location
**Describe the bug**
Files UWP automatically managed to figure out the location for the Documents, Pictures , Music and Videos folders but for some reason it failed to do so with the Downloads one. All these folders including the Downloads one are straight on my E: drive.
I am aware one can manually change where these folders are located in the settings but since the automatic detection works for the other folders I'd consider it a bug that still should be fixed.

**To Reproduce**
1. Have custom location for downloads folder since before.
2. Install and run Files UWP.
3. Click on "Downloads".
4. See it take you to the default/standard location instead of the custom one.

**Expected behavior**
Expected it to show me the custom location automatically since it worked with all the other folders with custom location.

**Desktop:**
 - OS Version: Windows 10 1909 18363.535
 - App version: v0.6.6.0

### PR DESCRIPTION
**Pull request by tsvietOK**
Get other default folders locations same way
Fixes #384

### CODE REVIEW

**Comment by duke7553** [comment]
@tsvietOK Excellent work! I didn't know UserDataPaths existed

**Review by lukeblevins — APPROVED** [review]

**Comment by yaichenbaum** [comment]
This change actually doesn't do anything, we actually set this data from the registry editor and this issue has already been fixed. I think this should be reverted.

**Comment by lukeblevins** [comment]
@yair100 I don't think we necessarily need to revert this because it does improve the detection of the downloads folder path. Before, we simply appended @"\Downloads" to the root user data folder path. 

If it is still a problem after this PR, we can work on improving the registry detection, but for now it looks like a decent improvement. (Unless there are other objections)

**Comment by tsvietOK** [comment]
@yair100 I think you are not right. As i understand, this part with registry detection in Files.Launcher don't even running, try to debug Program.cs.

**Comment by yaichenbaum** [comment]
@tsvietOK If that is the case we have some room for improvements in this area, if your change fixes the issue, then we should be able to remove the code from Files.Launcher.

**Comment by tsvietOK** [comment]
@yair100 it's smth strange, it is workig even if i change this vars to random symbols

image

**Comment by yaichenbaum** [comment]
I think we need to move the startup task to the UWP project, we are changing the value of the settings there but the setting view model isn't updated.

**Comment by yaichenbaum** [comment]
@tsvietOK Can you take a look at #614?

**Pull request merged**
