### PR TITLE
GitHub: Update issue templates to make users copy Windows version from settings

### PR DESCRIPTION
**Pull request by MarcAnt01**
**Validation**
How did you test these changes?
My own fork with issue template on

### CODE REVIEW

**Comment by MarcAnt01** [comment]
> On second thought, the about page doesn't actaully show the Windows version. It's only after pressing the copy button.

What would you like to be displayed there instead?

**Comment by yaira2** [comment]
We could theoretically explain that the copy button copies the Windows version as well, but I'm concerned that'll just confuse the issue authors. It might be best to just leave the template as is.

**Comment by MarcAnt01** [comment]
> We could theoretically explain that the copy button copies the Windows version as well, but I'm concerned that'll just confuse the issue authors. It might be best to just leave the template as is.

Or also add a further button to copy the Windows version

**Comment by yaira2** [comment]
It's not high priority but #4635 will make it a lot easier.

**Comment by 0x5bfa** [comment]
Do we really need specific windows version in the first place? Why not we make dropdown for the selection of Windows 10/11, and of Dev/Preview/Stable, and of 21H1/21H2/22H1…?

**Comment by yaira2** [comment]
A dropdown is a good idea, can you open a PR for this?

**Pull request closed without merging**
