### PR TITLE
Rework sidebar resizing to enable expanding the sidebar in compact mode

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**

**Details of Changes**
Add details of changes here.
- Make elements in MainPage children of the sidebar so that expanding the sidebar in compact mode works properly
- Remove code that hid the pane toggle button when in compact mode
- Enable horizontal manipulation on the sidebar border to allow for resizing, and show the resize cursor on hover (before the resizing relied on a grid splitter)
- Removed unnecessary elements from the view stack

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

https://user-images.githubusercontent.com/59544401/116501574-fb86a280-a865-11eb-95e2-0307fd528dfb.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de Whenever this is ready for review, can you test it in release mode?

**Comment by winston-de** [comment]
@yair100 Just tested, it works in release mode.

**Comment by josh-65** [comment]
Would this also fix the content staying collapse when going in and out of compact mode?

**Comment by yaichenbaum** [comment]
> Would this also fix the content staying collapse when going in and out of compact mode?

No.

**Review by yair100 — APPROVED** [review]
LGTM

**Comment by yaichenbaum** [comment]
@winston-de This seems to have broken the drag area above the sidebar, can you take a look at this?

**Pull request merged**
