### PR TITLE
Fix: Fixed an issue where panes couldn't be switched via touch

### PR DESCRIPTION
**Pull request by XTorLukas**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.

https://discord.com/channels/725513575971684472/958783217941487616/1245094972043296848
- An issue where there is no switching between panels using the touch screen.

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Switch between panels in Dual Pane mode via touch on touch screen

### CODE REVIEW

**Review by yaira2 — DISMISSED** [review]
This looks good to me but I'd like to wait until @hishitetsu can review.

**Review by hishitetsu — APPROVED** [review]
This also slightly changes the behavior when using a mouse. The pane will switch when the button is pressed instead of when the button is released, but it would rather do so.
LGTM

**Comment by XTorLukas** [comment]
@hishitetsu If we want to specify more precisely the finger tap, I can use `Tapped` instead of `PointerPressed`

**Comment by hishitetsu** [comment]
> @hishitetsu If we want to specify more precisely the finger tap, I can use `Tapped` instead of `PointerPressed`

I'd rather use `PointerPressed`.

**Pull request merged**
