### PR TITLE
Feature request: Add a recent items page #2718

### PR DESCRIPTION
**Pull request by oleitao**
**Details of Changes**
- Added context menu feature to add files and folders to recent files/folders panel

**Validation**
- [x] Select an file and select to add on Recent Panel
- [x] Confirm that file were added on Recent Panel
- [x] Select an folder and select to add on Recent Panel
- [x] Confirm that folder were added on Recent Panel

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao Btw, when you open a PR, you can add the issue number it closes to the PR description like this.
image

**Comment by yaichenbaum** [comment]
@oleitao This doesn't quite seem to work as described in the issue.

**Comment by oleitao** [comment]
> @oleitao This doesn't quite seem to work as described in the issue.

Sorry @yair100 maybe i didn't understand well the requirements of this feature. I will close this PR. 
Excuse my mistake.

**Comment by yaichenbaum** [comment]
@oleitao It's our mistake for not making them clear from the beginning, if you do want continue working on it, I updated the issue description to clarify on what needs to be done.

**Pull request closed without merging**
