### PR TITLE
rename items in all layout views

### PR DESCRIPTION
**Pull request by xwnb**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes...
  - https://github.com/files-community/Files/issues/4153
- Related...
  - https://github.com/files-community/Files/issues/2976
  - https://github.com/files-community/Files/issues/2963
  - https://github.com/files-community/Files/issues/5600

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...
- Fix
  - Fix item-rename in all layout reviews (detail, grid views, and etc.)

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

https://user-images.githubusercontent.com/45145954/127733002-0c9761f8-b47c-49a4-8c63-d30a10bb732e.mp4

### CODE REVIEW

**Comment by gave92** [comment]
Thanks for this contribution, it works great! Only think it does not allow to open a file by double clicking on the filename if the file is already selected (that was the reason for those timers), but I think the same is currently broken on main too.

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@xwnb Thank you!

**Comment by yaichenbaum** [comment]
> Thanks for this contribution, it works great! Only think it does not allow to open a file by double clicking on the filename if the file is already selected (that was the reason for those timers), but I think the same is currently broken on main too.

@gave92 This is a pretty significant issue, can you open an issue for tracking?

**Comment by xwnb** [comment]
> Thanks for this contribution, it works great! Only think it does not allow to open a file by double clicking on the filename if the file is already selected (that was the reason for those timers), but I think the same is currently broken on main too.

@gave92 @yair100 thanks for reviews. I missed this situation. Maybe we should delay `CheckRenameDoubleClick` execution. It would be easier and more stable to avoid this issue. I'm willing to solve the issue if tracked.

**Comment by gave92** [comment]
Thanks @xwnb, issue is tracked in #2967.

**Pull request merged**
