### PR TITLE
Attempt to fix #985

### LINKED ISSUE #985: Apps are launching behind the Files UWP app window
**Describe the bug**
If Windows Terminal set as default terminal app, after a click on 'Open in Terminal' context menu option the terminal window opens behind the Files UWP window, and the Files UWP window remains in focus.

**To Reproduce**
1. Go to 'Settings / Preferences'
2. Select 'Windows Terminal' in 'Terminal Applications' dropdown
3. Go to any directory
4. Open right click context menu
5. Click on 'Open in Terminal' option
6. The Windows Terminal window opens, but the Files UWP window remains in focus

**Expected behavior**
A newly opened terminal window should be focused like it is for CMD terminal application.

**Screenshot**
FilesUWP-WinTerminal

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 (Build: 18363.900)
 - Files UWP Version: 0.9.2.0
 - Windows Terminal Version: 1.0.1401.0

### PR DESCRIPTION
**Pull request by yair100**
Fixes #985?

### CODE REVIEW

**Comment by lukeblevins** [comment]
@yair100 I haven't been able to reproduce this one for a while. Does this actually fix the issue for you? I also doubt SetForegroundWindow() will be effective here because the limitations below apply: 
image

**Review by lukeblevins — CHANGES_REQUESTED** [review]
Not sure if the limitations are relevant since they are worded very poorly, but they are worth looking into.

**Comment by gave92** [comment]
@yair100 I'm pretty sure this won't solve the issue, I remember opening a PR like this and @tsvietOK was still able to reproduce the issue.
Unfortunately I get this bug way to rarely to be able to properly test this.
(Also without a delay mainwindowhandle  will be null most of the time)

**Comment by yaichenbaum** [comment]
@gave92 Luke pointed this out to me, I am closing this PR since it doesn't solve the issue

**Pull request closed without merging**
