### PR TITLE
Feature: Added file operation support for FTP

### PR DESCRIPTION
**Pull request by NicoooByte**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes partially #5833 (Move operation)

Adds feature of moving files and folders in an FTP storage via the FluentFTP library.

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

**Screenshots (optional)**
None

### CODE REVIEW

**Comment by gave92** [comment]
Hi, thanks for your contribution!

Please see https://github.com/NicoooByte/Files/pull/1/files for some suggested changes:
- Restored some of the previous code, needed for operations outside FTP folders
- Renamed MoveFolderAsync to MoveAsync, to match RenameAsync, etc..
- Made so the method returns the moved folder

Other than that this is looking good.

**Review by gave92 — APPROVED** [review]

**Comment by yaira2** [comment]
@NicoooByte thank you for your contribution, and congrats on your first pull request!

**Comment by NicoooByte** [comment]
Thanks, feels good :)

**Comment by yaira2** [comment]
You happened to have picked one of the more difficult issues, it's a good thing Gave was able to help with the review.

**Pull request merged**
