### PR TITLE
Fix: Fixed an issue where the eject drive option wasn't shown correctly

### LINKED ISSUE #10154: Virtual (vhdx) mounted drives don't have Eject option
### Description

File explorer has the option to eject a mounted drive in the context menu when Files doesn't.
image
image

### Steps To Reproduce

1. Create a Hyper-V VM
2. Right click virtual drive
3. Select mount option
4. Right click mounted drive
5. See no eject option

### Steps to fix

Add eject to context menu

### Files Version

2.3.47.0

### Windows Version

10.0.22621.608

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/9737867/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/9737865/debug_fulltrust.log)

### LINKED ISSUE #13462: Bug: "Eject" appears in the context menu of the floppy disk drive
### Description

"Eject" should not be displayed because floppy disk ejection is not controlled by software. When I select "Eject" on the floppy disk drive, I get a drive-in-use error.

### Steps To Reproduce

1. Right-click a floppy disk drive on the drive widget.
2. See "Eject" appears in the context menu.

### Requirements

"Eject" should not appear in the context menu of the floppy disk drive.

### Files Version

2.5.21.0

### Windows Version

10.0.22631.2361

### Log File

n/a

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #10154
- Closes #13462

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Confirmed the option is show for virtual drives

### CODE REVIEW

**Comment by yaira2** [comment]
@hecksmosis this is based on your earlier pull request #11135 but with the `CMF_OPTIMIZEFORINVOKE` flag. Could you check if the previous issues are solved?

**Comment by yaira2** [comment]
Unfortunately it looks like it's still failing to eject the virtual drive.

**Comment by 0x5bfa** [comment]
Ejecting USB works fine?

**Comment by yaira2** [comment]
I haven't tried, but in theory, if we find another way to eject drives, we can still merge this PR.

**Comment by 0x5bfa** [comment]
I found a mention that says what we use to eject IOCTL_STORAGE_EJECT_MEDIA (DeviceIoControl) has been deprecated since a Windows 10 Update and tells to use CM_Request_Device_EjectW. These have existed since XP and I have no idea why the former became deprecated and haven't tested if that is the case.
I'll find more rationales and find what base function the latter one calls.

**Comment by 0x5bfa** [comment]
@ahmed605 do you happen to know what function File Explorer uses?

**Comment by yaira2** [comment]
We currently use the context menu

**Pull request closed without merging**
