### PR TITLE
Add option to export\import settings #1260

### PR DESCRIPTION
**Pull request by oleitao**
**Resolved / Related Issues**
- Closes [#1260](https://github.com/files-community/Files/issues/1260)

**Details of Changes**
- Added import settings
- Added export settings

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao we're currently on feature freeze as we work on getting v2 finished. Also, in the future, please let us know before you start work on a PR so we can collaborate on it 🙂

**Comment by gave92** [comment]
Better wait for this after #6033 is implemented.

**Comment by d2dyno1** [comment]
> Better wait for this after #6033 is implemented.

@oleitao I'll also bundle this in #6113 since with the new implementation it'll be trivial to do so.

**Comment by yaichenbaum** [comment]
> > Better wait for this after #6033 is implemented.
> 
> @oleitao I'll also bundle this in #6113 since with the new implementation it'll be trivial to do so.

With users being able to view the json file themselves, I'm not sure an additional button makes sense... It's up for discussion in the relevant issue.

**Comment by d2dyno1** [comment]
> > @oleitao I'll also bundle this in #6113 since with the new implementation it'll be trivial to do so.
> 
> With users being able to view the json file themselves, I'm not sure an additional button makes sense... It's up for discussion in the relevant issue.

I'd aim for two simple buttons for exporting and importing. Obviously users can do it manually by swapping the json file themselves but wouldn't it better if this action was wrapped around a nice UI? Also, some users wouldn't even know that such possibility exited.

**Pull request closed without merging**
