### PR TITLE
Feature: Rename the "Path:" text to "Location" feature.

### PR DESCRIPTION
**Pull request by munnanadaf**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by 0x5bfa** [comment]
This is already resolving by #12243.

**Comment by yaira2** [comment]
@munnanadaf thank you for taking the time to open this PR, it looks like someone beat you to this by a couple of hours and it was implemented in #12243. If you're interested, let me know and I can suggest a different issue for you to work on.

**Comment by munnanadaf** [comment]
Yeah sure, since I'm new to this, i would love to keep learning and
contribute towards greater good.

**Comment by yaira2** [comment]
@munnanadaf how about #11945? If you decide to work on this, please note that it's enough to update the en-us resw file. The other files will automatically update in Crowdin.

**Comment by munnanadaf** [comment]
Okay, I'll check it out and let you know.

**Pull request closed without merging**
