### PR TITLE
Code Quality: Renamed ItemViewModel with ShellViewModel

### PR DESCRIPTION
**Pull request by 0x5bfa**
### Resolved / Related Issues

- Related: #4180

### Steps used to test these changes

_None_

### CODE REVIEW

**Comment by yaira2** [comment]
What's the goals here?

**Comment by 0x5bfa** [comment]
Preparing Storage Abstraction.
This is long term goals but it's to refactor to reduce code lines of ShellViewModel. Current code base relies on this class and makes us hard to create unit test or maintain.

**Comment by yaira2** [comment]
This PR seems to just be a rename, how does it further that goal?

**Comment by 0x5bfa** [comment]
Wdym, I just made it more accurate.
Besides being inside of Data.Models was also wrong.

**Comment by d2dyno1** [comment]
Good change! Hopefully it'll be less confusing

**Pull request merged**
