### PR TITLE
Move loading indicator to tab icon element

### LINKED ISSUE #3922: Enhancement: Move the loading indicator to the tab icon
- Replace the loading indicator with the progress ring in the tab.

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #3922 

**Details of Changes**
Add details of changes here.
- Added progress ring to TabViewItem template, and add visual states for loading/not loading
- Add and implemented code to switch the tab loading indicator
- Removed code for old loading status indicator

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

https://user-images.githubusercontent.com/59544401/121791871-8962e680-cba3-11eb-8a4a-128d85ee342a.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de Should this apply to the vertical tab flyout as well?

**Comment by winston-de** [comment]
> @winston-de Should this apply to the vertical tab flyout as well?

**Comment by R3voA3** [comment]
Been waiting for this for a while. Looks splendid!

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
