### PR TITLE
Feature: Disabled keyboard shortcuts when renaming items

### LINKED ISSUE #12053: Feature: Disable keyboard shortcuts when renaming items
### What feature or improvement do you think would benefit Files?

I think that keyboard shortcuts that are not related with editing should be disabled when renaming items.
We should still handle other common shortcuts such as `Esc`, `Ctrl + A`, ...

### Requirements

- This feature will prevent future issues involving RichCommands remapping (think of a user assigning a shortcut to `Shift + Letter`)

### Files Version

2.4.61.0

### Windows Version

Windows 11 Pro 22H2 10.0.22621.1485

### Comments

_No response_

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12053

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Start renaming an item
   2. Try to use any shortcut (you should consider changing some shortcuts to `Shift + Letter` to test deeper)

### CODE REVIEW

**Comment by yaira2** [comment]
Do the TextBox shortcuts work (eg, `ctrl + c`, `ctrl + v`, `ctrl + a`)?

**Comment by yaira2** [comment]
There are also some shortcuts for switching which file is being renamed (`tab` and `shift + tab`)

**Comment by ferrariofilippo** [comment]
> Do the TextBox shortcuts work (eg, `ctrl + c`, `ctrl + v`, `ctrl + a`)?
> There are also some shortcuts for switching which file is being renamed (`tab` and `shift + tab`)

They still work

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
