### PR TITLE
Refresh drives list when mounting/unmounting ISO file

### LINKED ISSUE #1257: Add the option to mount an ISO image

### LINKED ISSUE #1490: App Crashes when accessing ejected CD/DVD-Drive and no refresh
**Describe the bug**
When accessing an ejected CD/DVD-Drive the app crashes.

**To Reproduce**
1. Mount an ISO file in Windows
2. Start Files UWP
3. Eject ISO
4. Try to access the drive in Files UWP

**Expected behavior**
Files UWP should recognize that a drive disappears and refresh the list and catch the exception without crashing.

https://github.com/files-community/files-uwp/blob/master/Files/BaseLayout.cs#L221

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.12.0

**Additional context**
-

### LINKED ISSUE #2403: Left pane not refreshing to show recent mounted .iso file disk.
**Describe the bug**
Left pane not refreshing to show .iso file disk after mounted.

**To Reproduce**
1. Go to the application.
2. Click on on a .iso file disk.
3. Mount the file as a disk.
4. Left pane does not refresh to show the mounted disk.

**Expected behavior**
To refresh the left pane after mounting the .iso file disk.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630]
 - App version: [v0.20.2.0]

### PR DESCRIPTION
**Pull request by gave92**
Fixes #2403
Fixes #1490
Fixes #1257

Refresh drive list when an ISO, VHD gets inserted or removed.

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]

**Comment by tsvietOK** [comment]
@gave92 Sorry, but for some reason it is doesn't work for me.

**Comment by gave92** [comment]
@tsvietOK thanks for the feedback.
Are you ejecting the iso from Files or windows Explorer?

**Comment by tsvietOK** [comment]
@gave92 
image
It doesn't matter, both methods successfully ejects drive, but interface not updated.

**Comment by gave92** [comment]
@tsvietOK curious, for me it works correctly *if the iso is ejected from explorer*
If I eject it from Files, it looks like it was ejected but it will still appear both in Files and explorer
In explorer it will look like an empty drive:
image

**Comment by tsvietOK** [comment]
@gave92 Unmounted state: Normal state for empty virtual ISO drive
image
Mounted state: Name of drive should be updated like on the next screenshot.
image
After app restart:
image
Ejected from explorer or Files:
image
As you can see, any changes(except new drives plugged in) are not visible for Files.

When connected to fulltrust the Output window is empty when ejecting through explorer or from Files.
I am using Daemon Tools to mount ISO.

**Comment by gave92** [comment]
@tsvietOK ok I'm just mounting the iso with explorer, could you check if that works?
I'll test with daemon tools.

**Comment by tsvietOK** [comment]
@gave92 Same behavior when mounting with explorer.

**Comment by gave92** [comment]
@tsvietOK with the latest commit also works for daemon tools for me.
Have you been testing with debug or release version?

**Comment by tsvietOK** [comment]
@gave92 Debug version.

**Comment by tsvietOK** [comment]
@gave92 Now ISO ejecting works fine for explorer and Files. Can you do the same for flash rives? One issue remains, when mounting ISO disk name doesn't updating.

**Comment by gave92** [comment]
@tsvietOK flash drives should be already be working on master (added/removed from list when connected/disconnected). What are you experiencing?

**Comment by tsvietOK** [comment]
@gave92 When pressing eject on flash drive, it is successfully ejects, but Files keeps this drive in sidebar.

**Comment by gave92** [comment]
@tsvietOK drive name on sidebar and main page should now update when inserting/ejecting an ISO
Regarding removable drives: I have no issues with them sorry, even on master: when I physically disconnect them from pc they disappear from the list

**Comment by tsvietOK** [comment]
@gave92 When i say "eject" i mean ejecting, not disconnecting.

When mounting ISO through explorer and:
- unmounting through Files drive still in sidebar list
image

- unmounting through explorer drive removed from list <--- as it should be.

**Comment by tsvietOK** [comment]
About flash drive. Drive ejected but still connected:
image
Files shows this drive.
image
Explorer doesn't.

**Comment by gave92** [comment]
@tsvietOK 
1) For removable drives (e.g pen drive): clicking eject does not remove from list -> normal, does not remove from explorer either
2) For ISO drives: clicking eject from Files does not remove from list -> "normal", explorer will also show an empty drive
(2) indicates an issue with how we eject drives, not with this PR

**Comment by tsvietOK** [comment]
@gave92 About 2. When mounting an ISO through explorer, and ejects through explorer, it will not show an empty drive.

**Comment by gave92** [comment]
@tsvietOK But if you eject the ISO from Files, will explorer show an empty drive?
If yes, the issue is in the code we use to eject the drive, not in how we update the list (this PR)

**Comment by tsvietOK** [comment]
> @tsvietOK
> When mounting an ISO through explorer, and ejects through explorer -> does Files remove the drive from the list?

Yes.

> When mounting an ISO through explorer, and ejects through _Files_-> will explorer still show an empty drive?
> If yes, the issue is in the code we use to eject the drive, not in how we update the list

Yes.

I think drives list should be updated automatically when you eject drive. Maybe exist other way to eject drive.

**Comment by gave92** [comment]
Yeah atm I have no clue on how to do that, but I'm sure the author of PR #2328 will find a solution :)
What I can do in this PR is disable the "eject" item for ISO/CDROM drive.. what do you think?

**Comment by tsvietOK** [comment]
@gave92 Why? Eject function working with ISO better than with flash drives.

**Comment by gave92** [comment]
What? From what you said above I thought the issue was with ISO drives
> When mounting an ISO through explorer, and ejects through Files the drive remains in both Files and explorer

**Comment by tsvietOK** [comment]
@gave92 When ejecting drives, Files keeps them in list with original name, it will be removed when you disconnect drive. While Explorer successfully ejects drive and hides it.

Summary about ISO. 
When mounting through Daemon tools, drive added successfully. 
Ejecting through Files working (with empty drive in both explorer and Files). <-- normal
Ejecting through explorer working (with empty drive in both explorer and Files). <-- normal

When mounting through explorer, drive added successfully. 
Ejecting through Files working (with empty drive in both explorer and Files). <-- not normal
Ejecting through explorer working (without empty drive in both explorer and Files). <-- normal

About your PR. I think it is not only about ISO, VHS etc.. You changing device watcher system, so it could be fluent to other drives (flash). So if you successfully added "update" system when ISO drives are added/ejected, i thought you can add the same system for flash drive if possible. If not, it is not a problem, maybe problem is in eject algorithm.

**Comment by gave92** [comment]
@tsvietOK sorry I'm still confused, I'll think on it tomorrow :)

**Comment by gave92** [comment]
OK this is what I'm getting after the latest changes:

[DAEMON TOOLS LITE]
- adding a new virtual drive -> works, new cd drive is added to Files
- removing a virtual drive -> works, cd drive is removed from Files
- mounting an iso -> works, drive name is updated in Files
- unmounting an iso from Files -> works, drive name is updated in Files
- unmounting an iso from Explorer -> works, drive name is updated in Files
- unmounting an iso from DaemonTools tray -> works, drive name is updated in Files

[ISO MOUNTED IN EXPLORER]
- mounting an iso -> works, new cd drive is added to Files
- unmounting an iso from Explorer -> works, cd drive is removed from Files
- unmounting an iso from Files -> **doesn't work**, name changes but cd drive is not removed from Files *and Explorer*

[USB DRIVES]
- connecting a new device -> works, new device is added to Files
- physically detaching a device -> works, device is removed from Files
- ejecting device from taskbar -> works, device is removed from Files
- ejecting device from Files -> **doesn't work**, device is not removed from Files *and Explorer*
- ejecting device from explorer -> **doesn't work**, device is not removed from Files *but is removed from Explorer*

**Review by tsvietOK — APPROVED** [review]

**Pull request merged**
