### PR TITLE
Dual pane improvements

### LINKED ISSUE #2941: Ability to close second pane
**Is your feature request related to a problem? Please describe.**
When I need to do some stuff with the secondary pane, I'd love to close it again without having to open a whole new tab.
I tried my best but can't find a way to close secondary panes again

**Describe the solution you'd like**
Either a small X somewhere, or when you right click a free space, it would say "close secondary pane"
Alternatively / additionally: Resizing a secondary pane to the very far right / left will also close it

### LINKED ISSUE #4343: Crash when opening a folder beyond 255 path character limit.
**Expected behaviour**
It should give an in app error saying that the path character limited has been reached.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6217640/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6217641/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: 1.5.2.0

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #2941
- Fixes #4343

**Details of Changes**
Add details of changes here.
- Fixed an issue causing crash on path longer than 255 chars
- Added a close button for second pane
- Fixed sidebar not displaying selected item for path opened in second pane 
- Fixed an issue for which "open in second pane" button did not appear in sidebar and bundles

**Screenshots**
@yair100 there are a few issues about how closing the second pane is not intuitive. What do you think of this solution? Added a bar with folder name + close button (bar is collapsed when only one pane is open). Or is it better to add the close button to the toolbar like the toggle for the "Preview" pane? This solution would still work if/when we add support for more than 2 panes.

image

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 Instead of a dedicated button, can you just set the menu item to close the focused pane? This will be useful for when we add support for more panes.

**Comment by gave92** [comment]
The  the menu item in the "..." menu in the toolbar?

**Comment by yaichenbaum** [comment]
> Which menu item_ The one in the "..." menu in the toolbar?
> image

That one, and we can also add one to the right click menu.

**Comment by gave92** [comment]
Update: toolbar menu when pane is open
image

**Comment by yaichenbaum** [comment]
@gave92 It looks like the close pane menu item is always closing the right pane even when the left pane is active. It also looks like the border is on the bottom instead of the sides of the pane.

**Comment by gave92** [comment]
Can't close the left pane, I'm not adding this in the PR.
Moved the border to the bottom on purpose, why was it moved to the left? It looks pretty ugly and doesn't tell which pane is active doesn't it?

**Comment by yaichenbaum** [comment]
@gave92 It was moved to the middle to get ready for supporting more panes.

**Comment by gave92** [comment]
If you're sure.. =) Moved the border back.

**Comment by yaichenbaum** [comment]
@gave92 I'm fine with either way 😂

**Comment by esibruti** [comment]
I had an idea but I don't know if it already exists in Files: could there be a button to make that subpanel a new tab or a new window? I think it would be interesting to put this feature, if it doesn't already exist.

**Comment by phyllybb** [comment]
Ok I’m sorry

**Comment by phyllybb** [comment]
Ok what is that

**Comment by phyllybb** [comment]
My phone is so messed up
Im going to buy a mew one today

**Comment by yaichenbaum** [comment]
> @gave92 I had an idea but I don't know if it already exists in Files: could there be a button to make that second pane a new tab or a new window? I think it would be interesting to put this feature, if it doesn't already exist.

@esibruti If you want, you can open a new issue to start a discussion.

**Comment by esibruti** [comment]
> > @gave92 I had an idea but I don't know if it already exists in Files: could there be a button to make that second pane a new tab or a new window? I think it would be interesting to put this feature, if it doesn't already exist.
> 
> @esibruti If you want, you can open a new issue to start a discussion.

@yair100 Created right now: #5251

**Comment by winston-de** [comment]
Regarding the active pane indicator position, maybe we should try and replicate what Terminal does.
image

**Review by winston-de — APPROVED** [review]
Also LGTM

**Comment by yaichenbaum** [comment]
@gave92 are you sure #2941 was resolved by this?

**Comment by gave92** [comment]
It says "I tried my best but can't find a way to close secondary panes". Adding the close button pane to the "..." menu should solve this.

**Comment by yaichenbaum** [comment]
@gave92 Oh right, it's the first pane that can't be closed right now, is that correct?

**Comment by gave92** [comment]
Yeah, you can currently only close the secondary/right pane.

**Pull request merged**
