### PR TITLE
Fix: Fixed potential COMException when setting the wallpaper

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- Fixed com exception when setting wallpaper

`System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {C2CF3110-460E-4FC1-B9D0-8A1C0C9CC4BD} failed`

### CODE REVIEW

**Review by hishitetsu — COMMENTED** [review]
Wouldn't it be better to modify `SetSlideshow` in the same way?

**Review by hishitetsu — COMMENTED** [review]
You might want to make the same correction to `LockScreen.SetImageFileAsync` just to be safe.

**Comment by yaira2** [comment]
> You might want to make the same correction to `LockScreen.SetImageFileAsync` just to be safe.

I thought about it, but it's a different API. It might be worth leaving this alone in case there is an issue that needs to be handled differently.

**Review by hishitetsu — APPROVED** [review]
LGTM

**Pull request merged**
