### PR TITLE
Select Items using Space key #2310

### PR DESCRIPTION
**Pull request by oleitao**
**Details of Changes**
Add details of changes here.
- Added feature to use space key to select items (next file/folder)

test1

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao This PR isn't quite how the feature is meant to work, instead of selecting the next item, the space key is meant to select the first item in the list when it's not focused.

**Comment by josh-65** [comment]
Isn't this going to conflict with quick look also

**Comment by yaichenbaum** [comment]
> Isn't this going to conflict with quick look also

It shouldn't.

**Comment by oleitao** [comment]
Is required any corrections or that PR it's ok?

**Comment by yaichenbaum** [comment]
@oleitao Can you merge the latest from `main` so I can test the changes?

**Comment by oleitao** [comment]
> @oleitao Can you merge the latest from `main` so I can test the changes?

yes, i can merge

**Comment by yaichenbaum** [comment]
@oleitao This PR still doesn't work as expected, are you still working on this change?

**Comment by oleitao** [comment]
> @oleitao This PR still doesn't work as expected, are you still working on this change?

Yes, i will

**Pull request closed without merging**
