### PR TITLE
Merging my fork (Column View) with current master (files-community)

### PR DESCRIPTION
**Pull request by TyJOrtiz**

### CODE REVIEW

**Comment by TyJOrtiz** [comment]
Referencing #2500

**Comment by d2dyno1** [comment]
There are some big issues with this PR, mainly the old changes have been reverted while resolving conflicts. A lot have changed since you've opened ColumnView PR. I recommend you closing this PR, forking fresh, newest Files repo and copy existing ColumnView code over to new PR.

@TyJOrtiz

**Comment by d2dyno1** [comment]
For reference, this is an old change and should not be reverted. Probably resolve conflicts error:

https://github.com/files-community/Files/pull/3769/files#diff-5c7016f6890cdc950358f28dbc28c1c51825d7e03c41f499b820375bf30484e4R5

**Comment by TyJOrtiz** [comment]
Ok, I've downloaded the latest repo and I'm in the process of copying over code. I can't give any guarantees but I should be finished by the end of the week

**Pull request closed without merging**
