### PR TITLE
Implement filesystem watching via ReadDirectoryChangesW

### PR DESCRIPTION
**Pull request by lukeblevins**
This requires extensive testing as it may have introduced a few bugs.

### CODE REVIEW

**Comment by tsvietOK** [comment]
Random crash when navigating to a folder still exists and VS can't catch an exception. 

Files and folders are not sorted.
image

After folder creation or renaming there 3 or more folders displaying, fixes by folder refresh. For files the same.
Rename_1

**Comment by XPoppyX** [comment]
> After folder creation or renaming there 3 or more folders displaying, fixes by folder refresh. For files the same.

also when pasting a file/folder

**Comment by duke7553** [comment]
Thanks for the feedback everybody. I'll make it a priority to fix these. Keep up the testing!

**Comment by gave92** [comment]
@duke7553 Just a curiosity: There is the [FileSystemWatcher](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=netcore-3.1) class which *I think* is supported in UWP when you use the desktop bridge. It's basically a convenience class that calls ReadDirectoryChagesW internally. Have you considered using this instead of doing the stuff "low level"?

**Comment by duke7553** [comment]
@gave92 Personally, I'm trying to keep as much core functionality as possible outside the Full Trust component. This is because FullTrust components are not supported in Windows 10X.

**Comment by gave92** [comment]
I meant: I think that FileSystemWatcher is supported in UWP.

**Comment by duke7553** [comment]
@gave92 Good thought. Unfortunately, .NET Classes are unable to access brokered filesystem locations which WinRT apps use, which means we have to do it the native way.

**Comment by gave92** [comment]
@duke7553 thanks for the clarification. I thought that `broadFileSystemAccess` was enough to bypass this.

**Comment by lukeblevins** [comment]
@yair100 @tsvietOK @gave92 This is ready for review. If at all possible, we should review this one quickly before the next release.

**Review by tsvietOK — CHANGES_REQUESTED** [review]

**Review by tsvietOK — APPROVED** [review]

**Review by yair100 — APPROVED** [review]

**Comment by gave92** [comment]
@duke7553 refreshing + renaming still has some issues for me:

 >2020-06-11 07:47:45.2148|ERROR|Files.App|Collection was modified; enumeration operation may not execute.|System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at Files.Filesystem.ItemViewModel.<>c__DisplayClass72_0.<WatchForDirectoryChanges>b__0(IAsyncAction x)
--- End of stack trace from previous location where exception was thrown ---
   at Files.Filesystem.ItemViewModel.WatchForDirectoryChanges(String path)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**Pull request merged**
