### PR TITLE
Code Quality: Only execute actions once

### PR DESCRIPTION
**Pull request by HorseBandit**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #13397...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. hold ctrl+t to open a new pane
   3. notice that no actions allow continuous execution

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by HorseBandit** [comment]
@yaira2 Following your advice, here's the new branch and new PR for this issue.

**Comment by yaira2** [comment]
Interesting that the app still crashes in the automation tests. I can confirm they pass locally.

**Comment by yaira2** [comment]
Fyi @chingucoding and ideas?

**Comment by chingucoding** [comment]
Sorry for the delayed response, the issue is that the button to create a new folder seems to be disabled now:
Screenshot of desktop folder action bar

Since the test wants to create a folder using that button, it crashes.

**Comment by HorseBandit** [comment]
@yaira2 @chingucoding 

Is this caused by my changes to the files? The test result is the same for 'main'. Do I need to fix something or is the test itself having issues?

**Comment by yaira2** [comment]
@HorseBandit I believe so, this appears to be an issue only with these changes.

**Comment by chingucoding** [comment]
I think the issue is that the properties of the actions are now being wrapped using a control that cannot notify the UI of changes to the properties. So if "CanExecute" changes on the action, the debounce wrapper does not tell the UI that this happened as such, the UI won't update. In the case of our test, all the buttons in the quick items bar don't update resulting in all of them being disabled.

**Comment by HorseBandit** [comment]
@chingucoding @yaira2 

The 'new' button isn't clickable from the 'main' branch. Can we confirm that the changes in this PR broke something that worked properly in 'main'? I am not seeing that to be true. Open a few tabs with ctrl + t, close them, notice the 'new' button isn't selectable on 'main'.

**Comment by yaira2** [comment]
@HorseBandit have you considered an approach where the debounce timer is within the `ExecuteAsync` method in CommandManager?

**Comment by yaira2** [comment]
@HorseBandit

**Pull request closed without merging**
