### PR TITLE
Fix: Fixed sidebar context menu items not showing for recent files

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fixes a bug in #11204 where the context menu items in the sidebar would not show up

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]
lgtm

**Comment by yaira2** [comment]
This is causing the app to hang wen right clicking on recent files.

**Comment by hecksmosis** [comment]
This doesn't affect recent files, it's only modifying the sidebar

**Comment by yaira2** [comment]
The issue was resolved by @hishitetsu

**Pull request merged**
