### PR TITLE
Show permanent deletion warning if bin is full

### LINKED ISSUE #1768: Show permanent deletion warning
**Is your feature request related to a problem? Please describe.**
If I close the delete confirmation, the app will not confirm even if I delete a very big file or folder that cannot put it in the recycle bin. However, Windows explorer will warn you that this action will delete the file or folder permanently.

**Describe the solution you'd like**
When the file will be permanently deleted, I hope the app to warn the users regardless of whether the users turn on the delete confirmation.

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #1768

**Details of Changes**
Add details of changes here.
- Show system permanent deletion warning if a file is going to be permanently deleted instead of recycled (e.g in case of full recycle bin)

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by winston-de** [comment]
I tried deleting a 5gb file, and no warning about permanently deleting was displayed and permanently delete was not checked, however it was not placed in the recycle bin.

**Comment by gave92** [comment]
Removable drive?

**Comment by winston-de** [comment]
Yeah, is it not supposed to display then?

**Comment by gave92** [comment]
What kind of removable drive? Just a usb key or a phone or something? Do you know of shell file operations work there or of StorageFile operations are used? Could you retry with the latest commit?

**Comment by winston-de** [comment]
It's an sd card, and yeah it's using the ftp for file operations. With the latest commit it still just deletes permanently without warning.

**Comment by gave92** [comment]
Thanks @winston-de could you verify that with the latest commit you still don't get a warning but the files are not deleted from removable drives unless you tick the "permanent delete" dialog option?

**Review by winston-de — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 thank you!

**Pull request merged**
