### PR TITLE
Enable app elevation when deleting files

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**

Do not ask for elevation when deleting shortcuts.

**Details of Changes**

Enable request for elevation when deleting protected files.

**Validation**

How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@gave92 Can you resolve the merge conflicts?

**Comment by tasty0tomato** [comment]
Why not merge this to release 1.5?

**Comment by gave92** [comment]
@tasty0tomato this has been included in 1.5 👍

**Comment by tasty0tomato** [comment]
@gave92  Sorry, my _Files_ is still version 1.3. It seems that Microsoft Store have not updated it. Waiting for the update!

**Comment by gave92** [comment]
No problem, and store approval for 1.5 may take a while due to this change.

**Pull request merged**
