### PR TITLE
Refactor code to prepare for multi-panes

### PR DESCRIPTION
**Pull request by cinqmilleans**
**Resolved / Related Issues**
The code was designed to use only one type of right panel, the preview pane. The nomenclature, settings, view models, events have not been designed to display others. You should have a generic pane that can display the preview or other content.

**Details of Changes**
This pr refactors to make it very easy to display other content in the right panel. Only one panel can be displayed.
The code is modified a lot to change names and structure I tried, as always, to make the code cleaner than I found.

Unfortunately, the settings names have been changed and the user will lose the previewpane settings. Apart from that, there is no change for users, only for developers.

This pr is new version of #7892 because the base code had changed too much. I don't use the infrastructure branch because it doesn't compile.

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@cinqmilleans besides for the preview pane, do you think there is a pane that will be kept open across app sessions?

**Comment by cinqmilleans** [comment]
@yair100 I don't know, anything is possible. You can make panels for everything: image editing, editing mp3 tags, renaming several files at once, ....

**Comment by d2dyno1** [comment]
Batch select :eyes:

**Review by yair100 — APPROVED** [review]

**Comment by R3voA3** [comment]
> @cinqmilleans besides for the preview pane, do you think there is a pane that will be kept open across app sessions?

A drop folder where I can collect Items until I am ready to move them. Just a quick idea.

**Review by d2dyno1 — APPROVED** [review]

**Pull request merged**
