### PR TITLE
Added ability to close and open sidebar by resizing it

### LINKED ISSUE #4981: Ability to close sidebar by dragging
**Is your feature request related to a problem?**
right now we can close dual panel with drag behaviour. why we not do the same with sidebar, like finder macos do.

**Describe the solution**
ezgif-6-6a57cf1063e2

**Describe alternatives you've considered**
-

**Scope**

| Capability | Priority |
| :---------- | :------- |
| This proposal will collapse the sidebar when resizing it to have no width | Must |

**Additional comment**
-

### PR DESCRIPTION
**Pull request by winston-de**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #4981

**Details of Changes**
Add details of changes here.
- Added ability to close and open sidebar by resizing it
- Added constant for minimum sidebar size
- Added visual effects for drag and hover over sidebar resizer
- Fixed only being able to drag sidebar by border

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

https://user-images.githubusercontent.com/59544401/119286171-94f06c80-bbf8-11eb-8a5f-490179a96bbe.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de Is the resize janky on your end?

**Comment by winston-de** [comment]
Yeah a bit, I thought it may have just been my computer. I'll try and improve it.

**Comment by mdtauk** [comment]
Not sure how possible it is, but it feels like the sidebar resizing should snap to the closed state, when dragged below a minimum width.

If there is also a maximum width, the same should probably apply after the threshold is reached, when resizing outward.

**Comment by winston-de** [comment]
> Not sure how possible it is, but it feels like the sidebar resizing should snap to the closed state, when dragged below a minimum width.

That's what it does now, unless I'm misunderstanding what you're saying.

> If there is also a maximum width, the same should probably apply after the threshold is reached, when resizing outward.

I don't quite understand what you mean by this....

**Comment by winston-de** [comment]
@yair100 It looks like the jankiness was already there before this PR. I think it's caused by binding directly to the ``SidebarWidth`` app setting directly and updating it on manipulation delta, leading to a lot of calls to get and set app settings. I'm working on improving it though.

**Comment by yair100** [comment]
> @yair100 It looks like the jankiness was already there before this PR. I think it's caused by binding directly to the `SidebarWidth` app setting directly and updating it on manipulation delta, leading to a lot of calls to get and set app settings. I'm working on improving it though.

Interesting, it must have been introduced with all the recent refactoring around the sidebar, I'm glad we found it now!

**Comment by yaichenbaum** [comment]
@winston-de are you still working on this?

**Comment by winston-de** [comment]
> @winston-de are you still working on this?

Yes, I'll have it done within a few days.

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@winston-de Can you resolve the merge conflicts and test these changes with the keyboard?

**Pull request merged**
