### PR TITLE
[TEST ONLY] - Fix release crash

### LINKED ISSUE #4117: Bug report: Crash in release mode
```
Failed to assign to property 'Microsoft.UI.Xaml.Controls.IconSource.Foreground'. [Line: 13606 Position: 45]|Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Failed to assign to property 'Microsoft.UI.Xaml.Controls.IconSource.Foreground'. [Line: 13606 Position: 45]
```

### PR DESCRIPTION
**Pull request by gave92**
Fixes #4117

### CODE REVIEW

**Comment by gave92** [comment]
@yair100 this is just for test, not ready to review it yet. Anyway after "WinUI 2.6 Preview (#4090)" I can't even start the app in Debug mode. Is it just me?

**Comment by winston-de** [comment]
> @yair100 this is just for test, not ready to review it yet. Anyway after "WinUI 2.6 Preview (#4090)" I can't even start the app in Debug mode. Is it just me?

For me, it works in debug, but not in release.

**Comment by gave92** [comment]
Noope with WinUI 2.5 everything is fine but with 2.6 it crashes in Release Mode when setting the FontIcon foreground. 
You can revert #4091 (ideaaly you should only revert changes to StatusBarControl.xaml, the rest should be kept)

**Comment by yaichenbaum** [comment]
@gave92 Do you think we are missing something in the default.rd.xml file?

**Comment by gave92** [comment]
@yair100 I do not know. We need to test release mode a bit with 2.6 since what I was doing in #4091 looks pretty ordinary to me.

**Pull request closed without merging**
