### PR TITLE
Feature: Added media file resolution to the details pane

### LINKED ISSUE #5075: Feature: Added resolution info to details pane
### What feature or improvement do you think would benefit Files?

Add the file resolution to the file information in preview mode, and also let the user choose what information to display in this mode.

image

### Files Version

2.3.11.0

### Windows Version

10.19043.1899

### Comments

_No response_

### PR DESCRIPTION
**Pull request by puppetsw**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5075

Partially closes #5075. There is a request to allow users to customise the information in the details pane which hasn't been implemented here.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
image

### CODE REVIEW

**Review by yair100 — DISMISSED** [review]
LGTM

We still need to work on a UI for editing data in the preview pane, let me know if you're interested.

**Comment by puppetsw** [comment]
> LGTM
> 
> We still need to work on a UI for editing data in the preview pane, let me know if you're interested.

@yair100 I'm interested in working on this. Do you have any thoughts/concepts for how it will look?

**Comment by yaira2** [comment]
@puppetsw I think that if a user makes any changes, there should be a cancel and save button at the bottom of the details pane.

**Pull request merged**
