### PR TITLE
Fix: Fixed issue where properties window was always on top

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Fixed issue where properties window was always on top

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by gave92** [comment]
Didn't we have a problem where Properties would open behind Files?

**Comment by yaira2** [comment]
The issue is back (can't reproduce it consistently) but it introduced a bigger problem where the window was on top of everything else. This was most noticeable when trying to open the advanced permissions window.

**Comment by gave92** [comment]
I think the idea was to put the window always on top only for a short time as a workaround, but we removed/ forgot the code to make it stop being on top after open.
Perhaps reopen tbe old issue regarding opening behind if any?

**Comment by yaira2** [comment]
https://github.com/files-community/Files/issues/9926

**Comment by ferrariofilippo** [comment]
Just checked the commit history and it seems that the line you removed (`IsAlwaysOnTop = true`) was added in #10294 
I think we could solve this problem implementing @gave92 solution proposed in #9973

**Comment by gave92** [comment]
Oh you're right, I assumed that setting "alwaysontop" was the fix for #9926 but it wasn't. The fix from #9973 is still in place and appears to be working. I can't repro #9926 even after removing "alwaysontop".

**Pull request merged**
