### PR TITLE
Update Turkish Translation of "Drivers"

### PR DESCRIPTION
**Pull request by cotur**

### CODE REVIEW

**Review by tsvietOK — CHANGES_REQUESTED** [review]
Don't update translation via `Resources.resw` file, do it through appropriate file in `MultilingualResources` folder, `Resources.resw` file will be regenerated automatically.

**Comment by yaichenbaum** [comment]
@cotur You can find more information about working with translations over [here](https://files-community.github.io/docs/#/articles/translating-files).

**Comment by cotur** [comment]
Sorry I didn't know that,

There are some new translation also, I will update PR with all TR translations.

**Comment by yaichenbaum** [comment]
@cotur Feel free to reopen this pull request when you get a chance to update it.

**Comment by cotur** [comment]
@yair100 I've created a new PR for updating TR Locazliation
https://github.com/files-community/Files/pull/3752

**Comment by yaichenbaum** [comment]
@cotur Thank you!

**Pull request closed without merging**
