### PR TITLE
Code Quality: Updated commit message in `crowdin.yml` to match contribution guidelines

### PR DESCRIPTION
**Pull request by Lamparter**
**Resolved / Related Issues**

I resolved that this was too small a change to make it worth opening an issue.

**Steps used to test these changes**

N/A

---

I noticed that the commit message for Crowdin resource sync in `crowdin.yml` did not match that of Files's contribution style, which requires that each commit be in the present tense and not be lower case.

### CODE REVIEW

**Review by yaira2 — DISMISSED** [review]
LGTM

**Comment by yaira2** [comment]
Is there a way to set the PR title to "Code Quality: Updated translations"?

**Comment by 0x5bfa** [comment]
As far as I know, no. This is just commit message and it's fine as is.

**Comment by Lamparter** [comment]
I'm quite sure there is, it's also possible to change the branch name (in FluentHub it's `crowdin/locale`).

**Comment by 0x5bfa** [comment]
WHAT I'm pretty sure there wasn't before. It's great then.

**Review by yaira2 — APPROVED** [review]

**Pull request merged**
