### PR TITLE
After pasting, focus all pasted files/folders instead of just one

### LINKED ISSUE #8333: Focus on new items after pasting
### Description

Hi,

In Windows Explorer from Windows 10 or 11, whenever I copy files or folders, the focus is to the copied files or folders.
In Files 2.0, this doesn't happen.

Thanks

### Steps To Reproduce

Copy files or folders from one folder to another.

### Expected behavior

After copying, the focus on the destination folder should be on the copied files or folders.

### Files Version

2.1.13.0

### Windows Version

Windows 11 21H2

### Relevant Assets/Logs

N/A

### PR DESCRIPTION
**Pull request by IgorKordiukiewicz**
**Resolved / Related Issues**
Fixes #8333 

**Details of Changes**

**Validation**
How did you test these changes?
- [x] Built and ran the app

Before:

https://user-images.githubusercontent.com/25117425/171063890-7f921d9c-7468-466e-80b1-3b69584bf49e.mp4

After:

https://user-images.githubusercontent.com/25117425/171063899-223eb360-da14-43b5-9dd4-38164e631681.mp4

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@IgorKordiukiewicz thank you for the pr, can you check the validation check box in the PR description?

**Comment by IgorKordiukiewicz** [comment]
> @IgorKordiukiewicz thank you for the pr, can you check the validation check box in the PR description?

Updated

**Review by puppetsw — APPROVED** [review]
LGTM

**Review by yaichenbaum — APPROVED** [review]

**Comment by IgorKordiukiewicz** [comment]
Well, it kind of gets reset every time the `ProcessOperationQueue` is called sine its created there, so I don't think this will be a problem and I didn't notice this bug happening.

**Comment by puppetsw** [comment]
> I believe this introduces a bug where future pastes will focus on the previous ones since we never reset the `itemsAdded` list. This may be a little tricky to fix since we flatten out multi-paste operations into sequential ones.

I didn't notice this bug happening during testing, are you able to provide steps?

**Comment by puppetsw** [comment]
> Sure, a way to reproduce is to copy and paste some files, and then in the same directory, copy and paste some other files. You'll see the previous paste will be included as well. I've prepared a gif that demonstrates this issue.

Ah thank you. I was misunderstanding the method to replicate.

**Pull request merged**
