### PR TITLE
Fix: Fixed an issue where an invalid Git Remote would cause a crash

### LINKED ISSUE #13048: Bug: Invalid Git Remote crashes app
### Description

When a Git repository contains a remote that no longer is valid (e.g. repo deleted), the app crashes. Worst case is that the app tries to open the same folder on startup and crashes again.

Exception:

Screenshot of debugger inspecting uncaught exception "... is not a valid remote"

### Steps To Reproduce

1. Open a repository with invalid Git Remotes

### Requirements

- e.g. Fix crash that occurs when...
Should not crash

### Files Version

Commit: 75e41fafe7099e089a30f5b325b617b09aab9d0e

### Windows Version

22621.1992

### Log File

I can send them if requested.

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #13048 

**Possible Improvements**
At the moment this PRs only prevent the crash.
- Should we show a warning when there's an invalid remote?
- If the invalid remote is the current head, what should we do? Checkout to the first valid branch? Do not show any git info at all? (If the head is invalid we can't get its name and all the other infos [we do not know which branch is the head])

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app 
   2. Invalidate a git repo (I changed the last component of `ref: refs/...` to a `.` of the file `.git/HEAD`  )
   3. Open that git repo

### CODE REVIEW

**Comment by ferrariofilippo** [comment]
> Possible Improvements
At the moment this PRs only prevent the crash.

> Should we show a warning when there's an invalid remote?
If the invalid remote is the current head, what should we do? Checkout to the first valid branch? Do not show any git info at all? (If the head is invalid we can't get its name and all the other infos [we do not know which branch is the head])

@yaira2 what do you think?

**Comment by yaira2** [comment]
If the remote is invalid, do the local branches still work?

**Comment by ferrariofilippo** [comment]
> If the remote is invalid, do the local branches still work?

At the moment I can only reproduce the bug when the `HEAD` branch is invalid. In this case you can't do anything: you have no active branch (if the branch is invalid you can't check if it's the `HEAD`) and so `git status bar` is not shown

**Comment by ferrariofilippo** [comment]
@yaira2 I did some more testing:
- if the head is invalid we can't do anything (except showing a warning) [see above]
- if there are issues with a remote, after handling the exception, everything works well local-side (you can switch branch and the repo seems fine, but you can't get `ahead by/behind by`). I'll check what happens when you try to fetch/push/pull

**Comment by ferrariofilippo** [comment]
> * if the head is invalid we can't do anything (except showing a warning) [see above]
> * if there are issues with a remote, after handling the exception, everything works well local-side (you can switch branch and the repo seems fine, but you can't get `ahead by/behind by`).
>   I'll check what happens when you try to fetch/push/pull ->It fails and shows `git pull/push timeout error`, we should add a specific warning

Do you have any better ideas?

**Comment by yaira2** [comment]
Let's go with handling the exception without displaying a warning. If it becomes confusing in the future, we can add a warning.

**Comment by yaira2** [comment]
@ferrariofilippo can you fix the merge conflict?

**Review by yaira2 — DISMISSED** [review]

**Review by 0x5bfa — APPROVED** [review]
LGTM, in terms of the codebase. Thank you!

**Pull request merged**
