### PR TITLE
Fix: Fixed issue with resizing the status column

### LINKED ISSUE #10432: Feature: Allow resizing the status column
### Description

`Status` column cannot be resized by the user.

### Steps To Reproduce

1. Open OneDrive folder
2. Try to resize `Status` column

### Steps to fix

User should be able resize Status column

### Files Version

Version: 2.3.55.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 Home Version 22H2 22621.755

### Relevant Assets/Logs

Headers

### LINKED ISSUE #11103: Bug: Recycle bin original path and data deleted columns are set to 0 width
### Description

When I edit any column in details view out of the recycle bin original path and date deleted will be set to 0

### Steps To Reproduce

1. Turn off Files settings > Folder > Enable overriding folder preferences in individual directories
2. Go to recycle bin and set either original path or date deleted
3. Go to any other folder and edit size of a column
4. Go back to recycle bin and see both columns at 0 width

### Steps to fix

- Keep width of columns when others are edited.

### Files Version

2.4.25.0

### Windows Version

10.0.22621.1105

### Log file

[debug.log](https://github.com/files-community/Files/files/10527647/debug.log)

### PR DESCRIPTION
**Pull request by ferrariofilippo**
…olumns

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #11103 
- Closes #10432
- Related #10585 
- Related #10560
- Related #10117
- Related #10239

**Comments**
- I added a null check in `Win32Shell` to avoid an exception that was getting me mad
- To fix this bug we need to save the default size only when the column is visible. We have two ways to achieve this:
  - We can check if each column is actually visible (is not collapsed and has width > 0) -> This is what i proposed in this PR
  - We can use the less readable and less understandable, but faster approach I first proposed in #10117 (see `Unresolved Conversation`). I may add a comment to the first width setter that specify when width = 0

Let me know what you think

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Review by QuaintMako — APPROVED** [review]

**Comment by yaira2** [comment]
How is it different than any of the other columns that can be collapsed?

**Comment by ferrariofilippo** [comment]
> How is it different than any of the other columns that can be hidden, can't we reuse the logic?

The problem was that `Hidden` columns were not `Collapsed`, and so their sizes were saved. I changed the logic so that when a column is hidden it's collapsed too.

**Comment by yaira2** [comment]
Does this fix #11025?

**Comment by ferrariofilippo** [comment]
> Does this fix #11025?

It doesn't

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
