### PR TITLE
Add support for selecting multiple items in the recents widget #3677

### PR DESCRIPTION
**Pull request by oleitao**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes ([#3677](https://github.com/files-community/Files/issues/3677))

**Details of Changes**
Add details of changes here.
- Added feature to select multiple items on recent opened files (Home). Open multiple folder file location. Clean more than one item from recent opened files.

**Validation**
How did you test these changes?
- [x] Select multiple recent files 
- [x] Clean multiple recent files 
- [x] Open folders location of multiple recent files

**Screenshots (optional)**
Capture3

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@oleitao Are the checkboxes necessary or does a long tap also work to select an item?

**Comment by winston-de** [comment]
This seems to interfere with the "open items with a single click" setting, as in when you click an item with it enabled it toggles selection instead of opening it.

**Comment by oleitao** [comment]
> @oleitao Are the checkboxes necessary or does a long tap also work to select an item?

Checkboxes are automatically implemented when i selected on ListView  to enable multi-selection. I used checkboxes to simplify the interaction with items.

**Comment by oleitao** [comment]
> This seems to interfere with the "open items with a single click" setting, as in when you click an item with it enabled it toggles selection instead of opening it.

@yair100 , @winston-de  i think that issue should be discussed because that  "open items with a single click" is incompatible with items multi-selection.

**Comment by winston-de** [comment]
I don't think are incompatible. You can change selection mode to "Extended" (items are selected when ctrl is held) and then check if ctrl is not held before opening items on click. This is how it works in the file browsers (when multiselect is disabled).

**Comment by yaichenbaum** [comment]
@oleitao Can we get an update on this?

**Comment by oleitao** [comment]
> @oleitao Can we get an update on this?

Yes you can

**Pull request closed without merging**
