### PR TITLE
Feature: Added arm64 version 7z.dll

### PR DESCRIPTION
**Pull request by yaichenbaum**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
Added 7zip dll for arm64

**Validation**
How did you test these changes?
- Requires further validation

### CODE REVIEW

**Comment by gave92** [comment]
I also need to add some logic to load the arm version.

**Comment by yaichenbaum** [comment]
I was looking in the code but I didn't see where the dlls were being used 😂

**Comment by gave92** [comment]
Ehe, I know. Code for it is in the sevenzipsharp nuget package.

**Review by gave92 — DISMISSED** [review]

**Comment by gave92** [comment]
Not sure it works. Perhaps you can give the guy the package from azure to test before merging.

**Comment by gave92** [comment]
Confirmed working then?

**Comment by yaichenbaum** [comment]
> Confirmed working then?

Not yet...

**Review by gave92 — DISMISSED** [review]

**Comment by yaichenbaum** [comment]
@gave92 seems like I included the wrong dll file, do you know where I can find the correct file?

**Comment by yaichenbaum** [comment]
> That crash is not related to the 7z dll. It's a bug I've introduced in #9782. Remember me to fix it xD

Can this prevent users from opening 7z files on ARM64?

**Comment by gave92** [comment]
Nope, that should only happen if you open file properties window for an archive

**Comment by yaichenbaum** [comment]
Closing this for now since we don't have a working Arm64 build

**Comment by yaira2** [comment]
> I also need to add some logic to load the arm version.

@gave92 was any logic added?

**Comment by gave92** [comment]
I think so:
"return IsRunningOnArm ? "7zArm64.dll" : Environment.Is64BitProcess ? "7z64.dll" : "7z.dll";"

**Comment by yaira2** [comment]
Thank you for confirming! Where did you get the dll files for the other architectures?

**Pull request closed without merging**
