### PR TITLE
Fix issues with keyboard focus in Details view

### LINKED ISSUE #5681: Can't open folder with keyboard when only one folder is in view
### Description

When there is only one folder inside a folder and you travel with the keyboard keys and try to open the folder with the enter key, the folder isn't opened even when it is focused.

https://user-images.githubusercontent.com/7101531/128199478-eeffea91-95f8-4b6d-85a7-d85eb94b6bb9.mp4

### Steps To Reproduce

1. Create a folder
2. Create a folder inside the newly created folder.
3. Use keyboard to enter the first folder.
4. The second folder is focused, but you cannot enter it with pressing enter.

### Expected behavior

When pressing enter, the single focused folder should open.

### Files Version

v1.9.18.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

### Relevant Assets

_No response_

### LINKED ISSUE #6198: To be able to move with the arrows once i entered the folder
### What's the Problem?

I cannot move the arrows to select different files if the selection is not on one of the folders or files already

### Solution/Idea

Like file explorer, i would like to be able to allow the arrows to work directly once i'm inside the folder, without having to chose a file or a folder to start using the arrows afterwards

### Alternatives

nothing comes to mind 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

v2.0

### Windows Version

Windows 10 Pro Version	21H1 19043.1237

### Additional comment

_No response_

### LINKED ISSUE #6481: File Rename - Keyboard shortcut Ctrl-Shift moving focus out
### Description

In a file or folder, after entering rename mode (through F2 or Right-Click Rename), when we press Ctrl-Shift with Arrow keys (Left or Right) to select a word in the filename, the focus shifts out of the current file. It has to remain in the same mode for easy editing of the filenames.

### Steps To Reproduce

1. Go to any folder with a few files.
2. Click on a file, then press F2 to edit a filename say "Welcome to a new world"
3. Move the mouse to say end of the word 'to', now press Ctrl-Shift-Right Arrow (>) twice, to select the next two words.
4. You will see the focus shifting out of the edit more and out of the current file context.

### Expected behavior

Pressing Ctrl-Shift-Arrows twice should've selected the words " a new "

### Files Version

Version: 2.0.13.0 OS Version: 10.0.22000.194

### Windows Version

Windows 11 Version 21H2 (OS Build 22000.194)

### Relevant Assets

image

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #6481
- Closes #6198
- Related #4643

**Details of Changes**
Add details of changes here.
- For #4643
    - [x] Allow tab selecting columns
    - [x] Invoke headers with keyboard alone
    - [x]  Fix issue where columns can't be resized with keyboard only
- Switch back to (custom) StickyHeaderBehavior for Details view to fix Tab key behavior on header
- Allow to invoke footer button by keyboard in ListView and GridView
- Removed unused "ContextItemsChangedEventArgs.cs", "AcrylicTheme.cs"

**Known issues**
- ~Using arrow keys to modify columns width only resizes the header~
- Upon navigation the header gets focus. This is not really an issue, pressing down arrow will select the listview first item and explorer behaves similarly.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by gave92** [comment]
@winston-de could you check if you can still reproduce the bug you mentioned about StickyHeaderBehavior with this PR?

**Comment by yaichenbaum** [comment]
> Upon navigation the header gets focus. This is not really an issue, pressing down arrow will select the listview first item and explorer behaves similarly.

@gave92 if an item was already selected, will it have to focus?

**Comment by gave92** [comment]
- If an item is selected, pressing arrow down will move focus to that item
- When an item is selected "programmatically" (e.g when navigating to the parent folder) it will have focus too

**Comment by yaichenbaum** [comment]
@gave92 #5681 still seems to be an issue when opening a directory from the sidebar that only has one item in it.

**Comment by gave92** [comment]
@yaichenbaum in which layout modes?

**Comment by gave92** [comment]
@yaichenbaum this PR fixes #5681 for details view only. PR #7425 fixes it for the other modes. In which layout modes do you see the issue?

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
