### PR TITLE
Tabs now display the correct string for new tabs

### PR DESCRIPTION
**Pull request by yair100**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@tsvietOK What sort of detection is going to get messed up? I tested this and it worked fine.

**Comment by tsvietOK** [comment]
@yair100 if it works, ok, no problem. That was just my assumption.

**Comment by yaichenbaum** [comment]
@tsvietOK Can you review this pull request?

**Comment by tsvietOK** [comment]
@yair100 Yes, I can test it now

**Comment by tsvietOK** [comment]
@yair100 Now only one string not translated
image

**Comment by yaichenbaum** [comment]
@tsvietOK I wasn't able to get that one to use the string.

**Review by lukeblevins — APPROVED** [review]

**Pull request merged**
