### PR TITLE
Feature: Redesigned the app icon

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...

**Validation**
How did you test these changes?
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [x] Did you implement any design changes to an existing feature?
   - [x] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Built the app and confirmed the dev icons were working properly
   2. Renamed the preview folder to dev and confirmed the preview icons were working properly
   3. Renamed the release folder to dev and confirmed the release icons were working properly

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by 0x5bfa — APPROVED** [review]
Looks fantastic!!!

**Comment by 0x5bfa** [comment]
You can hide this comment and paste this on the your PR body.

Redesigned icons created by Files designer @mdtauk. Thank you!
image

**Comment by yaira2** [comment]
@0x5bfa that's an earlier version of the icons.

**Comment by mon-jai** [comment]
@yaira2 Maybe we should also include vector version of the icon, and put that to README instead.

**Pull request merged**
