### PR TITLE
Code Quality: Added AppLifecycleHelper class

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Code Quality: Added AppLifecycleHelper class

Reduced LOC from UI entry point. I can do as well in Program and MainWindow classes.

### Motivation & Context

- Improved readability
- Improved maintainability

### PR Checklist

- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related #4180
   Related #12340
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@yaira2 Can you review?

**Comment by yaira2** [comment]
I'd rather @d2dyno1 check this over when he has a chance.

**Comment by yaira2** [comment]
@0x5bfa why did you close this PR?

**Comment by 0x5bfa** [comment]
`App` class tend to change many times and so the PR got aoutdated.

**Pull request closed without merging**
