### PR TITLE
Handle rename correctly when only case changes

### LINKED ISSUE #3064: Rename if only change letter-case.
**Describe the bug**
Rename a file or folder that only change the letter-case.

**To Reproduce**
1. Create a folder `example`
2. Rename it with `Example`
3. Files regard the new name `Example` is conflict with the exists name, it will pop a dialog to hint this.

**Expected behavior**
Just rename it without any disturb.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - App version: 1.1.0.0

### PR DESCRIPTION
**Pull request by joergpichler**
Fixes #3064

### CODE REVIEW

**Comment by gave92** [comment]
@joergpichler thanks a lot for this PR! Could you verify if this change causes issues with undo/redo?
E.g does pressing Ctrl+Z after renaming a file (changing only case) work?

**Comment by joergpichler** [comment]
> 
> 
> @joergpichler thanks a lot for this PR! Could you verify if this change causes issues with undo/redo?
> E.g does pressing Ctrl+Z after renaming a file (changing only case) work?

Sure. It still works as expected.
2021-01-16_08h35_43

**Review by gave92 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@joergpichler Great work! LGTM

**Comment by yaichenbaum** [comment]
@joergpichler can you take a look at #7625?

**Pull request merged**
