### PR TITLE
Added uninstall action capability to package manifest

### PR DESCRIPTION
**Pull request by yaichenbaum**
Todo
- [ ] get a custom `catalog` from Microsoft for both the sideload and store version of Files
- [ ] modify the pipeline to adjust the package name CertificateSignatureHash in the sccd file
- [ ] modify the arguments to undo registry changes

### CODE REVIEW

**Comment by zhuxb711** [comment]
Good luck. It would be helpful to user if this capability is approved by Microsoft.

**Comment by Samuel12321** [comment]
Rescap Custom install actions isnt approved by MS Store

> This capability is designed for certain types of desktop PC games that are published by Microsoft and our partners. It will not be granted for other scenarios.

**Comment by yaichenbaum** [comment]
> Good luck. It would be helpful to user if this capability is approved by Microsoft.

I got it approved, I'm just having trouble building the app. Can you spot anything I did that's outright wrong (aside from the arguments that are passed to the full trust process)?

**Comment by zhuxb711** [comment]
> > Good luck. It would be helpful to user if this capability is approved by Microsoft.
> 
> I got it approved, I'm just having trouble building the app. Can you spot anything I did that's outright wrong (aside from the arguments that are passed to the full trust process)?

If Microsoft would like to approve this capability, I will take a look and try implement this capability on RX, I will share more information if I have the same trouble in building apps (If you have trouble in build app, how you submit you app to MStore?)

**Comment by zhuxb711** [comment]
> Rescap Custom install actions isnt approved by MS Store
> 
> > This capability is designed for certain types of desktop PC games that are published by Microsoft and our partners. It will not be granted for other scenarios.

I know that because I shared this capability to @yaichenbaum and just don't know if MS would like to approve it. So @yaichenbaum said he will try to do it.

**Comment by yaichenbaum** [comment]
@zhuxb711 It seems like there is more to the approval process than I originally thought, I updated the pull request description with more details.

**Comment by zhuxb711** [comment]
What is the cAI.sccd file? And why do we need customCapability?

I found an issue in [here](https://github.com/MicrosoftDocs/winrt-related/issues/168). InstallAction might be required otherwise UnstallAction will not be executed

**Comment by zhuxb711** [comment]
image
The same problem...Just don't allow to deploy

**Comment by yaichenbaum** [comment]
> What is the cAI.sccd file? And why do we need customCapability?

The sccd is what we need to get from Microsoft in order to use the custom capability. It seems that the rescap isn't enough.

> I found an issue in [here](https://github.com/MicrosoftDocs/winrt-related/issues/168). InstallAction might be required otherwise UnstallAction will not be executed

I tested without the install action and it worked fine.

**Comment by zhuxb711** [comment]
@yaichenbaum I found that you copid the Catalog from 'classicAppInstaller_WSA.scd' in 'WsaPackage_1.8.32822.0'. 
But seems no help with the deploy error. I don't know if CustomCapability is necessary because almost no guidance about that.

> DEP0700: Registration of the app failed. [0x80073CF6] error 0x80080204: While preparing to process the request, the system failed to register the windows.customInstall extension due to the following error: The Appx package's manifest is invalid.

**Comment by ADeltaX** [comment]
@zhuxb711 after various trials it seems that customInstallActions works ONLY if there is a specific custom capability, (classicAppInstaller), at the time I tested it. 

Especially because that cap (customInstallActions) was made only for MSIXVC.

Yes, to run the custom capability you need a signed custom capability descriptor file (.sccd) and I just put a random catalog in it (from WSA). Actually, only with developer mode enabled, you can put any catalog, even invalid, it will not be checked and enforced. So for testing is great but unfortunately with dev mode not enabled it will be verified and given it's not valid you know the result.

**Comment by zhuxb711** [comment]
> @zhuxb711 after various trials it seems that customInstallActions works ONLY if there is a specific custom capability, (classicAppInstaller), at the time I tested it. 
> 
> 
> 
> Yes, to run the custom capability you need a signed custom capability descriptor file (.sccd) and I just put a random catalog in it (from WSA). Actually, only with developer mode enabled, you can put any catalog, even invalid, it will not be checked and enforced. So for testing is great but unfortunately with dev mode not enabled it will be verified and given it's not valid you know the result.

Actually. I have deploy issue even debugging in VS. So that is really strange and deploying is not work for me even in dev mode.

**Comment by zhuxb711** [comment]
I make it worked. But I don't know why the fullTrustProcess could not be launched by FullTrustProcessLauncher.LaunchFullTrustProcessForCurrentAppAsync() with value does not fall in expected range exception

**Comment by yaichenbaum** [comment]
> I make it worked. But I don't know why the fullTrustProcess could not be launched by FullTrustProcessLauncher.LaunchFullTrustProcessForCurrentAppAsync() with value does not fall in expected range exception

@zhuxb711 do you have a branch with your changes?

**Comment by zhuxb711** [comment]
> > I make it worked. But I don't know why the fullTrustProcess could not be launched by FullTrustProcessLauncher.LaunchFullTrustProcessForCurrentAppAsync() with value does not fall in expected range exception
> 
> 
> 
> @zhuxb711 do you have a branch with your changes?

I created a new project for Uninstall action and it works well now. All I need is get the permission to use customInstallAction & Catalog. How could I get the catalog? Yes I have a branch for this "CustomUninstallAction"

**Comment by yaichenbaum** [comment]
@zhuxb711 I'm not sure if there is an official process to get the catalog.

**Comment by zhuxb711** [comment]
> @zhuxb711 I'm not sure if there is an official process to get the catalog.

It seems that we need to contact with Windows Technical Account Manager, but I think that is prepared for business users. Any solution?

**Comment by yaichenbaum** [comment]
@zhuxb711 we tried to get a catalog, but Microsoft doesn't want to provide one. @d2dyno1 suggested that we bundle a launcher together with Files which will install silently in the background if the user sets Files as the default file manager. The launcher will automatically revert the settings and remove itself if the user tries opening explorer and it detects that Files is no longer on the device. I think this is the safest way to make sure the settings don't corrupt Windows if the user removes Files without turning of the setting to make it the default file manager.

**Pull request closed without merging**
