### PR TITLE
Add ability to empty recycle bin from sidebar context menu

### PR DESCRIPTION
**Pull request by tsvietOK**
Align xaml markup

### CODE REVIEW

**Comment by duke7553** [comment]
Great work! I think we'll hold off on merging this one until I open the PR with the new Recycle Bin glyph icon.

image

**Comment by tsvietOK** [comment]
No problem.

**Review by yair100 — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@duke7553 Being that this pull request doesn't change anything in the menu in the screenshot above, I don't think we need to wait before merging this.

**Review by lukeblevins — APPROVED** [review]

**Comment by lukeblevins** [comment]
@yair100 Sorry about that. Accidentally requested your review again

**Pull request merged**
