### PR TITLE
Added a copy location button to the right click context menu

### LINKED ISSUE #1242: "Copy path" -button to files
Files need "Copy path" -button to the secondary menu.
Now it's possible to Copy path to the open folder via 3 dots menu.

### PR DESCRIPTION
**Pull request by jaigak**
Implements and closes #1242

I changed the existing string to 'Copy location' to keep it consistent.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you implement this as a setting? Not all users are going to want this so making it an option will help take up less space.

**Comment by jaigak** [comment]
@yair100 It's only a single option and also you are planning to put most used at the top right?

**Comment by jaigak** [comment]
@yair100 Where should I put the setting?

**Comment by jaigak** [comment]
@yair100 Done

**Review by yair100 — APPROVED** [review]
Great work!

**Pull request merged**
