### PR TITLE
Fix: Fixed issue where MenuFlyoutItemWithImage didn't use custom font

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Related #12026...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Set custom font
   2. Right click context menu and confirm `MenuFlyoutItemWithImage` items use the custom font

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by hishitetsu** [comment]
image

Only items with icons and no submenus use custom font.

**Comment by yaira2** [comment]
> Only items with icons and no submenus use custom font.

Yeah, this only helps for `MenuFlyoutItemWithImage`.

**Comment by hishitetsu** [comment]
Should this be merged as is?

**Comment by yaira2** [comment]
I pushed a commit that should help for `MenuFlyoutSubItemWithImageStyle` but sub items without icons still have this issue. We can merge as is but we should keep the issue open until it's fully resolved.

**Comment by hishitetsu** [comment]
I don't think we should merge until we can change the fonts on all the menus. It is not a good idea to have the fonts varied from item to item.

**Comment by yaira2** [comment]
Even without this change it's already varried with the main menu using the custom font.
image

**Comment by hishitetsu** [comment]
I mean that it is not good to mix fonts in one flyout, not between flyouts.

**Comment by yaira2** [comment]
@hishitetsu I've resolved the issues in #16035.

**Pull request closed without merging**
