### PR TITLE
Code Quality: Formatted csproj files with tabs

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Summary

As the title.

```diff
-<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
-    <DefineConstants>TRACE;DEBUG;NETFX_CORE</DefineConstants>
-</PropertyGroup>
-<PropertyGroup Condition="'$(Configuration)' != 'Debug'">
-    <DefineConstants>TRACE;RELEASE;NETFX_CORE</DefineConstants>
-    <Optimize>true</Optimize>
-</PropertyGroup>

+<DefineConstants Condition="'$(Configuration)' == 'Debug'">TRACE;DEBUG;NETFX_CORE</DefineConstants>
+<DefineConstants Condition="'$(Configuration)' != 'Debug'">TRACE;RELEASE;NETFX_CORE</DefineConstants>
+<Optimize Condition="'$(Configuration)' != 'Debug'">true</Optimize>
```

## PR Checklist

- [ ] **Development**: _N/A_
- [x] **Approval**: Have discussed with and got approval from the team[^1]
- [x] **Tests**: Tested accessibility on the local end
- [x] **Deployment**: Deployed the app on the local end
- [ ] **Localization**: Modified en-US string resources[^2]
- [ ] **Co-authors**: _N/A_

## Screenshots

_N/A_

[^1]: If the request hasn't been agreed by the team, this work might be rejected. Make sure that you get approval from the team before opening any PR related the request.
[^2]: If you removed any en-US string resources, make sure that there are no references of those resources. When you add a new en-US string resources, do not make any changes on other languages' resources; [Crowdin](https://crowdin.com/project/files-app) will do that, instead.

### CODE REVIEW

**Comment by 0x5bfa** [comment]
No other changes is here.

**Comment by 0x5bfa** [comment]
No other change is here.

**Comment by yaira2** [comment]
Does making a change to the project from the Visual Studio UI set it back to spaces?

**Comment by 0x5bfa** [comment]
At the first place, the VS format with 2 spaces, not 4.

image

**Comment by yaira2** [comment]
We had this issue back when we first switched from spaces to tabs, so we decided to stick with spaces in the csproj files to stay compatible with Visual Studio. Another place with this issue is with the localization files.

**Comment by 0x5bfa** [comment]
Good to hear. Ok, I'm gonna close.

**Pull request closed without merging**
