### PR TITLE
A better and user friendly read me!

### PR DESCRIPTION
**Pull request by coderzawad**
I made the read me better, Its friendly and easy to understand.

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Thanks for your contribution.

> 2. Review our [contributing guidelines](https://github.com/files-community/Files/blob/main/.github/CONTRIBUTING.md).

> # Contributions we accept
>
> **DO** create one pull request per Issue, and ensure that the Issue is linked in the pull request.

As you outlined this, we accept PRs that are linked to respective issue because we'd like to keep everyone being on the same page especially with @yaira2.

---

Also, in my honest opinion, adding emojis looks off and the current README keeps the best simplicity.

**Comment by 0x5bfa** [comment]
Thanks for your contribution.

> ## 🤝 Contributing
> 2. Review our [contributing guidelines](https://github.com/files-community/Files/blob/main/.github/CONTRIBUTING.md).

> ## Contributions we accept
>
> - **DO** create one pull request per Issue, and ensure that the Issue is linked in the pull request.
> - **DO** [link the issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue) you are addressing in the pull request.
> - **DO NOT** submit a PR unless it the connected issue is marked as ready to build or approved indirectly by an org member. This enables us to have a discussion on the idea before anyone invests time on the implementation.

As you outlined this, we accept PRs that are linked to respective issue to avoid wasting your and our time.

---

Also, in my honest opinion, adding emojis looks off and the current README keeps the best simplicity.

**Comment by 0x5bfa** [comment]
Thanks for your contribution.

> ## 🤝 Contributing
> 2. Review our [contributing guidelines](https://github.com/files-community/Files/blob/main/.github/CONTRIBUTING.md).

> ## Contributions we accept
>
> - **DO** create one pull request per Issue, and ensure that the Issue is linked in the pull request.
> - **DO** [link the issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue) you are addressing in the pull request.
> - **DO NOT** submit a PR unless it the connected issue is marked as ready to build or approved indirectly by an org member. This enables us to have a discussion on the idea before anyone invests time on the implementation.

As you outlined this, we accept PRs that are linked to respective issue to avoid wasting your and our time. I suggest to discuss with @yaira2 first and foremost.

---

In my honest opinion, adding emojis looks off and the current README keeps the best simplicity.

**Comment by coderzawad** [comment]
> In my honest opinion, adding emojis looks off and the current README keeps the best simplicity.

But its not simple most of the users are not familiar with github. and the current read me just kinda feels off

**Comment by 0x5bfa** [comment]
This is why we accept PRs that are approved either directly or indirectly. This is wasting time of both sides. We appreciate the contribution but this is clearly phrased out in our contribution guidelines. Please open an issue first.

Josh and Yair seem to be offline therefore let me close this for now.

**Comment by yaira2** [comment]
Hey @coderzawad, thanks for the PR! 😊 As @0x5bfa mentioned, linking to an approved issue is usually a good idea. It's not a hard rule, but it helps everyone by reducing extra work. You can look at the contributing section of the readme https://github.com/files-community/Files?tab=readme-ov-file#contributing-to-files to get started.

**Pull request closed without merging**
