### PR TITLE
Show localized names for system folders

### LINKED ISSUE #1226: Show localised (localized) names for system folders
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer, it will show the localized name instead of the real name for system folders such as Users folder.

2020-06-25 11-13-34_Trim

**Describe the solution you'd like**
Files UWP should show to localized name instead of the real name for system folders.

### PR DESCRIPTION
**Pull request by gave92**
Fixes #1226

This PR adds support for showing localized folder names (e.g. "Programmi" instead of "Program Files" for it-IT)
Does not slow down file loading, display name is loaded in LoadExtendedItemProperties() (if not cached).

@jakoss I've employed your caching feature to save the display name for files, I'd be happy if you could take a look at the code to see if there's anything amiss ;)

Note: This PR contains some changes done by @hez2010 for #3350 (also needed here)

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@gave92 What kind of impact will this have on performance?

**Comment by gave92** [comment]
@yair100 it should have almost no impact as the localized name is loaded in LoadExtendedItemProperties. Reading the name from cache should also be pretty fast. I haven't noticed slow downs in C:\Windows\System32 (big folder with lots of subfolders). Have you seen something different in your testing?

**Review by yair100 — DISMISSED** [review]
:shipit:

**Comment by yaichenbaum** [comment]
@gave92 There doesn't really seem to be any major impact, good work!

**Review by yair100 — DISMISSED** [review]

**Comment by gave92** [comment]
Aha sorry now it's ready I think

**Review by yair100 — APPROVED** [review]

**Pull request merged**
