### PR TITLE
Fix: Fixed crash in Dual Pane mode when switching away from Git folder

### LINKED ISSUE #12589: Bug: Consistent crash in Dual Pane mode when getting out of Git folder
### Description

In dual pane mode, opening a folder containing a Git repository in one of the pane and trying to switch focus to the other pane seems to provoke a crash.
 
Crash

### Steps To Reproduce

1. Open dual pane mode.
2. In first pane, open any folder with element. Select one element.
3. In the second pane, open a folder containing a Git repository. Select one element.
4. Switch to the first pane, the application should crash.

### Requirements

- No crash when switching out of the Git pane.

### Files Version

V.2.81.0 Dev

### Windows Version

Windows 10 (21H2): 19044

### Log File

[debug.log](https://github.com/files-community/Files/files/11724642/debug.log)

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12589

There seem to be an issue with x:Bind so that you can't use a TwoWay x:Bind on an element that is inside an element with x:Load:
```cs
<StackPanel x:Load="{x:Bind ...}">
    <RadioButton IsChecked="{x:Bind ..., Mode=TwoWay}" />
</StackPanel>
```
Workaround is to use Binding.

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open a non-git folder in left pane and set layout to Tiles
   2. Open a git folder in right pane and set layout to Details
   3. Switch focus between the two panes
   4. Verify that you can still switch between local and remote branches in the Git flyout

### CODE REVIEW

**Comment by gave92** [comment]
Uops I've just tested again and it crashes with a different error. Re-checking.

**Comment by QuaintMako** [comment]
Weird, I did not have any exception or crash while trying in the same set-up.

**Comment by gave92** [comment]
Ok the second error I think it was caused by running "git status" in cmd while having that folder open in dual pane.

**Review by yaira2 — APPROVED** [review]

**Comment by ferrariofilippo** [comment]
There are two problems related with this PR:
- You can't checkout branches (it will keep on checking out because `SelectedIndex` won't be reset to 0)
- Navigating to a git repository, going back and then reopening the repo will cause Files to create +80 branches (The `Locals` radio button will be unchecked)

**Comment by ferrariofilippo** [comment]
> Navigating to a git repository, going back and then reopening the repo will cause Files to create +80 branches (The Locals radio button will be unchecked)

We could solve this by changing the binding to `OneWay` and manually updating `ShowLocals` when the user clicks one of the two radios.
What do you think?

**Comment by yaira2** [comment]
Sounds good

**Comment by QuaintMako** [comment]
It could work I believe

**Pull request merged**
