### PR TITLE
Code Quality: Use SidebarContext and HomePageContext in OpenIn... RichCommands

### PR DESCRIPTION
**Pull request by 0x5bfa**
## PR Checklist

- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   _None_

## Screenshots

_None_

### CODE REVIEW

**Comment by 0x5bfa** [comment]
@hishitetsu Does tho look good to you and do you happen to have another idea to concern?

**Comment by 0x5bfa** [comment]
Should can IsExecutable in the first line of ExecuteAsync?

Idk but it looks odd to me somewhat though it's my idea lol.

**Comment by hishitetsu** [comment]
It would be better to do the same conditional branching in `ExecuteAsync` as in `GetIsExecutable`.
In the first place, is there a need to use SidebarContext or HomePageContext here?

**Comment by 0x5bfa** [comment]
I'm gonna use RochCommand for sidebar and widget card right click items.

**Comment by 0x5bfa** [comment]
> It would be better to do the same conditional branching in `ExecuteAsync` as in `GetIsExecutable`.
> 
> But in the first place, is there a need to use SidebarContext or HomePageContext here?

In that case, calling GetIsExecutable beforehand wouldn't work?

**Comment by hishitetsu** [comment]
Actions should be stateless. In other words, they shouldn't have any fields which change the process depending on the value. Control of processing should always be by reference to external properties.

**Comment by 0x5bfa** [comment]
As you may know we have discussion about Actions with multi-state. Why the actions should be stateless? ContentPageContext is already state and if user is viewing widgets page, ContentPageContext values are null. This means we determine the state already.

In this case, calling GetIsExecutable and return the context type (also remove the field) at the first line of ExecuteAsync is the best idea. Besides, this ExecutableContextType is just getting executable context type literally determining whether values of each context are null or not.

**Comment by 0x5bfa** [comment]
You are telling that there’s no guarantee of GetIsExecutable being called at all right?

**Comment by 0x5bfa** [comment]
I understand the point, then calling GetIsExecutable in ExecuteAsync and returning executable context might be a solution to this.

**Comment by 0x5bfa** [comment]
This is ready to be merged.

**Pull request closed without merging**
