### PR TITLE
Fix: Fixed issue where the last closed tab would be opened on next startup

### LINKED ISSUE #13181: Bug: Last closed tab reopens at next launch
### Description

When the startup setting is "Continue where you left off" and the app is closed by closing the last tab, the last closed tab reopens at next launch. But the expected behavior is to open the home page because the tab was closed.

### Steps To Reproduce

1. Set the startup setting to "Continue where you left off".
2. Exit the app by closing last tab.
3. Launch the app.
4. The last closed tab reopens.

### Requirements

The home page should be displayed at next launch.

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3324

### Log File

n/a

### PR DESCRIPTION
**Pull request by hishitetsu**
**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #13181 

**Validation**
How did you test these changes?
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?

### CODE REVIEW

**Comment by yaira2** [comment]
Does `ctrl` + `shift` + `t` still work?

**Comment by hishitetsu** [comment]
> Does `ctrl` + `shift` + `t` still work?

No. To begin with, there is no process to save the last closed tab when the app is closed.

**Comment by yaira2** [comment]
I guess that's a different issue, I'm happy to merge this as is.

**Comment by hishitetsu** [comment]
I'll try to add the process this evening (in Japan), could you wait a day?

**Comment by hishitetsu** [comment]
The last closed tab is now saved. If you accidentally close the last tab and exit the app, you can start the app again and press `Ctrl+Shift+T` to restore the closed tab.

**Comment by hishitetsu** [comment]
Maybe I can fix the pipeline failure. I'll see.

**Comment by hishitetsu** [comment]
Sorry, I have not tested it locally. Also, I am on summer vacation starting today so I won't be able to work on it for a couple of days.

**Comment by hishitetsu** [comment]
I had a little time to run the test locally, and it succeeds without any problems.
image

**Comment by yaira2** [comment]
@hishitetsu if the pipeline contains to fail, we can try creating a new branch and opening another PR.

**Pull request closed without merging**
