### PR TITLE
Fix: Fixed cloud icon for OneDrive work accounts

### LINKED ISSUE #8313: Feature: Use correct icon for work OneDrive accounts
### What's the Problem?

The icon for a work & school OneDrive Drive in the Cloud Drives section is a standard folder icon.

### Solution/Idea

Instead of the folder icon, the OneDrive Icon should be used -Ideally similar to the way the taskbar icons are represented ( white & blue cloud icons for Personal OneDrive, Work & School OneDrive, respectively.
image

### Alternatives

M$ File Explorer only represents them both as the Blue OneDrive Cloud icons, so I think that could be simpler solution as well.
image

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

Version: 2.1.13.0

### Windows Version

OS Version: 10.0.22000.493

### Comments

_No response_

### PR DESCRIPTION
**Pull request by yaira2**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #8313...

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ ] Are there any other steps that were used to validate these changes?
   1. Confirm the sidebar displays the OneDrive icon for OneDrive work accounts

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaira2** [comment]
@Lukiluc29 fyi

**Comment by Lukiluc29** [comment]
Thank you, I didn't think it would fix the issue, but in the end it did.

**Comment by Lukiluc29** [comment]
The icon in the sidebar updated successfully, but not in the preview pane.
Capture d'écran 2023-08-21 182911

**Comment by yaira2** [comment]
At the end of the day, the folder icon is the correct icon as that's what's provided by Windows (I imagine File Explorer does the same). I applied custom logic in the sidebar so that it doesn't look out of place next to the regular OneDrive item.

**Comment by Lukiluc29** [comment]
This doesn't solve the issue because my OneDrive, which previously didn't have an icon in the sidebar, now has one, but still not in the preview pane. It displays as a regular folder there, whereas the other one, where the icon was correctly displayed in the sidebar, also appears correctly in the preview pane.
Capture d'écran 2023-08-21 182911
Capture d'écran 2023-08-21 184450

**Comment by yaira2** [comment]
As mentioned above, the icon in the preview pane is the actual icon provided by File Explorer. We made an exception to override the real icon in the left-hand sidebar, but this is indeed the expected behavior.

**Comment by Lukiluc29** [comment]
Where can this problem come from? In my file explorer it shows me the OneDrive icon.
Capture d'écran 2023-08-21 190115
Capture d'écran 2023-08-21 190106

**Comment by yaira2** [comment]
It's possible they have custom behavior for the preview pane as well, as of now we don't plan to do this but it's not impossible that we'll do this at some point.

**Comment by Lukiluc29** [comment]
Finally, by completely uninstalling OneDrive, everything went back to normal.

**Pull request merged**
