### PR TITLE
Improved navigation animation

### PR DESCRIPTION
**Pull request by d2dyno1**
**Details of Changes**
Improves the DrillInNavigation animation transition. This does not however disable the animation when changing between tabs.

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@d2dyno1 What does this change?

**Comment by d2dyno1** [comment]
> @d2dyno1 What does this change?

I've added transition animation when leaving Homepage.

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you change the animations to an entrance animation?

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you make the requested changes?

**Comment by d2dyno1** [comment]
@yair100 Ready!

**Review by yair100 — APPROVED** [review]
Great work! Thanks!

**Pull request merged**
