### PR TITLE
Fix: Fixed issue where the date modified wasn't shown for items inside archives

### PR DESCRIPTION
**Pull request by gave92**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Similar to #10563 but for date modified property

Relevant SevenZipSharp commit: [f8b60c0](https://github.com/gave92/SevenZipSharp/commit/f8b60c01bd17eda90e2731dac2fee98be92ecc3e)

**Validation**
How did you test these changes?
- [x] Built and ran the app

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
Should we bring the nuget code into this repo for easier access and to better review the changes?

**Comment by gave92** [comment]
> Should we bring the nuget code into this repo for easier access and to better review the changes?

Yup I proposed this some time ago, so no problem for me 👍

**Comment by gave92** [comment]
Wait was it already there? https://github.com/files-community/SevenZipSharp

**Comment by yaira2** [comment]
We have a repo for it but I was thinking we should merge it with the main repo.

**Pull request merged**
