### PR TITLE
Fix: Fixed context menu hang in recent files and other widgets

### PR DESCRIPTION
**Pull request by hecksmosis**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes issue by #11204 where context menu didn't show up until shell extensions loaded
- Continues work by @hishitetsu on #11270 

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by yaira2** [comment]
The menu options don't load with these changes, I'm not convinced we need them though. It's working pretty well as is.

**Comment by hecksmosis** [comment]
> The shell extensions don't load with these changes, I'm not convinced we need them though. I'm not running into any issues before this PR.

This uses the Loading menu options text we implemented and makes the context menu much quicker to load

**Comment by yaira2** [comment]
It seems that I broke shell extensions on my device 😂 

Will test after restarting

**Comment by hecksmosis** [comment]
> 

How did you do that lol

**Comment by yaira2** [comment]
Probably by spamming requests

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
