### PR TITLE
Feature: Show drive name on tab header

### LINKED ISSUE #10859: Feature: Show drive name on tab header
### What feature or improvement do you think would benefit Files?

Show drive name when path is a drive's root
image

### Requirements

Use the drive name instead of (or in addition to) the drive letter.

### Files Version

Version: 2.4.8.0 OS Version: 10.0.19044.2006

### Windows Version

Windows 10 Pro 21H2 19044.2006

### Comments

_No response_

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #10859

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Review by hecksmosis — APPROVED** [review]
LGTM

**Review by QuaintMako — APPROVED** [review]
LGTM and works for me.

**Review by yaira2 — COMMENTED** [review]
LGTM

**Comment by benny779** [comment]
Thanks friends.
That was fast...

**Pull request merged**
