### PR TITLE
Rev esc

### PR DESCRIPTION
**Pull request by gave92**
@yair100 this simple check works for me.

### CODE REVIEW

**Comment by gave92** [comment]
Lol nevermind xD

**Comment by yaira2** [comment]
@gave92 I think there is an issue where it sometimes loses the focus.

**Comment by gave92** [comment]
Actually this pr works every time for me. But after some tries the tabs overlap each other.

**Comment by yaira2** [comment]
What if you add this to `TabView_TabDragCompleted` as well?

**Pull request closed without merging**
