### PR TITLE
Update  zh-Hans

### PR DESCRIPTION
**Pull request by x-Ai**
**Resolved / Related Issues**

Translation Two strings without Chinese localization.

**Details of Changes**
- Translate "Hidden files and folders" to "隐藏文件和文件夹"
- Translate "Contributors" to "贡献者"

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@x-Ai thank you for the pull request, we recently started using Crowdin to manage translations, can you make this change through Crowdin?

**Comment by x-Ai** [comment]
Hi, I have checked the pull request and the documentation before pulling, I didn't find the address of the Files App in Crowdin in these places, if you can provide it, I will translate it in Crowdin.

**Comment by yaichenbaum** [comment]
https://crowdin.com/project/files-app

**Comment by x-Ai** [comment]
Already translated by Crowdin. @yair100

**Pull request closed without merging**
