### PR TITLE
Feature: Reflect current layout in the Toolbar

### LINKED ISSUE #12894: Feature: Update layout button icon as layout changes
### What feature or improvement do you think would benefit Files?

At the moment, the layout button's icon does not match the current chosen layout from the flyout.

image

### Requirements

- This proposal will allow the user to see what the current layout is being used, and provides a better hint at what this button does, which is unlabelled in the UI

### Files Version

2.5.13 Preview

### Windows Version

22621.1928

### Comments

_No response_

### PR DESCRIPTION
**Pull request by ferrariofilippo**
**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #12894 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Open app and navigate to a folder
   2. Change layout

**Screenshots (optional)**
image

### CODE REVIEW

**Comment by yaira2** [comment]
@mdtauk would it look better if we used a single icon to represent whenever a grid layout is selected?

**Comment by mdtauk** [comment]
The majority of layout options are some kind of grid.

**Comment by ferrariofilippo** [comment]
What should we do then?
Also, can we sort layouts as below:
image

I think it would be better to have the three `grid layouts` in the same column

**Comment by yaira2** [comment]
> Also, can we sort layouts as below:

Do you want me to push a commit for this?

**Comment by ferrariofilippo** [comment]
> Do you want me to push a commit for this?

I can do it

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
